@startuml

card Légende #White;line:Black;line:Black;text:black {
circle " " #blue;line:blue;line.dashed;text:black
circle "Statuts" #Lime;line:Lime;line.dashed;text:black
circle "    " #red;line:red;line.dashed;text:red
rectangle "Actions initiateur\nde la demande" #Lavender;line:DarkMagenta;text:DarkMagenta
rectangle "Actions équipe NOS" #Azure;line:MediumBlue;text:MediumBlue
rectangle "Action comité \nde validation" #MistyRose;line:IndianRed;text:IndianRed
hexagon "Choice" as DMcomplete #GhostWhite;line:DimGrey;text:DimGrey
}

@enduml
