ValueSet: JDV_J186_ProfessionRessource_ROR
Id: JDV-J186-ProfessionRessource-ROR
Description: "Profession Ressource des offres dans le ROR"
* ^meta.versionId = "13"
* ^meta.lastUpdated = "2026-07-06T19:05:43.006+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-03-31T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J186-ProfessionRessource-ROR/FHIR/JDV-J186-ProfessionRessource-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.19"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-G15-ProfessionSante#10 "Médecin"
* $TRE-G15-ProfessionSante#21 "Pharmacien"
* $TRE-G15-ProfessionSante#26 "Audioprothésiste"
* $TRE-G15-ProfessionSante#28 "Opticien-Lunetier"
* $TRE-G15-ProfessionSante#31 "Assistant dentaire"
* $TRE-G15-ProfessionSante#32 "Physicien médical"
* $TRE-G15-ProfessionSante#35 "Aide-soignant"
* $TRE-G15-ProfessionSante#36 "Ambulancier"
* $TRE-G15-ProfessionSante#37 "Auxiliaire de puériculture"
* $TRE-G15-ProfessionSante#38 "Préparateur en pharmacie hospitalière"
* $TRE-G15-ProfessionSante#39 "Préparateur en pharmacie (officine)"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#69 "Infirmier psychiatrique"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#81 "Orthoprothésiste"
* $TRE-G15-ProfessionSante#82 "Podo-Orthésiste"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#84 "Oculariste"
* $TRE-G15-ProfessionSante#85 "Epithésiste"
* $TRE-G15-ProfessionSante#86 "Technicien de laboratoire médical"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"
* $TRE-G15-ProfessionSante#94 "Ergothérapeute"
* $TRE-G15-ProfessionSante#95 "Diététicien"
* $TRE-G15-ProfessionSante#96 "Psychomotricien"
* $TRE-G15-ProfessionSante#98 "Manipulateur ERM"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R94-ProfessionSocial#42 "Auxiliaire de vie sociale"
* $TRE-R94-ProfessionSocial#43 "Technicien de l'intervention sociale et familiale"
* $TRE-R94-ProfessionSocial#44 "Conseiller en économie sociale et familiale"
* $TRE-R94-ProfessionSocial#45 "Médiateur familial"
* $TRE-R94-ProfessionSocial#46 "Assistant familial"
* $TRE-R94-ProfessionSocial#47 "Aide médico-psychologique"
* $TRE-R94-ProfessionSocial#48 "Moniteur éducateur"
* $TRE-R94-ProfessionSocial#49 "Educateur de jeunes enfants"
* $TRE-R94-ProfessionSocial#51 "Educateur spécialisé"
* $TRE-R94-ProfessionSocial#52 "Educateur technique spécialisé"
* $TRE-R94-ProfessionSocial#53 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#350 "Aide à domicile"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE-R96-AutreFonctionSanitaire#408 "Perceur corporel"
* $TRE-R96-AutreFonctionSanitaire#409 "Maquilleur permanent"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R95-UsagerTitre#97 "Conseiller en génétique"
* $TRE-R356-ProfessionRessource#04 "Art-thérapeute"
* $TRE-R356-ProfessionRessource#05 "Neuropsychologue"
* $TRE-R356-ProfessionRessource#08 "Médiateur de santé pair"
* $TRE-R356-ProfessionRessource#10 "Socio-esthéticien"
* $TRE-R356-ProfessionRessource#11 "Enseignant du 1er degré"
* $TRE-R356-ProfessionRessource#12 "Enseignant du 2nd degré"
* $TRE-R356-ProfessionRessource#13 "Enseignant du supérieur"
* $TRE-R356-ProfessionRessource#14 "Puériculteur"
* $TRE-R356-ProfessionRessource#17 "Aide humaine en milieu scolaire"
* $TRE-R356-ProfessionRessource#19 "Médecin coordonnateur"
* $TRE-R356-ProfessionRessource#20 "Infirmier coordonnateur"
* $TRE-R356-ProfessionRessource#21 "Phoniatre"
* $TRE-R356-ProfessionRessource#22 "Audio phonologue"
* $TRE-R356-ProfessionRessource#23 "Ingénieur en analyse du mouvement"
* $TRE-R356-ProfessionRessource#24 "Psychologue clinicien"
* $TRE-R356-ProfessionRessource#25 "Animateur socio-culturel"
* $TRE-R356-ProfessionRessource#26 "Moniteur d'atelier"
* $TRE-R356-ProfessionRessource#38 "Enseignant en Activité Physique Adaptée (EAPA)"
* $TRE-R356-ProfessionRessource#39 "Accompagnant des Élèves en Situation de Handicap (AESH)"
* $TRE-R356-ProfessionRessource#43 "Pédopsychiatre"
* $TRE-R356-ProfessionRessource#44 "Veilleur de nuit"
* $TRE-R356-ProfessionRessource#45 "Assistant de soins en gérontologie"
* $TRE-R356-ProfessionRessource#50 "Avéjiste"
* $TRE-R356-ProfessionRessource#51 "Instructeur en locomotion"
* $TRE-R356-ProfessionRessource#52 "Educateur sportif"
* $TRE-R356-ProfessionRessource#53 "Conseiller en insertion professionnelle"
* $TRE-R356-ProfessionRessource#54 "Coordonnateur et gestionnaire de parcours handicap"
* $TRE-R356-ProfessionRessource#55 "Neuropédiatre"
* $TRE-R356-ProfessionRessource#56 "Psychopédagogue"
* $TRE-R356-ProfessionRessource#59 "Tabacologue"
* $TRE-R356-ProfessionRessource#60 "Addictologue"
* $TRE-R356-ProfessionRessource#61 "Allergologue"
* $TRE-R356-ProfessionRessource#63 "Cardiologue"
* $TRE-R356-ProfessionRessource#64 "Chercheur médical"
* $TRE-R356-ProfessionRessource#65 "Chirurgien digestif"
* $TRE-R356-ProfessionRessource#66 "Chirurgien général"
* $TRE-R356-ProfessionRessource#67 "Chirurgien maxillo-facial"
* $TRE-R356-ProfessionRessource#69 "Chirurgien oral"
* $TRE-R356-ProfessionRessource#70 "Chirurgien orthopédiste"
* $TRE-R356-ProfessionRessource#71 "Chirurgien pédiatrique"
* $TRE-R356-ProfessionRessource#72 "Chirurgien plastique, plasticien"
* $TRE-R356-ProfessionRessource#73 "Chirurgien thoracique et cardiaque"
* $TRE-R356-ProfessionRessource#74 "Chirurgien urologue"
* $TRE-R356-ProfessionRessource#75 "Chirurgien vasculaire"
* $TRE-R356-ProfessionRessource#76 "Dentiste"
* $TRE-R356-ProfessionRessource#77 "Dermatologue"
* $TRE-R356-ProfessionRessource#78 "Endocrinologue"
* $TRE-R356-ProfessionRessource#79 "Gastro-entérologue"
* $TRE-R356-ProfessionRessource#80 "Généticien médicale"
* $TRE-R356-ProfessionRessource#81 "Gériatre"
* $TRE-R356-ProfessionRessource#82 "Gynécologue"
* $TRE-R356-ProfessionRessource#83 "Gynéco-obstétricien"
* $TRE-R356-ProfessionRessource#84 "Hématologue"
* $TRE-R356-ProfessionRessource#85 "Infectiologue"
* $TRE-R356-ProfessionRessource#86 "Infirmier en pratique avancée (IPA)"
* $TRE-R356-ProfessionRessource#87 "Médecin anesthésiste-réanimateur"
* $TRE-R356-ProfessionRessource#90 "Médecin généraliste"
* $TRE-R356-ProfessionRessource#91 "Médecin interniste"
* $TRE-R356-ProfessionRessource#92 "Médecin légiste"
* $TRE-R356-ProfessionRessource#93 "Médecin nucléaire"
* $TRE-R356-ProfessionRessource#94 "Médecin rééducateur"
* $TRE-R356-ProfessionRessource#95 "Médecin vasculaire"
* $TRE-R356-ProfessionRessource#96 "Néphrologue"
* $TRE-R356-ProfessionRessource#97 "Neurochirurgien"
* $TRE-R356-ProfessionRessource#98 "Neurologue"
* $TRE-R356-ProfessionRessource#99 "Neuro-psychiatre"
* $TRE-R356-ProfessionRessource#100 "Onco-hématologue"
* $TRE-R356-ProfessionRessource#101 "Oncologue"
* $TRE-R356-ProfessionRessource#102 "Ophtalmologue"
* $TRE-R356-ProfessionRessource#103 "ORL"
* $TRE-R356-ProfessionRessource#104 "Pathologiste"
* $TRE-R356-ProfessionRessource#105 "Pédiatre"
* $TRE-R356-ProfessionRessource#107 "Pneumologue"
* $TRE-R356-ProfessionRessource#108 "Psychiatre"
* $TRE-R356-ProfessionRessource#109 "Radiologue"
* $TRE-R356-ProfessionRessource#110 "Radiologue et radiothérapeute"
* $TRE-R356-ProfessionRessource#111 "Radiothérapeute"
* $TRE-R356-ProfessionRessource#112 "Réanimateur intensiviste"
* $TRE-R356-ProfessionRessource#113 "Rhumatologue"
* $TRE-R356-ProfessionRessource#114 "Stomatologue"
* $TRE-R356-ProfessionRessource#115 "Urgentiste"
* $TRE-R356-ProfessionRessource#116 "Biologiste médical"
* $TRE-R356-ProfessionRessource#117 "Médecin du travail"
* $TRE-R356-ProfessionRessource#118 "Médecin de santé public"
* $TRE-R356-ProfessionRessource#119 "Médecin anesthésiste-réanimateur pédiatrique"
* $TRE-R356-ProfessionRessource#120 "Chirurgien viscéral"
* $TRE-R356-ProfessionRessource#121 "Cardiologue interventionnelle"
* $TRE-R356-ProfessionRessource#122 "Cardiologue en imagerie"
* $TRE-R356-ProfessionRessource#123 "Cardiologue rythmologue"
* $TRE-R356-ProfessionRessource#124 "Réanimateur pédiatrique"
* $TRE-R356-ProfessionRessource#125 "Neurologue interventionnelle"
* $TRE-R356-ProfessionRessource#126 "Ophtalmologue pédiatrique"
* $TRE-R356-ProfessionRessource#127 "Réanimateur néonatologiste"
* $TRE-R356-ProfessionRessource#128 "Conseiller conjugal et familial"
* $TRE-R356-ProfessionRessource#129 "Ergonome"
* $TRE-R356-ProfessionRessource#130 "Psychologue du travail"
* $TRE-R356-ProfessionRessource#131 "Intermédiateur"
* $TRE-R356-ProfessionRessource#132 "Stomathérapeute"