ValueSet: JDV_J227_NiveauExpertise_ROR
Id: JDV-J227-NiveauExpertise-ROR
Description: "Niveau de ressources humaines et matérielles utiles pour la réalisation de l'offre"
* ^meta.versionId = "15"
* ^meta.lastUpdated = "2026-07-06T19:06:03.812+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J227-NiveauExpertise-ROR/FHIR/JDV-J227-NiveauExpertise-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.59"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R253-TypeMaternite#01 "Maternité de type 1"
* $TRE-R253-TypeMaternite#02 "Maternité de type 2A"
* $TRE-R253-TypeMaternite#03 "Maternité de type 2B"
* $TRE-R253-TypeMaternite#04 "Maternité de type 3"
* $TRE-R344-NiveauExpertise#10 "Centre de référence labellisé"
* $TRE-R344-NiveauExpertise#11 "Centre de compétences labellisé"
* $TRE-R344-NiveauExpertise#12 "Structure spécialisée labellisée"
* $TRE-R344-NiveauExpertise#13 "SMR Labellisé réadaptation des personnes en état de conscience altérée (ex EVC/EPR)"
* $TRE-R344-NiveauExpertise#14 "SMR Labellisé réadaptation des patients amputés, appareillés ou non"
* $TRE-R344-NiveauExpertise#15 "SMR Labellisé réadaptation PREcoce Post-Aiguë Cardiologique (PREPAC)"
* $TRE-R344-NiveauExpertise#16 "SMR Labellisé réadaptation PREcoce Post-Aiguë Respiratoire (PREPAR)"
* $TRE-R344-NiveauExpertise#17 "SMR Labellisé réadaptation neuro-orthopédique"
* $TRE-R344-NiveauExpertise#18 "SMR Labellisé réadaptation post-réanimation (SRPR)"
* $TRE-R344-NiveauExpertise#19 "SMR Labellisé réadaptation PREcoce Post-Aiguë Neurologique (PREPAN)"
* $TRE-R344-NiveauExpertise#20 "SMR Labellisé réadaptation des troubles cognitifs et comportementaux des patients cérébro-lésés"
* $TRE-R344-NiveauExpertise#21 "SMR Labellisé réadaptation des lésions médullaires"
* $TRE-R344-NiveauExpertise#22 "SMR Labellisé réadaptation des obésités complexes"
* $TRE-R344-NiveauExpertise#23 "SMR Labellisé réadaptation des troubles cognitifs sévères liés à une conduite addictive"
* $TRE-R344-NiveauExpertise#24 "SMR Labellisé réadaptation du polyhandicap"
* $TRE-R344-NiveauExpertise#25 "SMR Labellisé réadaptation des troubles du langage et des apprentissages"
* $TRE-R344-NiveauExpertise#26 "Centre de recours pour chirurgie oncologique complexe"
* $TRE-R344-NiveauExpertise#27 "Premier niveau de recours"
* $TRE-R344-NiveauExpertise#28 "Deuxième niveau de recours"
* $TRE-R344-NiveauExpertise#29 "Troisième niveau de recours"
* $TRE-R344-NiveauExpertise#30 "Unité de réanimation pédiatrique de recours"
* $TRE-R344-NiveauExpertise#31 "Filière endométriose - premier niveau de recours"
* $TRE-R344-NiveauExpertise#32 "Filière endométriose - deuxième niveau de recours"
* $TRE-R344-NiveauExpertise#33 "Filière endométriose - troisième niveau de recours"
* $TRE-R344-NiveauExpertise#34 "Centre labellisé Covid-Long"
* $TRE-R344-NiveauExpertise#35 "Centre de réhabilitation psychosociale - Centre de recours labellisé"
* $TRE-R344-NiveauExpertise#36 "Centre de réhabilitation psychosociale - Centre de proximité labellisé"
* $TRE-R344-NiveauExpertise#37 "Unité neuro-vasculaire (UNV) de territoire"
* $TRE-R344-NiveauExpertise#38 "Unité neuro-vasculaire (UNV) de recours"
* $TRE-R344-NiveauExpertise#39 "Filière Obésité - Niveau 1 Conventionné Centres Spécialisés Obésité (CSO)"
* $TRE-R344-NiveauExpertise#40 "Filière Obésité - Niveau 2 Conventionné Centres Spécialisés Obésité (CSO)"
* $TRE-R344-NiveauExpertise#41 "Filière Obésité - Niveau 3 Conventionné Centres Spécialisés Obésité (CSO)"
* $TRE-R344-NiveauExpertise#42 "Filière Obésité - Niveau 3 (Centre Spécialisé Obésité)"
* $TRE-R344-NiveauExpertise#43 "Centre Ressources Autisme (CRA)"
* $TRE-R344-NiveauExpertise#44 "Centre de référence des Troubles du Langage et de l’Apprentissage (CRTLA)"
* $TRE-R344-NiveauExpertise#45 "Centre de référence du Trouble Déficit de l’Attention avec ou sans Hyperactivité (CRTDAH)"
* $TRE-R344-NiveauExpertise#46 "Centre de compétence centre mémoire ressources et recherche (CMRR)"
* $TRE-R344-NiveauExpertise#47 "Centre expert maladie de Parkinson"
* $TRE-R344-NiveauExpertise#48 "Centre de ressources et de compétences sclérose en plaques (SEP)"
* $TRE-R344-NiveauExpertise#49 "Agrément Fédération Européenne des Services d'Urgence de la Main (FESUM) - SOS mains"
* $TRE-R344-NiveauExpertise#50 "Centre de Traitement des Brûlés (CTB)"
* $TRE-R344-NiveauExpertise#51 "Réseau France Santé"
* $TRE-R344-NiveauExpertise#52 "Autorisation par l’ARS pour la sous-traitance de préparation pharmaceutique"
* $TRE-R344-NiveauExpertise#53 "Centre de Référence d'Infection Ostéo-Articulaire/ Complexes (CRIOA/ C) - Niveau 1 \"coordonnateur\""
* $TRE-R344-NiveauExpertise#54 "Centre de Référence d'Infection Ostéo-Articulaire/ Complexes (CRIOA/ C) - Niveau 2 \"correspondant\""
* $TRE-R344-NiveauExpertise#55 "Accréditation par la Société Française de Recherche en Médecine du Sommeil (SFRMS)"
