ValueSet: JDV_J133_ActiviteSanitaireRegulee_RASS
Id: JDV-J133-ActiviteSanitaireRegulee-RASS
Description: "Activités sanitaires soumises à une régulation de la part de l'ARS dans le RASS"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-08-27T15:18:03.430+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J133-ActiviteSanitaireRegulee-RASS/FHIR/JDV-J133-ActiviteSanitaireRegulee-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.219"
* ^version = "20260827120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-08-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R274-ActiviteSanitaireRegulee#01 "Médecine"
* $TRE-R274-ActiviteSanitaireRegulee#02 "Chirurgie"
* $TRE-R274-ActiviteSanitaireRegulee#03 "Gynécologie, obstétrique, néonatologie, réanimation néonatale"
* $TRE-R274-ActiviteSanitaireRegulee#04 "Psychiatrie"
* $TRE-R274-ActiviteSanitaireRegulee#07 "Soins de longue durée"
* $TRE-R274-ActiviteSanitaireRegulee#09 "Traitement des grands brûlés"
* $TRE-R274-ActiviteSanitaireRegulee#10 "Chirurgie cardiaque"
* $TRE-R274-ActiviteSanitaireRegulee#11 "Activités interventionnelles sous imagerie méd, voie endovasculaire, cardio"
* $TRE-R274-ActiviteSanitaireRegulee#12 "Neurochirurgie"
* $TRE-R274-ActiviteSanitaireRegulee#13 "Activités interventionnelles sous imagerie méd, voie endovasculaire, neurorad"
* $TRE-R274-ActiviteSanitaireRegulee#14 "Médecine d'urgence"
* $TRE-R274-ActiviteSanitaireRegulee#15 "Réanimation"
* $TRE-R274-ActiviteSanitaireRegulee#16 "Traitement de l'insuffisance rénale chronique par épuration extrarénale"
* $TRE-R274-ActiviteSanitaireRegulee#17 "AMP DPN"
* $TRE-R274-ActiviteSanitaireRegulee#18 "Traitement du cancer"
* $TRE-R274-ActiviteSanitaireRegulee#19 "Exam carac géné d'une pers ou ident d'une pers par empreintes géné fins méd"
* $TRE-R274-ActiviteSanitaireRegulee#50 "Soins de suite et de réadaptation non spécialisés"
* $TRE-R274-ActiviteSanitaireRegulee#51 "SSR spécialisés - Affections de l'appareil locomoteur"
* $TRE-R274-ActiviteSanitaireRegulee#52 "SSR spécialisés - Affections du système nerveux"
* $TRE-R274-ActiviteSanitaireRegulee#53 "SSR spécialisés - Affections cardio-vasculaires"
* $TRE-R274-ActiviteSanitaireRegulee#54 "SSR spécialisés - Affections respiratoires"
* $TRE-R274-ActiviteSanitaireRegulee#55 "SSR spécialisés - Affections systèmes digestif, métabolique et endocrinien"
* $TRE-R274-ActiviteSanitaireRegulee#56 "SSR spécialisés - Affections onco-hématologiques"
* $TRE-R274-ActiviteSanitaireRegulee#57 "SSR spécialisés - Affections des brulés"
* $TRE-R274-ActiviteSanitaireRegulee#58 "SSR spécialisés - Affections liées aux conduites addictives"
* $TRE-R274-ActiviteSanitaireRegulee#59 "SSR spécialisés - Affections pers agée polypathologique, dép ou risque dép"
* $TRE-R274-ActiviteSanitaireRegulee#80 "Greffe de rein"
* $TRE-R274-ActiviteSanitaireRegulee#81 "Greffe de pancréas"
* $TRE-R274-ActiviteSanitaireRegulee#82 "Greffe rein-pancréas"
* $TRE-R274-ActiviteSanitaireRegulee#83 "Greffe de foie"
* $TRE-R274-ActiviteSanitaireRegulee#84 "Greffe d'intestin"
* $TRE-R274-ActiviteSanitaireRegulee#85 "Greffe de coeur"
* $TRE-R274-ActiviteSanitaireRegulee#86 "Greffe de poumon"
* $TRE-R274-ActiviteSanitaireRegulee#87 "Greffe coeur-poumons"
* $TRE-R274-ActiviteSanitaireRegulee#88 "Greffe de cellules hématopoïétiques allogreffe"
* $TRE-R274-ActiviteSanitaireRegulee#A0 "Installation de chirurgie esthétique"
* $TRE-R274-ActiviteSanitaireRegulee#A1 "Dépôt de sang"
* $TRE-R274-ActiviteSanitaireRegulee#A2 "Lactarium"
* $TRE-R274-ActiviteSanitaireRegulee#A3 "Lieux de recherches impliquant la personne humaine"
* $TRE-R274-ActiviteSanitaireRegulee#A4 "Prélèvement de cellules hématopoïétiques"
* $TRE-R274-ActiviteSanitaireRegulee#A5 "Prélèvement d'organes"
* $TRE-R274-ActiviteSanitaireRegulee#A6 "Prélèvement de tissus"
* $TRE-R274-ActiviteSanitaireRegulee#R1 "Addictologie"
* $TRE-R274-ActiviteSanitaireRegulee#R2 "Infections ostéo-articulaires complexes"
* $TRE-R274-ActiviteSanitaireRegulee#R3 "Plateau technique hautement spécialisé"
* $TRE-R274-ActiviteSanitaireRegulee#R4 "Soins palliatifs"
* $TRE-R274-ActiviteSanitaireRegulee#R5 "Soins intensifs"
* $TRE-R274-ActiviteSanitaireRegulee#R6 "Unité Neuro-vasculaire"
* $TRE-R274-ActiviteSanitaireRegulee#R7 "Surveillance continue"
* $TRE-R274-ActiviteSanitaireRegulee#R8 "Centre de maladies rares"
* $TRE-R274-ActiviteSanitaireRegulee#R9 "Etablissement associé cancéro - Traitement dont chimiothérapie"
* $TRE-R274-ActiviteSanitaireRegulee#S1 "Prise en charge de la douleur chronique rebelle"
* $TRE-R274-ActiviteSanitaireRegulee#S2 "Prise en charge des patients atteints d'obésité sévère ou multi-compliquée"
* $TRE-R274-ActiviteSanitaireRegulee#S3 "Prise en charge des personnes âgées"
* $TRE-R274-ActiviteSanitaireRegulee#S4 "Soins de Rééducation Post-Réanimation"
* $TRE-R274-ActiviteSanitaireRegulee#S5 "Soins de suite et de réadaptation"
* $TRE-R274-ActiviteSanitaireRegulee#S6 "Structure spécifique d'hospitalisation"
* $TRE-R274-ActiviteSanitaireRegulee#S7 "Prise en charge des patients atteints de sclérose en plaques"
* $TRE-R274-ActiviteSanitaireRegulee#T0 "SSRS- EVC-EVP (lits Eveil de Coma-Etat Végétatif Persistant)"
* $TRE-R274-ActiviteSanitaireRegulee#T1 "SSRS - Affections de la personne âgée"
* $TRE-R274-ActiviteSanitaireRegulee#T2 "SSRS - Basse vision"
* $TRE-R274-ActiviteSanitaireRegulee#T3 "SSRS - Etablissement associé en cancéro"
* $TRE-R274-ActiviteSanitaireRegulee#T4 "SSRS - EVC EPR (Etat Végétatif Chronique Etat Pauci Relationnel)"
* $TRE-R274-ActiviteSanitaireRegulee#T5 "SSRS - Lymphologie"
* $TRE-R274-ActiviteSanitaireRegulee#T6 "SSRS - Néphrologie"
* $TRE-R274-ActiviteSanitaireRegulee#T8 "SSRS - Viroses chroniques"
* $TRE-R274-ActiviteSanitaireRegulee#A8 "Greffe de face ou de face inférieure"
* $TRE-R274-ActiviteSanitaireRegulee#A9 "Greffe unilatérale ou bilatérale de main"
* $TRE-R274-ActiviteSanitaireRegulee#B0 "Prélèvement de cellules mononuclées autologues"
* $TRE-R274-ActiviteSanitaireRegulee#B1 "Prélèvement de cellules mononuclées allogéniques"
* $TRE-R274-ActiviteSanitaireRegulee#C1 "Greffe unilatérale ou bilatérale d'avant-bras"
* $TRE-R274-ActiviteSanitaireRegulee#C3 "Greffe unilatérale ou bilatérale de bras"
* $TRE-R274-ActiviteSanitaireRegulee#D1 "Greffe de membre inférieur"
* $TRE-R274-ActiviteSanitaireRegulee#F4 "Greffe de langue"
* $TRE-R274-ActiviteSanitaireRegulee#F9 "Greffe de pénis"
* $TRE-R274-ActiviteSanitaireRegulee#H2 "Greffe de paroi abdominale"
* $TRE-R274-ActiviteSanitaireRegulee#H3 "Greffe de tissus cutanés conjonctifs et vasculo- nerveux"
* $TRE-R274-ActiviteSanitaireRegulee#S8 "Maison de naissance"