ValueSet: JDV_J250_MotifStatutPersonnePriseChargeUnite
Id: JDV-J250-MotifStatutPersonnePriseChargeUnite
Description: "Motif du statut de la personne prise en charge au sein d'une unité"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:06:18.107+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-06-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J250-MotifStatutPersonnePriseChargeUnite/FHIR/JDV-J250-MotifStatutPersonnePriseChargeUnite"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.114"
* ^version = "20240126120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-01-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R358-MotifStatutPersonnePriseCharge#84 "Le demandeur ne remplit pas les exigences d'admission"
* $TRE-R358-MotifStatutPersonnePriseCharge#85 "Volonté du demandeur"
* $TRE-R358-MotifStatutPersonnePriseCharge#87 "L'usager est admis dans un autre ESMS suite à un déménagement"
* $TRE-R358-MotifStatutPersonnePriseCharge#88 "Suite à la décision de la CDAPH"
* $TRE-R358-MotifStatutPersonnePriseCharge#89 "L'usager ne souhaite plus être pris en charge par l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#91 "L'usager est admis dans un autre ESMS suite à une réorientation"
* $TRE-R358-MotifStatutPersonnePriseCharge#92 "Amélioration notoire de la situation de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#93 "Aggravation notoire de la situation de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#95 "Annulation automatique"
* $TRE-R358-MotifStatutPersonnePriseCharge#98 "Fin de validité de la notification"
* $TRE-R358-MotifStatutPersonnePriseCharge#100 "Volonté de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#109 "Déménagement"
* $TRE-R358-MotifStatutPersonnePriseCharge#112 "Erreur d'utilisation du logiciel"
* $TRE-R358-MotifStatutPersonnePriseCharge#124 "L'usager est décédé"
* $TRE-R358-MotifStatutPersonnePriseCharge#125 "L'usager a démissionné (ESAT)"
* $TRE-R358-MotifStatutPersonnePriseCharge#126 "L'usager est pris en charge par la sécurité sociale au titre de l'invalidité (ESAT)"
* $TRE-R358-MotifStatutPersonnePriseCharge#127 "L'usager a fait valoir ses droits à la retraite (ESAT)"
* $TRE-R358-MotifStatutPersonnePriseCharge#128 "L'usager est arrivé à la fin du contrat de prise en charge (SAVS/SAMSAH/SESSAD)"
* $TRE-R358-MotifStatutPersonnePriseCharge#135 "Fin de période d'essai"
* $TRE-R358-MotifStatutPersonnePriseCharge#136 "Renouvellement"
* $TRE-R358-MotifStatutPersonnePriseCharge#146 "L'usager a pu entrer en apprentissage"
* $TRE-R358-MotifStatutPersonnePriseCharge#147 "L'usager a pu se réinsérer en milieu ordinaire"
* $TRE-R358-MotifStatutPersonnePriseCharge#157 "Hospitalisation"
* $TRE-R358-MotifStatutPersonnePriseCharge#158 "L'usager est admis dans un établissement pour personnes âgées"
* $TRE-R358-MotifStatutPersonnePriseCharge#159 "Fin de formation"
* $TRE-R358-MotifStatutPersonnePriseCharge#172 "Changement de situation de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#184 "L'usager est accueilli en famille d'accueil"
* $TRE-R358-MotifStatutPersonnePriseCharge#204 "Fin de l'accueil temporaire"
* $TRE-R358-MotifStatutPersonnePriseCharge#253 "L'usager est transféré dans une autre unité"