ValueSet: JDV_J71_ProfessionFonction_MSSante
Id: JDV-J71-ProfessionFonction-MSSante
Description: "Professions et fonctions MSSanté"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:06:52.686+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-05-29T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J71-ProfessionFonction-MSSante/FHIR/JDV-J71-ProfessionFonction-MSSante"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.9.1.2"
* ^version = "20260629120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-06-29T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-G15-ProfessionSante#10 "Médecin"
* $TRE-G15-ProfessionSante#21 "Pharmacien"
* $TRE-G15-ProfessionSante#26 "Audioprothésiste"
* $TRE-G15-ProfessionSante#28 "Opticien-Lunetier"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#81 "Orthoprothésiste"
* $TRE-G15-ProfessionSante#82 "Podo-Orthésiste"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#84 "Oculariste"
* $TRE-G15-ProfessionSante#85 "Epithésiste"
* $TRE-G15-ProfessionSante#86 "Technicien de laboratoire médical"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"
* $TRE-G15-ProfessionSante#94 "Ergothérapeute"
* $TRE-G15-ProfessionSante#95 "Diététicien"
* $TRE-G15-ProfessionSante#96 "Psychomotricien"
* $TRE-G15-ProfessionSante#98 "Manipulateur ERM"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie (officine)"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"