ValueSet: JDV_J136_DisciplineEquipementSocial_RASS
Id: JDV-J136-DisciplineEquipementSocial-RASS
Description: "Disciplines d'équipement pour le social dans le RASS"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:05:07.487+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^extension.valuePeriod.end = "2026-02-23T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J136-DisciplineEquipementSocial-RASS/FHIR/JDV-J136-DisciplineEquipementSocial-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.222"
* ^version = "20260223120000"
* ^status = #retired
* ^experimental = false
* ^date = "2026-02-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R280-DisciplineEquipementSocial#177 "Section Cure Médicale (dont)"
* $TRE-R280-DisciplineEquipementSocial#246 "Hébergement Accueil Mère Enfant"
* $TRE-R280-DisciplineEquipementSocial#247 "Hébergement en centre parental"
* $TRE-R280-DisciplineEquipementSocial#257 "Aide éducative à Domicile"
* $TRE-R280-DisciplineEquipementSocial#258 "Action Éducative en Milieu Ouvert"
* $TRE-R280-DisciplineEquipementSocial#259 "Activ.Club et Équipe de Prévention"
* $TRE-R280-DisciplineEquipementSocial#278 "Aide Psychologique Universitaire"
* $TRE-R280-DisciplineEquipementSocial#320 "Activité C.M.P.P."
* $TRE-R280-DisciplineEquipementSocial#354 "Restaurant pour Personnes Âgées"
* $TRE-R280-DisciplineEquipementSocial#357 "Activité soins d'accompagnement et de réhabilitation"
* $TRE-R280-DisciplineEquipementSocial#358 "Soins infirmiers à Domicile"
* $TRE-R280-DisciplineEquipementSocial#359 "Repas à Domicile"
* $TRE-R280-DisciplineEquipementSocial#360 "Blanchisserie à Domicile"
* $TRE-R280-DisciplineEquipementSocial#365 "Alarme Médico-Sociale"
* $TRE-R280-DisciplineEquipementSocial#377 "Stationnement Pour Nomades"
* $TRE-R280-DisciplineEquipementSocial#380 "Mesure judiciaire aide gestion budget familial"
* $TRE-R280-DisciplineEquipementSocial#381 "Héberg. non médicalisé de patients, accompagnants, aidants"
* $TRE-R280-DisciplineEquipementSocial#382 "Tutelle aux Prestations Sociales"
* $TRE-R280-DisciplineEquipementSocial#399 "Préorientation pour Adultes handicapés"
* $TRE-R280-DisciplineEquipementSocial#410 "Information,conseil, expertise, coordination"
* $TRE-R280-DisciplineEquipementSocial#411 "Evaluation des situations des personnes"
* $TRE-R280-DisciplineEquipementSocial#412 "Centre de ressources territorial pour les personnes âgées"
* $TRE-R280-DisciplineEquipementSocial#442 "Veille sociale"
* $TRE-R280-DisciplineEquipementSocial#443 "Soutien et accompagnement social"
* $TRE-R280-DisciplineEquipementSocial#445 "Aide Psychopédagogique"
* $TRE-R280-DisciplineEquipementSocial#469 "Aide à Domicile"
* $TRE-R280-DisciplineEquipementSocial#506 "Evaluat réentraînem orientat soc. et socioprof cérébro-lésés"
* $TRE-R280-DisciplineEquipementSocial#507 "Hébergement médico soc personnes en difficultés spécifiques"
* $TRE-R280-DisciplineEquipementSocial#508 "Accueil orientation soins accompagnement diff spécifiques"
* $TRE-R280-DisciplineEquipementSocial#511 "Equipe mobile santé précarité"
* $TRE-R280-DisciplineEquipementSocial#512 "Equipe spécialisée de soins infirmiers précarité"
* $TRE-R280-DisciplineEquipementSocial#520 "Tutelle curatelle mandat spécial sauvegarde justice pers maj"
* $TRE-R280-DisciplineEquipementSocial#521 "Mesure d'accompagnement judiciaire"
* $TRE-R280-DisciplineEquipementSocial#522 "Mesure d'accompagnement social personnalisé"
* $TRE-R280-DisciplineEquipementSocial#523 "Information des tuteurs familiaux"
* $TRE-R280-DisciplineEquipementSocial#633 "Services expérimentaux en faveur des personnes âgées"
* $TRE-R280-DisciplineEquipementSocial#655 "Prestation de Service Pr Association"
* $TRE-R280-DisciplineEquipementSocial#657 "Accueil temporaire pour Personnes Âgées"
* $TRE-R280-DisciplineEquipementSocial#660 "Réalisation d'Enquêtes sociales"
* $TRE-R280-DisciplineEquipementSocial#661 "Permanence des Assistants de Service Social"
* $TRE-R280-DisciplineEquipementSocial#697 "Intermédiaire de placement Social"
* $TRE-R280-DisciplineEquipementSocial#714 "Recherche dans Domaine Social"
* $TRE-R280-DisciplineEquipementSocial#840 "Accompagnement précoce de jeunes enfants"
* $TRE-R280-DisciplineEquipementSocial#841 "Acc. dans l'acquisition de l'autonomie et la scolarisation"
* $TRE-R280-DisciplineEquipementSocial#842 "Préparation à la vie professionnelle"
* $TRE-R280-DisciplineEquipementSocial#843 "Accompagnement enseignement supérieur"
* $TRE-R280-DisciplineEquipementSocial#844 "Tous projets éducatifs thérapeutiques et pédagogiques"
* $TRE-R280-DisciplineEquipementSocial#900 "Action Médico-Sociale Précoce"
* $TRE-R280-DisciplineEquipementSocial#906 "Réadaptation Professionnelle pour Adultes Handicapés"
* $TRE-R280-DisciplineEquipementSocial#907 "Adaptation à la vie active"
* $TRE-R280-DisciplineEquipementSocial#908 "Aide par le travail pour Adultes Handicapés"
* $TRE-R280-DisciplineEquipementSocial#909 "Travail protégé pour Adultes Handicapés"
* $TRE-R280-DisciplineEquipementSocial#912 "Accueil au titre de la protection de l'enfance"
* $TRE-R280-DisciplineEquipementSocial#913 "Accueil d'urgence protection de l'enfance"
* $TRE-R280-DisciplineEquipementSocial#914 "Accueil temporaire saisonnier ou week-end protection de l'enfance"
* $TRE-R280-DisciplineEquipementSocial#916 "Hébergement Réadapt. Sociale Pers.Familles en Difficulté"
* $TRE-R280-DisciplineEquipementSocial#920 "Hébergement Ouvert en Ets Pr Adultes & Familles"
* $TRE-R280-DisciplineEquipementSocial#921 "Séjours de rupture/distanciation/apaisement"
* $TRE-R280-DisciplineEquipementSocial#922 "Accueil Temporaire d'Urgence Pr Adultes & Familles"
* $TRE-R280-DisciplineEquipementSocial#923 "Accueil Temp.Saisonnier ou W E Adultes & Familles"
* $TRE-R280-DisciplineEquipementSocial#924 "Accueil pour Personnes Âgées"
* $TRE-R280-DisciplineEquipementSocial#925 "Hébergement résidence autonomie personnes âgées seules F1"
* $TRE-R280-DisciplineEquipementSocial#926 "Hébergement résidence autonomie personnes âgées couple F2"
* $TRE-R280-DisciplineEquipementSocial#927 "Hébergement résidence autonomie personnes âgées F1BIS"
* $TRE-R280-DisciplineEquipementSocial#928 "Observation en Milieu Ouvert Pour Mineurs Justice (O.M.O)"
* $TRE-R280-DisciplineEquipementSocial#929 "Consultation d'Orientation Pour Mineurs Justice"
* $TRE-R280-DisciplineEquipementSocial#930 "Observation Orientation Pour Mineurs Justice"
* $TRE-R280-DisciplineEquipementSocial#931 "Suivi Social en Milieu Ouvert"
* $TRE-R280-DisciplineEquipementSocial#932 "Animation de la Vie Sociale"
* $TRE-R280-DisciplineEquipementSocial#935 "Activités des Établissements Expérimentaux"
* $TRE-R280-DisciplineEquipementSocial#937 "Réinsertion Par l'Économie"
* $TRE-R280-DisciplineEquipementSocial#939 "Accueil médicalisé pour adultes handicapés"
* $TRE-R280-DisciplineEquipementSocial#941 "Maisons Relais - Résidence Accueil"
* $TRE-R280-DisciplineEquipementSocial#942 "Maisons Relais pour Personnes Vieillissantes"
* $TRE-R280-DisciplineEquipementSocial#943 "Maisons Relais \"Classique\""
* $TRE-R280-DisciplineEquipementSocial#944 "Résidences Sociales ex Foyer Jeunes Travailleurs"
* $TRE-R280-DisciplineEquipementSocial#945 "Résidences Sociales ex Foyers Travailleurs Migrants"
* $TRE-R280-DisciplineEquipementSocial#946 "Résidences Sociales créées ex Nihilo"
* $TRE-R280-DisciplineEquipementSocial#947 "Résidence sociale FJT"
* $TRE-R280-DisciplineEquipementSocial#948 "C.H.R.S. Hors les murs"
* $TRE-R280-DisciplineEquipementSocial#957 "Hébergement d'insertion Adultes,Familles Difficulté"
* $TRE-R280-DisciplineEquipementSocial#958 "Hébergement de Stabilisation Adultes,familles Difficulté"
* $TRE-R280-DisciplineEquipementSocial#959 "Hébergement d'Urgence Adultes, Familles Difficulté"
* $TRE-R280-DisciplineEquipementSocial#960 "Hébergement d'Urgence avec Accompagnement Social (H.U.A.S.)"
* $TRE-R280-DisciplineEquipementSocial#961 "Pôles d'activité et de soins adaptés"
* $TRE-R280-DisciplineEquipementSocial#962 "Unités d'hébergement renforcées"
* $TRE-R280-DisciplineEquipementSocial#963 "Plateforme d'accompagnement et de répit des aidants (PFR)"
* $TRE-R280-DisciplineEquipementSocial#964 "Accueil et accompagnement spécialisé personnes handicapés"
* $TRE-R280-DisciplineEquipementSocial#965 "Accueil et accompagnement non médical. personnes handicapées"
* $TRE-R280-DisciplineEquipementSocial#966 "Accueil et accompagnement médicalisé personnes handicapées"