ValueSet: JDV_J251_MotifStatutPersonnePriseChargeESMS
Id: JDV-J251-MotifStatutPersonnePriseChargeESMS
Description: "Motif du statut de la personne prise en charge au sein d'un ESMS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:06:18.559+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-06-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J251-MotifStatutPersonnePriseChargeESMS/FHIR/JDV-J251-MotifStatutPersonnePriseChargeESMS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.115"
* ^version = "20230922120000"
* ^status = #active
* ^experimental = false
* ^date = "2023-09-22T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R358-MotifStatutPersonnePriseCharge#86 "Le plateau technique n'est pas adapté à la prise en charge de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#109 "Déménagement"
* $TRE-R358-MotifStatutPersonnePriseCharge#112 "Erreur d'utilisation du logiciel"
* $TRE-R358-MotifStatutPersonnePriseCharge#113 "Eloignement géographique"
* $TRE-R358-MotifStatutPersonnePriseCharge#114 "Les ressources de l'ESMS ne sont pas suffisantes"
* $TRE-R358-MotifStatutPersonnePriseCharge#115 "L'ESMS n'est pas adapté au projet de vie actuel de l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#116 "Le type de handicap ne relève pas de l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#117 "La situation de l'usager a changé, l'ESMS n'est pas adapté"
* $TRE-R358-MotifStatutPersonnePriseCharge#118 "L'usager ou son représentant légal refuse de s'inscrire dans l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#119 "L'usager a été admis dans un autre ESMS, l'orientation n'est plus pertinente"
* $TRE-R358-MotifStatutPersonnePriseCharge#120 "L'usager a déménagé, l'orientation n'est plus pertinente géographiquement"
* $TRE-R358-MotifStatutPersonnePriseCharge#121 "L'usager ou son représentant légal refuse d'adhérer au projet de vie de l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#122 "L'âge de l'usager est incompatible"
* $TRE-R358-MotifStatutPersonnePriseCharge#124 "L'usager est décédé"
* $TRE-R358-MotifStatutPersonnePriseCharge#127 "L'usager a fait valoir ses droits à la retraite (ESAT)"
* $TRE-R358-MotifStatutPersonnePriseCharge#148 "L'ESMS n'a pas réussi à joindre l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#150 "L'usager a pris contact avec l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#151 "L'ESMS a pris contact avec l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#152 "L'usager a visité l'ESMS"
* $TRE-R358-MotifStatutPersonnePriseCharge#153 "L'ESMS a envoyé une documentation à l'usager"
* $TRE-R358-MotifStatutPersonnePriseCharge#168 "Pour placer l'usager en liste d'attente"
* $TRE-R358-MotifStatutPersonnePriseCharge#170 "Pour prendre en charge l'usager à temps adapté"
* $TRE-R358-MotifStatutPersonnePriseCharge#173 "Une autre décision annule et remplace cette décision"
* $TRE-R358-MotifStatutPersonnePriseCharge#174 "Décision clôturée par la MDPH"