ValueSet: JDV_J100_FinessStatutJuridique_RASS
Id: JDV-J100-FinessStatutJuridique-RASS
Description: "Statut juridique FINESS dans le RASS"
* ^meta.versionId = "4"
* ^meta.lastUpdated = "2026-07-06T19:04:38.438+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J100-FinessStatutJuridique-RASS/FHIR/JDV-J100-FinessStatutJuridique-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.168"
* ^version = "20200424120000"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R72-FinessStatutJuridique#000 "En cours de vérification"
* $TRE-R72-FinessStatutJuridique#01 "Etat"
* $TRE-R72-FinessStatutJuridique#02 "Département"
* $TRE-R72-FinessStatutJuridique#03 "Commune"
* $TRE-R72-FinessStatutJuridique#04 "Région"
* $TRE-R72-FinessStatutJuridique#05 "Territoire d'Outre Mer"
* $TRE-R72-FinessStatutJuridique#06 "Autre Collectivité Territoriale"
* $TRE-R72-FinessStatutJuridique#07 "Métropole ou pôle métropolitain"
* $TRE-R72-FinessStatutJuridique#08 "Centre Intercommunal d'Action Sociale"
* $TRE-R72-FinessStatutJuridique#10 "Etablissement Public National d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#11 "Etablissement Public Départemental d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#12 "Etablissement Public Interdépartemental d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#13 "Etablissement Public Communal d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#14 "Etablissement Public Intercommunal d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#15 "Etablissement Public Régional d'Hospitalisation"
* $TRE-R72-FinessStatutJuridique#16 "Syndicat Inter Hospitalier"
* $TRE-R72-FinessStatutJuridique#17 "Centre Communal d'Action Sociale"
* $TRE-R72-FinessStatutJuridique#18 "Etablissement Social et Médico-Social National"
* $TRE-R72-FinessStatutJuridique#19 "Etablissement Social et Médico-Social Départemental"
* $TRE-R72-FinessStatutJuridique#20 "Etablissement Social et Médico-Social Interdépartemental"
* $TRE-R72-FinessStatutJuridique#21 "Etablissement Social et Médico-Social Communal"
* $TRE-R72-FinessStatutJuridique#22 "Etablissement Social et Médico-Social Intercommunal"
* $TRE-R72-FinessStatutJuridique#23 "Etablissement Social et Médico-Social Régional"
* $TRE-R72-FinessStatutJuridique#24 "Office Public d'H.L.M."
* $TRE-R72-FinessStatutJuridique#25 "Caisse des Ecoles"
* $TRE-R72-FinessStatutJuridique#26 "Autre Etablissement Public à Caractère Administratif"
* $TRE-R72-FinessStatutJuridique#27 "Etablissement Public à Caractère Industriel ou Commercial"
* $TRE-R72-FinessStatutJuridique#28 "Groupement d'Intérêt Public (G.I.P.)"
* $TRE-R72-FinessStatutJuridique#29 "Groupement de Coopération Sanitaire public"
* $TRE-R72-FinessStatutJuridique#30 "Groupement de Coopération Sociale ou Médico-Sociale public"
* $TRE-R72-FinessStatutJuridique#40 "Régime Général de Sécurité Sociale"
* $TRE-R72-FinessStatutJuridique#41 "Régime Spécial de Sécurité Sociale"
* $TRE-R72-FinessStatutJuridique#42 "Institution de Prévoyance"
* $TRE-R72-FinessStatutJuridique#43 "Mutualité Sociale Agricole (M.S.A.)"
* $TRE-R72-FinessStatutJuridique#44 "Régime Maladie des non Salariés non Agricole"
* $TRE-R72-FinessStatutJuridique#45 "Régime Vieillesse Particulier"
* $TRE-R72-FinessStatutJuridique#46 "Autre Régime de Prévoyance Sociale"
* $TRE-R72-FinessStatutJuridique#47 "Société Mutualiste"
* $TRE-R72-FinessStatutJuridique#48 "Assurance Mutuelle Agricole"
* $TRE-R72-FinessStatutJuridique#49 "Autre Organisme Mutualiste"
* $TRE-R72-FinessStatutJuridique#50 "Comité d'Entreprise ou Comité d'Etablissement"
* $TRE-R72-FinessStatutJuridique#51 "Syndicat"
* $TRE-R72-FinessStatutJuridique#52 "Syndicat de Propriétaires"
* $TRE-R72-FinessStatutJuridique#60 "Association Loi 1901 non Reconnue d'Utilité Publique"
* $TRE-R72-FinessStatutJuridique#61 "Association Loi 1901 Reconnue d'Utilité Publique"
* $TRE-R72-FinessStatutJuridique#62 "Association de Droit Local"
* $TRE-R72-FinessStatutJuridique#63 "Fondation"
* $TRE-R72-FinessStatutJuridique#64 "Congrégation"
* $TRE-R72-FinessStatutJuridique#65 "Autre Organisme Privé à But non Lucratif"
* $TRE-R72-FinessStatutJuridique#66 "Groupement de Coopération Sociale ou Médico-Sociale privé"
* $TRE-R72-FinessStatutJuridique#70 "Personne Physique"
* $TRE-R72-FinessStatutJuridique#71 "Société en Nom Collectif (S.N.C.)"
* $TRE-R72-FinessStatutJuridique#72 "Société A Responsabilité Limitée (S.A.R.L.)"
* $TRE-R72-FinessStatutJuridique#73 "Société Anonyme (S.A.)"
* $TRE-R72-FinessStatutJuridique#74 "Société Civile"
* $TRE-R72-FinessStatutJuridique#75 "Autre Société"
* $TRE-R72-FinessStatutJuridique#76 "Groupement d'Intérêt Economique (G.I.E.)"
* $TRE-R72-FinessStatutJuridique#77 "Autre Organisme Privé à Caractère Commercial"
* $TRE-R72-FinessStatutJuridique#78 "Entreprise Unipersonnelle Responsabilité Limitée (E.U.R.L.)"
* $TRE-R72-FinessStatutJuridique#79 "Société Civile de Moyens (S.C.M.)"
* $TRE-R72-FinessStatutJuridique#80 "Société Interprofessionnelle Soins Ambulatoires (S.I.S.A.)"
* $TRE-R72-FinessStatutJuridique#85 "Soc. Exercice Libéral Responsabilité Limitée (S.E.L.A.R.L.)"
* $TRE-R72-FinessStatutJuridique#86 "Société d'Exercice Libéral à Forme Anonyme (S.E.L.A.F.A.)"
* $TRE-R72-FinessStatutJuridique#87 "Société Exercice Libéral Commandite par Actions (S.E.L.C.A.)"
* $TRE-R72-FinessStatutJuridique#88 "Société Civile Professionnelle (S.C.P.)"
* $TRE-R72-FinessStatutJuridique#89 "Groupement de Coopération Sanitaire Privé"
* $TRE-R72-FinessStatutJuridique#90 "Organisme de Droit Etranger"
* $TRE-R72-FinessStatutJuridique#91 "Société Exercice Libéral par Actions Simplifiée (S.E.L.A.S.)"
* $TRE-R72-FinessStatutJuridique#93 "Société en commandite"
* $TRE-R72-FinessStatutJuridique#95 "Société par Actions Simplifiée (S.A.S.)"
* $TRE-R72-FinessStatutJuridique#100 "Société d'exercice libéral à responsabilité limitée unipersonnelle (SELURL)"
* $TRE-R72-FinessStatutJuridique#101 "Société d'exercice libéral par actions simplifiée (SELAS)"
* $TRE-R72-FinessStatutJuridique#102 "Société d'exercice libéral par actions simplifiée unipersonnelle (SELASU)"
* $TRE-R72-FinessStatutJuridique#103 "Société en commandite simple (SCS)"
* $TRE-R72-FinessStatutJuridique#104 "Société en commandite par actions (SCA)"
* $TRE-R72-FinessStatutJuridique#105 "Société par actions simplifiée (SAS)"
* $TRE-R72-FinessStatutJuridique#106 "Société anonyme à directoire (SADI)"
* $TRE-R72-FinessStatutJuridique#107 "Société Anonyme à conseil d'administration (SACA)"
* $TRE-R72-FinessStatutJuridique#110 "Société en participation (SEP)"