ValueSet: JDV_J33_CompetenceSpecifique_ROR
Id: JDV-J33-CompetenceSpecifique-ROR
Description: "Compétence spécifique - ROR"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:06:31.038+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2017-10-13T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J33-CompetenceSpecifique-ROR/FHIR/JDV-J33-CompetenceSpecifique-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.38"
* ^version = "20260629120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-06-29T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R243-CompetenceSpecifique#01 "Maîtrise de la Langue des Signes Française (LSF)"
* $TRE-R243-CompetenceSpecifique#02 "Maîtrise de la Langue Parlé Complété (LPC)"
* $TRE-R243-CompetenceSpecifique#03 "Maîtrise de la lecture et de l'écriture du Braille"
* $TRE-R243-CompetenceSpecifique#04 "Art-thérapeute"
* $TRE-R243-CompetenceSpecifique#05 "Neuropsychologue"
* $TRE-R243-CompetenceSpecifique#06 "Maîtrise de langue étrangère"
* $TRE-R243-CompetenceSpecifique#07 "Maîtrise de langue régionale"
* $TRE-R243-CompetenceSpecifique#08 "Intervenant pair (médiateur, pair-aidant)"
* $TRE-R243-CompetenceSpecifique#10 "Socio-esthéticienne"
* $TRE-R243-CompetenceSpecifique#11 "Enseignant du 1er degré"
* $TRE-R243-CompetenceSpecifique#12 "Enseignant du 2nd degré"
* $TRE-R243-CompetenceSpecifique#13 "Enseignant du supérieur"
* $TRE-R243-CompetenceSpecifique#14 "Puéricultrice"
* $TRE-R243-CompetenceSpecifique#19 "Médecin coordonnateur"
* $TRE-R243-CompetenceSpecifique#20 "Infirmier coordonnateur"
* $TRE-R243-CompetenceSpecifique#21 "Phoniatre"
* $TRE-R243-CompetenceSpecifique#22 "Audio phonologue"
* $TRE-R243-CompetenceSpecifique#23 "Ingénieur en analyse du mouvement"
* $TRE-R243-CompetenceSpecifique#24 "Psychologue clinicien"
* $TRE-R243-CompetenceSpecifique#25 "Animateur socio-culturel"
* $TRE-R243-CompetenceSpecifique#26 "Moniteur d'atelier"
* $TRE-R243-CompetenceSpecifique#27 "Maîtrise de la Méthode verbo-tonale : aide à l'apprentissage de la parole"
* $TRE-R243-CompetenceSpecifique#29 "Maîtrise du PECS"
* $TRE-R243-CompetenceSpecifique#30 "Maîtrise de la Méthode ABA"
* $TRE-R243-CompetenceSpecifique#31 "Maîtrise du MAKATON"
* $TRE-R243-CompetenceSpecifique#32 "Maîtrise des Gestes Borel-Maisonny"
* $TRE-R243-CompetenceSpecifique#33 "Maîtrise de la COGHAMO"
* $TRE-R243-CompetenceSpecifique#34 "Maîtrise des Codes de communication pictographiques (classeurs, planches)"
* $TRE-R243-CompetenceSpecifique#35 "Maîtrise des outils informatisés avec synthèse vocale à entrée orthographique ou pictographique (téléthèses, logiciels de communication)"
* $TRE-R243-CompetenceSpecifique#36 "Maîtrise des logiciels d'aide à la transcription (retour vocal, prédicteur de mots)"
* $TRE-R243-CompetenceSpecifique#37 "Ostéopathe"
* $TRE-R243-CompetenceSpecifique#38 "Enseignant en Activité Physique Adaptée (EAPA)"
* $TRE-R243-CompetenceSpecifique#39 "Accompagnant des Élèves en Situation de Handicap (AESH)"
* $TRE-R243-CompetenceSpecifique#40 "Maîtrise de programmes d'intervention globaux à référence développementale (TEACCH, DENVER,...)"
* $TRE-R243-CompetenceSpecifique#41 "Psychiatre"
* $TRE-R243-CompetenceSpecifique#42 "Gériatre"
* $TRE-R243-CompetenceSpecifique#43 "Pédopsychiatre"
* $TRE-R243-CompetenceSpecifique#44 "Veilleur de nuit"
* $TRE-R243-CompetenceSpecifique#45 "Assistant(e) de soins en gérontologie"
* $TRE-R243-CompetenceSpecifique#46 "Conseillère en économie sociale et familiale (CESF)"
* $TRE-R243-CompetenceSpecifique#47 "Aide médico psychologique (AMP)"
* $TRE-R243-CompetenceSpecifique#48 "Auxiliaire de vie sociale (AVS)"
* $TRE-R243-CompetenceSpecifique#49 "Accompagnant Educatif et Social (AES)"
* $TRE-R243-CompetenceSpecifique#50 "Avéjiste"
* $TRE-R243-CompetenceSpecifique#51 "Instructeur en locomotion"
* $TRE-R243-CompetenceSpecifique#52 "Educateur sportif"
* $TRE-R243-CompetenceSpecifique#53 "Conseiller en insertion professionnelle"
* $TRE-R243-CompetenceSpecifique#54 "Coordonnateur et gestionnaire de parcours handicap"
* $TRE-R243-CompetenceSpecifique#55 "Neuropédiatre"
* $TRE-R243-CompetenceSpecifique#56 "Psychopédagogue"
* $TRE-R243-CompetenceSpecifique#57 "Ergonome"
* $TRE-R243-CompetenceSpecifique#58 "Psychologue du travail"
* $TRE-R243-CompetenceSpecifique#59 "Tabacologue"
* $TRE-R243-CompetenceSpecifique#60 "Addictologue"
* $TRE-R243-CompetenceSpecifique#61 "Conseiller conjugal et familial"
* $TRE-R243-CompetenceSpecifique#62 "Maîtrise du Facile à Lire et à Comprendre (FALC)"
* $TRE-R243-CompetenceSpecifique#63 "Maitrise des outils informatisés à commande oculaire"