ValueSet: JDV_J14_QualiteRepresentantLegal_CISIS
Id: JDV-J14-QualiteRepresentantLegal-CISIS
Description: "Qualité représentant légal - CI-SIS"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:05:14.354+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J14-QualiteRepresentantLegal-CISIS/FHIR/JDV-J14-QualiteRepresentantLegal-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.468"
* ^version = "20241213120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-12-13T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R216-HL7RoleCode#MTH "Mère"
* $TRE-R216-HL7RoleCode#FTH "Père"
* $TRE-R216-HL7RoleCode#STPMTH "Belle-mère - épouse du père ou de la mère"
* $TRE-R216-HL7RoleCode#STPFTH "Beau-père - époux du père ou de la mère"
* $TRE-R216-HL7RoleCode#GRMTH "Grand-mère"
* $TRE-R216-HL7RoleCode#GRFTH "Grand-père"
* $TRE-R216-HL7RoleCode#GGRMTH "Arrière-grand-mère"
* $TRE-R216-HL7RoleCode#GGRFTH "Arrière-grand-père"
* $TRE-R216-HL7RoleCode#BRO "Frère"
* $TRE-R216-HL7RoleCode#SIS "Soeur"
* $TRE-R216-HL7RoleCode#GRNDDAU "Petite-fille"
* $TRE-R216-HL7RoleCode#GRNDSO "Petit-fils"
* $TRE-R216-HL7RoleCode#UNCLE "Oncle"
* $TRE-R216-HL7RoleCode#AUNT "Tante"
* $TRE-R216-HL7RoleCode#SPS "Epoux ou épouse"
* $TRE-R216-HL7RoleCode#DOMPART "Concubin(e) ou partenaire PACS"
* $TRE-R216-HL7RoleCode#DAUC "Fille"
* $TRE-R216-HL7RoleCode#SONC "Fils"
* $TRE-R216-HL7RoleCode#FMRSPS "Ancien époux ou ancienne épouse"
* $TRE-R216-HL7RoleCode#SONINLAW "Gendre"
* $TRE-R216-HL7RoleCode#ADOPTF "Père adoptif"
* $TRE-R216-HL7RoleCode#ADOPTM "Mère adoptive"
* $TRE-R216-HL7RoleCode#FTHFOST "Assistant familial - Famille d'accueil"
* $TRE-R216-HL7RoleCode#COUSN "Cousin(e)"
* $TRE-R216-HL7RoleCode#BROINLAW "Beau-frère"
* $TRE-R216-HL7RoleCode#CHILD "Enfant"
* $TRE-R216-HL7RoleCode#DAUINLAW "Belle-fille"
* $TRE-R216-HL7RoleCode#FAMMEMB "Autre membre de la famille"
* $TRE-R216-HL7RoleCode#FRND "Autre proche"
* $TRE-R216-HL7RoleCode#FTHINLAW "Beau-père"
* $TRE-R216-HL7RoleCode#HBRO "Demi-frère"
* $TRE-R216-HL7RoleCode#HUSB "Epoux"
* $TRE-R216-HL7RoleCode#MTHFOST "Assistante familiale - Famille d'accueil"
* $TRE-R216-HL7RoleCode#MTHINLAW "Belle-mère"
* $TRE-R216-HL7RoleCode#NEPHEW "Neveu"
* $TRE-R216-HL7RoleCode#NIECE "Nièce"
* $TRE-R216-HL7RoleCode#SIGOTHR "Conjoint"
* $TRE-R216-HL7RoleCode#SISINLAW "Belle-soeur"
* $TRE-R216-HL7RoleCode#STPSIS "Fille du beau-père ou de la belle-mère"
* $TRE-R216-HL7RoleCode#STPSON "Fils du conjoint, issu d'un mariage précédent"
* $TRE-R216-HL7RoleCode#WIFE "Epouse"
* $TRE-R216-HL7RoleCode#STPDAU "Fille du conjoint, issue d'un mariage précédent"
* $TRE-R216-HL7RoleCode#HSIS "Demi-soeur"