ValueSet: JDV_J35_SpecialisationDePriseEnCharge_ROR
Id: JDV-J35-SpecialisationDePriseEnCharge-ROR
Description: "Spécialisation de prise en charge - ROR"
* ^meta.versionId = "13"
* ^meta.lastUpdated = "2026-07-06T19:06:33.852+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2017-10-13T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J35-SpecialisationDePriseEnCharge-ROR/FHIR/JDV-J35-SpecialisationDePriseEnCharge-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.42"
* ^version = "20260330120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R245-SpecialisationDePriseEnCharge#01 "Troubles des conduites alimentaires (TCA)"
* $TRE-R245-SpecialisationDePriseEnCharge#02 "Troubles du spectre de l'autisme"
* $TRE-R245-SpecialisationDePriseEnCharge#03 "Troubles du déficit de l'attention avec ou sans hyperactivité (TDAH)"
* $TRE-R245-SpecialisationDePriseEnCharge#04 "Troubles psychiques des victimes de violences sexuelles"
* $TRE-R245-SpecialisationDePriseEnCharge#05 "Troubles psychiques des auteurs de violences sexuelles"
* $TRE-R245-SpecialisationDePriseEnCharge#06 "Schizophrénie émergente"
* $TRE-R245-SpecialisationDePriseEnCharge#07 "Troubles psychotiques (schizophrénie, délires)"
* $TRE-R245-SpecialisationDePriseEnCharge#08 "Troubles de l'humeur (bipolaire, dépression...)"
* $TRE-R245-SpecialisationDePriseEnCharge#09 "Troubles Obsessionnels Compulsifs (TOC)"
* $TRE-R245-SpecialisationDePriseEnCharge#10 "Conduites addictives"
* $TRE-R245-SpecialisationDePriseEnCharge#11 "Troubles spécifiques de la communication (dysphasie, bégaiement, etc.) et / ou des apprentissages (dyslexie, dysorthographie, dyscalculie) hors TSA"
* $TRE-R245-SpecialisationDePriseEnCharge#12 "Troubles psychiques dûs à une affection organique ou à une lésion cérébrale (épilepsie...)"
* $TRE-R245-SpecialisationDePriseEnCharge#13 "Démence dégénérative"
* $TRE-R245-SpecialisationDePriseEnCharge#14 "Troubles du développement intellectuel (TDI)"
* $TRE-R245-SpecialisationDePriseEnCharge#16 "Handicap psychique"
* $TRE-R245-SpecialisationDePriseEnCharge#17 "Polyhandicap"
* $TRE-R245-SpecialisationDePriseEnCharge#18 "Déficience auditive grave"
* $TRE-R245-SpecialisationDePriseEnCharge#19 "Déficience visuelle grave"
* $TRE-R245-SpecialisationDePriseEnCharge#21 "Handicap rare"
* $TRE-R245-SpecialisationDePriseEnCharge#22 "Déficience à prédominance motrice"
* $TRE-R245-SpecialisationDePriseEnCharge#23 "Handicap cognitif spécifique"
* $TRE-R245-SpecialisationDePriseEnCharge#24 "Handicap à prédominance cognitive avec trouble du comportement (dont traumatisé crânien, syndrome de Korsakoff,...)"
* $TRE-R245-SpecialisationDePriseEnCharge#25 "Surdi-cécité avec ou sans troubles associés"
* $TRE-R245-SpecialisationDePriseEnCharge#26 "Difficulté psychologique avec troubles du comportement"
* $TRE-R245-SpecialisationDePriseEnCharge#27 "Troubles neuro-cognitifs chroniques (Alzheimer et apparentées) avec troubles du comportement perturbateurs"
* $TRE-R245-SpecialisationDePriseEnCharge#28 "Maladies d'Alzheimer et apparentées"
* $TRE-R245-SpecialisationDePriseEnCharge#29 "Maladies rares liées à une anomalie du développement embryonnaire"
* $TRE-R245-SpecialisationDePriseEnCharge#30 "Maladies rares de l'infertilité"
* $TRE-R245-SpecialisationDePriseEnCharge#31 "Maladies rares allergiques"
* $TRE-R245-SpecialisationDePriseEnCharge#32 "Maladies rares cardiaques"
* $TRE-R245-SpecialisationDePriseEnCharge#33 "Maladies rares chirurgicales abdominales"
* $TRE-R245-SpecialisationDePriseEnCharge#34 "Maladies rares endocriniennes"
* $TRE-R245-SpecialisationDePriseEnCharge#35 "Maladies rares gastro-entérologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#36 "Maladies rares génétiques"
* $TRE-R245-SpecialisationDePriseEnCharge#37 "Maladies rares gynécologiques et obstétriques"
* $TRE-R245-SpecialisationDePriseEnCharge#38 "Maladies rares hématologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#39 "Maladies rares hépatiques"
* $TRE-R245-SpecialisationDePriseEnCharge#40 "Maladies rares immunologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#41 "Maladies rares infectieuses"
* $TRE-R245-SpecialisationDePriseEnCharge#42 "Maladies rares métaboliques"
* $TRE-R245-SpecialisationDePriseEnCharge#43 "Maladies rares néoplasiques"
* $TRE-R245-SpecialisationDePriseEnCharge#44 "Maladies rares neurologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#45 "Maladies rares odontologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#46 "Maladies rares ophtalmiques"
* $TRE-R245-SpecialisationDePriseEnCharge#47 "Maladies rares osseuses"
* $TRE-R245-SpecialisationDePriseEnCharge#48 "Maladies rares oto-rhino-laryngologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#49 "Maladies rares de la peau"
* $TRE-R245-SpecialisationDePriseEnCharge#50 "Maladies rares du système circulatoire"
* $TRE-R245-SpecialisationDePriseEnCharge#51 "Maladies rares dues à des effets toxiques"
* $TRE-R245-SpecialisationDePriseEnCharge#52 "Maladies rares liées à la transplantation"
* $TRE-R245-SpecialisationDePriseEnCharge#53 "Maladies rares rénales"
* $TRE-R245-SpecialisationDePriseEnCharge#54 "Maladies rares respiratoires"
* $TRE-R245-SpecialisationDePriseEnCharge#55 "Maladies rares systémiques et rhumatologiques"
* $TRE-R245-SpecialisationDePriseEnCharge#56 "Maladies rares systémiques ou rhumatologiques de l'enfant"
* $TRE-R245-SpecialisationDePriseEnCharge#57 "Maladies rares thoraciques chirurgicales"
* $TRE-R245-SpecialisationDePriseEnCharge#58 "Maladies rares urogénitales"
* $TRE-R245-SpecialisationDePriseEnCharge#59 "Maladies rares liées à une malformation cardiaque"
* $TRE-R245-SpecialisationDePriseEnCharge#60 "Maladies rares chirurgicales maxillo-faciales"
* $TRE-R245-SpecialisationDePriseEnCharge#61 "Maladies rares liées à un trouble tératologique rare"
* $TRE-R245-SpecialisationDePriseEnCharge#62 "Suicidant"
* $TRE-R245-SpecialisationDePriseEnCharge#63 "Troubles de la personnalité sévères"
* $TRE-R245-SpecialisationDePriseEnCharge#64 "Endométriose"
* $TRE-R245-SpecialisationDePriseEnCharge#65 "Troubles anxieux"
* $TRE-R245-SpecialisationDePriseEnCharge#66 "Troubles du neurodéveloppement à prédominance motrice (dont Trouble Développemental de la Coordination TDC, dyspraxie, mouvements stéréotypés, tics)"
* $TRE-R245-SpecialisationDePriseEnCharge#67 "Trouble psychotraumatique (dont Troubles Stress Post-Traumatique)"
* $TRE-R245-SpecialisationDePriseEnCharge#68 "Troubles cognitifs ou du comportement et de la relation affective dus à une lésion cérébrale acquise"