ValueSet: JDV_J54_Profession_ROR
Id: JDV-J54-Profession-ROR
Description: "Profession de santé - ROR"
* ^meta.versionId = "7"
* ^meta.lastUpdated = "2026-07-06T19:06:40.370+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2018-10-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J54-Profession-ROR/FHIR/JDV-J54-Profession-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.64"
* ^version = "20250523120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-05-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-G15-ProfessionSante#10 "Médecin"
* $TRE-G15-ProfessionSante#21 "Pharmacien"
* $TRE-G15-ProfessionSante#26 "Audioprothésiste"
* $TRE-G15-ProfessionSante#28 "Opticien-Lunetier"
* $TRE-G15-ProfessionSante#31 "Assistant dentaire"
* $TRE-G15-ProfessionSante#32 "Physicien médical"
* $TRE-G15-ProfessionSante#35 "Aide-soignant"
* $TRE-G15-ProfessionSante#36 "Ambulancier"
* $TRE-G15-ProfessionSante#37 "Auxiliaire de puériculture"
* $TRE-G15-ProfessionSante#38 "Préparateur en pharmacie hospitalière"
* $TRE-G15-ProfessionSante#39 "Préparateur en pharmacie (officine)"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#69 "Infirmier psychiatrique"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#81 "Orthoprothésiste"
* $TRE-G15-ProfessionSante#82 "Podo-Orthésiste"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#84 "Oculariste"
* $TRE-G15-ProfessionSante#85 "Epithésiste"
* $TRE-G15-ProfessionSante#86 "Technicien de laboratoire médical"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"
* $TRE-G15-ProfessionSante#93 "Psychologue"
* $TRE-G15-ProfessionSante#94 "Ergothérapeute"
* $TRE-G15-ProfessionSante#95 "Diététicien"
* $TRE-G15-ProfessionSante#96 "Psychomotricien"
* $TRE-G15-ProfessionSante#98 "Manipulateur ERM"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R94-ProfessionSocial#42 "Auxiliaire de vie sociale"
* $TRE-R94-ProfessionSocial#43 "Technicien de l'intervention sociale et familiale"
* $TRE-R94-ProfessionSocial#44 "Conseiller en économie sociale et familiale"
* $TRE-R94-ProfessionSocial#45 "Médiateur familial"
* $TRE-R94-ProfessionSocial#46 "Assistant familial"
* $TRE-R94-ProfessionSocial#47 "Aide médico-psychologique"
* $TRE-R94-ProfessionSocial#48 "Moniteur éducateur"
* $TRE-R94-ProfessionSocial#49 "Educateur de jeunes enfants"
* $TRE-R94-ProfessionSocial#51 "Educateur spécialisé"
* $TRE-R94-ProfessionSocial#52 "Educateur technique spécialisé"
* $TRE-R94-ProfessionSocial#53 "Accompagnant éducatif et social"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#97 "Conseiller en génétique"
* $TRE-R96-AutreFonctionSanitaire#407 "Tatoueur"
* $TRE-R96-AutreFonctionSanitaire#408 "Perceur corporel"
* $TRE-R96-AutreFonctionSanitaire#409 "Maquilleur permanent"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#350 "Aide à domicile"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"