ValueSet: JDV_J239_SpecialitesSNP_SAS
Id: JDV-J239-SpecialitesSNP-SAS
Description: "Professions de santé participant au Service d'Accès aux Soins"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:06:11.177+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-03-31T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J239-SpecialitesSNP-SAS/FHIR/JDV-J239-SpecialitesSNP-SAS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.104"
* ^version = "20240126120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-01-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R38-SpecialiteOrdinale#SM03 "Biologie médicale"
* $TRE-R38-SpecialiteOrdinale#SM04 "Cardio et Maladies vasculaires"
* $TRE-R38-SpecialiteOrdinale#SM15 "Dermatologie, Vénéréologie"
* $TRE-R38-SpecialiteOrdinale#SM16 "Endocrinologie, Métabolisme"
* $TRE-R38-SpecialiteOrdinale#SM19 "Gynécologie médicale"
* $TRE-R38-SpecialiteOrdinale#SM20 "Gynécologie-obstétrique"
* $TRE-R38-SpecialiteOrdinale#SM21 "Hématologie"
* $TRE-R38-SpecialiteOrdinale#SM32 "Neurologie"
* $TRE-R38-SpecialiteOrdinale#SM36 "Oncologie, opt médicale"
* $TRE-R38-SpecialiteOrdinale#SM38 "Ophtalmologie"
* $TRE-R38-SpecialiteOrdinale#SM39 "ORL"
* $TRE-R38-SpecialiteOrdinale#SM40 "Pédiatrie"
* $TRE-R38-SpecialiteOrdinale#SM42 "Psychiatrie"
* $TRE-R38-SpecialiteOrdinale#SM43 "Psychiatrie, opt enfant et ado"
* $TRE-R38-SpecialiteOrdinale#SM44 "Radio-diagnostic"
* $TRE-R38-SpecialiteOrdinale#SM54 "Médecine générale"
* $TRE-R38-SpecialiteOrdinale#SM57 "Allergologie"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#69 "Infirmier psychiatrique"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"