ValueSet: JDV_J215_DESCnonQualifiant_ROR
Id: JDV-J215-DESCnonQualifiant-ROR
Description: "DESC non qualifiant"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:05:57.355+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J215-DESCnonQualifiant-ROR/FHIR/JDV-J215-DESCnonQualifiant-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.47"
* ^version = "20220826120000"
* ^status = #active
* ^experimental = false
* ^date = "2022-08-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R42-DESCnonQualifiant#DSM200 "Addictologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM201 "Allergologie et Immunologie clinique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM202 "Andrologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM203 "Biochimie hormonale et métabolique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM204 "Biologie des agents infectieux (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM205 "Biologie moléculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM206 "Cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM207 "Chirurgie de la face et du cou (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM208 "Chirurgie plastique et reconstructrice (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM209 "Chirurgie vasculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM210 "Cytogénétique humaine (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM211 "Dermatopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM212 "Foetopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM213 "Gériatrie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM214 "Hématologie biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM215 "Hématologie maladies du sang (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM216 "Hémobiologie-transfusion (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM217 "Immunologie et Immunopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM218 "Médecine de la reproduction (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM219 "Médecine du sport (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM220 "Médecine d'urgence (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM221 "Médecine légale et Expertises médicales (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM222 "Médecine nucléaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM223 "Médecine vasculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM224 "Néonatalogie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM225 "Neuropathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM226 "Nutrition (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM227 "Orthopédie dento-maxillo-faciale (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM228 "Pathologie infectieuse et tropicale, clinique et biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM229 "Pharmacocinétique et Métabolisme des médicaments (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM230 "Pharmacologie clinique et Evaluation des thérapeutiques (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM231 "Psychiatrie de l'enfant et de l'adolescent (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM232 "Radiopharmacie et Radiobiologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM233 "Réanimation médicale (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM234 "Toxicologie biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM235 "Médecine de la douleur et Médecine palliative (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM236 "Cancérologie, option Traitements médicaux des cancers (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM237 "Cancérologie, option Chirurgie cancérologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM238 "Cancérologie, option Réseaux de cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM239 "Cancérologie, option Biologie cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM240 "Cancérologie, option Imagerie cancérologie (DNQ)"