ValueSet: JDV_J238_TypeOffre_ROR
Id: JDV-J238-TypeOffre-ROR
Description: "Prestations que peut réaliser une structure et qui permettent de répondre au besoin de santé d'une personne"
* ^meta.versionId = "33"
* ^meta.lastUpdated = "2026-07-06T19:06:10.658+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-01-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J238-TypeOffre-ROR/FHIR/JDV-J238-TypeOffre-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.65"
* ^version = "20260629120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-06-29T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R244-CategorieOrganisation#01 "Appartement thérapeutique en psychiatrie"
* $TRE-R244-CategorieOrganisation#02 "Atelier thérapeutique en psychiatrie"
* $TRE-R244-CategorieOrganisation#03 "Cellule d'Urgences Médico-Psychologique (CUMP)"
* $TRE-R244-CategorieOrganisation#04 "Centre d'Accueil Permanent (CAP)"
* $TRE-R244-CategorieOrganisation#05 "Centre d’Activités Thérapeutiques et de Temps de Groupe (CATTG) – ex CATTP"
* $TRE-R244-CategorieOrganisation#06 "Centre de crise"
* $TRE-R244-CategorieOrganisation#07 "Centre de soins post-aigus (CeSPA)"
* $TRE-R244-CategorieOrganisation#08 "Centre de Référence Troubles du Neuro-développement (TND) - Centre de Diagnostic et d’évaluation expert (CDE)"
* $TRE-R244-CategorieOrganisation#09 "Centre Expert"
* $TRE-R244-CategorieOrganisation#10 "Centre Médico-Psychologique (CMP) Adulte"
* $TRE-R244-CategorieOrganisation#11 "Hôpital De Jour (HDJ)"
* $TRE-R244-CategorieOrganisation#12 "Hôpital De Nuit (HDN)"
* $TRE-R244-CategorieOrganisation#13 "Service d'Accueil Familial Thérapeutique en psychiatrie"
* $TRE-R244-CategorieOrganisation#14 "Service Médico-Psychologique Régional (SMPR)"
* $TRE-R244-CategorieOrganisation#15 "Unité de Soins Intensifs Psychiatriques (USIP)"
* $TRE-R244-CategorieOrganisation#16 "Unité d'hospitalisation (hors HDJ)"
* $TRE-R244-CategorieOrganisation#17 "Unité Hospitalière Spécialement Aménagé (UHSA)"
* $TRE-R244-CategorieOrganisation#18 "Unité Malade Difficile (UMD)"
* $TRE-R244-CategorieOrganisation#19 "Unités Soins Etudes"
* $TRE-R244-CategorieOrganisation#20 "Structure des urgences polyvalentes 24h/24 7j/7"
* $TRE-R244-CategorieOrganisation#21 "Accueil ou hébergement pour personnes âgées dépendantes, sans spécificité"
* $TRE-R244-CategorieOrganisation#22 "Accueil ou hébergement pour personnes âgées autonomes, sans spécificité"
* $TRE-R244-CategorieOrganisation#23 "Accueil ou hébergement pour personnes âgées dépendantes, avec spécificité Unité d'Hébergement Renforcé (UHR)"
* $TRE-R244-CategorieOrganisation#24 "Accueil ou hébergement pour personnes âgées dépendantes, avec spécificité Unité de vie protégée (UVP, Cantou,...)"
* $TRE-R244-CategorieOrganisation#25 "Pôle d'activité de Soins Adaptés (PASA)"
* $TRE-R244-CategorieOrganisation#26 "Accueil ou hébergement pour personnes âgées dépendantes, avec spécificité Petites unités de vie (PUV)"
* $TRE-R244-CategorieOrganisation#27 "Accueil ou hébergement pour personnes âgées autonomes, avec spécificité Maison d'accueil rural (MARPA)"
* $TRE-R244-CategorieOrganisation#28 "Services Soins infirmiers à domicile (SSIAD)"
* $TRE-R244-CategorieOrganisation#29 "Equipe spécialisée Alzheimer (ESA)"
* $TRE-R244-CategorieOrganisation#30 "Service autonomie à domicile (SAD) aide"
* $TRE-R244-CategorieOrganisation#31 "Service d'Accompagnement à la Vie Sociale (SAVS)"
* $TRE-R244-CategorieOrganisation#32 "Service d'accompagnement médico-social adultes handicapés (SAMSAH)"
* $TRE-R244-CategorieOrganisation#33 "Service de portage de repas à domicile"
* $TRE-R244-CategorieOrganisation#34 "Service de Téléassistance"
* $TRE-R244-CategorieOrganisation#35 "Foyer restaurant"
* $TRE-R244-CategorieOrganisation#36 "Dispositif d'accueil familial social PA-PH"
* $TRE-R244-CategorieOrganisation#37 "Centre d'accueil familial spécialisé (CAFS)"
* $TRE-R244-CategorieOrganisation#38 "Plateforme d'accompagnement et de répit"
* $TRE-R244-CategorieOrganisation#39 "Foyer ou établissement d'accueil médicalisé (FAM ou EAM)"
* $TRE-R244-CategorieOrganisation#40 "Maison d'accueil spécialisée (MAS)"
* $TRE-R244-CategorieOrganisation#41 "Etablissement d'accueil non médicalisé (EANM) dont foyer de vie et foyer d'hébergement"
* $TRE-R244-CategorieOrganisation#43 "Unité d'aide par le travail (ESAT)"
* $TRE-R244-CategorieOrganisation#44 "Etablissements et Service de Réadaptation Professionnelle (ESRP)"
* $TRE-R244-CategorieOrganisation#45 "Unités évaluation réentraînement et d'orientation sociale et professionnel (UEROS)"
* $TRE-R244-CategorieOrganisation#46 "Établissement et Service de Préorientation (ESPO)"
* $TRE-R244-CategorieOrganisation#47 "Plateforme Emploi Accompagné (PEA)"
* $TRE-R244-CategorieOrganisation#48 "Institut médico-éducatif (IME)"
* $TRE-R244-CategorieOrganisation#49 "Institut d'éducation motrice (IEM)"
* $TRE-R244-CategorieOrganisation#50 "Institut thérapeutique éducatif et pédagogique (ITEP)"
* $TRE-R244-CategorieOrganisation#51 "Etablissement pour enfant ou ado polyhandicapé (EEAP)"
* $TRE-R244-CategorieOrganisation#52 "Institut déficient visuel"
* $TRE-R244-CategorieOrganisation#53 "Institut déficient auditif"
* $TRE-R244-CategorieOrganisation#54 "Institut déficient Visuel et Auditif"
* $TRE-R244-CategorieOrganisation#55 "Unité d'enseignement interne"
* $TRE-R244-CategorieOrganisation#56 "Unité d'enseignement externalisée"
* $TRE-R244-CategorieOrganisation#57 "Service d'accompagnement, Service d'Education Spécialisée de Soins à Domicile (SESSAD)"
* $TRE-R244-CategorieOrganisation#58 "Service d'accompagnement, Service d'Accompagnement Familial et d'Education Précoce (SAFEP)"
* $TRE-R244-CategorieOrganisation#59 "Service d'accompagnement, Services de Soutien à l'Education Familiale et à la Scolarisation (SSEFIS)"
* $TRE-R244-CategorieOrganisation#60 "Service d'accompagnement, Service d'Aide à l'Acquisition de l'Autonomie et à l'Intégration Scolaire (S3AIS)"
* $TRE-R244-CategorieOrganisation#61 "Centre d'action médico-sociale précoce (CAMSP)"
* $TRE-R244-CategorieOrganisation#62 "Centre médico-psycho-pédagogique (CMPP)"
* $TRE-R244-CategorieOrganisation#63 "Jardin d'enfants spécialisé"
* $TRE-R244-CategorieOrganisation#64 "Bureau d'Aide Psychologique Universitaire (B.A.P.U.)"
* $TRE-R244-CategorieOrganisation#65 "Pôle de compétences et de prestations externalisées (PCPE)"
* $TRE-R244-CategorieOrganisation#66 "Equipe Relais Handicaps Rares (ERHR)"
* $TRE-R244-CategorieOrganisation#67 "Lieu de vie et d'accueil (hors ESMS)"
* $TRE-R244-CategorieOrganisation#68 "Unité d'hospitalisation fermée"
* $TRE-R244-CategorieOrganisation#69 "Consultation externe en établissement de santé"
* $TRE-R244-CategorieOrganisation#70 "Unité d'intervention extra-hospitalière"
* $TRE-R244-CategorieOrganisation#71 "Equipe de liaison et de soins (intra-hospitalière)"
* $TRE-R244-CategorieOrganisation#72 "Guichet d'accueil, écoute, conseil, orientation"
* $TRE-R244-CategorieOrganisation#73 "Gestion de cas MAIA"
* $TRE-R244-CategorieOrganisation#74 "Logement inclusif"
* $TRE-R244-CategorieOrganisation#75 "Services Soins infirmiers à domicile renforcé (SSIAD renforcé)"
* $TRE-R244-CategorieOrganisation#76 "Unité d'évaluation et de régulation des admissions en psychiatrie"
* $TRE-R244-CategorieOrganisation#77 "Equipe Mobile Psychiatrie et Précarité (EMPP)"
* $TRE-R244-CategorieOrganisation#78 "Equipe Mobile Géronto-Psychiatrie (EMGP)"
* $TRE-R244-CategorieOrganisation#79 "Equipe Mobile Ambulatoire de Réadaptation Spécialisé (EARS)"
* $TRE-R244-CategorieOrganisation#80 "Centre de Soins, d'Accompagnement et de Prévention en Addictologie (CSAPA)"
* $TRE-R244-CategorieOrganisation#81 "Centre d'Accueil et d'Accompagnement à la Réduction des risques pour Usagers de Drogues (CAARUD)"
* $TRE-R244-CategorieOrganisation#82 "Pharmacie à Usage Intérieur (PUI)"
* $TRE-R244-CategorieOrganisation#83 "Chambre mortuaire"
* $TRE-R244-CategorieOrganisation#84 "Plateforme de Coordination et d'Orientation (PCO)"
* $TRE-R244-CategorieOrganisation#85 "Equipe Mobile Autisme"
* $TRE-R244-CategorieOrganisation#86 "Consultation Jeune Consommateur (CJC)"
* $TRE-R244-CategorieOrganisation#87 "Dispositif VigilanS"
* $TRE-R244-CategorieOrganisation#88 "Dispositif expérimental"
* $TRE-R244-CategorieOrganisation#89 "Centre de santé sexuelle"
* $TRE-R244-CategorieOrganisation#90 "Equipe mobile de prévention du risque infectieux"
* $TRE-R244-CategorieOrganisation#91 "Equipe opérationnelle d'hygiène (EOH)"
* $TRE-R244-CategorieOrganisation#92 "Soins non programmés de ville"
* $TRE-R244-CategorieOrganisation#93 "Lits halte soins santé (LHSS)"
* $TRE-R244-CategorieOrganisation#94 "Appartement de coordination thérapeutique (ACT)"
* $TRE-R244-CategorieOrganisation#95 "Lits d'accueil médicalisés (L.A.M.)"
* $TRE-R244-CategorieOrganisation#96 "Etablissement d'accueil non médicalisé (EANM) - foyer d'hébergement (classique ou en milieu ouvert)"
* $TRE-R244-CategorieOrganisation#97 "Etablissement d'accueil non médicalisé (EANM) - foyer de vie"
* $TRE-R244-CategorieOrganisation#98 "Espaces de vie affective, relationnelle et sexuelle (EVARS)"
* $TRE-R244-CategorieOrganisation#99 "Maison de santé pluriprofessionnelle (MSP)"
* $TRE-R244-CategorieOrganisation#100 "Soins Médicaux et de Réadaptation (SMR) polyvalent"
* $TRE-R244-CategorieOrganisation#101 "Soins Médicaux et de Réadaptation (SMR) gériatrie"
* $TRE-R244-CategorieOrganisation#102 "Soins Médicaux et de Réadaptation (SMR) locomoteur"
* $TRE-R244-CategorieOrganisation#103 "Soins Médicaux et de Réadaptation (SMR) système nerveux"
* $TRE-R244-CategorieOrganisation#104 "Soins Médicaux et de Réadaptation (SMR) cardio-vasculaire"
* $TRE-R244-CategorieOrganisation#105 "Soins Médicaux et de Réadaptation (SMR) pneumologie"
* $TRE-R244-CategorieOrganisation#106 "Soins Médicaux et de Réadaptation (SMR) système digestif, endocrinologie, diabétologie, nutrition"
* $TRE-R244-CategorieOrganisation#107 "Soins Médicaux et de Réadaptation (SMR) brûlés"
* $TRE-R244-CategorieOrganisation#108 "Soins Médicaux et de Réadaptation (SMR) conduites addictives"
* $TRE-R244-CategorieOrganisation#109 "Soins Médicaux et de Réadaptation (SMR) pédiatriques (enfants et adolescents)"
* $TRE-R244-CategorieOrganisation#110 "Soins Médicaux et de Réadaptation (SMR) pédiatriques (jeunes enfants, enfants et adolescents)"
* $TRE-R244-CategorieOrganisation#111 "Soins Médicaux et de Réadaptation (SMR) oncologie"
* $TRE-R244-CategorieOrganisation#112 "Soins Médicaux et de Réadaptation (SMR) oncologie et hématologie"
* $TRE-R244-CategorieOrganisation#113 "Centre de Réhabilitation Psychosociale"
* $TRE-R244-CategorieOrganisation#114 "Centre Ressource pour les Intervenants auprès des Auteurs de Violences Sexuelles (CRIAVS)"
* $TRE-R244-CategorieOrganisation#115 "Equipe Spécialisée de Soins Infirmiers Précarité (ESSIP)"
* $TRE-R244-CategorieOrganisation#117 "Unité de radiothérapie"
* $TRE-R244-CategorieOrganisation#119 "Unité mère-enfant"
* $TRE-R244-CategorieOrganisation#120 "Centre de recours Troubles du Comportement Alimentaire (TCA)"
* $TRE-R244-CategorieOrganisation#121 "Unité de réanimation"
* $TRE-R244-CategorieOrganisation#122 "Unité de soins intensifs polyvalents (USIP) contiguë"
* $TRE-R244-CategorieOrganisation#123 "Unité de soins intensifs polyvalents (USIP) dérogatoire"
* $TRE-R244-CategorieOrganisation#124 "Unité de soins intensifs (USI) de spécialité (hors USIC, USINV, USIH)"
* $TRE-R244-CategorieOrganisation#125 "Centre de protection maternelle et infantile (PMI)"
* $TRE-R244-CategorieOrganisation#126 "Structure Douleur Chronique (SDC)"
* $TRE-R244-CategorieOrganisation#127 "Centre régional du psychotraumatisme (CRP)"
* $TRE-R244-CategorieOrganisation#128 "Unité d'hospitalisation à domicile socle"
* $TRE-R244-CategorieOrganisation#129 "Unité d'hospitalisation à domicile ante et post-partum"
* $TRE-R244-CategorieOrganisation#130 "Unité d'hospitalisation à domicile réadaptation"
* $TRE-R244-CategorieOrganisation#131 "Unité d'hospitalisation à domicile enfants de moins de trois ans"
* $TRE-R244-CategorieOrganisation#132 "Service autonomie à domicile (SAD) aide et soins"
* $TRE-R244-CategorieOrganisation#134 "Maison des adolescents (MDA)"
* $TRE-R244-CategorieOrganisation#135 "Points Accueil Ecoute Jeunes (PAEJ)"
* $TRE-R244-CategorieOrganisation#136 "Centre de ressources territorial (CRT)"
* $TRE-R244-CategorieOrganisation#137 "Maison sport-santé"
* $TRE-R244-CategorieOrganisation#138 "Unité de soins non programmés en établissement de santé"
* $TRE-R244-CategorieOrganisation#139 "Unité de soins intensifs polyvalents (USIP) non contiguë"
* $TRE-R244-CategorieOrganisation#140 "Equipe Mobile d'Appui à la Scolarisation (EMAS)"
* $TRE-R244-CategorieOrganisation#141 "Espace Santé Jeune (ESJ)"
* $TRE-R244-CategorieOrganisation#142 "Equipes Mobiles Santé Précarité (EMSP)"
* $TRE-R244-CategorieOrganisation#143 "Communauté 360"
* $TRE-R244-CategorieOrganisation#144 "Equipe Mobile de Psychiatrie de la Personne Âgée"
* $TRE-R244-CategorieOrganisation#145 "Unité hospitalière d'addictologie"
* $TRE-R244-CategorieOrganisation#146 "Unité hospitalière de brûlologie"
* $TRE-R244-CategorieOrganisation#148 "Unité hospitalière d'allergologie"
* $TRE-R244-CategorieOrganisation#149 "Unité hospitalière de cardiologie"
* $TRE-R244-CategorieOrganisation#150 "Unité hospitalière de chirurgie orthopédique et traumatologique"
* $TRE-R244-CategorieOrganisation#151 "Unité hospitalière de chirurgie thoracique et cardiovasculaire"
* $TRE-R244-CategorieOrganisation#152 "Unité hospitalière de chirurgie vasculaire"
* $TRE-R244-CategorieOrganisation#153 "Unité hospitalière de chirurgie viscérale et digestive"
* $TRE-R244-CategorieOrganisation#154 "Unité hospitalière de dermatologie"
* $TRE-R244-CategorieOrganisation#155 "Unité hospitalière de génétique médicale"
* $TRE-R244-CategorieOrganisation#156 "Unité hospitalière de gériatrie"
* $TRE-R244-CategorieOrganisation#157 "Unité hospitalière de gynécologie"
* $TRE-R244-CategorieOrganisation#158 "Unité hospitalière de médecine vasculaire"
* $TRE-R244-CategorieOrganisation#159 "Unité hospitalière de néphrologie"
* $TRE-R244-CategorieOrganisation#160 "Unité hospitalière de neurochirurgie"
* $TRE-R244-CategorieOrganisation#161 "Unité hospitalière de neurologie"
* $TRE-R244-CategorieOrganisation#162 "Unité hospitalière de pédiatrie"
* $TRE-R244-CategorieOrganisation#163 "Unité hospitalière de pneumologie"
* $TRE-R244-CategorieOrganisation#164 "Unité hospitalière d'imagerie médicale"
* $TRE-R244-CategorieOrganisation#165 "Unité hospitalière de rhumatologie"
* $TRE-R244-CategorieOrganisation#166 "Unité hospitalière de stomatologie, chirurgie orale et maxillo faciale"
* $TRE-R244-CategorieOrganisation#167 "Unité hospitalière d'endocrinologie, diabétologie et nutrition"
* $TRE-R244-CategorieOrganisation#168 "Unité hospitalière des maladies infectieuses et tropicales (MIT)"
* $TRE-R244-CategorieOrganisation#169 "Unité hospitalière d'hématologie"
* $TRE-R244-CategorieOrganisation#170 "Unité hospitalière d'hépato-gastro-entérologie (HGE)"
* $TRE-R244-CategorieOrganisation#171 "Unité hospitalière d'oncologie"
* $TRE-R244-CategorieOrganisation#172 "Unité hospitalière d'ophtalmologie"
* $TRE-R244-CategorieOrganisation#173 "Unité hospitalière oto-rhino-laryngologie (ORL)"
* $TRE-R244-CategorieOrganisation#174 "Unité hospitalière de psychiatrie de l’adulte"
* $TRE-R244-CategorieOrganisation#175 "Unités de soins palliatifs"
* $TRE-R244-CategorieOrganisation#176 "Unité hospitalière de médecine interne"
* $TRE-R244-CategorieOrganisation#177 "Dispositif de consultation dédié pour les personnes en situation de handicap"
* $TRE-R244-CategorieOrganisation#178 "Dispositif d'Appui à la Coordination (DAC)"
* $TRE-R244-CategorieOrganisation#179 "Cabinet de ville d'oto-rhino-laryngologie (ORL)"
* $TRE-R244-CategorieOrganisation#180 "Cabinet de ville d'allergologie"
* $TRE-R244-CategorieOrganisation#181 "Cabinet de ville d'anatomo-cytopathologie"
* $TRE-R244-CategorieOrganisation#182 "Cabinet de ville d'anesthésie-réanimation"
* $TRE-R244-CategorieOrganisation#183 "Cabinet de ville de cardiologie"
* $TRE-R244-CategorieOrganisation#184 "Cabinet de ville de chirurgie orthopédique et traumatologique"
* $TRE-R244-CategorieOrganisation#185 "Cabinet de ville de chirurgie pédiatrique"
* $TRE-R244-CategorieOrganisation#186 "Cabinet de ville de chirurgie plastique"
* $TRE-R244-CategorieOrganisation#187 "Cabinet de ville de chirurgie thoracique et cardiovasculaire"
* $TRE-R244-CategorieOrganisation#188 "Cabinet de ville de chirurgie vasculaire"
* $TRE-R244-CategorieOrganisation#189 "Cabinet de ville de chirurgie viscérale et digestive"
* $TRE-R244-CategorieOrganisation#190 "Cabinet de ville de dermatologie"
* $TRE-R244-CategorieOrganisation#191 "Cabinet de ville de diététique"
* $TRE-R244-CategorieOrganisation#192 "Cabinet de ville de génétique médicale"
* $TRE-R244-CategorieOrganisation#193 "Cabinet de ville de gériatrie"
* $TRE-R244-CategorieOrganisation#194 "Cabinet de ville de gynécologie et/ou obstétrique"
* $TRE-R244-CategorieOrganisation#195 "Cabinet de ville de kinésithérapie"
* $TRE-R244-CategorieOrganisation#196 "Cabinet de ville de médecine générale"
* $TRE-R244-CategorieOrganisation#197 "Cabinet de ville de médecine interne"
* $TRE-R244-CategorieOrganisation#198 "Cabinet de ville de médecine légale et expertise médicale"
* $TRE-R244-CategorieOrganisation#199 "Cabinet de ville de médecine nucléaire"
* $TRE-R244-CategorieOrganisation#200 "Cabinet de ville de médecine physique et réadaptation (MPR)"
* $TRE-R244-CategorieOrganisation#201 "Cabinet de ville de médecine vasculaire"
* $TRE-R244-CategorieOrganisation#202 "Cabinet de ville de néphrologie"
* $TRE-R244-CategorieOrganisation#203 "Cabinet de ville de neurochirurgie"
* $TRE-R244-CategorieOrganisation#204 "Cabinet de ville de neurologie"
* $TRE-R244-CategorieOrganisation#205 "Cabinet de ville de pédiatrie"
* $TRE-R244-CategorieOrganisation#206 "Cabinet de ville de pédicure-podologie"
* $TRE-R244-CategorieOrganisation#207 "Cabinet de ville de pneumologie"
* $TRE-R244-CategorieOrganisation#208 "Cabinet de ville de psychiatrie"
* $TRE-R244-CategorieOrganisation#209 "Cabinet de ville de psychologie"
* $TRE-R244-CategorieOrganisation#210 "Cabinet de ville de psychomotricité"
* $TRE-R244-CategorieOrganisation#211 "Cabinet de ville d'imagerie médicale"
* $TRE-R244-CategorieOrganisation#212 "Cabinet de ville de rhumatologie"
* $TRE-R244-CategorieOrganisation#213 "Cabinet de ville de sages-femmes"
* $TRE-R244-CategorieOrganisation#214 "Cabinet de ville de stomatologie, chirurgie orale et maxillo faciale"
* $TRE-R244-CategorieOrganisation#215 "Cabinet de ville d'endocrinologie, diabétologie et nutrition"
* $TRE-R244-CategorieOrganisation#216 "Cabinet de ville d'ergothérapie"
* $TRE-R244-CategorieOrganisation#217 "Cabinet de ville des maladies infectieuses et tropicales (MIT)"
* $TRE-R244-CategorieOrganisation#218 "Cabinet de ville d'hématologie"
* $TRE-R244-CategorieOrganisation#219 "Cabinet de ville d'hépato-gastro-entérologie"
* $TRE-R244-CategorieOrganisation#220 "Cabinet de ville d'oncologie"
* $TRE-R244-CategorieOrganisation#221 "Cabinet de ville d'ophtalmologie"
* $TRE-R244-CategorieOrganisation#222 "Cabinet de ville d'orthophonie"
* $TRE-R244-CategorieOrganisation#223 "Cabinet de ville d'orthoptie"
* $TRE-R244-CategorieOrganisation#224 "Cabinet de ville d'urologie"
* $TRE-R244-CategorieOrganisation#225 "Cabinet de ville infirmier"
* $TRE-R244-CategorieOrganisation#226 "Cabinet dentaire de chirurgie dentaire"
* $TRE-R244-CategorieOrganisation#227 "Cabinet dentaire de chirurgie orale"
* $TRE-R244-CategorieOrganisation#228 "Cabinet dentaire de médecine bucco-dentaire"
* $TRE-R244-CategorieOrganisation#229 "Cabinet dentaire d'orthopédie dento-faciale"
* $TRE-R244-CategorieOrganisation#230 "Unité hospitalière d'anatomo-cytopathologie"
* $TRE-R244-CategorieOrganisation#231 "Unité hospitalière de médecine du sport"
* $TRE-R244-CategorieOrganisation#232 "Unité hospitalière de médecine légale et expertise médicale"
* $TRE-R244-CategorieOrganisation#233 "Unité hospitalière de médecine physique et réadaptation (MPR)"
* $TRE-R244-CategorieOrganisation#234 "Unité hospitalière d'urologie"
* $TRE-R244-CategorieOrganisation#236 "Unité hospitalière d'odontologie"
* $TRE-R244-CategorieOrganisation#237 "Unité hospitalière d'anesthésie"
* $TRE-R244-CategorieOrganisation#238 "Unité hospitalière de médecine polyvalente"
* $TRE-R244-CategorieOrganisation#239 "Unité hospitalière de médecine nucléaire"
* $TRE-R244-CategorieOrganisation#240 "Unité hospitalière de médecine du travail"
* $TRE-R244-CategorieOrganisation#241 "Unité hospitalière de chirurgie pédiatrique"
* $TRE-R244-CategorieOrganisation#242 "Unité hospitalière de chirurgie plastique, reconstructrice et esthétique"
* $TRE-R244-CategorieOrganisation#244 "Equipe Mobile d'Expertise en Réadaptation (EMER) neuro-locomoteur"
* $TRE-R244-CategorieOrganisation#245 "Centre expert en maladies rares"
* $TRE-R244-CategorieOrganisation#246 "Service d'Aide Médicale Urgente (SAMU)"
* $TRE-R244-CategorieOrganisation#247 "Structure Mobile d'Urgence et de Réanimation (SMUR)"
* $TRE-R244-CategorieOrganisation#248 "Unité de biologie"
* $TRE-R244-CategorieOrganisation#249 "Unité de Soins de Longue Durée (USLD)"
* $TRE-R244-CategorieOrganisation#250 "Centres Gratuits d'Information, de Dépistage et de Diagnostic (CeGIDD)"
* $TRE-R244-CategorieOrganisation#251 "Centre Périnatal de Proximité (CPP)"
* $TRE-R244-CategorieOrganisation#253 "Equipe Ressource Régionale de Soins Palliatifs Pédiatriques (ERRSPP)"
* $TRE-R244-CategorieOrganisation#254 "Unité de surveillance continue"
* $TRE-R244-CategorieOrganisation#255 "Communauté Professionnelle Territoriale de Santé (CPTS)"
* $TRE-R244-CategorieOrganisation#256 "Etablissement d'accueil temporaire pour adultes handicapés"
* $TRE-R244-CategorieOrganisation#257 "Unité pour Personnes Handicapées Vieillissantes (UPHV - UPHA)"
* $TRE-R244-CategorieOrganisation#258 "Hébergement Temporaire d'urgence (dont HT-SH)"
* $TRE-R244-CategorieOrganisation#259 "Point d'information local dédié aux personnes âgées"
* $TRE-R244-CategorieOrganisation#262 "Unité de soins intensifs spécialisés cardiologie (USIC)"
* $TRE-R244-CategorieOrganisation#263 "Unité de soins intensifs spécialisés neurologie vasculaire (USINV)"
* $TRE-R244-CategorieOrganisation#264 "Unité de soins intensifs spécialisés hématologie (USIH)"
* $TRE-R244-CategorieOrganisation#268 "Centre de lutte antituberculeuse (CLAT)"
* $TRE-R244-CategorieOrganisation#269 "Centre de vaccination"
* $TRE-R244-CategorieOrganisation#270 "Centre de vaccination internationale"
* $TRE-R244-CategorieOrganisation#271 "Dialyse à Domicile"
* $TRE-R244-CategorieOrganisation#272 "Equipe de Liaison et de Soins en Addictologie (ELSA)"
* $TRE-R244-CategorieOrganisation#273 "Unité d’auto-dialyse assistée (UAD)"
* $TRE-R244-CategorieOrganisation#274 "Unité de dialyse en centre lourd"
* $TRE-R244-CategorieOrganisation#275 "Unité de dialyse Médicalisée (UDM)"
* $TRE-R244-CategorieOrganisation#276 "Unité d’Accueil et de Soins pour personnes Sourdes et malentendantes (UASS)"
* $TRE-R244-CategorieOrganisation#277 "Equipe de coordination hospitalière de tissus et/ou d’organes"
* $TRE-R244-CategorieOrganisation#278 "Unité Hospitalière de Courte Durée (UHCD)"
* $TRE-R244-CategorieOrganisation#279 "Equipe Mobile de Psychiatrie de l’Enfant et de l’Adolescent (EMPEA)"
* $TRE-R244-CategorieOrganisation#280 "Equipe mobile de psychiatrie adulte"
* $TRE-R244-CategorieOrganisation#281 "Centre Médico-Psychologique Enfant et Adolescent (CMPEA)"
* $TRE-R244-CategorieOrganisation#282 "Unité hospitalière de psychiatrie de l’enfant et de l’adolescent (pédopsychiatrie)"
* $TRE-R244-CategorieOrganisation#283 "Equipe mobile de psychiatrie périnatale"
* $TRE-R244-CategorieOrganisation#284 "Equipe Spécialisée de Prévention et de Réadaptation à Domicile (ESPRAD)"
* $TRE-R244-CategorieOrganisation#285 "Centre Anti-Poison et de Toxico-Vigilance (CAPTV)"
* $TRE-R244-CategorieOrganisation#286 "Unité hospitalière de Soins Intensifs Néonatals (USIN)"
* $TRE-R244-CategorieOrganisation#287 "Unité hospitalière de réanimation néonatale"
* $TRE-R244-CategorieOrganisation#288 "Unité hospitalière « kangourou » ou « koala »"
* $TRE-R244-CategorieOrganisation#289 "Unité hospitalière de néonatalogie"
* $TRE-R244-CategorieOrganisation#290 "Unité hospitalière de maternité"
* $TRE-R244-CategorieOrganisation#291 "Halte Soins Addiction (HSA)"
* $TRE-R244-CategorieOrganisation#292 "Unité Hospitalière Sécurisée Interrégionale (UHSI)"
* $TRE-R244-CategorieOrganisation#293 "Unité hospitalière dédiée grossesse pathologique (GHR)"
* $TRE-R244-CategorieOrganisation#294 "Unité hospitalière de soins externes"
* $TRE-R244-CategorieOrganisation#295 "Permanence d'Accès aux Soins de Santé (PASS)"
* $TRE-R244-CategorieOrganisation#296 "Groupe d’Entraide Mutuelle (GEM)"
* $TRE-R244-CategorieOrganisation#297 "Centre ressource IntimAgir"
* $TRE-R244-CategorieOrganisation#298 "Dispositif sanitaire dédié à la prise en charge des femmes victimes de violences (Maison des Femmes Santé)"
* $TRE-R244-CategorieOrganisation#299 "Equipe de Diagnostic de Proximité – Autisme (PDAP, EDAP)"
* $TRE-R244-CategorieOrganisation#301 "Unité d'urgences psychiatriques"
* $TRE-R244-CategorieOrganisation#302 "Centre d’Accueil et de Crise (CAC)"
* $TRE-R244-CategorieOrganisation#303 "Cabinet de ville infirmier en pratique avancée en pathologies chroniques stabilisées"
* $TRE-R244-CategorieOrganisation#304 "Cabinet de ville infirmier en pratique avancée en oncologie et hémato-oncologie"
* $TRE-R244-CategorieOrganisation#305 "Cabinet de ville infirmier en pratique avancée en maladie rénale chronique"
* $TRE-R244-CategorieOrganisation#306 "Cabinet de ville infirmier en pratique avancée en santé mentale"
* $TRE-R244-CategorieOrganisation#307 "Unité d’Education Thérapeutique du Patient (ETP)"
* $TRE-R244-CategorieOrganisation#308 "Unité de réanimation des brûlés"
* $TRE-R244-CategorieOrganisation#309 "Unité Sanitaire en Milieu Pénitentiaire (USMP, ex UCSA)"
* $TRE-R244-CategorieOrganisation#310 "Lactarium"
* $TRE-R244-CategorieOrganisation#311 "Structure des urgences pédiatriques"
* $TRE-R244-CategorieOrganisation#312 "Pharmacie d'officine (dont mutualiste)"
* $TRE-R244-CategorieOrganisation#313 "Antennes des urgences"