ValueSet: JDV_J105_EnsembleDiplome_RASS
Id: JDV-J105-EnsembleDiplome-RASS
Description: "Ensemble des diplômes et qualifications du RASS"
* ^meta.versionId = "21"
* ^meta.lastUpdated = "2026-07-06T19:04:45.797+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J105-EnsembleDiplome-RASS/FHIR/JDV-J105-EnsembleDiplome-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.173"
* ^version = "20260223120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-02-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP02 "Doctorat de 3ème cycle sciences Odontologiques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP38 "DIU Accueil des urgences service pédiatrique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP39 "DIU Arthroscopie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP40 "DIU Cardiologie interventionnelle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP41 "DIU Acupuncture"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP42 "DIU Médecine manuelle et Ostéopathie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP43 "DIU Médecine subaquatique et hyperbare"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP44 "DIU Pathologie neuro-vasculaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP45 "DIU Phoniatrie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP46 "DIU Réparation juridique du dommage corporel"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP47 "DIU Veille et sommeil"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP48 "DIU Dermatologie esthétique et Cosmétologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP49 "DIU Pathologie du sommeil et de la vigilance"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP50 "DIU Pathologie foetale et placentaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP51 "DIU Soins palliatifs et accompagnement"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP52 "DIU Tabacologie et d'Aide au sevrage tabagique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP53 "DIU Chirurgie réfractive et Chirurgie de la myopie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP54 "DIU Chirurgie de la main"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP55 "DIU Proctologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP56 "DIU Echocardiographie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP57 "DIU Echographie générale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP58 "DIU Echographie gynécologique et obstétricale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP59 "DU Adaptation de lentilles de contact"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP60 "DU Angiographie et Pathologie rétinienne"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP61 "DIU Stimulation cardiaque"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP62 "DIU Mésothérapie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP63 "DU Réparation juridique du dommage corporel"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP64 "DIU Echographie vasculaire et urinaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP65 "DIU Imagerie vasculaire non invasive"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP66 "DU Etudes de réparation du dommage corporel"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP67 "DIU Soins palliatifs"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP68 "DIU Chirurgie endocrinienne et métabolique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP69 "DIU Echographie vasculaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP70 "DIU Sommeil et sa pathologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP71 "DIU Chirurgie cancérologique digestive"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP72 "DU ou DIU Médecine foetale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP75 "DU Indemnisation du dommage corporel Médecin conseil société d'assurance"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP76 "DIU Physiopathologie exploration fonctionnel neurosensorielle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP77 "DIU Echographie abdominale et urinaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP78 "DIU Explorations fonctionnelles digestives"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP79 "DIU Chirurgie rétino-vitréenne"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP80 "DIU Echocardiographie et doppler"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP81 "DIU Médecine et Réanimation néonatales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP82 "DIU Médecine morphologique et anti-âge"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP83 "DIU Chirurgie du pied et de la cheville"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP84 "DDCD Diplôme de Chirurgien-Dentiste"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP85 "DIU Angiographie et Pathologie rétinienne"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP86 "DIU Réparation juridique du dommage corporel expertise médico-légale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP87 "DU Etudes médicales relatives à la réparation du dommage corporel"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP88 "DIU Droit de l'expertise médico-légale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP89 "DIU Echographie, option Echographie de spécialité"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP90 "DIU Echocardiographie cardiaque et vasculaire Méditerranéen"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP91 "DIU Etudes approfondies polyarthrites-maladies"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP92 "DIU Maladies respiratoires et allergiques de l'enfant"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP93 "DIU Etudes maladies inflammatoires chroniques intestinales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP180 "DIU Dermato-esthétique, laser dermato-cosmétologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP181 "DU Echo-cardiographie et écho-doppler cardiovasculaire"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP182 "DU Gériatrie et Gérontologie médico-sociale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP183 "DIU Physiologie et Pathologie du sommeil"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP184 "DIU, DU ou CU Radiologie oto-neuro-ophtalmologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP185 "DU Gérontologie et Gériatrie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP186 "DU, Att Médecine orthopédique et thérapeutiques manuelles"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP187 "DIU Sommeil et sa pathologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP188 "DU Repar jurid dommage corporel, module SS et législation du trafic"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP189 "DIU Pathologie chirurgicale rétino-vitréenne"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP190 "DIU Coelio-chirurgie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP191 "DIU Rythmologie et stimulation cardiaque"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP192 "DIU Proctologie médico-instrumentale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP193 "DU Echographie cardiologique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP199 "DIU Enseignement supérieur de Neuroradiologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP201 "DU Méthodes ultrasonores en médecine"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP206 "DIU Endoscopie digestive interventionnelle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP207 "DIU Pathologies osseuses médicales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP210 "DIU Médecine manuelle et orthopédique, Ostéopathie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP211 "DIU Expertises accidents médicaux"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP216 "DIU Epileptologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP219 "DIU Onco-urologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP221 "DIU Echocardiographie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP222 "DIU Endocrinologie diabétologie pédiatrique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP224 "DIU Appareillage"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP225 "DIU Aptitude à l'expertise médicale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP226 "DIU Neurophysiologie clinique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP227 "DIU Approfondissement soins palliatifs et soins d'accompagnement"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP228 "DIU Migraine et céphalées"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP229 "DIU Chirurgie du rachis"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP234 "DIU Analyse du mouvement chez l'enfant et l'adolescent"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP235 "DIU Biologie du vieillissement"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP236 "DIU Cicatrisation des plaies aiguës et chroniques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP237 "DIU Dermatologie psychosomatique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP238 "DIU Education du patient"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP239 "DIU Education pour la santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP240 "DIU Ethique des professions de santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP241 "DIU Ethique et pratiques médicales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP242 "DIU Evaluation en santé, accréditation démarche qualité"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP243 "DIU Formation prise en charge douleur par professionnel de santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP244 "DIU Nutrition et activité physique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP245 "DIU Posturologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP246 "DIU Posturologie clinique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP247 "DIU Réflexion éthique et philosophique pour les soins"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP248 "DU Algologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP249 "DU Amélioration de la prise en charge du diabète"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP250 "DU Anatomie chirurgicale et sectionnelle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP251 "DU Anatomie et Biomécanique de l'appareil locomoteur"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP252 "DU Biomécanique de l'appareil locomoteur"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP253 "DU Biomécanique appareil locomoteur et mouvement"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP254 "DU Cicatrisation des plaies brûlures et nécroses"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP255 "DU Comprendre, organiser et promouvoir le travail en réseau"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP256 "DU Concept et méthodes en éducation pour la santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP257 "DU Education du patient à l'alliance thérapeutique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP258 "DU DEA Psy de la cognition : acquisitions, représentations, communication"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP259 "DU Doctorat sensibilité et motricité podales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP260 "DU Education du patient"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP261 "DU Education thérapeutique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP262 "DU Education thérapeutique : expérimenter et formaliser"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP263 "DU Education thérapeutique et maladies chroniques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP264 "DU Education du patient et maladies chroniques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP265 "DU Education thérapeutique du patient"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP266 "DU Education thérapeutique et maladies ostéo-articulaires"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP267 "DU Education thérapeutique et prévention et maladies"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP268 "DU Effets indésirables des thérapies anticancéreuses"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP269 "DU Ethique médicale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP270 "DU Evaluation qualité des soins et la gestion des risques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP271 "DU Formation paramédicale en diabétologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP272 "DU Hygiène et Epidémiologie infectieuse"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP273 "DU Management des actions de santé publique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP274 "DU Nutrition appliquée aux activités physiques et sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP275 "DU Nutrition et activités physiques et sportives"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP276 "DU Perception actions et troubles apprentissages"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP277 "DU Physiologie de la posture et du mouvement"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP278 "DU Physiologie et physiopathologie du sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP279 "DU Pied diabétique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP280 "DU Plaies et cicatrisations"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP281 "DU Podologie médicale et du sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP282 "DU Podologie appliquée au sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP283 "DU Podologie appliquée aux activités physiques et sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP284 "DU Podologie du sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP285 "DU Pratique soignante en soins de suite et réadaptation"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP286 "DU Prise en charge globale du pied diabétique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP287 "DU Prise en charge multidisciplinaire du patient diabétique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP288 "DU Problèmes éthiques soulevés par la prise en charge patient âgé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP289 "DU Promotion de la santé et éducation pour la santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP290 "DU Promotion de la santé pour les activités physiques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP291 "DU Psychiatrie à l'usage du non spécialiste"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP292 "DU Réharmonisation posturale en Podologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP293 "DU Sécurité sociale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP294 "DU Sport et Nutrition"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP295 "DU Sport et Podologie approche de la globalité fonctionnelle et posturale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP296 "DU Sport et santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP297 "DU Sport et santé, option Podologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP298 "DU Sport et santé avec AU Podologie appliquée au sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP299 "Doctorat ès sciences plus option"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP300 "DIU Soigner les soignants"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP301 "DIU d'OCT en ophtalmologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP308 "DIU Pratique médicale en station thermale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP309 "DU Ostéopathie clinique et fonctionnelle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP310 "DIU Pneumologie pédiatrique"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP311 "DIU Médecine du Sommeil Appliquée Gérontologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP312 "DIU Laryngo-Phoniatrie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP313 "DIU Echocardiog. et imag. cardiovasc. non invasive"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP320 "DU ou DIU Ostéopathe d'une université de médecine reconnu par le CNOM"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP330 "DU de Chiropraxie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP344 "DU ou DIU d'Orthopédie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP346 "DU Prothèse Oculaire appliquée"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP347 "DU Prothèse faciale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP351 "DUT Génie biologique option analyses biologiques et biochimiques (avant 2023)"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP365 "DUT Génie biologique option diététique (avant 2023)"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP369 "BUT Génie biologique parcours diététique et nutrition"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP391 "DU Ostéopathie Médecine Manuelle"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP392 "DIU Médecine Manuelle - Ostéopathie Médicale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP393 "DIU Expertise médico-légale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP394 "DU ou DIU Phlébologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP395 "DIU Pancréatologie médico-chirurgicale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP396 "DIU de Pathologie et chirurgie orbito-palpébro-lacrymales (OPL)"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP397 "DIU Techniques avancées en phlébologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP399 "DU Sciences du mouvement, posture et podologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP400 "DU Init recherche professions sanitaires sociales"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP401 "DU Enseignement pratique pluridis santé connectée"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP402 "DU Evaluation biomécanique performance sportive"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP403 "DU Podologie biomécanique et sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP404 "DU Posture, mouvement et santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP405 "DU P. diabétique rôle podologue parcours de soins"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP406 "DU Podologie du sport"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP407 "DU Ethique du numérique en santé"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP408 "DIU Analyse du mouvement et de la marche"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP410 "DUT Biologie appliquée option analyses biologiques et biochimiques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP411 "BUT Génie biologique parcours biologie médicale et biotechnologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP413 "DU Analyses des milieux biologiques université de Corte"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP416 "DUT Biologie appliquée option diététique"
* $TRE-R58-AutreTypeDiplome#DIP03 "Diplôme d'habilitation à diriger des recherches"
* $TRE-R58-AutreTypeDiplome#DIP04 "Maîtrise de Biologie humaine"
* $TRE-R58-AutreTypeDiplome#DIP05 "Maîtrise de Sciences biologiques et médicales"
* $TRE-R58-AutreTypeDiplome#DIP06 "Maîtrise de Sciences dentaires"
* $TRE-R58-AutreTypeDiplome#DIP07 "Diplôme d'études et de Recherche biologie humaine"
* $TRE-R58-AutreTypeDiplome#DIP30 "Diplôme d'Appareillage des handicapés moteurs"
* $TRE-R58-AutreTypeDiplome#DIP31 "Diplôme de la Marine marchande"
* $TRE-R58-AutreTypeDiplome#DIP32 "Diplôme de Podologie"
* $TRE-R58-AutreTypeDiplome#DIP33 "Diplôme de Sexologie"
* $TRE-R58-AutreTypeDiplome#DIP34 "Diplôme de Thérapeutiques manuelles"
* $TRE-R58-AutreTypeDiplome#DIP35 "Diplôme relatif à la Réparation juridique du dommage corporel"
* $TRE-R58-AutreTypeDiplome#DIP36 "Diplôme études médicales relatives à la Réparation juridique du dommage corporel"
* $TRE-R58-AutreTypeDiplome#DIP37 "CA ou DU Expertise du Dommage corporel"
* $TRE-R58-AutreTypeDiplome#DIP73 "Diplôme de Médecine agricole"
* $TRE-R58-AutreTypeDiplome#DIP74 "Diplôme d'études et de recherche science Odontologique"
* $TRE-R58-AutreTypeDiplome#DIP173 "Diplôme de Gérontologie clinique"
* $TRE-R58-AutreTypeDiplome#DIP174 "DEC de Gérontologie et Gériatrie"
* $TRE-R58-AutreTypeDiplome#DIP175 "Diplome d'Implantologie"
* $TRE-R58-AutreTypeDiplome#DIP176 "Maladies sexuellement transmissibles"
* $TRE-R58-AutreTypeDiplome#DIP177 "Ostéopathie par arrêté préfectoral"
* $TRE-R58-AutreTypeDiplome#DIP178 "CU Application de l'écho à l'obstétrique et à la gynécologie"
* $TRE-R58-AutreTypeDiplome#DIP179 "CE Enseignement spécial écho gynécologie et obstétrique"
* $TRE-R58-AutreTypeDiplome#DIP203 "CU de Proctologie médico-chirurgicale"
* $TRE-R58-AutreTypeDiplome#DIP204 "Diplôme (ou Attest d'étude) Electro-encephalographie clinique"
* $TRE-R58-AutreTypeDiplome#DIP212 "CU d'Echographie clinique"
* $TRE-R58-AutreTypeDiplome#DIP213 "Généraliste qualifié"
* $TRE-R58-AutreTypeDiplome#DIP214 "CU d'Echographie clinique (ancien diplôme autorisé)"
* $TRE-R58-AutreTypeDiplome#DIP215 "Diplôme de Médecine agricole de Tours"
* $TRE-R58-AutreTypeDiplome#DIP220 "Diplôme d'études complémentaires, option Ultrasonologie"
* $TRE-R58-AutreTypeDiplome#DIP223 "Diplôme d'indemnisation du dommage corporel"
* $TRE-R58-AutreTypeDiplome#DIP230 "AUEC Plaies et cicatrisation"
* $TRE-R58-AutreTypeDiplome#DIP231 "AUEC Podologie médicale et du sport"
* $TRE-R58-AutreTypeDiplome#DIP232 "CEU Biomécanique de l'appareil locomoteur"
* $TRE-R58-AutreTypeDiplome#DIP233 "CEU Pédagogie dans les professions de santé"
* $TRE-R58-AutreTypeDiplome#DIP299 "Doctorat ès science, option Immunologie"
* $TRE-R58-AutreTypeDiplome#DIP302 "CU d'Ultrasonologie Médicale"
* $TRE-R58-AutreTypeDiplome#DIP303 "Diplôme infirmier non reconnu pays EEE ou hors EEE"
* $TRE-R58-AutreTypeDiplome#DIP304 "Diplôme infirmier du secteur psychiatrique"
* $TRE-R58-AutreTypeDiplome#DIP305 "Formation de directeur de soins de l'EHESP"
* $TRE-R58-AutreTypeDiplome#DIP306 "Titre militaire autorisant la profession d'infirmier"
* $TRE-R58-AutreTypeDiplome#DIP314 "Formation exceptionnelle en médecine du travail"
* $TRE-R58-AutreTypeDiplome#DIP315 "Psychothérapeute par autorisation ARS"
* $TRE-R58-AutreTypeDiplome#DIP316 "Validation d'un DPC Prescription de dispositif PPC"
* $TRE-R58-AutreTypeDiplome#DIP317 "Validation d'un DPC Otologie médicale"
* $TRE-R58-AutreTypeDiplome#DIP319 "Titre d'assistant dentaire"
* $TRE-R58-AutreTypeDiplome#DIP321 "Diplôme d'Ostéopathe d'un établissement agréé pour la formation en Ostéopathie"
* $TRE-R58-AutreTypeDiplome#DIP322 "Master en Psychologie ou Psychanalyse"
* $TRE-R58-AutreTypeDiplome#DIP323 "Master mention psychologie"
* $TRE-R58-AutreTypeDiplome#DIP324 "Licence + Master mention psychologie clinique, psychopatho et psycho santé + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP325 "Licence + Master mention psychologie sociale, du travail et des organisations + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP326 "Licence + Master mention psychologie de l'éducation et de la formation + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP327 "Licence + Master mention psychologie: psychopatho clinique psychanalytique + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP328 "Diplôme de niveau Master en psychanalyse"
* $TRE-R58-AutreTypeDiplome#DIP329 "Diplôme de Chiropraxie"
* $TRE-R58-AutreTypeDiplome#DIP331 "Certificat d'études techniques d'acoustique appareillage de prothèse auditive"
* $TRE-R58-AutreTypeDiplome#DIP332 "Examen professionnel d'Audio-Prothésiste"
* $TRE-R58-AutreTypeDiplome#DIP333 "Diplôme d'Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP334 "Brevet de technicien supérieur d'Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP335 "Brevet professionnel d'Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP336 "Certificat d'études de l'Ecole des métiers d'optique"
* $TRE-R58-AutreTypeDiplome#DIP337 "Diplôme d'élève breveté des écoles nationales professionnelles, section d'optique-lunetterie"
* $TRE-R58-AutreTypeDiplome#DIP338 "Titre désigné par arrêté des ministres du commerce, économie et finances, enseignement sup et santé permettant d'exercer comme Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP339 "Brevet de technicien supérieur d'Orthoprothésiste"
* $TRE-R58-AutreTypeDiplome#DIP340 "Brevet de technicien supérieur de Prothésiste-Orthésiste"
* $TRE-R58-AutreTypeDiplome#DIP341 "Brevet de technicien supérieur de Podo-Orthésiste"
* $TRE-R58-AutreTypeDiplome#DIP342 "Titre d'Orthopédiste-Orthésiste obtenu avant 2007"
* $TRE-R58-AutreTypeDiplome#DIP343 "Titre RNCP de Technicien Supérieur Orthopédiste-Orthésiste obtenu après 2007"
* $TRE-R58-AutreTypeDiplome#DIP345 "Titre RNCP d'Orthopédiste-Orthésiste obtenu après 2007"
* $TRE-R58-AutreTypeDiplome#DIP348 "Diplôme de Technicien de Laboratoire de l'arrêté du 21/10/1992"
* $TRE-R58-AutreTypeDiplome#DIP349 "Diplôme de Technicien de Laboratoire de l'arrêté du 04/11/1976"
* $TRE-R58-AutreTypeDiplome#DIP350 "BTS/BTSA de technicien de laboratoire listé dans l'arrêté du 21/10/1992"
* $TRE-R58-AutreTypeDiplome#DIP353 "Certificat de Capacité d'Orthophoniste"
* $TRE-R58-AutreTypeDiplome#DIP354 "Diplôme ou attestation MEN"
* $TRE-R58-AutreTypeDiplome#DIP355 "Certificat de Capacité d'Orthoptiste"
* $TRE-R58-AutreTypeDiplome#DIP356 "Licence psychologie + Maîtrise psychologie + DESS en psychologie"
* $TRE-R58-AutreTypeDiplome#DIP357 "Licence psychologie + Maîtrise psychologie + diplôme annexe Décret 90-255"
* $TRE-R58-AutreTypeDiplome#DIP358 "Licence psychologie + Maîtrise psychologie + DEA psychologie + Attestation Stage"
* $TRE-R58-AutreTypeDiplome#DIP359 "Diplôme permettant l'usage du titre de psychologue (alinéa 6 à 9 de l'article 1 du décret 90-255)"
* $TRE-R58-AutreTypeDiplome#DIP360 "Usage restreint du titre de Psychologue (arrêté du 14/01/1993)"
* $TRE-R58-AutreTypeDiplome#DIP361 "Licence psychologie + Master psychologie + Stage psychologie"
* $TRE-R58-AutreTypeDiplome#DIP362 "Décision de Validation des Acquis de l'Expérience de Psychologue"
* $TRE-R58-AutreTypeDiplome#DIP364 "Brevet de technicien ou brevet de technicien supérieur Diététique"
* $TRE-R58-AutreTypeDiplome#DIP367 "Diplôme de technicien supérieur ou brevet de technicien supérieur Manipulateur d'Electro-Radiologie médicale"
* $TRE-R58-AutreTypeDiplome#DIP368 "Diplôme de technicien supérieur imagerie médicale et radiologie thérapeutique"
* $TRE-R58-AutreTypeDiplome#DIP398 "Lauréat de l'Académie Nationale de Médecine"
* $TRE-R58-AutreTypeDiplome#DIP409 "Diplôme de Qualification en Physique Radiologique et Médicale INSTN (dès 1996)"
* $TRE-R58-AutreTypeDiplome#DIP412 "Diplôme ou titre ou certification délivré par le CNAM"
* $TRE-R58-AutreTypeDiplome#DIP414 "Diplôme ou titre délivré par l'AFPICL de Lyon (UCLy - ESTBB)"
* $TRE-R58-AutreTypeDiplome#DIP415 "Certificat de formation tech supérieur Physicien chimiste ministère travail"
* $TRE-R58-AutreTypeDiplome#DSCD01 "Certificat d'études cliniques, mention Orthodontie"
* $TRE-R58-AutreTypeDiplome#DSCD02 "Diplôme d'études supérieures de Chirurgie buccale"
* $TRE-R55-CertificatEtudeSpeciale#CESC01 "CES Biologie de la bouche, option Histo-embryologique"
* $TRE-R55-CertificatEtudeSpeciale#CESC02 "CES Biologie de la bouche, option Anatomo-physiologue"
* $TRE-R55-CertificatEtudeSpeciale#CESC03 "CES Technologie des matériaux employés art dentaire"
* $TRE-R55-CertificatEtudeSpeciale#CESC04 "CES Odontologie chirurgicale"
* $TRE-R55-CertificatEtudeSpeciale#CESC05 "CES Odontologie conservatrice"
* $TRE-R55-CertificatEtudeSpeciale#CESC06 "CES Odontologie légale"
* $TRE-R55-CertificatEtudeSpeciale#CESC07 "CES Orthopédie dento-faciale"
* $TRE-R55-CertificatEtudeSpeciale#CESC08 "CES Pédodontie-prévention"
* $TRE-R55-CertificatEtudeSpeciale#CESC09 "CES Prothèse adjointe partielle"
* $TRE-R55-CertificatEtudeSpeciale#CESC10 "CES Prothèse adjointe complète"
* $TRE-R55-CertificatEtudeSpeciale#CESC11 "CES Prothèse adjointe maxillo-faciale"
* $TRE-R55-CertificatEtudeSpeciale#CESC12 "CES Prothèse scellée"
* $TRE-R55-CertificatEtudeSpeciale#CESM01 "CES Médecine aéronautique"
* $TRE-R55-CertificatEtudeSpeciale#CESM02 "CES Anatomie et Cytologie pathologiques"
* $TRE-R55-CertificatEtudeSpeciale#CESM03 "CES Anesthésie-réanimation"
* $TRE-R55-CertificatEtudeSpeciale#CESM04 "CES Cardiologie et Maladies vasculaires"
* $TRE-R55-CertificatEtudeSpeciale#CESM05 "CES Chirurgie générale"
* $TRE-R55-CertificatEtudeSpeciale#CESM06 "CES Dermato-vénéréologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM07 "CES Electro-radiologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM09 "CES Gynécologie médicale"
* $TRE-R55-CertificatEtudeSpeciale#CESM10 "CES Maladies de l'appareil digestif"
* $TRE-R55-CertificatEtudeSpeciale#CESM13 "CES Néphrologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM14 "CES Neuro-chirurgie"
* $TRE-R55-CertificatEtudeSpeciale#CESM15 "CES Neurologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM16 "CES Pédiatrie"
* $TRE-R55-CertificatEtudeSpeciale#CESM17 "CES Pneumologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM18 "CES Psychiatrie"
* $TRE-R55-CertificatEtudeSpeciale#CESM19 "CES Psychiatrie, option enfant et adolescent"
* $TRE-R55-CertificatEtudeSpeciale#CESM20 "CES Radio-diagnostic"
* $TRE-R55-CertificatEtudeSpeciale#CESM21 "CES Radio-thérapie"
* $TRE-R55-CertificatEtudeSpeciale#CESM22 "CES Médecine physique et réadaptation fonctionnelle"
* $TRE-R55-CertificatEtudeSpeciale#CESM23 "CES Rhumatologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM24 "CES Médecine Nucléaire"
* $TRE-R55-CertificatEtudeSpeciale#CESM25 "CES Endocrinologie, diabète, Maladies métaboliques"
* $TRE-R55-CertificatEtudeSpeciale#CESM26 "CES Gynécologie médicale et Obstétrique"
* $TRE-R55-CertificatEtudeSpeciale#CESM27 "CES Médecine appliquée aux sports"
* $TRE-R55-CertificatEtudeSpeciale#CESM28 "CES Médecine légale"
* $TRE-R55-CertificatEtudeSpeciale#CESM29 "CES Maladies du sang"
* $TRE-R55-CertificatEtudeSpeciale#CESM30 "CES Obstétrique"
* $TRE-R55-CertificatEtudeSpeciale#CESM31 "CES Ophtalmologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM32 "CES Otho-rhino-laryngologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM33 "CES Stomatologie"
* $TRE-R55-CertificatEtudeSpeciale#CESM34 "CES Médecine du travail"
* $TRE-R55-CertificatEtudeSpeciale#CESM35 "CES Orthopédie dento-maxillo-faciale"
* $TRE-R55-CertificatEtudeSpeciale#CESM36 "CES Neuro psychiatrie"
* $TRE-R55-CertificatEtudeSpeciale#CESM37 "CES Radio-diagnostic et thérapie"
* $TRE-R55-CertificatEtudeSpeciale#CESP01 "Bactérologie et Virologie clinique"
* $TRE-R55-CertificatEtudeSpeciale#CESP02 "Biochimie"
* $TRE-R55-CertificatEtudeSpeciale#CESP06 "Diagnostic biologiste parasitaire"
* $TRE-R55-CertificatEtudeSpeciale#CESP07 "Hématologie"
* $TRE-R55-CertificatEtudeSpeciale#CESP08 "Immunologie générale et appliquée"
* $TRE-R56-Attestation#DIP24 "Attestation études Léprologie"
* $TRE-R56-Attestation#DIP25 "Attestation études Electroencéphalographie clinique"
* $TRE-R56-Attestation#DIP26 "Attestation études Endoscopie digestive"
* $TRE-R56-Attestation#DIP27 "Attestation EU Réparation juridique du dommage corporel"
* $TRE-R56-Attestation#DIP28 "Attestation études Exploration fonctionnelle neuromusculaire"
* $TRE-R56-Attestation#DIP29 "Attestation EU Vertébrothérapie et Médecine manuelle"
* $TRE-R56-Attestation#DIP194 "Attestation EU Echographie générale"
* $TRE-R56-Attestation#DIP200 "Attestation études supérieures de Proctologie"
* $TRE-R56-Attestation#DIP202 "Attestation études Thérapeutiques manuelles et Médecine physique"
* $TRE-R56-Attestation#DIP205 "Attestation formation à l'Ostéodensitométrie"
* $TRE-R56-Attestation#DIP208 "Attestation étude complémentaire Echographie hépato-gastro-entérologie"
* $TRE-R56-Attestation#DIP217 "Attestation étude complémentaire Echographie, option Echotomographie"
* $TRE-R56-Attestation#DIP307 "Attestation de 5ième année de médecine validée"
* $TRE-R56-Attestation#DIP363 "Attestation de vérification de connaissances d'Ergothérapeute"
* $TRE-R56-Attestation#DIP366 "Attestation de vérification de connaissances de Psychomotricien"
* $TRE-R56-Attestation#DIP370 "Attestation de vérification de connaissances de Manipulateur d'Electro-Radiologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP94 "DEES Allergologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP95 "DEES Anatomie et Cytologie pathologiques humaines"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP97 "DEES Anesthésie-réanimation"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP98 "DEES Angéiologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP99 "DEES Biologie médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP100 "DEES Cancérologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP101 "DEES Cardiologie et Maladies vasculaires"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP102 "DEES Cardiologie et Médecine des affections vasculaires"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP103 "DEES Chirurgie de la face et du cou"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP104 "DEES Chirurgie générale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP105 "DEES Chirurgie infantile"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP106 "DEES Chirurgie maxillo-faciale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP107 "DEES Chirurgie maxillo-faciale et Stomatologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP108 "DEES Chirurgie orthopédique et Traumatologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP109 "DEES Chirurgie pédiatrique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP110 "DEES Chirurgie plastique, reconstructrice et esthétique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP111 "DEES Chirurgie thoracique et cardio-vasculaire"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP112 "DEES Chirurgie urologique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP113 "DEES Chirurgie vasculaire"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP114 "DEES Chirurgie viscérale et digestive"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP115 "DEES Dermato-vénéréologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP116 "DEES Diabétologie-nutrition"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP117 "DEES Electro-radiologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP118 "DEES Endocrinologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP119 "DEES Endocrinologie, diabète, Maladies métaboliques"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP120 "DEES Gastro-entérologie et Hépatologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP121 "DEES Génétique médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP122 "DEES Gériatrie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP123 "DEES Gynécologie médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP124 "DEES Gynécologie médicale et obstétrique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP125 "DEES Gynécologie-obstétrique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP126 "DEES Hématologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP127 "DEES Maladies de l'appareil digestif"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP128 "DEES Maladies du sang"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP129 "DEES Médecine physique et Réadaptation fonctionnelle"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP130 "DEES Médecine appliquée aux sports"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP131 "DEES Médecine du travail"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP132 "DEES Médecine exotique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP133 "DEES Médecine générale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP134 "DEES Médecine interne"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP135 "DEES Médecine légale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP136 "DEES Médecine nucléaire"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP137 "DEES Médecine physique et Réadapt fonctionnelle"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP138 "DEES Médecine thermale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP139 "DEES Néphrologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP140 "DEES Neuro-chirurgie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP141 "DEES Neuro-psychiatrie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP142 "DEES Neuro-chirurgie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP143 "DEES Neurologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP145 "DEES Obstétrique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP146 "DEES Oncologie médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP147 "DEES Oncologie, option médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP148 "DEES Oncologie, option Radio-thérapie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP150 "DEES Ophtalmologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP151 "DEES ORL et Chirurgie cervico-faciale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP152 "DEES Orthopédie dento-maxillo-faciale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP153 "DEES Oto-rhino-laryngologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP154 "DEES Pathologie cardio-vasculaire"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP155 "DEES Pédiatrie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP156 "DEES Phoniatrie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP157 "DEES Pneumologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP158 "DEES Psychiatrie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP159 "DEES Psychiatrie infantile"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP160 "DEES Psychiatrie, option enfant adolescent"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP161 "DEES Radio-diagnostic"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP162 "DEES Radio-diagnostic et Thérapie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP163 "DEES Radio-thérapie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP164 "DEES Radio-diagnostic et Imagerie médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP166 "DEES Réanimation"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP167 "DEES Réanimation médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP168 "DEES Recherche médicale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP169 "DEES Rhumatologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP170 "DEES Santé publique et Médecine sociale"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP171 "DEES Stomatologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP172 "DEES Urologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP195 "DEES Gynéco-obstétrique et Gynéco-médicale, option Gynéco-obstétrique"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP196 "DEES Hématologie, option Maladies du sang"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP197 "DEES Hématologie, option Onco-hématologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP198 "DEES Oncologie, option Onco-hématologie"
* $TRE-R57-DiplomeEuropeenEtudeSpecialisee#DIP209 "DEES Gyneco-obs et Gynéco-médicale, option Gynéco-médicale"
* $TRE-R226-Dip2iemeCycleNQ#DFASO "Dip de Formation approfondie Sc odontologiques"
* $TRE-R226-Dip2iemeCycleNQ#DFASM "Dip de Formation approfondie Sc médicales"
* $TRE-R36-AutreDiplomeObtenu#AUT001 "Diplôme Université Kabul (Afghanistan)"
* $TRE-R36-AutreDiplomeObtenu#AUT002 "Faculté de Médecine de Annaba (Algérie)"
* $TRE-R36-AutreDiplomeObtenu#AUT003 "Diplôme Université Alger (Algérie)"
* $TRE-R36-AutreDiplomeObtenu#AUT004 "Diplôme Université Constantine (Algérie)"
* $TRE-R36-AutreDiplomeObtenu#AUT005 "Diplôme Université Oran (Algérie)"
* $TRE-R36-AutreDiplomeObtenu#AUT006 "Diplôme Université Buenos Aires (Argentine)"
* $TRE-R36-AutreDiplomeObtenu#AUT007 "Diplôme Université Australie"
* $TRE-R36-AutreDiplomeObtenu#AUT008 "Diplôme Université Santa-Catarina (Brésil)"
* $TRE-R36-AutreDiplomeObtenu#AUT009 "Diplôme Université de Médecine de Sofia"
* $TRE-R36-AutreDiplomeObtenu#AUT010 "Diplôme Université Santiago (Chili)"
* $TRE-R36-AutreDiplomeObtenu#AUT011 "Diplôme Université Congo"
* $TRE-R36-AutreDiplomeObtenu#AUT012 "Diplôme Université Danemark"
* $TRE-R36-AutreDiplomeObtenu#AUT013 "Diplôme Université Alexandrie (Egypte)"
* $TRE-R36-AutreDiplomeObtenu#AUT014 "Diplôme Université Le Caire (Egypte)"
* $TRE-R36-AutreDiplomeObtenu#AUT015 "Diplôme Université Athènes (Grèce)"
* $TRE-R36-AutreDiplomeObtenu#AUT016 "Diplôme Université San Carlos (Guatemala)"
* $TRE-R36-AutreDiplomeObtenu#AUT017 "Diplôme Université Conakry (Guinée)"
* $TRE-R36-AutreDiplomeObtenu#AUT018 "Diplôme Université Téhéran (Iran)"
* $TRE-R36-AutreDiplomeObtenu#AUT019 "Faculté de Pharmacie Université Saint-Joseph Beyrouth"
* $TRE-R36-AutreDiplomeObtenu#AUT020 "Diplôme Université Bamako (Mali)"
* $TRE-R36-AutreDiplomeObtenu#AUT021 "Diplôme Université Bucarest"
* $TRE-R36-AutreDiplomeObtenu#AUT022 "Diplôme Université Cluj-Napoca (Roumanie)"
* $TRE-R36-AutreDiplomeObtenu#AUT023 "Diplôme Université Roumanie"
* $TRE-R36-AutreDiplomeObtenu#AUT024 "Diplôme Université Kharkov (Russie)"
* $TRE-R36-AutreDiplomeObtenu#AUT025 "Faculté de Médecine, Pharmacie de Dakar"
* $TRE-R36-AutreDiplomeObtenu#AUT026 "Diplôme Université Damas (Syrie)"
* $TRE-R36-AutreDiplomeObtenu#AUT027 "Diplôme Université Monastir (Tunisie)"
* $TRE-R36-AutreDiplomeObtenu#AUT028 "Faculté de Médecine Hanoï (Viêt Nam)"
* $TRE-R36-AutreDiplomeObtenu#AUT029 "Diplôme Université Saigon (Viêt Nam)"
* $TRE-R36-AutreDiplomeObtenu#AUT030 "Diplôme Faculté Médecine, Pharmacie Rabat (Maroc)"
* $TRE-R36-AutreDiplomeObtenu#AUT031 "Diplôme équivalent d'un pays hors EEE profession Médecin"
* $TRE-R36-AutreDiplomeObtenu#AUT032 "Diplôme éq de Pharmacie d'un pays hors EEE"
* $TRE-R36-AutreDiplomeObtenu#AUT033 "Diplôme équivalent d'un pays hors EEE profession Chirurgien-Dentiste"
* $TRE-R36-AutreDiplomeObtenu#AUT034 "Diplôme équivalent d'un pays hors EEE profession Sage-Femme"
* $TRE-R36-AutreDiplomeObtenu#AUT035 "Diplôme Université d'Etat Méd Pharm Erevan (Arménie)"
* $TRE-R36-AutreDiplomeObtenu#AUT036 "Diplôme Université Tichrine (Syrie)"
* $TRE-R36-AutreDiplomeObtenu#AUT100 "Diplôme d'Etat français de docteur en Pharmacie"
* $TRE-R36-AutreDiplomeObtenu#AUT101 "DEES Médecine générale"
* $TRE-R36-AutreDiplomeObtenu#AUT102 "DEES Anesthésie réanimation"
* $TRE-R36-AutreDiplomeObtenu#AUT103 "DEES Chirurgie générale"
* $TRE-R36-AutreDiplomeObtenu#AUT104 "DEES Médecine physique et de réadaptation"
* $TRE-R36-AutreDiplomeObtenu#AUT105 "DEES Radio-diagnostic et Imagerie médicale"
* $TRE-R36-AutreDiplomeObtenu#AUT106 "DEES Rhumatologie"
* $TRE-R36-AutreDiplomeObtenu#AUT107 "DEES Médecine du travail"
* $TRE-R36-AutreDiplomeObtenu#AUT108 "DEES Neurologie"
* $TRE-R36-AutreDiplomeObtenu#AUT109 "DEES Pédiatrie"
* $TRE-R36-AutreDiplomeObtenu#AUT110 "DEES Neuro-chirurgie"
* $TRE-R36-AutreDiplomeObtenu#AUT111 "DEES Psychiatrie"
* $TRE-R36-AutreDiplomeObtenu#AUT112 "DEES Médecine générale nouveau régime"
* $TRE-R36-AutreDiplomeObtenu#AUT113 "DEES Cardiologie et Maladies vasculaires"
* $TRE-R36-AutreDiplomeObtenu#AUT114 "DEES Ophtalmologie"
* $TRE-R36-AutreDiplomeObtenu#AUT115 "DEES Biologie médicale"
* $TRE-R36-AutreDiplomeObtenu#AUT116 "DEES Chirurgie orthopédique et traumatologique"
* $TRE-R36-AutreDiplomeObtenu#AUT117 "DEES hématologie"
* $TRE-R36-AutreDiplomeObtenu#AUT118 "DEES Gynécologie-obstétrique"
* $TRE-R36-AutreDiplomeObtenu#AUT119 "DEES Chirurgie plastique, reconstructrice et esthétique"
* $TRE-R36-AutreDiplomeObtenu#AUT120 "DEES Médecine interne"
* $TRE-R36-AutreDiplomeObtenu#AUT121 "DEES Chirurgie urologique"
* $TRE-R36-AutreDiplomeObtenu#AUT122 "DEES Pathologie cardio-vasculaire"
* $TRE-R36-AutreDiplomeObtenu#AUT123 "DEES Radio-thérapie"
* $TRE-R36-AutreDiplomeObtenu#AUT124 "DEES Chirurgie vasculaire"
* $TRE-R36-AutreDiplomeObtenu#AUT125 "DEES Dermato-vénéréologie"
* $TRE-R36-AutreDiplomeObtenu#AUT126 "DEES Chirurgie orthopédique et traumatologique"
* $TRE-R36-AutreDiplomeObtenu#AUT127 "DEES Chirurgie vasculaire"
* $TRE-R36-AutreDiplomeObtenu#AUT128 "DEES Pneumologie"
* $TRE-R36-AutreDiplomeObtenu#AUT129 "DEES Anatomie et Cytologie pathologiques"
* $TRE-R36-AutreDiplomeObtenu#AUT130 "DEES Chirurgie thoracique et cardio-vasculaire"
* $TRE-R36-AutreDiplomeObtenu#AUT131 "DEES Psychiatrie infantile"
* $TRE-R36-AutreDiplomeObtenu#AUT132 "DEES ORL et Chirurgie cervico-faciale"
* $TRE-R36-AutreDiplomeObtenu#AUT133 "DEES ORL"
* $TRE-R36-AutreDiplomeObtenu#AUT134 "DEES Chirurgie thoracique et cardio-vasculaire"
* $TRE-R36-AutreDiplomeObtenu#AUT135 "DEES Génétique médicale"
* $TRE-R36-AutreDiplomeObtenu#AUT136 "DEES Néphrologie"
* $TRE-R36-AutreDiplomeObtenu#AUT140 "Dip d'un pays hors EEE profession Médecin"
* $TRE-R36-AutreDiplomeObtenu#AUT141 "Diplôme équivalent d'un pays hors EEE profession Médecin"
* $TRE-R36-AutreDiplomeObtenu#AUT142 "Dip Université Montréal (Canada)"
* $TRE-R36-AutreDiplomeObtenu#AUT143 "Dip Faculté Pharm Univ Cocody (Côte d'Ivoire)"
* $TRE-R36-AutreDiplomeObtenu#AUT144 "Dip Université Beyrouth"
* $TRE-R36-AutreDiplomeObtenu#AUT145 "Dip Faculté Pharm Univ Lattaquié (Syrie)"
* $TRE-R36-AutreDiplomeObtenu#AUT154 "Dip Université Saint-Joseph Beyrouth"
* $TRE-R36-AutreDiplomeObtenu#AUT159 "Dip Faculté Pharm Univ Alep (Syrie)"
* $TRE-R36-AutreDiplomeObtenu#AUT164 "Dip Faculté Pharm Univ Koursk (Russie)"
* $TRE-R36-AutreDiplomeObtenu#AUT169 "Dip Université Mogi das Cruzes (Brésil)"
* $TRE-R36-AutreDiplomeObtenu#AUT174 "Diplôme Faculté Méd Univ Tirana Département Pharm (Albanie)"
* $TRE-R36-AutreDiplomeObtenu#AUT179 "Dip Université Al Baath (Homs,Syrie)"
* $TRE-R36-AutreDiplomeObtenu#AUT184 "Dip Université de Saint-Petersbourg (Russie)"
* $TRE-R36-AutreDiplomeObtenu#AUT189 "Dip Université Lima (Pérou)"
* $TRE-R36-AutreDiplomeObtenu#AUT194 "Dip Université Cordoba (Argentine)"
* $TRE-R36-AutreDiplomeObtenu#AUT199 "Nomenclature interne"
* $TRE-R36-AutreDiplomeObtenu#AUT204 "Dip Université Chisinau (Moldavie)"
* $TRE-R36-AutreDiplomeObtenu#AUT209 "Diplôme Univ Djillali Liabès, Sidi Bel Abbès (Algérie)"
* $TRE-R36-AutreDiplomeObtenu#AUT214 "Dip Université de Moscou (Russie)"
* $TRE-R48-DiplomeEtatFrancais#DE01 "DE Pharmacien"
* $TRE-R48-DiplomeEtatFrancais#DE02 "DE Docteur en pharmacie"
* $TRE-R48-DiplomeEtatFrancais#DE03 "DE Docteur en chirurgie dentaire"
* $TRE-R48-DiplomeEtatFrancais#DE04 "DE Chirurgien-Dentiste"
* $TRE-R48-DiplomeEtatFrancais#DE05 "DE Docteur en médecine"
* $TRE-R48-DiplomeEtatFrancais#DE06 "DE Sage-Femme"
* $TRE-R48-DiplomeEtatFrancais#DE08 "DE Opticien-Lunetier"
* $TRE-R48-DiplomeEtatFrancais#DE09 "DE Infirmier"
* $TRE-R48-DiplomeEtatFrancais#DE10 "DE Infirmier psychiatrique"
* $TRE-R48-DiplomeEtatFrancais#DE11 "DE Masseur-Kinésithérapeute"
* $TRE-R48-DiplomeEtatFrancais#DE12 "DE Pédicure-Podologue"
* $TRE-R48-DiplomeEtatFrancais#DE13 "DE Orthophoniste"
* $TRE-R48-DiplomeEtatFrancais#DE14 "DE Orthoptiste"
* $TRE-R48-DiplomeEtatFrancais#DE15 "DE Psychologue"
* $TRE-R48-DiplomeEtatFrancais#DE18 "DE Manipulateur ERM"
* $TRE-R48-DiplomeEtatFrancais#DE19 "DE Infirmier de bloc opératoire"
* $TRE-R48-DiplomeEtatFrancais#DE20 "DE Infirmier anesthésiste"
* $TRE-R48-DiplomeEtatFrancais#DE21 "DE Infirmier puériculteur"
* $TRE-R48-DiplomeEtatFrancais#DE22 "DE Cadre de santé"
* $TRE-R48-DiplomeEtatFrancais#DE23 "DE Infirmier en pratique avancée mention pathologies chroniques stabilisées"
* $TRE-R48-DiplomeEtatFrancais#DE24 "DE Infirmier en pratique avancée mention oncologie et hémato-oncologie"
* $TRE-R48-DiplomeEtatFrancais#DE25 "DE Infirmier en pratique avancée mention maladie rénale chronique, dialyse et transplantation rénale"
* $TRE-R48-DiplomeEtatFrancais#DE26 "DE Infirmier en pratique avancée mention santé mentale"
* $TRE-R48-DiplomeEtatFrancais#DE27 "DE Infirmier en pratique avancée mention urgences"
* $TRE-R48-DiplomeEtatFrancais#DE28 "DE Assistant de Service Social"
* $TRE-R48-DiplomeEtatFrancais#DE29 "DE Audioprothésiste"
* $TRE-R48-DiplomeEtatFrancais#DE30 "DE Ergothérapeute"
* $TRE-R48-DiplomeEtatFrancais#DE32 "DE Psychomotricien"
* $TRE-R48-DiplomeEtatFrancais#DE38 "DE Technicien de Laboratoire Médical (DETLM, DETAB ou DELAM)"
* $TRE-R48-DiplomeEtatFrancais#DE39 "DE Manipulateur d'Electro-Radiologie médicale"
* $TRE-R48-DiplomeEtatFrancais#DIP01 "Doctorat d'Etat Biologie humaine"
* $TRE-R49-DiplomeEtudeSpecialisee#DSD01 "DES Orthopédie Dento-Faciale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSD02 "DES Médecine Bucco-Dentaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM01 "DES Anatomie et Cytologie pathologiques"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM02 "DES Anesthésie-réanimation"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM03 "DES Biologie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM04 "DES Cardiologie et Maladies vasculaires"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM05 "DES Chirurgie générale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM06 "DES Chirurgie infantile"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM07 "DES Chirurgie maxillo-faciale et Stomatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM08 "DES Chirurgie orthopédique et Traumatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM09 "DES Chirurgie plastique, reconstructrice et esthétique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM10 "DES Chirurgie thoracique et cardio-vasculaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM11 "DES Chirurgie urologique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM12 "DES Chirurgie vasculaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM13 "DES Chirurgie viscérale et digestive"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM14 "DES Dermatologie et Vénéréologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM15 "DES Endocrinologie, diabète, maladies métaboliques"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM16 "DES Gastro-entérologie et Hépatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM17 "DES Génétique médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM18 "DES Gynécologie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM19 "DES Gynécologie-obstétrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM20 "DES Hématologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM21 "DES Hématologie, option Maladies du sang"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM22 "DES Hématologie, option Onco-hématologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM23 "DES Médecine du travail"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM24 "DES Médecine générale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM25 "DES Médecine interne"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM26 "DES Médecine nucléaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM27 "DES Médecine physique et de réadaptation"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM28 "DES Néphrologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM29 "DES Neuro-chirurgie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM30 "DES Neurologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM31 "DES Neuro-psychiatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM32 "DES Oncologie, option Hématologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM33 "DES Oncologie, option Médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM34 "DES Oncologie, option Radio-thérapie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM35 "DES Ophtalmologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM36 "DES ORL et Chirurgie cervico-faciale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM37 "ORL et Chirurgie cervico-faciale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM38 "Pathologies cardio-vasculaires"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM39 "DES Pédiatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM40 "DES Pneumologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM41 "DES Psychiatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM42 "Psychiatrie infantile"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM43 "DES Radio-diagnostic et Imagerie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM44 "DES Radio-thérapie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM45 "DES Recherche médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM46 "DES Rhumatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM47 "DES Santé publique et Médecine sociale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM48 "DES Stomatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM49 "DES Gynéco-obs et Gynéco-médicale, option Obstétrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM50 "DES Gynéco-obs et Gynéco-médicale, option Gynéco-médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM51 "DES Chirurgie orale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM52 "DES Allergologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM53 "DES Chirurgie maxillo-faciale (réforme 2017)"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM54 "DES Chirurgie orthopédique et traumatologique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM55 "DES Endocrinologie-diabétologie-nutrition"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM56 "DES Hématologie (réforme 2017)"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM57 "DES Hépato-gastro-entérologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM58 "DES Maladies infectieuses et tropicales"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM59 "DES Médecine cardiovasculaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM60 "DES Médecine d'urgence"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM61 "DES Médecine et santé au travail"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM62 "DES Médecine intensive-réanimation"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM63 "DES Médecine interne et immunologie clinique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM64 "DES Médecine légale et expertises médicales"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM65 "DES Médecine vasculaire"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM66 "DES Radiologie et imagerie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM67 "DES Santé publique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM68 "DES Urologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM69 "DES Anesthésie-réanimation opt réanim-pédiatrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM70 "DES Biologie médicale option agents infectieux"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM71 "DES Biologie médicale option biologie générale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM72 "DES Biologie médic opt hématologie et immunologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM73 "DES Biologie médic opt méd moléc génétique pharmac"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM74 "DES Biologie médic opt biologie de la reproduction"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM75 "DES Chir maxillo-faciale opt orthod dysmo max-fac"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM76 "DES Chirurgie viscérale et digestive opt endo chir"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM77 "DES Chir pédiatrique opt orthopédie pédiatrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM78 "DES Chir pédiatrique opt chir visc pédiatrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM79 "DES Méd cardiovascul opt card intervention adulte"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM80 "DES Méd cardiovascul opt imagerie cardio d'expert."
* $TRE-R49-DiplomeEtudeSpecialisee#DSM81 "DES Méd cardiovascul opt rythmo inter stimu card"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM82 "DES Méd intensive-réanimation opt réa pédiatrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM83 "DES Néphrologie opt soins intensifs néphrologiques"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM84 "DES Neurolog opt trait interv ischémie céréb aigüe"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM85 "DES Oncologie option oncologie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM86 "DES Oncologie option oncologie radiothérapie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM87 "DES Ophtalmo opt chir ophtalmopéd strabologique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM88 "DES ORL - chir cervico-faciale opt audiophonologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM89 "DES Pédiatrie option néonatologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM90 "DES Pédiatrie option neuropédiatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM91 "DES Pédiatrie option pneumopédiatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM92 "DES Pédiatrie option réanimation pédiatrique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM93 "DES Pneumologie opt soins intensifs respiratoires"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM94 "DES Psychiatrie option enfant et adolescent"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM95 "DES Psychiatrie opt psychiatrie personne âgée"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM96 "DES Radiologie imagerie médic opt radio inter av"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM97 "DES Santé publique opt administration de la santé"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM98 "DES Biologie méd opt bactério, virologie, hygiène"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM99 "DES Biologie méd opt biochimie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM100 "DES Biologie méd opt biologie de la reproduction"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM101 "DES Biologie méd opt génétique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM102 "DES Biologie méd opt hématologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM103 "DES Biologie méd opt immunologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM104 "DES Biologie méd opt parasitologie-mycologie, risq"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM105 "DES Biologie méd opt pharmacologie-toxicologie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM106 "DES Biologie méd opt thérapie cellulaire-génique"
* $TRE-R49-DiplomeEtudeSpecialisee#DSM412 "DES Gériatrie"
* $TRE-R49-DiplomeEtudeSpecialisee#DSP04 "DES Biologie médicale"
* $TRE-R49-DiplomeEtudeSpecialisee#DSP06 "DES Pharmacie hospitalière"
* $TRE-R49-DiplomeEtudeSpecialisee#DSP10 "DES Pharmacie hospitalière générale (PHG)"
* $TRE-R49-DiplomeEtudeSpecialisee#DSP11 "DES Pharmacie hospitalière développement-sécurisation des produits santé (DSPS)"
* $TRE-R49-DiplomeEtudeSpecialisee#DSP12 "DES Pharmacie hospitalière radiopharmacie (RPH)"
* $TRE-R50-DESCGroupe1Diplome#DSM200 "Addictologie"
* $TRE-R50-DESCGroupe1Diplome#DSM201 "Allergologie et Immunologie clinique"
* $TRE-R50-DESCGroupe1Diplome#DSM202 "Andrologie"
* $TRE-R50-DESCGroupe1Diplome#DSM203 "Biochimie hormonale et métabolique"
* $TRE-R50-DESCGroupe1Diplome#DSM204 "Biologie des agents infectieux"
* $TRE-R50-DESCGroupe1Diplome#DSM205 "Biologie moléculaire"
* $TRE-R50-DESCGroupe1Diplome#DSM206 "Cancérologie"
* $TRE-R50-DESCGroupe1Diplome#DSM207 "Chirurgie de la face et du cou"
* $TRE-R50-DESCGroupe1Diplome#DSM208 "Chirurgie plastique et reconstructrice"
* $TRE-R50-DESCGroupe1Diplome#DSM209 "Chirurgie vasculaire"
* $TRE-R50-DESCGroupe1Diplome#DSM210 "Cytogénétique humaine"
* $TRE-R50-DESCGroupe1Diplome#DSM211 "Dermatopathologie"
* $TRE-R50-DESCGroupe1Diplome#DSM212 "Foetopathologie"
* $TRE-R50-DESCGroupe1Diplome#DSM213 "Gériatrie"
* $TRE-R50-DESCGroupe1Diplome#DSM214 "Hématologie biologique"
* $TRE-R50-DESCGroupe1Diplome#DSM215 "Hématologie, Maladies du sang"
* $TRE-R50-DESCGroupe1Diplome#DSM216 "Hémobiologie-transfusion"
* $TRE-R50-DESCGroupe1Diplome#DSM217 "Immunologie et Immunopathologie"
* $TRE-R50-DESCGroupe1Diplome#DSM218 "Médecine de la reproduction"
* $TRE-R50-DESCGroupe1Diplome#DSM219 "Médecine du sport"
* $TRE-R50-DESCGroupe1Diplome#DSM220 "Médecine d'urgence"
* $TRE-R50-DESCGroupe1Diplome#DSM221 "Médecine légale et Expertises médicales"
* $TRE-R50-DESCGroupe1Diplome#DSM222 "Médecine nucléaire"
* $TRE-R50-DESCGroupe1Diplome#DSM223 "Médecine vasculaire"
* $TRE-R50-DESCGroupe1Diplome#DSM224 "Néonatalogie"
* $TRE-R50-DESCGroupe1Diplome#DSM225 "Neuro-pathologie"
* $TRE-R50-DESCGroupe1Diplome#DSM226 "Nutrition"
* $TRE-R50-DESCGroupe1Diplome#DSM227 "Orthopédie dento-maxillo-faciale"
* $TRE-R50-DESCGroupe1Diplome#DSM228 "Pathologie infectieuse et tropicale, clinique et biologique"
* $TRE-R50-DESCGroupe1Diplome#DSM229 "Pharmacocinétique et Métabolisme des médicaments"
* $TRE-R50-DESCGroupe1Diplome#DSM230 "Pharmacologie clinique et Evaluation des thérapeutiques"
* $TRE-R50-DESCGroupe1Diplome#DSM231 "Psychiatrie de l'enfant et de l'adolescent"
* $TRE-R50-DESCGroupe1Diplome#DSM232 "Radiopharmacie et Radiobiologie"
* $TRE-R50-DESCGroupe1Diplome#DSM233 "Réanimation médicale"
* $TRE-R50-DESCGroupe1Diplome#DSM234 "Toxicologie biologique"
* $TRE-R50-DESCGroupe1Diplome#DSM235 "Médecine de la douleur et Médecine palliative"
* $TRE-R50-DESCGroupe1Diplome#DSM236 "Cancérologie, option Traitements médicaux des cancers"
* $TRE-R50-DESCGroupe1Diplome#DSM237 "Cancérologie, option Chirurgie cancérologique"
* $TRE-R50-DESCGroupe1Diplome#DSM238 "Cancérologie, option Réseaux de cancérologie"
* $TRE-R50-DESCGroupe1Diplome#DSM239 "Cancérologie, option Biologie cancérologie"
* $TRE-R50-DESCGroupe1Diplome#DSM240 "Cancérologie, option Imagerie cancérologie"
* $TRE-R50-DESCGroupe1Diplome#DSP01 "Radiopharmacie et Radiobiologie"
* $TRE-R50-DESCGroupe1Diplome#DSP02 "Toxicologie biologique"
* $TRE-R50-DESCGroupe1Diplome#DSP03 "Biologie des agents infectieux"
* $TRE-R51-DESCGroupe2Diplome#DSM400 "DESC2 Chirurgie infantile"
* $TRE-R51-DESCGroupe2Diplome#DSM401 "DESC2 Chirurgie maxillo-faciale"
* $TRE-R51-DESCGroupe2Diplome#DSM402 "DESC2 Chirurgie maxillo-faciale et Stomatologie"
* $TRE-R51-DESCGroupe2Diplome#DSM403 "DESC2 Chirurgie de la face et du cou"
* $TRE-R51-DESCGroupe2Diplome#DSM404 "DESC2 Chirurgie orthopédique et Traumatologie"
* $TRE-R51-DESCGroupe2Diplome#DSM405 "DESC2 Chirurgie plastique, reconstructrice et esthétique"
* $TRE-R51-DESCGroupe2Diplome#DSM406 "DESC2 Chirurgie thoracique et cardio-vasculaire"
* $TRE-R51-DESCGroupe2Diplome#DSM407 "DESC2 Chirurgie urologique"
* $TRE-R51-DESCGroupe2Diplome#DSM408 "DESC2 Chirurgie vasculaire"
* $TRE-R51-DESCGroupe2Diplome#DSM409 "DESC2 Chirurgie viscérale et digestive"
* $TRE-R51-DESCGroupe2Diplome#DSM410 "DESC2 Gériatrie"
* $TRE-R51-DESCGroupe2Diplome#DSM411 "DESC2 Réanimation médicale"
* $TRE-R52-CapaciteDiplome#CAPA01 "Addictologie clinique"
* $TRE-R52-CapaciteDiplome#CAPA02 "Aide médicale urgente"
* $TRE-R52-CapaciteDiplome#CAPA03 "Allergologie"
* $TRE-R52-CapaciteDiplome#CAPA04 "Angéiologie"
* $TRE-R52-CapaciteDiplome#CAPA05 "Evaluation et traitement de la douleur"
* $TRE-R52-CapaciteDiplome#CAPA06 "Gérontologie"
* $TRE-R52-CapaciteDiplome#CAPA07 "Hydrologie et Climatologie médicales"
* $TRE-R52-CapaciteDiplome#CAPA08 "Médecine aérospatiale"
* $TRE-R52-CapaciteDiplome#CAPA09 "Médecine de catastrophe"
* $TRE-R52-CapaciteDiplome#CAPA10 "Médecine et Biologie du sport"
* $TRE-R52-CapaciteDiplome#CAPA11 "Médecine de santé au travail et prévention des risques professionnelles"
* $TRE-R52-CapaciteDiplome#CAPA12 "Médecine pénitentiaire"
* $TRE-R52-CapaciteDiplome#CAPA13 "Médecine tropicale"
* $TRE-R52-CapaciteDiplome#CAPA14 "Pratiques médico-judiciaires"
* $TRE-R52-CapaciteDiplome#CAPA15 "Technologie transfusionnelle"
* $TRE-R52-CapaciteDiplome#CAPA16 "Toxicomanies et alcoologies"
* $TRE-R52-CapaciteDiplome#CAPA17 "Acupuncture"
* $TRE-R53-DiplomePaysEEE#DE80 "Diplôme éq d'un pays de l'EEE profession Médecin"
* $TRE-R53-DiplomePaysEEE#DE81 "Diplôme éq d'un pays de l'EEE profession Pharmacien"
* $TRE-R53-DiplomePaysEEE#DE82 "Diplôme éq d'un pays de l'EEE profession Chirurgien-Dentiste"
* $TRE-R53-DiplomePaysEEE#DE83 "Diplôme éq d'un pays de l'EEE profession Sage-Femme"
* $TRE-R53-DiplomePaysEEE#DE84 "Diplôme éq d'un pays de l'EEE profession Infirmier"
* $TRE-R53-DiplomePaysEEE#DE85 "Diplôme éq d'un pays de l'EEE profession Masseur-Kinésithérapeute"
* $TRE-R53-DiplomePaysEEE#DE86 "Diplôme d'un pays de l'EEE profession Pédicure-Podologue"
* $TRE-R53-DiplomePaysEEE#DIP218 "Diplôme Neuro-pédiatrie de l'université libre de Bruxelles"
* $TRE-R348-FormationSpecialiseeTransversale#FST01 "FST Addictologie"
* $TRE-R348-FormationSpecialiseeTransversale#FST02 "FST Bio-informatique médicale"
* $TRE-R348-FormationSpecialiseeTransversale#FST03 "FST Cancérologie déc. hémato-cancéro pédiatrique"
* $TRE-R348-FormationSpecialiseeTransversale#FST04 "FST Cancérologie traitements médicaux des cancers"
* $TRE-R348-FormationSpecialiseeTransversale#FST05 "FST Cardiologie pédiatrique et congénitale"
* $TRE-R348-FormationSpecialiseeTransversale#FST06 "FST Chirurgie de la main"
* $TRE-R348-FormationSpecialiseeTransversale#FST07 "FST Chirurgie situation de guerre ou catastrophe"
* $TRE-R348-FormationSpecialiseeTransversale#FST08 "FST Chirurgie orbito-palpébro-lacrymale"
* $TRE-R348-FormationSpecialiseeTransversale#FST09 "FST Douleur"
* $TRE-R348-FormationSpecialiseeTransversale#FST10 "FST Expertise médicale-préjudice corporel"
* $TRE-R348-FormationSpecialiseeTransversale#FST11 "FST Foetopathologie"
* $TRE-R348-FormationSpecialiseeTransversale#FST12 "FST Génétique et médecine moléculaire bioclinique"
* $TRE-R348-FormationSpecialiseeTransversale#FST13 "FST Hématologie bioclinique"
* $TRE-R348-FormationSpecialiseeTransversale#FST14 "FST Hygiène-prévention de l'infection, résistances"
* $TRE-R348-FormationSpecialiseeTransversale#FST15 "FST Maladies allergiques"
* $TRE-R348-FormationSpecialiseeTransversale#FST16 "FST Médecine hospitalière polyvalente"
* $TRE-R348-FormationSpecialiseeTransversale#FST17 "FST Médecine palliative"
* $TRE-R348-FormationSpecialiseeTransversale#FST18 "FST Médecine scolaire"
* $TRE-R348-FormationSpecialiseeTransversale#FST19 "FST Médecine en situation de guerre ou en SSE"
* $TRE-R348-FormationSpecialiseeTransversale#FST20 "FST Médecine et biologie reproduction-andrologie"
* $TRE-R348-FormationSpecialiseeTransversale#FST21 "FST Médecine du sport"
* $TRE-R348-FormationSpecialiseeTransversale#FST22 "FST Nutrition appliquée"
* $TRE-R348-FormationSpecialiseeTransversale#FST23 "FST Pharmacologie médicale/ thérapeutique"
* $TRE-R348-FormationSpecialiseeTransversale#FST24 "FST Sommeil"
* $TRE-R348-FormationSpecialiseeTransversale#FST25 "FST Thérapie cellulaire/ transfusion"
* $TRE-R348-FormationSpecialiseeTransversale#FST26 "FST Urgences pédiatriques"
* $TRE-R348-FormationSpecialiseeTransversale#FST27 "FST Innovation et recherche en sciences biologiques et pharmaceutiques"