ValueSet: JDV_J183_Diplome_EPARS
Id: JDV-J183-Diplome-EPARS
Description: "Diplômes pour l'application EPARS"
* ^meta.versionId = "19"
* ^meta.lastUpdated = "2026-07-29T10:33:49.962+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2021-11-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J183-Diplome-EPARS/FHIR/JDV-J183-Diplome-EPARS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.240"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R48-DiplomeEtatFrancais#DE28 "DE Assistant de Service Social"
* $TRE-R48-DiplomeEtatFrancais#DE29 "DE Audioprothésiste"
* $TRE-R48-DiplomeEtatFrancais#DE30 "DE Ergothérapeute"
* $TRE-R48-DiplomeEtatFrancais#DE32 "DE Psychomotricien"
* $TRE-R48-DiplomeEtatFrancais#DE38 "DE Technicien de Laboratoire Médical (DETLM, DETAB ou DELAM)"
* $TRE-R48-DiplomeEtatFrancais#DE39 "DE Manipulateur d'Electro-Radiologie médicale"
* $TRE-R58-AutreTypeDiplome#DIP319 "Titre d'assistant dentaire"
* $TRE-R58-AutreTypeDiplome#DIP321 "Diplôme d'Ostéopathe d'un établissement agréé"
* $TRE-R58-AutreTypeDiplome#DIP322 "Master en Psychologie ou Psychanalyse + formation établissement agréé incluant un stage en ESSMS"
* $TRE-R58-AutreTypeDiplome#DIP323 "Licence + Master mention psychologie + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP324 "Licence + Master mention psychologie clinique, psychopatho et psycho santé + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP325 "Licence + Master mention psychologie sociale, du travail et des organisations + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP326 "Licence + Master mention psychologie de l'éducation et de la formation + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP327 "Licence + Master mention psychologie: psychopatho clinique psychanalytique + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP328 "Diplôme de niveau Master en psychanalyse"
* $TRE-R58-AutreTypeDiplome#DIP329 "Diplôme de Chiropraxie"
* $TRE-R58-AutreTypeDiplome#DIP331 "Certificat d'études acoustique prothèse auditive"
* $TRE-R58-AutreTypeDiplome#DIP332 "Examen professionnel d'Audio-Prothésiste"
* $TRE-R58-AutreTypeDiplome#DIP333 "Diplôme d'Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP334 "BTS Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP335 "Brevet professionnel d'Opticien-Lunetier"
* $TRE-R58-AutreTypeDiplome#DIP336 "Certificat d'études Ecole des métiers d'optique"
* $TRE-R58-AutreTypeDiplome#DIP337 "Diplôme écoles nat prof section Optique-lunetterie"
* $TRE-R58-AutreTypeDiplome#DIP338 "Titre ministres du commerce, économie et finances, enseignement sup et santé"
* $TRE-R58-AutreTypeDiplome#DIP340 "BTS Prothésiste-Orthésiste"
* $TRE-R58-AutreTypeDiplome#DIP341 "BTS Podo-Orthésiste"
* $TRE-R58-AutreTypeDiplome#DIP342 "Titre d'Orthopédiste-Orthésiste obtenu avant 2007"
* $TRE-R58-AutreTypeDiplome#DIP343 "Titre RNCP de Technicien Supérieur Orthopédiste-Orthésiste obtenu après 2007"
* $TRE-R58-AutreTypeDiplome#DIP345 "Titre RNCP d'Orthopédiste-Orthésiste obtenu après 2007"
* $TRE-R58-AutreTypeDiplome#DIP348 "Diplôme Technicien Laboratoire arrêté 21/10/1992"
* $TRE-R58-AutreTypeDiplome#DIP349 "Diplôme Technicien Laboratoire arrêté 04/11/1976"
* $TRE-R58-AutreTypeDiplome#DIP350 "BTS/BTSA de technicien de laboratoire listé dans l'arrêté du 21/10/1992"
* $TRE-R58-AutreTypeDiplome#DIP353 "Certificat de Capacité d'Orthophoniste"
* $TRE-R58-AutreTypeDiplome#DIP354 "Diplôme ou attestation MEN"
* $TRE-R58-AutreTypeDiplome#DIP355 "Certificat de Capacité d'Orthoptiste"
* $TRE-R58-AutreTypeDiplome#DIP356 "Licence psychologie + Maîtrise psychologie + DESS en psychologie"
* $TRE-R58-AutreTypeDiplome#DIP357 "Licence psychologie + Maîtrise psychologie + diplôme annexe Décret 90-255"
* $TRE-R58-AutreTypeDiplome#DIP358 "Licence psychologie + Maîtrise psychologie + DEA psychologie + Attestation Stage"
* $TRE-R58-AutreTypeDiplome#DIP359 "Diplôme pour usage du titre de psychologue (alinéa 6 à 9 art 1 décret 90-255)"
* $TRE-R58-AutreTypeDiplome#DIP360 "Usage restreint du titre de Psychologue (arrêté du 14/01/1993)"
* $TRE-R58-AutreTypeDiplome#DIP361 "Licence + Master psychologie + Attest stage"
* $TRE-R58-AutreTypeDiplome#DIP362 "Décision de Validation des Acquis de l'Expérience de Psychologue"
* $TRE-R58-AutreTypeDiplome#DIP364 "BT ou BTS de Diététique"
* $TRE-R58-AutreTypeDiplome#DIP409 "Diplôme de Qualification en Physique Radiologique et Médicale INSTN (dès 1996)"
* $TRE-R58-AutreTypeDiplome#DIP367 "DTS/BTS Manipulateur d'Electro-Radiologie médicale"
* $TRE-R58-AutreTypeDiplome#DIP368 "DTS imagerie médicale et radiologie thérapeutique"
* $TRE-R58-AutreTypeDiplome#DIP412 "Diplôme ou titre ou certification délivré par le CNAM"
* $TRE-R58-AutreTypeDiplome#DIP414 "Diplôme ou titre délivré par l'AFPICL de Lyon (UCLy - ESTBB)"
* $TRE-R58-AutreTypeDiplome#DIP415 "Certificat de formation tech supérieur Physicien chimiste ministère travail"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP320 "DU ou DIU Ostéopathe université médecine reconnu CNOM"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP330 "DU Chiropraxie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP344 "DU ou DIU Orthopédie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP346 "DU Prothèse Oculaire appliquée"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP347 "DU Prothèse faciale"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP351 "DUT Génie biologique option analyses biologiques et biochimiques (avant 2023)"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP365 "DUT Génie biologique option diététique (avant 2023)"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP369 "BUT Génie biologique parcours diététique et nutrition"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP410 "DUT Biologie appliquée option analyses biologiques et biochimiques"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP411 "BUT Génie biologique parcours biologie médicale et biotechnologie"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP413 "DU Analyses des milieux biologiques université de Corte"
* $TRE-R54-DiplomeUniversiteInterUniversitaire#DIP416 "DUT Biologie appliquée option diététique"
* $TRE-R56-Attestation#DIP363 "Attestation de connaissances d'Ergothérapeute"
* $TRE-R56-Attestation#DIP366 "Attestation de connaissances de Psychomotricien"
* $TRE-R56-Attestation#DIP370 "Attestation de connaissances de MER"