ValueSet: JDV_J46_TypeEvenementNotification_CISIS
Id: JDV-J46-TypeEvenementNotification-CISIS
Description: "Liste de types d'évènement pour lesquels une notification est possible"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:06:36.733+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2018-03-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J46-TypeEvenementNotification-CISIS/FHIR/JDV-J46-TypeEvenementNotification-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.101"
* ^version = "20220624120000"
* ^status = #active
* ^experimental = false
* ^date = "2022-06-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R254-TypeEvenement#ADM "Admission d'un patient dans un établissement de santé"
* $TRE-R254-TypeEvenement#AUT "Autorisation de paiement de la facture des dispositifs médicaux"
* $TRE-R254-TypeEvenement#CDM "Commande de dispositifs médicaux"
* $TRE-R254-TypeEvenement#DEM "Demande de dispositifs médicaux à la pharmacie de l'établissement de santé"
* $TRE-R254-TypeEvenement#DEL "Délivrance des dispositifs médicaux au service en charge de la pose chez le patient"
* $TRE-R254-TypeEvenement#DOC "Dépôt de document pour un patient"
* $TRE-R254-TypeEvenement#ECH "Echec de pose du dispositif médical"
* $TRE-R254-TypeEvenement#ESD "Entrée de stock des dispositifs médicaux au sein de l'établissement de santé"
* $TRE-R254-TypeEvenement#NCO "Dispositif médical non-conforme, présentant un risque inacceptable pour la santé et la sécurité"
* $TRE-R254-TypeEvenement#NOT "Création d'une note pour un patient dans le cahier de liaison"
* $TRE-R254-TypeEvenement#PER "Dispositif médical périmé"
* $TRE-R254-TypeEvenement#POS "Pose du dispositif médical"
* $TRE-R254-TypeEvenement#REA "Demande de réassort en dispositifs médicaux"
* $TRE-R254-TypeEvenement#REC "Réception valide du dispositif médical par l'établissement de santé"
* $TRE-R254-TypeEvenement#REP "Réponse de la pharmacie de l'établissement de santé au service responsable de la demande"
* $TRE-R254-TypeEvenement#SDM "Suppression de la demande de dispositif médicaux"
* $TRE-R254-TypeEvenement#SOR "Sortie d'un patient de l'établissement de santé"
* $TRE-R254-TypeEvenement#SSD "Sortie de stock des dispositifs médicaux"
* $TRE-R254-TypeEvenement#TRA "Transport des dispositifs médicaux"