ValueSet: JDV_J18_EquipementSpecifique_ROR
Id: JDV-J18-EquipementSpecifique-ROR
Description: "Equipement spécifique - ROR"
* ^meta.versionId = "23"
* ^meta.lastUpdated = "2026-07-29T08:04:51.592+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J18-EquipementSpecifique-ROR/FHIR/JDV-J18-EquipementSpecifique-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.6"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R212-Equipement#003 "Angioscope"
* $TRE-R212-Equipement#005 "Autotransfuseur"
* $TRE-R212-Equipement#009 "Chambre à pression négative"
* $TRE-R212-Equipement#010 "Chambre à pression positive (chambre stérile)"
* $TRE-R212-Equipement#017 "Coronaroscanner"
* $TRE-R212-Equipement#021 "Echographe transportable"
* $TRE-R212-Equipement#030 "Echographe 3D"
* $TRE-R212-Equipement#040 "Equipement pour réentraînement (cycloergomètre, tapis roulant)"
* $TRE-R212-Equipement#041 "Ergorameur"
* $TRE-R212-Equipement#051 "Impédance masse graisseuse"
* $TRE-R212-Equipement#052 "IRM obésité diamètre de 70 cm - bariatrique"
* $TRE-R212-Equipement#054 "Imagerie par Résonance Magnétique (IRM) corps entier"
* $TRE-R212-Equipement#064 "Planche à massage cardiaque automatique"
* $TRE-R212-Equipement#065 "Polysomnographe portatif"
* $TRE-R212-Equipement#068 "Réaction en chaîne par polymérase (PCR)"
* $TRE-R212-Equipement#069 "Robot opératoire pour chirurgie robot assistée"
* $TRE-R212-Equipement#071 "Spectromètre de masse"
* $TRE-R212-Equipement#072 "Table de bloc opératoire obésité (poids > 250 kg) - bariatrique"
* $TRE-R212-Equipement#083 "Table de radiologie interventionnelle obésité (poids entre 150 et 250 kg) - bariatrique"
* $TRE-R212-Equipement#084 "Table de radiologie interventionnelle obésité (poids supérieur à 250 kg) - bariatrique"
* $TRE-R212-Equipement#085 "Scanner (TDM) obésité diamètre de 80 cm - bariatrique"
* $TRE-R212-Equipement#086 "Scanner (TDM) obésité champ ouvert - bariatrique"
* $TRE-R212-Equipement#087 "Imagerie par Résonance Magnétique (IRM) à champ ouvert"
* $TRE-R212-Equipement#088 "Table de bloc opératoire obésité (poids entre 150 et 250 kg) - bariatrique"
* $TRE-R212-Equipement#089 "Lit d'hospitalisation obésité (poids entre 250 et 350 kg) - bariatrique"
* $TRE-R212-Equipement#090 "Lit d'hospitalisation obésité (poids entre 350 et 450 kg) - bariatrique"
* $TRE-R212-Equipement#091 "Brancard obésité (poids entre 180 et 250 kg) - bariatrique"
* $TRE-R212-Equipement#092 "Brancard obésité (poids entre 250 et 350 kg) - bariatrique"
* $TRE-R212-Equipement#093 "ECMO transportable"
* $TRE-R212-Equipement#094 "Mammographe"
* $TRE-R212-Equipement#095 "Laboratoire microbiologie P3"
* $TRE-R212-Equipement#096 "Laboratoire microbiologie P4"
* $TRE-R212-Equipement#097 "Chambre d'isolement et de contention"
* $TRE-R212-Equipement#098 "Bassin thérapeutique pour balnéothérapie (<25m2)"
* $TRE-R212-Equipement#099 "Bassin thérapeutique pour balnéothérapie (>=25m2)"
* $TRE-R212-Equipement#100 "Salle aménagée pour la thérapie systémique"
* $TRE-R212-Equipement#101 "Salle de stimulation multi-sensorielle"
* $TRE-R212-Equipement#102 "Appareil d'isocinétisme"
* $TRE-R212-Equipement#103 "Assistance robotisée à la marche"
* $TRE-R212-Equipement#104 "Assistance robotisée des membres supérieurs et de la préhension"
* $TRE-R212-Equipement#106 "Laboratoire d'analyse tridimensionnelle du mouvement, de la marche"
* $TRE-R212-Equipement#109 "Equipement de réadaptation obésité - bariatrique"
* $TRE-R212-Equipement#110 "Studio pré-greffe et post-greffe"
* $TRE-R212-Equipement#111 "Douche filiforme pour brûlés"
* $TRE-R212-Equipement#112 "Equipement pour monitorage par télémétrie"
* $TRE-R212-Equipement#113 "Prises d'oxygène en salle de rééducation"
* $TRE-R212-Equipement#114 "Locaux adaptés à la désorientation temporo-spatiale"
* $TRE-R212-Equipement#115 "Prises d'oxygène dans les chambres"
* $TRE-R212-Equipement#116 "Appartement pour mise en situation d'autonomie"
* $TRE-R212-Equipement#118 "Monitoring cardiaque portatif"
* $TRE-R212-Equipement#119 "Plateau technique neuropsycho cognitif"
* $TRE-R212-Equipement#120 "Simulateur de conduite automobile"
* $TRE-R212-Equipement#121 "Véhicules adaptés à la conduite en situation de handicap"
* $TRE-R212-Equipement#122 "Mur d'escalade"
* $TRE-R212-Equipement#123 "Chambre domotisée"
* $TRE-R212-Equipement#124 "Atelier de confection de prothèses"
* $TRE-R212-Equipement#125 "Gymnase"
* $TRE-R212-Equipement#126 "Cuisine thérapeutique et éducative"
* $TRE-R212-Equipement#127 "Système de traction halo-crânienne"
* $TRE-R212-Equipement#128 "Plateforme multitest équilibre"
* $TRE-R212-Equipement#129 "Plateau d'analyse informatisée du rachis"
* $TRE-R212-Equipement#130 "Chambre et locaux sécurisés permettant la prise en charge des personnes à risque suicidaire"
* $TRE-R212-Equipement#131 "Module fixe de décontamination"
* $TRE-R212-Equipement#132 "Module transportable de décontamination"
* $TRE-R212-Equipement#134 "Appareil de biologie délocalisé"
* $TRE-R212-Equipement#135 "Incubateur de transport"
* $TRE-R212-Equipement#136 "Respirateur néonatal et pédiatrique de transport"
* $TRE-R212-Equipement#137 "Chambre carcérale"
* $TRE-R212-Equipement#138 "PSM1 (Poste Sanitaire Mobile niveau 1)"
* $TRE-R212-Equipement#139 "PSM2 (Poste Sanitaire Mobile niveau 2)"
* $TRE-R212-Equipement#140 "PSM3 (Poste Sanitaire Mobile niveau 3)"
* $TRE-R212-Equipement#141 "Poste médical avancé (PMA)"
* $TRE-R212-Equipement#142 "Appareil de mesure de la glycémie capillaire"
* $TRE-R212-Equipement#144 "Système EOS"
* $TRE-R212-Equipement#145 "Salle physiologique (salle nature accouchement)"
* $TRE-R212-Equipement#147 "Espace de calme-retrait, d'apaisement"
* $TRE-R212-Equipement#148 "Jardin pédagogique et-ou thérapeutique"
* $TRE-R212-Equipement#149 "Ferme pédagogique et-ou thérapeutique"
* $TRE-R212-Equipement#150 "Plateau ou salle de rééducation"
* $TRE-R212-Equipement#152 "Equipement de géolocalisation des personnes vulnérables"
* $TRE-R212-Equipement#153 "Equipement de télémédecine (chariot, cabine, équipement mobile…)"
* $TRE-R212-Equipement#154 "Chambre à double flux"
* $TRE-R212-Equipement#155 "Rails de transfert"
* $TRE-R212-Equipement#157 "Systèmes corporels d'alerte sans fil"
* $TRE-R212-Equipement#158 "Fauteuil rotatoire"
* $TRE-R212-Equipement#159 "Plateforme verticale subjective"
* $TRE-R212-Equipement#160 "Appartement domotisé pour mise en situation d'autonomie"
* $TRE-R212-Equipement#161 "Caisson hyperbare occupation simple"
* $TRE-R212-Equipement#162 "Caisson hyperbare occupation multiple patient intubé"
* $TRE-R212-Equipement#163 "Caisson hyperbare occupation multiple patient non intubé"
* $TRE-R212-Equipement#164 "Cabine de cryothérapie"
* $TRE-R212-Equipement#165 "PCA ou autre injecteur automatique d'antalgiques"
* $TRE-R212-Equipement#166 "PCR multiplex (Film array)"
* $TRE-R212-Equipement#167 "Séquenceurs haut débit (NGS)"
* $TRE-R212-Equipement#168 "Cytomètre de flux"
* $TRE-R212-Equipement#169 "Atelier de confection d'orthèse"
* $TRE-R212-Equipement#170 "Atelier de confection aide technique"
* $TRE-R212-Equipement#173 "Polymorphisme mononucléotidique"
* $TRE-R212-Equipement#174 "Hybridation génomique comparative (HGC)"
* $TRE-R212-Equipement#175 "Spectromètre de masse haute résolution"
* $TRE-R212-Equipement#176 "Chromatographe haute performance en phase liquide"
* $TRE-R212-Equipement#177 "Chromatographe en phase gazeuse"
* $TRE-R212-Equipement#178 "Agrégomètre optique"
* $TRE-R212-Equipement#179 "Véhicules adaptés au transport de personnes à mobilité réduite"
* $TRE-R212-Equipement#180 "Pupillomètre"
* $TRE-R212-Equipement#181 "Accélérateur réchauffeur de sang"
* $TRE-R212-Equipement#183 "Equipement d'oxygénothérapie de déambulation"
* $TRE-R212-Equipement#184 "Dispositif de réadaptation à la marche par allègement du poids du corps (anti-gravité)"
* $TRE-R212-Equipement#185 "PSM pédiatriques (Poste Sanitaire Mobile)"
* $TRE-R212-Equipement#186 "Lit fluidisé"
* $TRE-R212-Equipement#187 "Table réfrigérée"
* $TRE-R212-Equipement#188 "Case réfrigérée"
* $TRE-R212-Equipement#189 "Table de coronarographie obésité (poids entre 150 et 250 kg) - bariatrique"
* $TRE-R212-Equipement#190 "Table de coronarographie obésité (poids entre 250 et 350 kg) - bariatrique"
* $TRE-R212-Equipement#191 "Table de coronarographie obésité (poids entre 350 et 450 kg) - bariatrique"
* $TRE-R212-Equipement#192 "Arthromoteurs (genoux, épaules, coudes)"
* $TRE-R212-Equipement#193 "Appareils de renforcement musculaire"
* $TRE-R212-Equipement#194 "Appareil d'ondes de choc pour traitement non invasif"
* $TRE-R212-Equipement#195 "Appareil de massage par vacuo-aspiration"
* $TRE-R212-Equipement#196 "Absorptiomètre obésité 70-80 cm (densitomètre bariatrique)"
* $TRE-R212-Equipement#197 "Fauteuil obésité (poids entre 250 et 350 kg) bariatrique"
* $TRE-R212-Equipement#198 "Holter tensionnel bariatrique"
* $TRE-R212-Equipement#199 "Appareil d'imagerie volumétrique par faisceau conique (CBCT)"
* $TRE-R212-Equipement#200 "Fauteuil dentaire adapté au handicap moteur"
* $TRE-R212-Equipement#201 "Laser rétinien"
* $TRE-R212-Equipement#202 "Laser Yag ophtalmologique"
* $TRE-R212-Equipement#203 "Atelier intégré d'appareillage"
* $TRE-R212-Equipement#204 "Imagerie par fluorescence"
* $TRE-R212-Equipement#205 "Ultrason de haute intensité (HIFU)"
* $TRE-R212-Equipement#206 "Dispositif mobile de traitement d'air"
* $TRE-R212-Equipement#207 "Défibrillateur semi-automatique"
* $TRE-R212-Equipement#208 "Equipement de téléradiographie"
* $TRE-R212-Equipement#209 "Arthromoteurs membres inférieurs (genoux)"
* $TRE-R212-Equipement#210 "Arthromoteurs membres supérieurs (épaules, coudes)"
* $TRE-R212-Equipement#211 "Salle hybride"
* $TRE-R212-Equipement#212 "Vidéo assistance"
* $TRE-R212-Equipement#213 "Dermatoscope connecté"
* $TRE-R212-Equipement#214 "Débitmètre de pointe adulte / enfant (peakflow)"
* $TRE-R212-Equipement#215 "Otoscope connecté"
* $TRE-R212-Equipement#216 "Stéthoscope connecté"
* $TRE-R212-Equipement#217 "Appareil de pressothérapie"
* $TRE-R212-Equipement#218 "Dispositif d'électrostimulation fonctionnelle"
* $TRE-R212-Equipement#219 "Parcours de marche"
* $TRE-R212-Equipement#220 "ECG portable"
* $TRE-R212-Equipement#221 "Imagerie par Résonance Magnétique (IRM) obésité – bariatrique"
* $TRE-R212-Equipement#222 "Scanner (TDM) obésité - bariatrique"
* $TRE-R212-Equipement#223 "Table d'accouchement obésité - bariatrique"
* $TRE-R212-Equipement#224 "Table de coronarographie obésité - bariatrique"
* $TRE-R212-Equipement#225 "Chambre adaptée obésité - bariatrique"
* $TRE-R212-Equipement#226 "Table de radiologie interventionnelle obésité - bariatrique"
* $TRE-R212-Equipement#227 "Table de bloc opératoire obésité - bariatrique"
* $TRE-R212-Equipement#228 "Plateau de rééducation intensive des membres inférieurs"
* $TRE-R212-Equipement#229 "Douche accessible aux personnes en fauteuil roulant"
* $TRE-R212-Equipement#234 "Espace de consommation de drogues injectables"
* $TRE-R212-Equipement#235 "Espace de consommation de drogues à fumer"
* $TRE-R212-Equipement#236 "Appareil de thermoformage"
* $TRE-R212-Equipement#237 "Appareil de thermosoudage"
* $TRE-R212-Equipement#238 "Plateforme de force (étude de la posture)"
* $TRE-R212-Equipement#239 "Plateforme de pression (étude de la marche)"
* $TRE-R212-Equipement#240 "Piste de marche"
* $TRE-R212-Equipement#241 "Tapis de course"
* $TRE-R212-Equipement#242 "Système vidéo d'analyse de la marche et de la course"
* $TRE-R212-Equipement#243 "Semelles avec capteurs embarqués"
* $TRE-R212-Equipement#246 "Échographe polyvalent"
* $TRE-R212-Equipement#247 "Imagerie par Résonance Magnétique (IRM) à champ fermé (ou tunnel)"
* $TRE-R212-Equipement#248 "Imagerie par Résonance Magnétique (IRM) pédiatrique (compatible anesthésie)"
* $TRE-R212-Equipement#249 "Radiologie numérique standard"
* $TRE-R212-Equipement#250 "Scanner base dose (LDCT)"
* $TRE-R212-Equipement#251 "Plateau réfraction - Pachymétrie"
* $TRE-R212-Equipement#252 "Rétinographe"
* $TRE-R212-Equipement#253 "Oculomètre certifié (C2)"
* $TRE-R212-Equipement#254 "Coordimètre"
* $TRE-R212-Equipement#255 "Tests scorés et/ou normés en neurovision"
* $TRE-R212-Equipement#256 "Accompagnement à l’essai de fauteuil roulant"