ValueSet: JDV_J51_FamilleActiviteOperationnelle_ROR
Id: JDV-J51-FamilleActiviteOperationnelle-ROR
Description: "Famille Activité Opérationnelle"
* ^meta.versionId = "3"
* ^meta.lastUpdated = "2026-07-06T19:06:38.930+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2018-05-31T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J51-FamilleActiviteOperationnelle-ROR/FHIR/JDV-J51-FamilleActiviteOperationnelle-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.62"
* ^version = "20230127120000"
* ^status = #active
* ^experimental = false
* ^date = "2023-01-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R266-FamilleActiviteOperationnelleHorsSerafin#01 "Accompagnement des aidants"
* $TRE-R266-FamilleActiviteOperationnelleHorsSerafin#02 "Prévention et éducation thérapeutique"
* $TRE-R266-FamilleActiviteOperationnelleHorsSerafin#03 "Prévention des violences"
* $TRE-R266-FamilleActiviteOperationnelleHorsSerafin#04 "Hébergement et logement"
* $TRE-R265-PrestationPilotageSerafin#004 "2.1.1.1 Soins médicaux à visée préventive, curative et palliative"
* $TRE-R265-PrestationPilotageSerafin#005 "2.1.1.2 Soins techniques et de surveillance infirmiers ou délégués"
* $TRE-R265-PrestationPilotageSerafin#006 "2.1.1.3 Prestations des psychologues"
* $TRE-R265-PrestationPilotageSerafin#009 "2.1.2.1 Prestations des auxiliaires médicaux, des instructeurs en locomotion et avéjistes"
* $TRE-R265-PrestationPilotageSerafin#011 "2.2.1.1 Accompagnements pour les actes de la vie quotidienne"
* $TRE-R265-PrestationPilotageSerafin#012 "2.2.1.2 Accompagnements pour la communication et les relations avec autrui"
* $TRE-R265-PrestationPilotageSerafin#013 "2.2.1.3 Accompagnements pour prendre des décisions adaptées et pour la sécurité"
* $TRE-R265-PrestationPilotageSerafin#019 "2.3.2.1 Accompagnements pour vivre dans un logement"
* $TRE-R265-PrestationPilotageSerafin#020 "2.3.2.2 Accompagnements pour accomplir les activités domestiques"
* $TRE-R265-PrestationPilotageSerafin#022 "2.3.3.1 Accompagnements pour mener sa vie d'élève, d'étudiant ou d'apprenti"
* $TRE-R265-PrestationPilotageSerafin#023 "2.3.3.2 Accompagnements pour préparer sa vie professionnelle"
* $TRE-R265-PrestationPilotageSerafin#024 "2.3.3.3 Accompagnements pour mener sa vie professionnelle"
* $TRE-R265-PrestationPilotageSerafin#025 "2.3.3.4 Accompagnements pour réaliser des activités de jour spécialisées"
* $TRE-R265-PrestationPilotageSerafin#026 "2.3.3.5 Accompagnements de la vie familiale, de la parentalité, de la vie affective et sexuelle"
* $TRE-R265-PrestationPilotageSerafin#027 "2.3.3.6 Accompagnements pour l'exercice de mandats électoraux, la représentation des pairs et la pair aidance"
* $TRE-R265-PrestationPilotageSerafin#029 "2.3.4.1 Accompagnements du lien avec les proches et le voisinage"
* $TRE-R265-PrestationPilotageSerafin#030 "2.3.4.2 Accompagnements pour la participation aux activités sociales et de loisirs"
* $TRE-R265-PrestationPilotageSerafin#031 "2.3.4.3 Accompagnements pour le développement de l'autonomie pour les déplacements"
* $TRE-R265-PrestationPilotageSerafin#034 "2.3.5.1 Accompagnements pour l'ouverture des droits"
* $TRE-R265-PrestationPilotageSerafin#035 "2.3.5.2 Accompagnements pour l'autonomie de la personne dans la gestion de ses ressources"
* $TRE-R265-PrestationPilotageSerafin#037 "2.4 Prestation de coordination renforcée pour la cohérence du parcours"
* $TRE-R265-PrestationPilotageSerafin#053 "3.1.5 Relations avec le territoire"
* $TRE-R265-PrestationPilotageSerafin#054 "3.1.5.1 Coopération, conventions avec les acteurs spécialisés et du droit commun"
* $TRE-R265-PrestationPilotageSerafin#065 "3.2.2.1 Fournir des repas"
* $TRE-R265-PrestationPilotageSerafin#067 "3.2.3.1 Entretenir le linge"