ValueSet: JDV_J108_EnsembleFonction_RASS
Id: JDV-J108-EnsembleFonction-RASS
Description: "Ensemble des fonctions et rôles du RASS"
* ^meta.versionId = "25"
* ^meta.lastUpdated = "2026-07-06T19:04:49.335+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J108-EnsembleFonction-RASS/FHIR/JDV-J108-EnsembleFonction-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.176"
* ^version = "20260505120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-05-05T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R21-Fonction#FON-01 "Titulaire de cabinet"
* $TRE-R21-Fonction#FON-02 "Associé dans une société d'exercice (SEL ou SCP)"
* $TRE-R21-Fonction#FON-03 "Titulaire d'officine"
* $TRE-R21-Fonction#FON-04 "Remplaçant du titulaire d'officine"
* $TRE-R21-Fonction#FON-05 "Adjoint"
* $TRE-R21-Fonction#FON-07 "Gérant après incapacité ou décès"
* $TRE-R21-Fonction#FON-09 "Responsable d'établissement"
* $TRE-R21-Fonction#FON-15 "Directeur de laboratoire"
* $TRE-R21-Fonction#FON-16 "Directeur-adjoint de laboratoire"
* $TRE-R21-Fonction#FON-17 "Collaborateur"
* $TRE-R21-Fonction#FON-18 "Assistant"
* $TRE-R21-Fonction#FON-19 "Praticien Conseil"
* $TRE-R21-Fonction#FON-21 "Médecin scolaire"
* $TRE-R21-Fonction#FON-22 "Remplaçant, intérimaire, intermittent"
* $TRE-R21-Fonction#FON-23 "Gérant"
* $TRE-R21-Fonction#FON-24 "Médecin de santé publique"
* $TRE-R21-Fonction#FON-29 "Médecin du travail"
* $TRE-R21-Fonction#FON-32 "Régulateur libéral"
* $TRE-R21-Fonction#FON-33 "Salarié en poste fixe"
* $TRE-R21-Fonction#FON-36 "Délégué"
* $TRE-R21-Fonction#FON-37 "Gérant de PUI"
* $TRE-R21-Fonction#FON-39 "Exercice en PMI"
* $TRE-R21-Fonction#FON-40 "Biologiste responsable"
* $TRE-R21-Fonction#FON-41 "Biologiste médical"
* $TRE-R21-Fonction#FON-42 "Assistant collaborateur"
* $TRE-R21-Fonction#FON-43 "Cadre de santé"
* $TRE-R21-Fonction#FON-45 "Directeur des soins"
* $TRE-R21-Fonction#FON-46 "Enseignant salarié"
* $TRE-R21-Fonction#FON-47 "Etudiant remplaçant, adjoint"
* $TRE-R21-Fonction#FON-48 "Interne"
* $TRE-R21-Fonction#FON-49 "Pharmacien responsable BPDO"
* $TRE-R21-Fonction#FON-50 "Pharmacien adjoint BPDO"
* $TRE-R21-Fonction#FON-51 "Remplacement partiel"
* $TRE-R21-Fonction#FON-52 "Etudiant militaire"
* $TRE-R21-Fonction#FON-54 "Permanence des soins ambulatoires hors cabinet"
* $TRE-R21-Fonction#FON-55 "Participation libérale aux missions de service public d'un ES"
* $TRE-R21-Fonction#FON-56 "Intervention libérale dans le cadre d'un GCS"
* $TRE-R21-Fonction#FON-57 "Docteur junior"
* $TRE-R21-Fonction#FON-58 "Activité en piscine ou bassin"
* $TRE-R21-Fonction#FON-59 "Gérant d'antenne"
* $TRE-R21-Fonction#FON-60 "Pharmacien remplaçant BPDO"
* $TRE-R21-Fonction#FON-61 "Prestataire de Services"
* $TRE-R21-Fonction#FON-62 "Consultations de solidarité territoriale"
* $TRE-R21-Fonction#FON-63 "Coordonnateur en EHPAD"
* $TRE-R21-Fonction#FON-AU "Fonction non définie"
* $TRE-R96-AutreFonctionSanitaire#407 "Tatoueur"
* $TRE-R96-AutreFonctionSanitaire#408 "Perceur corporel"
* $TRE-R96-AutreFonctionSanitaire#409 "Maquilleur permanent"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#331 "Secrétaire assistante médico-administrative"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#336 "Autre professionnel intervenant dans l'accueil et l'orientation des personnes"
* $TRE-R85-RolePriseCharge#337 "Autre professionnel intervenant dans la logistique"
* $TRE-R85-RolePriseCharge#338 "Autre professionnel intervenant dans l'hôtellerie et la restauration"
* $TRE-R85-RolePriseCharge#339 "Autre professionnel intervenant dans la direction de la qualité, hygiène, sécurité et environnement"
* $TRE-R85-RolePriseCharge#340 "Autre professionnel intervenant dans la direction des systèmes d'information"
* $TRE-R85-RolePriseCharge#341 "Autre professionnel intervenant dans la direction des finances et comptabilité"
* $TRE-R85-RolePriseCharge#342 "Autre professionnel intervenant dans la direction de la communication"
* $TRE-R85-RolePriseCharge#343 "Autre professionnel intervenant dans la direction des ressources humaines"
* $TRE-R85-RolePriseCharge#344 "Autre professionnel intervenant dans la direction des affaires médicales"
* $TRE-R85-RolePriseCharge#345 "Autre professionnel intervenant dans le social, éducatif, psychologie et culturel"
* $TRE-R85-RolePriseCharge#346 "Etudiant - infirmier"
* $TRE-R85-RolePriseCharge#347 "Etudiant - aide-soignant"
* $TRE-R85-RolePriseCharge#348 "Etudiant - auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#349 "Etudiant - masseur-kinésithérapeute"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE-R85-RolePriseCharge#353 "Membre de l'équipe de soins"
* $TRE-R85-RolePriseCharge#354 "Externe en médecine"
* $TRE-R85-RolePriseCharge#355 "Externe en odontologie"
* $TRE-R85-RolePriseCharge#356 "Externe en maïeutique"
* $TRE-R85-RolePriseCharge#357 "Externe en pharmacie"
* $TRE-R85-RolePriseCharge#358 "Autre étudiant"
* $TRE-R85-RolePriseCharge#359 "Directeur d'établissement"
* $TRE-R85-RolePriseCharge#360 "Brancardier"
* $TRE-R85-RolePriseCharge#361 "Educateur en activité physique adaptée"
* $TRE-R85-RolePriseCharge#362 "Technicien d'informations médicales"
* $TRE-R85-RolePriseCharge#363 "Attaché de recherche clinique"
* $TRE-R85-RolePriseCharge#364 "Praticien A Diplôme Hors Union Européenne (PADHUE)"
* $TRE-R85-RolePriseCharge#365 "Gestionnaire admissions / frais de séjour / traitement externe"
* $TRE-R85-RolePriseCharge#366 "Archiviste"
* $TRE-R85-RolePriseCharge#367 "Surveillant de nuit"
* $TRE-R85-RolePriseCharge#368 "Animateur"
* $TRE-R85-RolePriseCharge#370 "Opérateur de Soins Non Programmés"
* $TRE-R85-RolePriseCharge#371 "Aide à domicile qualifié(e)"
* $TRE-R85-RolePriseCharge#372 "Aide à domicile"
* $TRE-R85-RolePriseCharge#374 "Agent d'autorité d'enregistrement"
* $TRE-R85-RolePriseCharge#375 "Conseiller conjugal et familial"
* $TRE-R85-RolePriseCharge#376 "PADHUE - Médecin"
* $TRE-R85-RolePriseCharge#377 "PADHUE - Pharmacien"
* $TRE-R85-RolePriseCharge#378 "PADHUE - Sage Femme"
* $TRE-R85-RolePriseCharge#379 "PADHUE - Chirurgien Dentiste"