ValueSet: JDV_J132_ModaliteActivite_RASS
Id: JDV-J132-ModaliteActivite-RASS
Description: "Mode d'application ou type de soins encadrant une activité dans le RASS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:05:05.001+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J132-ModaliteActivite-RASS/FHIR/JDV-J132-ModaliteActivite-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.218"
* ^version = "20220325120000"
* ^status = #active
* ^experimental = false
* ^date = "2022-03-25T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R275-ModaliteActivite#00 "Pas de modalité"
* $TRE-R275-ModaliteActivite#01 "Gynécologie obstétrique"
* $TRE-R275-ModaliteActivite#02 "Néonatologie sans soins intensifs"
* $TRE-R275-ModaliteActivite#03 "Néonatologie avec soins intensifs"
* $TRE-R275-ModaliteActivite#04 "Réanimation néonatale"
* $TRE-R275-ModaliteActivite#05 "Centre périnatal de proximité"
* $TRE-R275-ModaliteActivite#06 "Générale"
* $TRE-R275-ModaliteActivite#07 "Infanto-juvénile"
* $TRE-R275-ModaliteActivite#08 "En milieu pénitentiaire"
* $TRE-R275-ModaliteActivite#09 "Adulte (age >=18 ans)"
* $TRE-R275-ModaliteActivite#10 "Pédiatrique"
* $TRE-R275-ModaliteActivite#11 "Poumon"
* $TRE-R275-ModaliteActivite#12 "Foie"
* $TRE-R275-ModaliteActivite#13 "Rein"
* $TRE-R275-ModaliteActivite#22 "SAMU Service d'aide médicale urgente"
* $TRE-R275-ModaliteActivite#23 "SU Structure des urgences"
* $TRE-R275-ModaliteActivite#24 "SUP Structure des urgences pédiatriques"
* $TRE-R275-ModaliteActivite#26 "SMUR Structure mobile d'urgence et de réanimation"
* $TRE-R275-ModaliteActivite#27 "SMURP Structure mobile d'urgence et de réanimation pédiatrique"
* $TRE-R275-ModaliteActivite#29 "SMUR Antenne"
* $TRE-R275-ModaliteActivite#30 "USI Pneumologie Pédiatrique"
* $TRE-R275-ModaliteActivite#31 "Multi-organes"
* $TRE-R275-ModaliteActivite#40 "Hémodialyse en centre pour adultes"
* $TRE-R275-ModaliteActivite#41 "Hémodialyse en centre pour enfants"
* $TRE-R275-ModaliteActivite#42 "Hémodialyse en unité médicalisée"
* $TRE-R275-ModaliteActivite#43 "Hémodialyse en unité d'auto dialyse simple"
* $TRE-R275-ModaliteActivite#44 "Hémodialyse en unité d'auto dialyse assistée"
* $TRE-R275-ModaliteActivite#45 "Hémodialyse à domicile"
* $TRE-R275-ModaliteActivite#46 "Dialyse péritonéale à domicile"
* $TRE-R275-ModaliteActivite#47 "AMP clinique : prélèvement d'ovocytes en vue d'une AMP"
* $TRE-R275-ModaliteActivite#48 "AMP clinique : prélèvement d'ovocytes en vue d'un don"
* $TRE-R275-ModaliteActivite#49 "AMP clinique : prélèvement de spermatozoïdes"
* $TRE-R275-ModaliteActivite#50 "AMP clinique : transfert des embryons en vue de leur implantation"
* $TRE-R275-ModaliteActivite#51 "Bio : préparation et conservation du sperme pour insémination artificielle"
* $TRE-R275-ModaliteActivite#52 "AMP Bio : recueil, prép, conservation et mise à disposition du sperme pour don"
* $TRE-R275-ModaliteActivite#54 "AMP Bio : prépa, conservation et mise à disposition d'ovocytes en vue d'un don"
* $TRE-R275-ModaliteActivite#59 "AMP Bio : Conservation des embryons pour accueil et mise en oeuvre de celui-ci"
* $TRE-R275-ModaliteActivite#60 "DPN : Exams de cytogénétique inclus exams moléculaires appliqués cytogénétique"
* $TRE-R275-ModaliteActivite#62 "DPN : Les examens en vue du diagnostic de maladies infectieuses"
* $TRE-R275-ModaliteActivite#67 "Chimiothérapie ou autres traitements médicaux spécifiques du cancer"
* $TRE-R275-ModaliteActivite#68 "Radiothérapie externe"
* $TRE-R275-ModaliteActivite#69 "Chirurgie des cancers hors soumis à seuil"
* $TRE-R275-ModaliteActivite#70 "Curiethérapie"
* $TRE-R275-ModaliteActivite#71 "Utilisation thérapeutique de radioéléments en sources non scellées"
* $TRE-R275-ModaliteActivite#72 "Unité de dialyse saisonnière"
* $TRE-R275-ModaliteActivite#73 "AMP Clinique : mise en oeuvre de l'accueil des embryons"
* $TRE-R275-ModaliteActivite#74 "AMP Bio : conservation des embryons en vue d'un projet parental"
* $TRE-R275-ModaliteActivite#75 "AMP Bio : conservation à usage autologue des gamètes et tissus germinaux"
* $TRE-R275-ModaliteActivite#76 "Adulte et pédiatrique"
* $TRE-R275-ModaliteActivite#77 "Enfant (< de 6 ans)"
* $TRE-R275-ModaliteActivite#78 "Juvénile (age >= 6 ans et < 18 ans)"
* $TRE-R275-ModaliteActivite#79 "Pédiatrie - âges non différenciés"
* $TRE-R275-ModaliteActivite#80 "AMP Bio : activité relative à la FIV avec ou sans micromanipulation"
* $TRE-R275-ModaliteActivite#81 "Actes électrophysio de rythmologie intervent, stimul multi sites et défibril"
* $TRE-R275-ModaliteActivite#82 "Actes sur cardiopathies enfant, y compris éventuelles ré-interventions adulte"
* $TRE-R275-ModaliteActivite#83 "Actes portant sur les autres cardiopathies de l'adulte"
* $TRE-R275-ModaliteActivite#84 "Analyses cytogénétique, y compris les analyses cytogénétique moléculaire"
* $TRE-R275-ModaliteActivite#85 "Analyses de génétique moléculaire"
* $TRE-R275-ModaliteActivite#87 "Fonctionnelle cérébrale"
* $TRE-R275-ModaliteActivite#88 "Radiochirurgie intracrânienne et extracrânienne en conditions stéréotaxiques"
* $TRE-R275-ModaliteActivite#89 "Radiothérapie externe dérogatoire éloignement géographique"
* $TRE-R275-ModaliteActivite#90 "Chirurgie des cancers : digestif"
* $TRE-R275-ModaliteActivite#91 "Chirurgie des cancers : sein"
* $TRE-R275-ModaliteActivite#92 "Chirurgie des cancers : urologie"
* $TRE-R275-ModaliteActivite#93 "Chirurgie des cancers : thorax"
* $TRE-R275-ModaliteActivite#94 "Chirurgie des cancers : gynécologie"
* $TRE-R275-ModaliteActivite#95 "Chirurgie des cancers : ORL et maxillo-faciale"
* $TRE-R275-ModaliteActivite#97 "Adulte (age >=18 ans) dérogatoire éloignement géographique"
* $TRE-R275-ModaliteActivite#98 "Pédiatrique spécialisée"
* $TRE-R275-ModaliteActivite#99 "Sans autre indication"
* $TRE-R275-ModaliteActivite#AL "DPN : Les examens de biochimie portant sur les marqueurs sériques maternels"
* $TRE-R275-ModaliteActivite#AM "DPN : Les examens de biochimie foetale à visée diagnostique"
* $TRE-R275-ModaliteActivite#AN "DPN : Les examens de génétique moléculaire"
* $TRE-R275-ModaliteActivite#AP "DPN : Exams de génétique sur l'ADN foetal libre circulant dans le sang maternel"
* $TRE-R275-ModaliteActivite#AQ "1ère administration à l'homme d'un médicament"
* $TRE-R275-ModaliteActivite#AR "1ère administration à l'homme autre que médicament"
* $TRE-R275-ModaliteActivite#B1 "Chirurgie orthopédique et traumatologique"
* $TRE-R275-ModaliteActivite#B2 "Chirurgie pédiatrique"
* $TRE-R275-ModaliteActivite#B3 "Clinique ouverte"
* $TRE-R275-ModaliteActivite#B4 "Gériatrie"
* $TRE-R275-ModaliteActivite#B5 "Grands brûlés"
* $TRE-R275-ModaliteActivite#B7 "Grands brûlés - Adulte"
* $TRE-R275-ModaliteActivite#B8 "Orthogénie"
* $TRE-R275-ModaliteActivite#B9 "Grands brûlés - Pédiatrique"
* $TRE-R275-ModaliteActivite#C2 "Adulte (âge >=18 ans) - Traitement dont chimiothérapie"
* $TRE-R275-ModaliteActivite#C4 "Neurovasculaire"
* $TRE-R275-ModaliteActivite#C5 "Obstétrique - Anesthésie"
* $TRE-R275-ModaliteActivite#C6 "Odontologie"
* $TRE-R275-ModaliteActivite#C7 "Pédiatrique - Traitement dont chimiothérapie"
* $TRE-R275-ModaliteActivite#C8 "Pneumologie - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#C9 "Polytraumatismes graves et complexes multiples"
* $TRE-R275-ModaliteActivite#D2 "Réhabilitation et réinsertion psycho-sociale"
* $TRE-R275-ModaliteActivite#D3 "S.O.S. mains"
* $TRE-R275-ModaliteActivite#D4 "Structure de sevrage niveau 2"
* $TRE-R275-ModaliteActivite#D5 "Structure de sevrage niveau 3"
* $TRE-R275-ModaliteActivite#D6 "Traitements médicaux - Allogreffes de moelle osseuse - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#D7 "Traitements médicaux - Allogreffes de moelle osseuse - Pédiatrique"
* $TRE-R275-ModaliteActivite#D8 "Traitements médicaux - Autogreffes de moelle osseuse - Adulte (âge >= 18 ans )"
* $TRE-R275-ModaliteActivite#D9 "Traitements médicaux - Autogreffes de moelle osseuse - Pédiatrique"
* $TRE-R275-ModaliteActivite#E1 "Traitements médicaux - Autres traitements spécifiques - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#E2 "Traitements médicaux - Autres traitements spécifiques - Pédiatrique"
* $TRE-R275-ModaliteActivite#E3 "Traitements médicaux - Endoscopies digestives interventionnelles - Adulte"
* $TRE-R275-ModaliteActivite#E4 "Traumatismes cranio-cérébraux et médullaires"
* $TRE-R275-ModaliteActivite#E5 "Unité Cognitivo-Comportementale - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#E7 "Unité d'Hébergement Renforcée"
* $TRE-R275-ModaliteActivite#E8 "Unités de soins palliatifs à vocation régionale"
* $TRE-R275-ModaliteActivite#E9 "Urologie"
* $TRE-R275-ModaliteActivite#F1 "USI Chirurgie thoracique et cardio-vasculaire - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#F2 "USI Chirurgie thoracique et cardio-vasculaire - Pédiatrique"
* $TRE-R275-ModaliteActivite#F3 "USI Dermato - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#F5 "USI Hémato - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#F6 "USI Hémato - Pédiatrique"
* $TRE-R275-ModaliteActivite#F7 "USI Hématologie avec système de traitement de l'air"
* $TRE-R275-ModaliteActivite#F8 "USI hépato-gastro-entérologie - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#G1 "USI Maladie infectieuse - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#G3 "USI Néphrologie - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#G5 "USI Neuro - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#G6 "USI Neuro - Pédiatrique"
* $TRE-R275-ModaliteActivite#G8 "Lit de Soins Intensifs - Pédiatrique"
* $TRE-R275-ModaliteActivite#G9 "USI Oncologie - Pédiatrique"
* $TRE-R275-ModaliteActivite#H1 "USI Oncologie- Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#H4 "USI Pneumologie - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#H5 "USI Urologie - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#H8 "Prise en charge Covid long"
* $TRE-R275-ModaliteActivite#H9 "Vasculaire"
* $TRE-R275-ModaliteActivite#M0 "Dépôt d'urgence"
* $TRE-R275-ModaliteActivite#M1 "Dépôt de délivrance"
* $TRE-R275-ModaliteActivite#M2 "Dépôt relais"
* $TRE-R275-ModaliteActivite#M3 "A usage intérieur"
* $TRE-R275-ModaliteActivite#M4 "A usage intérieur et extérieur"
* $TRE-R275-ModaliteActivite#M5 "CSH moelle osseuse allogéniques"
* $TRE-R275-ModaliteActivite#M6 "CSH moelle osseuse autologues"
* $TRE-R275-ModaliteActivite#M7 "CSH sang périphérique allogéniques"
* $TRE-R275-ModaliteActivite#M8 "CSH sang périphérique autologues"
* $TRE-R275-ModaliteActivite#M9 "CSH sang de cordon ou sang placentaire"
* $TRE-R275-ModaliteActivite#N0 "Structure de sevrage niveau 2 ou 3"
* $TRE-R275-ModaliteActivite#N1 "Unité de soins palliatifs"
* $TRE-R275-ModaliteActivite#N2 "Lits identifiés (Médecine) - adulte"
* $TRE-R275-ModaliteActivite#N3 "Lits identifiés (Médecine) - pédiatrique"
* $TRE-R275-ModaliteActivite#N4 "Equipe mobile"
* $TRE-R275-ModaliteActivite#N5 "Unité de soins intensifs (hors cardiologie)"
* $TRE-R275-ModaliteActivite#N6 "Unité de soins intensifs en cardiologie"
* $TRE-R275-ModaliteActivite#N7 "USC polyvalente - adulte (adossée à une unité de réanimation)"
* $TRE-R275-ModaliteActivite#N8 "USC polyvalente - adulte (non adossée à une unité de réanimation)"
* $TRE-R275-ModaliteActivite#N9 "USC polyvalente - pédiatrique (adossée à une unité de réanimation)"
* $TRE-R275-ModaliteActivite#P0 "USC polyvalente - pédiatrique (non adossée à une unité de réanimation)"
* $TRE-R275-ModaliteActivite#P1 "USC spécialisée cancérologie- pédiatrique"
* $TRE-R275-ModaliteActivite#P2 "USC spécialisée transplantation d'organes - pédiatrique"
* $TRE-R275-ModaliteActivite#P3 "USC chirurgicale individualisée - pédiatrique"
* $TRE-R275-ModaliteActivite#P4 "A l'occasion d'un prélèvement multi-organes"
* $TRE-R275-ModaliteActivite#P5 "Adulte (âge >=18 ans) - Traitement sans chimiothérapie"
* $TRE-R275-ModaliteActivite#P6 "Anesthésie"
* $TRE-R275-ModaliteActivite#P7 "Cardiologie"
* $TRE-R275-ModaliteActivite#P8 "Cardiologie interventionnelle"
* $TRE-R275-ModaliteActivite#P9 "Centre de référence"
* $TRE-R275-ModaliteActivite#U0 "Neurologie - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U1 "Chambre stérile en hématologie"
* $TRE-R275-ModaliteActivite#U2 "Chimiothérapie - Hémopathies malignes (certains types) - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U3 "Chimiothérapie - Hémopathies malignes (tous types) - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U4 "Chimiothérapie - Tumeurs solides - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U5 "Chirurgie cancer - Os et tissus mous - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U6 "Chirurgie cancer - Autres traitements spécifiques - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#U8 "Chirurgie cancer - Cancer in situ du col de l'utérus - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#U9 "Chirurgie cancer - Cancer Thyroïde - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#V1 "Chirurgie cancer - Cancers cutanés - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#V2 "Chirurgie cancer - Pathologies ophtalmologiques - Pédiatrique"
* $TRE-R275-ModaliteActivite#V3 "Chirurgie cancer - Pathologies ORL et maxillo-faciales - Pédiatrique"
* $TRE-R275-ModaliteActivite#V4 "Chirurgie cancer - Pathologies orthopédiques - Pédiatrique"
* $TRE-R275-ModaliteActivite#V5 "Chirurgie cancer - Pathologies viscérales - Pédiatrique"
* $TRE-R275-ModaliteActivite#V6 "Chirurgie cancer - Système nerveux central - Pédiatrique"
* $TRE-R275-ModaliteActivite#V7 "Chirurgie cancer - Système nerveux central - Adulte (âge >= 18 ans)"
* $TRE-R275-ModaliteActivite#V8 "Chirurgie complexe de la main"
* $TRE-R275-ModaliteActivite#V9 "Chirurgie digestive et viscérale"
* $TRE-R275-ModaliteActivite#W1 "Unité péri-opératoire gériatrique"
* $TRE-R275-ModaliteActivite#W2 "Lits identifiés (SSR) - adulte"
* $TRE-R275-ModaliteActivite#W3 "Lits identifiés (SSR) - Pédiatrique"
* $TRE-R275-ModaliteActivite#W4 "Lit de Soins Intensifs - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#W5 "USPC - Adulte (âge >=18 ans)"
* $TRE-R275-ModaliteActivite#W6 "USPC - Pédiatrique"