ValueSet: JDV_J127_StatutJuridique_ENREG
Id: JDV-J127-StatutJuridique-ENREG
Description: "Jeu de valeur sur les statuts juridiques pour ENREG"
* ^meta.versionId = "4"
* ^meta.lastUpdated = "2026-07-06T19:05:00.412+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J127-StatutJuridique-ENREG/FHIR/JDV-J127-StatutJuridique-ENREG"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.213"
* ^version = "20231215120000"
* ^status = #active
* ^experimental = false
* ^date = "2023-12-15T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R72-FinessStatutJuridique#000 "En cours de vérification"
* $TRE-R72-FinessStatutJuridique#01 "Etat"
* $TRE-R72-FinessStatutJuridique#02 "Département"
* $TRE-R72-FinessStatutJuridique#03 "Commune"
* $TRE-R72-FinessStatutJuridique#04 "Région"
* $TRE-R72-FinessStatutJuridique#05 "Territoire Outre Mer"
* $TRE-R72-FinessStatutJuridique#06 "Autre Collect. Terr."
* $TRE-R72-FinessStatutJuridique#07 "Métropole"
* $TRE-R72-FinessStatutJuridique#08 "C.I.A.S"
* $TRE-R72-FinessStatutJuridique#10 "Etb.Public Nat.Hosp."
* $TRE-R72-FinessStatutJuridique#11 "Etb.Pub.Départ.Hosp."
* $TRE-R72-FinessStatutJuridique#12 "Etb.Pub.Intdép.Hosp."
* $TRE-R72-FinessStatutJuridique#13 "Etb.Pub.Commun.Hosp."
* $TRE-R72-FinessStatutJuridique#14 "Etb.Pub.Intcom.Hosp."
* $TRE-R72-FinessStatutJuridique#15 "Etb.Public Rég.Hosp."
* $TRE-R72-FinessStatutJuridique#16 "S.I.H."
* $TRE-R72-FinessStatutJuridique#17 "C.C.A.S."
* $TRE-R72-FinessStatutJuridique#18 "Etb.Social National"
* $TRE-R72-FinessStatutJuridique#19 "Etb.Social Départ."
* $TRE-R72-FinessStatutJuridique#20 "Etb.Social Interdept"
* $TRE-R72-FinessStatutJuridique#21 "Etb.Social Communal"
* $TRE-R72-FinessStatutJuridique#22 "Etb.Social Intercom."
* $TRE-R72-FinessStatutJuridique#23 "Etb.Social Régional"
* $TRE-R72-FinessStatutJuridique#24 "Office Public H.L.M."
* $TRE-R72-FinessStatutJuridique#25 "Caisse des Ecoles"
* $TRE-R72-FinessStatutJuridique#26 "Autre Etb. Pub. Adm"
* $TRE-R72-FinessStatutJuridique#27 "Etb.Pub. Indus. Com."
* $TRE-R72-FinessStatutJuridique#28 "G.I.P."
* $TRE-R72-FinessStatutJuridique#29 "G.C.S. public"
* $TRE-R72-FinessStatutJuridique#30 "G.C.S.M.S. public"
* $TRE-R72-FinessStatutJuridique#40 "Rég.Gén.Sécu.Sociale"
* $TRE-R72-FinessStatutJuridique#41 "Rég.Spé.Sécu.Sociale"
* $TRE-R72-FinessStatutJuridique#42 "Institut Prévoyance"
* $TRE-R72-FinessStatutJuridique#43 "Mut.Sociale Agricole"
* $TRE-R72-FinessStatutJuridique#44 "Rég.Mal.n Sal.n Agr."
* $TRE-R72-FinessStatutJuridique#45 "Rég.Vieillesse Part."
* $TRE-R72-FinessStatutJuridique#46 "Autre Rég.Prév.Soc."
* $TRE-R72-FinessStatutJuridique#47 "Société Mutualiste"
* $TRE-R72-FinessStatutJuridique#48 "Assur. Mut. Agricole"
* $TRE-R72-FinessStatutJuridique#49 "Autre Org.Mutualiste"
* $TRE-R72-FinessStatutJuridique#50 "Comité d'Entreprise"
* $TRE-R72-FinessStatutJuridique#51 "Syndicat"
* $TRE-R72-FinessStatutJuridique#52 "Synd. Propriétaires"
* $TRE-R72-FinessStatutJuridique#60 "Ass.L.1901 non R.U.P"
* $TRE-R72-FinessStatutJuridique#61 "Ass.L.1901 R.U.P."
* $TRE-R72-FinessStatutJuridique#62 "Ass. de Droit Local"
* $TRE-R72-FinessStatutJuridique#63 "Fondation"
* $TRE-R72-FinessStatutJuridique#64 "Congrégation"
* $TRE-R72-FinessStatutJuridique#65 "Autr.Org.Pri.non Luc"
* $TRE-R72-FinessStatutJuridique#66 "G.C.S.M.S. privé"
* $TRE-R72-FinessStatutJuridique#70 "Personne Physique"
* $TRE-R72-FinessStatutJuridique#71 "S.N.C."
* $TRE-R72-FinessStatutJuridique#72 "S.A.R.L."
* $TRE-R72-FinessStatutJuridique#73 "Société Anonyme"
* $TRE-R72-FinessStatutJuridique#74 "Société Civile"
* $TRE-R72-FinessStatutJuridique#75 "Autre Société"
* $TRE-R72-FinessStatutJuridique#76 "G.I.E."
* $TRE-R72-FinessStatutJuridique#77 "Autre Org.Priv.Com."
* $TRE-R72-FinessStatutJuridique#78 "E.U.R.L."
* $TRE-R72-FinessStatutJuridique#79 "S.C.M."
* $TRE-R72-FinessStatutJuridique#80 "S.I.S.A."
* $TRE-R72-FinessStatutJuridique#85 "S.E.L.A.R.L."