ValueSet: JDV_J171_TypeAutorisation_EPARS
Id: JDV-J171-TypeAutorisation-EPARS
Description: "Types d'autorisation d'exercice pour EPARS"
* ^meta.versionId = "10"
* ^meta.lastUpdated = "2026-07-06T19:05:33.356+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2021-06-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J171-TypeAutorisation-EPARS/FHIR/JDV-J171-TypeAutorisation-EPARS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.232"
* ^version = "20250523120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-05-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R17-TypeAutorisation#AM01 "Autorisation de plein exercice"
* $TRE-R17-TypeAutorisation#AM14 "Arrangement France-Québec (art L 4111-3-1 CSP)"
* $TRE-R17-TypeAutorisation#AM22 "Agrément Caisse Régionale d'Assurance Maladie"
* $TRE-R17-TypeAutorisation#AM23 "Agrément Ministère des anciens combattants"
* $TRE-R17-TypeAutorisation#AM24 "Exerce comme tech lab avant le 08/11/1976"
* $TRE-R17-TypeAutorisation#AM25 "Exerce comme tech lab au 29/11/1997"
* $TRE-R17-TypeAutorisation#AM26 "Exerce comme tech lab au 30/05/2013"
* $TRE-R17-TypeAutorisation#AM27 "Autorisation d'exercice UE/EEE"
* $TRE-R17-TypeAutorisation#AM28 "Autorisation d'user du titre d'Ostéopathe"
* $TRE-R17-TypeAutorisation#AM29 "Autorisation titre diététicien décision admin 86"
* $TRE-R17-TypeAutorisation#AM30 "Autorisation titre diététicien emploi permanent 86"
* $TRE-R17-TypeAutorisation#AM31 "Autorisation d'exercice de psychologue diplôme étranger"
* $TRE-R17-TypeAutorisation#AM32 "Autorisation préfectorale d'exercice de psychologue décret 90-259"
* $TRE-R17-TypeAutorisation#AM33 "Docteur en médecine spécialité psychiatrie"
* $TRE-R17-TypeAutorisation#AM34 "Diplôme, certificat ou titre permettant d'exercer la médecine en France"
* $TRE-R17-TypeAutorisation#AM35 "Autorisation d'user du titre de Chiropraxie"
* $TRE-R17-TypeAutorisation#AM36 "Autorisation d'exercice d'épithésiste pour chirurgien-dentiste"
* $TRE-R17-TypeAutorisation#AM37 "Autorisation épithésiste pour médecin stomatologue ou chirurgie maxillo-faciale"
* $TRE-R17-TypeAutorisation#AM38 "Arrêté de nomination de MER du Secteur Public"
* $TRE-R17-TypeAutorisation#AM39 "Docteur en médecine + formation + stage"
* $TRE-R17-TypeAutorisation#AM41 "Agrément de radiophysicien avant le 28/11/2004"
* $TRE-R17-TypeAutorisation#AM42 "Autorisation d'user du titre de Psychothérapeute"