ValueSet: JDV_J106_EnsembleProfession_RASS
Id: JDV-J106-EnsembleProfession-RASS
Description: "Ensemble des professions du RASS"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:04:46.389+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J106-EnsembleProfession-RASS/FHIR/JDV-J106-EnsembleProfession-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.174"
* ^version = "20260330120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-03-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-G15-ProfessionSante#10 "Médecin"
* $TRE-G15-ProfessionSante#21 "Pharmacien"
* $TRE-G15-ProfessionSante#26 "Audioprothésiste"
* $TRE-G15-ProfessionSante#28 "Opticien-Lunetier"
* $TRE-G15-ProfessionSante#31 "Assistant dentaire"
* $TRE-G15-ProfessionSante#32 "Physicien médical"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#81 "Orthoprothésiste"
* $TRE-G15-ProfessionSante#82 "Podo-Orthésiste"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#84 "Oculariste"
* $TRE-G15-ProfessionSante#85 "Epithésiste"
* $TRE-G15-ProfessionSante#86 "Technicien de laboratoire médical"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"
* $TRE-G15-ProfessionSante#94 "Ergothérapeute"
* $TRE-G15-ProfessionSante#95 "Diététicien"
* $TRE-G15-ProfessionSante#96 "Psychomotricien"
* $TRE-G15-ProfessionSante#98 "Manipulateur ERM"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R291-AutreProfession#99 "Acteur participant au système de santé caractérisé par rôle"