ValueSet: JDV_J129_CategorieEtablissement_RASS
Id: JDV-J129-CategorieEtablissement-RASS
Description: "Catégorie d'établissement du RASS"
* ^meta.versionId = "19"
* ^meta.lastUpdated = "2026-07-06T19:05:02.911+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^extension.valuePeriod.end = "2026-02-23T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J129-CategorieEtablissement-RASS/FHIR/JDV-J129-CategorieEtablissement-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.215"
* ^version = "20260223120000"
* ^status = #retired
* ^experimental = false
* ^date = "2026-02-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R66-CategorieEtablissement#001 "Autres lits de m.R."
* $TRE-R66-CategorieEtablissement#002 "Autres places de l-f."
* $TRE-R66-CategorieEtablissement#003 "Autres lits de l-s"
* $TRE-R66-CategorieEtablissement#101 "Centre Hospitalier Régional (C.H.R.)"
* $TRE-R66-CategorieEtablissement#106 "Centre hospitalier, ex Hôpital local"
* $TRE-R66-CategorieEtablissement#108 "Etablissement de Convalescence et de Repos"
* $TRE-R66-CategorieEtablissement#109 "Etablissement de santé privé autorisé en SSR"
* $TRE-R66-CategorieEtablissement#112 "Centre de Convalescence Cure ou Réadaptation"
* $TRE-R66-CategorieEtablissement#114 "Hôpital des armées"
* $TRE-R66-CategorieEtablissement#115 "Etablissement de Soins du Service de Santé des Armées"
* $TRE-R66-CategorieEtablissement#119 "Maison de Régime"
* $TRE-R66-CategorieEtablissement#122 "Etablissement Soins Obstétriques Chirurgico-Gynécologiques"
* $TRE-R66-CategorieEtablissement#124 "Centre de Santé"
* $TRE-R66-CategorieEtablissement#125 "Centre de Santé Dentaire"
* $TRE-R66-CategorieEtablissement#126 "Etablissement Thermal"
* $TRE-R66-CategorieEtablissement#127 "Hospitalisation à Domicile"
* $TRE-R66-CategorieEtablissement#128 "Etablissement de Soins Chirurgicaux"
* $TRE-R66-CategorieEtablissement#129 "Etablissement de Soins Médicaux"
* $TRE-R66-CategorieEtablissement#130 "Centre de Soins Médicaux"
* $TRE-R66-CategorieEtablissement#131 "Centre de Lutte Contre Cancer"
* $TRE-R66-CategorieEtablissement#132 "Etablissement de Transfusion Sanguine"
* $TRE-R66-CategorieEtablissement#135 "Etablissement Réadaptation Fonctionnelle"
* $TRE-R66-CategorieEtablissement#136 "Banque de Sperme"
* $TRE-R66-CategorieEtablissement#137 "Banque d'Organes"
* $TRE-R66-CategorieEtablissement#138 "Centre de Dialyse Périodique"
* $TRE-R66-CategorieEtablissement#139 "Centre de Dialyse et d'entraînement à la Dialyse"
* $TRE-R66-CategorieEtablissement#140 "Centre d'Entraînement à la Dialyse"
* $TRE-R66-CategorieEtablissement#141 "Centre de dialyse"
* $TRE-R66-CategorieEtablissement#142 "Dispensaire Antituberculeux"
* $TRE-R66-CategorieEtablissement#143 "Centre de Vaccination BCG"
* $TRE-R66-CategorieEtablissement#144 "Etablissement de Lutte Contre la Tuberculose"
* $TRE-R66-CategorieEtablissement#146 "Structure d'Alternative à la dialyse en centre"
* $TRE-R66-CategorieEtablissement#156 "Centre Médico-Psychologique (C.M.P.)"
* $TRE-R66-CategorieEtablissement#157 "Centre de Postcure"
* $TRE-R66-CategorieEtablissement#159 "Centre Parental"
* $TRE-R66-CategorieEtablissement#160 "Centre de Soins Spécifiques pour Toxicomanes (C.S.S.T.)"
* $TRE-R66-CategorieEtablissement#161 "Maison de Santé pour Maladies Mentales"
* $TRE-R66-CategorieEtablissement#162 "Centre de Cure Ambulatoire en Alcoologie (C.C.A.A.)"
* $TRE-R66-CategorieEtablissement#163 "Maison d'Enfants à Caractère Sanitaire Temporaire"
* $TRE-R66-CategorieEtablissement#164 "Etablissements Expérimentaux Accueil de la Petite Enfance"
* $TRE-R66-CategorieEtablissement#165 "Appartement de Coordination Thérapeutique (A.C.T.)"
* $TRE-R66-CategorieEtablissement#166 "Centre Parents-Enfants de moins de 3 ans"
* $TRE-R66-CategorieEtablissement#167 "Crèche Collective"
* $TRE-R66-CategorieEtablissement#168 "Service Accueil Familial pour la Petite Enfance"
* $TRE-R66-CategorieEtablissement#169 "Crèche Multi Accueil Collectif et Familial"
* $TRE-R66-CategorieEtablissement#170 "Halte Garderie"
* $TRE-R66-CategorieEtablissement#171 "Garderie et Jardin d'Enfants"
* $TRE-R66-CategorieEtablissement#172 "Pouponnière à Caractère Social"
* $TRE-R66-CategorieEtablissement#173 "Pouponnière à Caractère Sanitaire"
* $TRE-R66-CategorieEtablissement#174 "Etablissement d'Accueil Collectif Régulier et Occasionnel"
* $TRE-R66-CategorieEtablissement#175 "Foyer de l'Enfance"
* $TRE-R66-CategorieEtablissement#176 "Village d'Enfants"
* $TRE-R66-CategorieEtablissement#177 "Maison d'Enfants à Caractère Social"
* $TRE-R66-CategorieEtablissement#178 "Ctre.Accueil- Accomp.Réduc.Risq.Usag. Drogues (C.A.A.R.U.D.)"
* $TRE-R66-CategorieEtablissement#179 "Maison d'Enfants à Caractère Sanitaire Permanente"
* $TRE-R66-CategorieEtablissement#180 "Lits Halte Soins Santé (L.H.S.S.)"
* $TRE-R66-CategorieEtablissement#181 "Maison Familiale de Vacances"
* $TRE-R66-CategorieEtablissement#182 "Service d'Éducation Spéciale et de Soins à Domicile"
* $TRE-R66-CategorieEtablissement#183 "Institut Médico-Educatif (I.M.E.)"
* $TRE-R66-CategorieEtablissement#184 "Institut Médico-Pédagogique (I.M.P.)"
* $TRE-R66-CategorieEtablissement#185 "Institut Médico-Professionnel (I.M.Pro.)"
* $TRE-R66-CategorieEtablissement#186 "Institut Thérapeutique Éducatif et Pédagogique (I.T.E.P.)"
* $TRE-R66-CategorieEtablissement#188 "Etablissement pour Enfants ou Adolescents Polyhandicapés"
* $TRE-R66-CategorieEtablissement#189 "Centre Médico-Psycho-Pédagogique (C.M.P.P.)"
* $TRE-R66-CategorieEtablissement#190 "Centre Action Médico-Sociale Précoce (C.A.M.S.P.)"
* $TRE-R66-CategorieEtablissement#191 "Etablissement pour Déficients Moteurs Cérébraux"
* $TRE-R66-CategorieEtablissement#192 "Institut d'éducation motrice"
* $TRE-R66-CategorieEtablissement#193 "Etablissement pour Déficients Moteurs et Moteurs Cérébraux"
* $TRE-R66-CategorieEtablissement#194 "Institut pour Déficients Visuels"
* $TRE-R66-CategorieEtablissement#195 "Institut pour Déficients Auditifs"
* $TRE-R66-CategorieEtablissement#196 "Institut d'Education Sensorielle Sourd-Aveugle"
* $TRE-R66-CategorieEtablissement#197 "Centre soins accompagnement prévention addictologie (CSAPA)"
* $TRE-R66-CategorieEtablissement#198 "Établissement et Service de Préorientation"
* $TRE-R66-CategorieEtablissement#199 "Hospice"
* $TRE-R66-CategorieEtablissement#200 "Maison de Retraite"
* $TRE-R66-CategorieEtablissement#202 "Résidences autonomie"
* $TRE-R66-CategorieEtablissement#207 "Centre de Jour pour Personnes Agées"
* $TRE-R66-CategorieEtablissement#208 "Service d'Aide Ménagère à Domicile"
* $TRE-R66-CategorieEtablissement#209 "Service autonomie aide et soins (SAAS)"
* $TRE-R66-CategorieEtablissement#212 "Alarme Médico-Sociale"
* $TRE-R66-CategorieEtablissement#213 "Lits d'Accueil Médicalisés (L.A.M.)"
* $TRE-R66-CategorieEtablissement#214 "Centre Hébergement & Réinsertion Sociale (C.H.R.S.)"
* $TRE-R66-CategorieEtablissement#215 "Maison Relai"
* $TRE-R66-CategorieEtablissement#216 "Résidence Hôtelière à Vocation Sociale (R.H.V.S)"
* $TRE-R66-CategorieEtablissement#217 "Cité de Transit"
* $TRE-R66-CategorieEtablissement#218 "Aire Station Nomades"
* $TRE-R66-CategorieEtablissement#219 "Autre Centre d'Accueil"
* $TRE-R66-CategorieEtablissement#220 "Centre Social"
* $TRE-R66-CategorieEtablissement#221 "Bureau d'Aide Psychologique Universitaire (B.A.P.U.)"
* $TRE-R66-CategorieEtablissement#223 "Protection Maternelle et Infantile (P.M.I.)"
* $TRE-R66-CategorieEtablissement#224 "Etablissement de Consultation Pré et Post-natale"
* $TRE-R66-CategorieEtablissement#225 "Consultations de Nourrissons"
* $TRE-R66-CategorieEtablissement#228 "Centre de Santé Sexuelle"
* $TRE-R66-CategorieEtablissement#229 "Consultation Problèmes naissance"
* $TRE-R66-CategorieEtablissement#230 "Etablissement Consultation Protection Infantile"
* $TRE-R66-CategorieEtablissement#231 "Espaces de vie affective, relationnelle et sexuelle (EVARS)"
* $TRE-R66-CategorieEtablissement#233 "Lactarium"
* $TRE-R66-CategorieEtablissement#236 "Centre Placement Familial Socio-Educatif (C.P.F.S.E.)"
* $TRE-R66-CategorieEtablissement#237 "Centre de Placement Familial Spécialisé"
* $TRE-R66-CategorieEtablissement#238 "Centre d'Accueil Familial Spécialisé"
* $TRE-R66-CategorieEtablissement#241 "Établissement de Placement"
* $TRE-R66-CategorieEtablissement#242 "Service d'Activité de Jour"
* $TRE-R66-CategorieEtablissement#246 "Etablissement et Service d'Aide par le Travail (E.S.A.T.)"
* $TRE-R66-CategorieEtablissement#247 "Entreprise adaptée"
* $TRE-R66-CategorieEtablissement#249 "Établissement et Service de Réadaptation Professionnelle"
* $TRE-R66-CategorieEtablissement#250 "Centre Réentrainement au travail"
* $TRE-R66-CategorieEtablissement#251 "Maison Vacances pour Handicapés"
* $TRE-R66-CategorieEtablissement#252 "Foyer Hébergement Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#253 "Foyer d'Accueil Polyvalent pour Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#255 "Maison d'Accueil Spécialisée (M.A.S.)"
* $TRE-R66-CategorieEtablissement#256 "Foyer Travailleurs Migrants non transformé en Résidence Soc."
* $TRE-R66-CategorieEtablissement#257 "Foyers de jeunes travailleurs"
* $TRE-R66-CategorieEtablissement#258 "Maisons Relais - Pensions de Famille"
* $TRE-R66-CategorieEtablissement#259 "Autres résidences sociales"
* $TRE-R66-CategorieEtablissement#261 "D.D.A.S.S."
* $TRE-R66-CategorieEtablissement#262 "Etablissement Régional d'Enseignement Adapté"
* $TRE-R66-CategorieEtablissement#265 "Section Education Spéciale Classe Atelier"
* $TRE-R66-CategorieEtablissement#266 "Dispensaire Antivénérien"
* $TRE-R66-CategorieEtablissement#267 "Dispensaire Antihansénien"
* $TRE-R66-CategorieEtablissement#268 "Centre Médico-Scolaire"
* $TRE-R66-CategorieEtablissement#269 "Centre de Médecine Universitaire"
* $TRE-R66-CategorieEtablissement#270 "Centre de Médecine Sportive"
* $TRE-R66-CategorieEtablissement#271 "Maison d'accueil Hospitalière"
* $TRE-R66-CategorieEtablissement#272 "Ecole d'ambulanciers"
* $TRE-R66-CategorieEtablissement#273 "Institut de formation en soins infirmiers (I.F.S.I.)"
* $TRE-R66-CategorieEtablissement#274 "Ecole de sages_femmes"
* $TRE-R66-CategorieEtablissement#275 "Ecole de masseurs-kinésithérapeutes"
* $TRE-R66-CategorieEtablissement#276 "Ecole de laborantins d'analyses médicales"
* $TRE-R66-CategorieEtablissement#277 "Ecole de péricultrices"
* $TRE-R66-CategorieEtablissement#278 "Etablissement de formation polyvalent"
* $TRE-R66-CategorieEtablissement#279 "Ecole de service social"
* $TRE-R66-CategorieEtablissement#280 "Ecole d'éducateurs spécialisés"
* $TRE-R66-CategorieEtablissement#281 "Centre de formation d'aides soignants"
* $TRE-R66-CategorieEtablissement#282 "Ecole de pédicures-podologues"
* $TRE-R66-CategorieEtablissement#283 "Ecole de manipulateurs d'électro-radiologie"
* $TRE-R66-CategorieEtablissement#284 "Ecole de travailleuses familiales"
* $TRE-R66-CategorieEtablissement#285 "Centres de Loisirs sans Hébergement"
* $TRE-R66-CategorieEtablissement#286 "Service de prévention spécialisée"
* $TRE-R66-CategorieEtablissement#289 "Centre de Soins Infirmiers"
* $TRE-R66-CategorieEtablissement#292 "Centre Hospitalier Spécialisé lutte Maladies Mentales"
* $TRE-R66-CategorieEtablissement#294 "Centre de Consultations Cancer"
* $TRE-R66-CategorieEtablissement#295 "Service AEMO et AED"
* $TRE-R66-CategorieEtablissement#297 "Dispensaire Polyvalent"
* $TRE-R66-CategorieEtablissement#300 "Ecoles Formant aux Professions Sanitaires"
* $TRE-R66-CategorieEtablissement#303 "Ecole de conseillers en économie sociale et familiale"
* $TRE-R66-CategorieEtablissement#304 "Ecole d'ergothérapeutes"
* $TRE-R66-CategorieEtablissement#305 "Ecole de psycho-motriciens"
* $TRE-R66-CategorieEtablissement#306 "Ecole d'infirmiers anesthésistes"
* $TRE-R66-CategorieEtablissement#307 "Ecole d'infirmiers de bloc opératoire"
* $TRE-R66-CategorieEtablissement#308 "Centre de formation professionnelle de secteur psychiatrique"
* $TRE-R66-CategorieEtablissement#309 "Ecole de cadres infirmiers"
* $TRE-R66-CategorieEtablissement#310 "Ecole de cadres de secteur psychiatrique"
* $TRE-R66-CategorieEtablissement#311 "Ecole de cadres de masseurs-kinésithérapeutes"
* $TRE-R66-CategorieEtablissement#312 "Ecole de cadres de manipulateurs d'électro-radiologie"
* $TRE-R66-CategorieEtablissement#313 "Ecole d'éducateurs de jeunes enfants"
* $TRE-R66-CategorieEtablissement#314 "Ecole d'éducateurs techniques spécialisés"
* $TRE-R66-CategorieEtablissement#315 "Ecole de moniteurs-éducateurs"
* $TRE-R66-CategorieEtablissement#316 "Ecole d'aides médico-psychologiques"
* $TRE-R66-CategorieEtablissement#317 "Ecole d'animateurs socio-éducatifs"
* $TRE-R66-CategorieEtablissement#319 "Inst. régional de formation des travailleurs sociaux"
* $TRE-R66-CategorieEtablissement#320 "S.A.M.U. et Centre 15"
* $TRE-R66-CategorieEtablissement#321 "Unité Mobile Hospitalière"
* $TRE-R66-CategorieEtablissement#322 "Centre Rég.Informatiq.Hospit."
* $TRE-R66-CategorieEtablissement#324 "Logement Foyer non Spécialisé"
* $TRE-R66-CategorieEtablissement#326 "Ecole de cadres"
* $TRE-R66-CategorieEtablissement#327 "Service d'Ambulances"
* $TRE-R66-CategorieEtablissement#328 "Centre Consultation Soins Dentaire"
* $TRE-R66-CategorieEtablissement#329 "Sectorisation Psychiatrique"
* $TRE-R66-CategorieEtablissement#330 "Ecoles Formant aux Professions Sociales"
* $TRE-R66-CategorieEtablissement#340 "Service mandataire judiciaire à la protection des majeurs"
* $TRE-R66-CategorieEtablissement#341 "Service dédié mesures d'accompagnement social personnalisé"
* $TRE-R66-CategorieEtablissement#342 "Service d'information et de soutien aux tuteurs familiaux"
* $TRE-R66-CategorieEtablissement#343 "Equipe Préparation et Suite Reclassement (EPSR)"
* $TRE-R66-CategorieEtablissement#344 "Service délégué aux prestations familiales"
* $TRE-R66-CategorieEtablissement#345 "Service Tutelle Prestation Sociale"
* $TRE-R66-CategorieEtablissement#346 "Service de Travailleuses Familiales"
* $TRE-R66-CategorieEtablissement#347 "Centre d'Examens de Santé"
* $TRE-R66-CategorieEtablissement#349 "Ecole de cadres de sages-femmes"
* $TRE-R66-CategorieEtablissement#350 "Centre de formation d'auxiliaires de puériculture"
* $TRE-R66-CategorieEtablissement#352 "Centre de Psychothérapie"
* $TRE-R66-CategorieEtablissement#353 "Hôpital de Jour Spécialités Médicales"
* $TRE-R66-CategorieEtablissement#354 "Service de Soins Infirmiers A Domicile (S.S.I.A.D)"
* $TRE-R66-CategorieEtablissement#355 "Centre Hospitalier (C.H.)"
* $TRE-R66-CategorieEtablissement#357 "Association Aide aux Insuffisants Respiratoires"
* $TRE-R66-CategorieEtablissement#359 "Centre Circonscription Sanitaire et Sociale"
* $TRE-R66-CategorieEtablissement#361 "Centre de Cure Médicale"
* $TRE-R66-CategorieEtablissement#362 "Etablissement de Soins Longue Durée"
* $TRE-R66-CategorieEtablissement#363 "Centre moyen et long séjour"
* $TRE-R66-CategorieEtablissement#365 "Etablissement de Soins Pluridisciplinaire"
* $TRE-R66-CategorieEtablissement#366 "Atelier Thérapeutique"
* $TRE-R66-CategorieEtablissement#367 "Maison d'Enfants non Conventionnée ni Habilitée"
* $TRE-R66-CategorieEtablissement#368 "Service de Repas à Domicile"
* $TRE-R66-CategorieEtablissement#369 "Centre Adaptation Vie Active (C.A.V.A.)"
* $TRE-R66-CategorieEtablissement#370 "Etablissement Expérimental pour personnes handicapées"
* $TRE-R66-CategorieEtablissement#371 "Service Action Socio-Educative pour Familles en difficulté"
* $TRE-R66-CategorieEtablissement#373 "Centre de formation supérieure des travailleurs sociaux"
* $TRE-R66-CategorieEtablissement#374 "Ecole Nationale Santé Publique (E.N.S.P.)"
* $TRE-R66-CategorieEtablissement#375 "Classe d'Adaptation"
* $TRE-R66-CategorieEtablissement#376 "Classe Spéciale Ecole Primaire"
* $TRE-R66-CategorieEtablissement#377 "Etablissement Expérimental pour Enfance Handicapée"
* $TRE-R66-CategorieEtablissement#378 "Etablissement Expérimental Enfance Protégée"
* $TRE-R66-CategorieEtablissement#379 "Etablissement Expérimental pour Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#380 "Etablissement Expérimental Autres Adultes"
* $TRE-R66-CategorieEtablissement#381 "Etablissement Expérimental pour Personnes Agées"
* $TRE-R66-CategorieEtablissement#382 "Foyer de Vie pour Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#386 "Ecole Secondaire Spéciale"
* $TRE-R66-CategorieEtablissement#390 "Etablissement d'Accueil Temporaire d'Enfants Handicapés"
* $TRE-R66-CategorieEtablissement#393 "Autre résidence But lucratif pr personnes Âgées"
* $TRE-R66-CategorieEtablissement#394 "Etablissement d'Accueil Temporaire pour Personnes Agées"
* $TRE-R66-CategorieEtablissement#395 "Etablissement d'Accueil Temporaire pour Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#396 "Foyer Hébergement Enfants et Adolescents Handicapés"
* $TRE-R66-CategorieEtablissement#397 "Service Auxiliaire de Vie pour Handicapés"
* $TRE-R66-CategorieEtablissement#398 "Crèche Parentale"
* $TRE-R66-CategorieEtablissement#399 "Halte Garderie Parentale"
* $TRE-R66-CategorieEtablissement#400 "Centre de Services pour Associations"
* $TRE-R66-CategorieEtablissement#401 "D.R.A.S.S."
* $TRE-R66-CategorieEtablissement#402 "Jardin d'Enfants Spécialisé"
* $TRE-R66-CategorieEtablissement#403 "Service Social Spécialisé ou Polyvalent de Catégorie"
* $TRE-R66-CategorieEtablissement#404 "Etablissement Acc.Collect.Parental Régulier & Occasionnel"
* $TRE-R66-CategorieEtablissement#405 "Service Social Polyvalent de Secteur"
* $TRE-R66-CategorieEtablissement#411 "Intermédiaire de Placement Social"
* $TRE-R66-CategorieEtablissement#412 "Appartement Thérapeutique"
* $TRE-R66-CategorieEtablissement#413 "C.E.C.O.S"
* $TRE-R66-CategorieEtablissement#414 "Centre Anti Poison"
* $TRE-R66-CategorieEtablissement#415 "Service Médico-Psychologique Régional (S.M.P.R.)"
* $TRE-R66-CategorieEtablissement#419 "Centre d'Accueil Toxicomanes"
* $TRE-R66-CategorieEtablissement#420 "Entreprise d'Insertion"
* $TRE-R66-CategorieEtablissement#421 "Centre d'enseignement aux secours d'urgence"
* $TRE-R66-CategorieEtablissement#422 "Traitements Spécialisés à Domicile"
* $TRE-R66-CategorieEtablissement#423 "Ecole des cadres de laborantins d'analyses médicales"
* $TRE-R66-CategorieEtablissement#425 "Centre d'Accueil Thérapeutique à temps partiel (C.A.T.T.P.)"
* $TRE-R66-CategorieEtablissement#426 "Syndicat Inter Hospitalier (S.I.H.)"
* $TRE-R66-CategorieEtablissement#430 "Centre Postcure Malades Mentaux"
* $TRE-R66-CategorieEtablissement#431 "Centre Postcure pour Alcooliques"
* $TRE-R66-CategorieEtablissement#432 "Centre Postcure pour Toxicomanes"
* $TRE-R66-CategorieEtablissement#433 "Etablissement Sanitaire des Prisons"
* $TRE-R66-CategorieEtablissement#434 "Classe Spéciale en Ecole Maternelle"
* $TRE-R66-CategorieEtablissement#435 "Centre de formation d'aide à domicile"
* $TRE-R66-CategorieEtablissement#436 "Ecoles Formant aux Professions Sanitaires et Sociales"
* $TRE-R66-CategorieEtablissement#437 "Foyer d'Accueil Médicalisé pour Adultes Handicapés (F.A.M.)"
* $TRE-R66-CategorieEtablissement#438 "Centre de Médecine collective"
* $TRE-R66-CategorieEtablissement#439 "Centre Santé Polyvalent"
* $TRE-R66-CategorieEtablissement#440 "Service d'Investigation Educative"
* $TRE-R66-CategorieEtablissement#441 "Service d'Intervention Educative en Milieu Ouvert"
* $TRE-R66-CategorieEtablissement#442 "Centre Provisoire Hébergement (C.P.H.)"
* $TRE-R66-CategorieEtablissement#443 "Centre Accueil Demandeurs Asile (C.A.D.A.)"
* $TRE-R66-CategorieEtablissement#444 "Centre Crise Accueil Permanent"
* $TRE-R66-CategorieEtablissement#445 "Service d'accompagnement médico-social adultes handicapés"
* $TRE-R66-CategorieEtablissement#446 "Service d'Accompagnement à la Vie Sociale (S.A.V.S.)"
* $TRE-R66-CategorieEtablissement#447 "Entreprise Intérim Insertion"
* $TRE-R66-CategorieEtablissement#448 "Etab.Acc.Médicalisé en tout ou partie personnes handicapées"
* $TRE-R66-CategorieEtablissement#449 "Etab.Accueil Non Médicalisé pour personnes handicapées"
* $TRE-R66-CategorieEtablissement#450 "Service d'Aide aux Personnes Agées"
* $TRE-R66-CategorieEtablissement#451 "Service d'Aide aux Familles en Difficulté"
* $TRE-R66-CategorieEtablissement#452 "Régie de Quartier"
* $TRE-R66-CategorieEtablissement#460 "Service autonomie aide (SAA)"
* $TRE-R66-CategorieEtablissement#461 "Centres de Ressources S.A.I. (Sans Aucune Indication)"
* $TRE-R66-CategorieEtablissement#462 "Lieux de Vie et d'Accueil"
* $TRE-R66-CategorieEtablissement#463 "Centres Locaux Information Coordination P.A.(C.L.I.C.)"
* $TRE-R66-CategorieEtablissement#464 "Unités Evaluation Réentraînement et d'Orient. Soc. et Pro."
* $TRE-R66-CategorieEtablissement#500 "Etablissement d'hébergement pour personnes âgées dépendantes"
* $TRE-R66-CategorieEtablissement#501 "EHPA percevant des crédits d'assurance maladie"
* $TRE-R66-CategorieEtablissement#502 "EHPA ne percevant pas des crédits d'assurance maladie"
* $TRE-R66-CategorieEtablissement#601 "Cabinet Libéral Médical"
* $TRE-R66-CategorieEtablissement#602 "Cabinet de Groupe"
* $TRE-R66-CategorieEtablissement#603 "Maison de santé (L.6223-3)"
* $TRE-R66-CategorieEtablissement#604 "Communauté Professionnelle Territoriale de Santé (CPTS)"
* $TRE-R66-CategorieEtablissement#605 "Cabinet d'Auxiliaires Médicaux"
* $TRE-R66-CategorieEtablissement#606 "Dispositif d'appui à la coordination (DAC)"
* $TRE-R66-CategorieEtablissement#607 "Groupement Régional d'Appui au Développement de la e-Santé (GRADeS)"
* $TRE-R66-CategorieEtablissement#608 "Equipe mobile médico-sociale précarité (EMMSP)"
* $TRE-R66-CategorieEtablissement#609 "Maison Départementale pour Personnes Handicapées (MDPH)"
* $TRE-R66-CategorieEtablissement#610 "Laboratoire d'Analyses"
* $TRE-R66-CategorieEtablissement#611 "Laboratoire de Biologie Médicale"
* $TRE-R66-CategorieEtablissement#612 "Autre Laboratoire de Biologie Médicale sans FSE"
* $TRE-R66-CategorieEtablissement#614 "Dispositif Spécifique Régional du Cancer (DSRC)"
* $TRE-R66-CategorieEtablissement#616 "Services de Prévention et de Santé au Travail (SPST)"
* $TRE-R66-CategorieEtablissement#617 "Lieu de soins non programmés"
* $TRE-R66-CategorieEtablissement#618 "Autre structure de soins non programmés (SNP)"
* $TRE-R66-CategorieEtablissement#620 "Pharmacie d'Officine"
* $TRE-R66-CategorieEtablissement#621 "Lunetterie Médicale"
* $TRE-R66-CategorieEtablissement#622 "Centre d'Appareillage & Prothèse"
* $TRE-R66-CategorieEtablissement#623 "Herboristerie"
* $TRE-R66-CategorieEtablissement#624 "Laboratoire pharmaceutique préparant délivrant allergènes"
* $TRE-R66-CategorieEtablissement#627 "Propharmacie"
* $TRE-R66-CategorieEtablissement#628 "Pharmacie Minière"
* $TRE-R66-CategorieEtablissement#629 "Pharmacie Mutualiste"
* $TRE-R66-CategorieEtablissement#630 "Installation autonome de chirurgie esthétique"
* $TRE-R66-CategorieEtablissement#631 "Maisons de naissance"
* $TRE-R66-CategorieEtablissement#632 "Structure Dispensatrice à domicile d'Oxygène à usage médical"
* $TRE-R66-CategorieEtablissement#633 "Structure Expérimentale en Santé"
* $TRE-R66-CategorieEtablissement#636 "Centre de soins et de prévention"
* $TRE-R66-CategorieEtablissement#637 "Centre de Lutte Antituberculeuse (CLAT)"
* $TRE-R66-CategorieEtablissement#638 "Centre gratuit d'information de dépistage et de diagnostic (CeGIDD)"
* $TRE-R66-CategorieEtablissement#639 "Sociétés de téléconsultation (STLC)"
* $TRE-R66-CategorieEtablissement#640 "Service d'aide et d'accompagnement à domicile aux familles (SAADF)"
* $TRE-R66-CategorieEtablissement#641 "Antenne de Pharmacie d'officine"
* $TRE-R66-CategorieEtablissement#642 "Services départementaux d'incendie et de secours"
* $TRE-R66-CategorieEtablissement#643 "Serv. d'éval de la minorité de l'isolement pour les pers. se déclarant mineures"
* $TRE-R66-CategorieEtablissement#644 "Etab. de mise à l'abri pour les pers. se déclarant mineures non accompagnées"
* $TRE-R66-CategorieEtablissement#645 "Centre de Vaccination"
* $TRE-R66-CategorieEtablissement#646 "Centre de Vaccination Internationale"
* $TRE-R66-CategorieEtablissement#647 "Equipe de Soins Spécialisés"
* $TRE-R66-CategorieEtablissement#648 "Structure qui contribue au Service d'Accès aux Soins"
* $TRE-R66-CategorieEtablissement#649 "Centre de santé et de médiation en santé sexuelle"
* $TRE-R66-CategorieEtablissement#650 "Dispositifs Spécifiques Régionaux en périnatalité"
* $TRE-R66-CategorieEtablissement#695 "Groupement de coopération sanitaire de moyens - Exploitant"
* $TRE-R66-CategorieEtablissement#696 "Groupement de coopération sanitaire de moyens"
* $TRE-R66-CategorieEtablissement#697 "Groupement de coopération sanitaire - Etablissement de santé"
* $TRE-R66-CategorieEtablissement#698 "Autre Etablissement Loi Hospitalière"
* $TRE-R66-CategorieEtablissement#699 "Entité Ayant Autorisation"