ValueSet: JDV_J99_InseeNAFrav2Niveau5_RASS
Id: JDV-J99-InseeNAFrav2Niveau5-RASS
Description: "Sous-classes de la Nomenclature Activités Française (INSEE) des prof du RASS"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:07:10.468+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^extension.valuePeriod.end = "2026-02-23T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J99-InseeNAFrav2Niveau5-RASS/FHIR/JDV-J99-InseeNAFrav2Niveau5-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.167"
* ^version = "20260223120000"
* ^status = #retired
* ^experimental = false
* ^date = "2026-02-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R75-InseeNAFrev2Niveau5#01.11Z "Culture de céréales (sf riz) légumineuses, graines oléagineuses"
* $TRE-R75-InseeNAFrev2Niveau5#01.12Z "Culture du riz"
* $TRE-R75-InseeNAFrev2Niveau5#01.13Z "Culture de légumes, de melons, de racines et de tubercules"
* $TRE-R75-InseeNAFrev2Niveau5#01.14Z "Culture de la canne à sucre"
* $TRE-R75-InseeNAFrev2Niveau5#01.15Z "Culture du tabac"
* $TRE-R75-InseeNAFrev2Niveau5#01.16Z "Culture de plantes à fibres"
* $TRE-R75-InseeNAFrev2Niveau5#01.19Z "Autres cultures non permanentes"
* $TRE-R75-InseeNAFrev2Niveau5#01.21Z "Culture de la vigne"
* $TRE-R75-InseeNAFrev2Niveau5#01.22Z "Culture de fruits tropicaux et subtropicaux"
* $TRE-R75-InseeNAFrev2Niveau5#01.23Z "Culture d'agrumes"
* $TRE-R75-InseeNAFrev2Niveau5#01.24Z "Culture de fruits à pépins et à noyau"
* $TRE-R75-InseeNAFrev2Niveau5#01.25Z "Culture d'aut. fruits d'arbres ou d'arbustes et de fruits a coque"
* $TRE-R75-InseeNAFrev2Niveau5#01.26Z "Culture de fruits oléagineux"
* $TRE-R75-InseeNAFrev2Niveau5#01.27Z "Culture de plantes à boissons"
* $TRE-R75-InseeNAFrev2Niveau5#01.28Z "Culture plantes à épices aromatiques médicinales pharmaceutiques"
* $TRE-R75-InseeNAFrev2Niveau5#01.29Z "Autres cultures permanentes"
* $TRE-R75-InseeNAFrev2Niveau5#01.30Z "Reproduction de plantes"
* $TRE-R75-InseeNAFrev2Niveau5#01.41Z "Élevage de vaches laitières"
* $TRE-R75-InseeNAFrev2Niveau5#01.42Z "Élevage d'autres bovins et de buffles"
* $TRE-R75-InseeNAFrev2Niveau5#01.43Z "Élevage de chevaux et d'autres équidés"
* $TRE-R75-InseeNAFrev2Niveau5#01.44Z "Élevage de chameaux et d'autres camélidés"
* $TRE-R75-InseeNAFrev2Niveau5#01.45Z "Élevage d'ovins et de caprins"
* $TRE-R75-InseeNAFrev2Niveau5#01.46Z "Élevage de porcins"
* $TRE-R75-InseeNAFrev2Niveau5#01.47Z "Élevage de volailles"
* $TRE-R75-InseeNAFrev2Niveau5#01.49Z "Élevage d'autres animaux"
* $TRE-R75-InseeNAFrev2Niveau5#01.50Z "Culture et élevage associés"
* $TRE-R75-InseeNAFrev2Niveau5#01.61Z "Activités de soutien aux cultures"
* $TRE-R75-InseeNAFrev2Niveau5#01.62Z "Activités de soutien à la production animale"
* $TRE-R75-InseeNAFrev2Niveau5#01.63Z "Traitement primaire des récoltes"
* $TRE-R75-InseeNAFrev2Niveau5#01.64Z "Traitement des semences"
* $TRE-R75-InseeNAFrev2Niveau5#01.70Z "Chasse, piégeage et services annexes"
* $TRE-R75-InseeNAFrev2Niveau5#02.10Z "Sylviculture et autres activités forestières"
* $TRE-R75-InseeNAFrev2Niveau5#02.20Z "Exploitation forestière"
* $TRE-R75-InseeNAFrev2Niveau5#02.30Z "Récolte prod. forestiers non ligneux poussant à l'état sauvage"
* $TRE-R75-InseeNAFrev2Niveau5#02.40Z "Services de soutien à l'exploitation forestière"
* $TRE-R75-InseeNAFrev2Niveau5#03.11Z "Pêche en mer"
* $TRE-R75-InseeNAFrev2Niveau5#03.12Z "Pêche en eau douce"
* $TRE-R75-InseeNAFrev2Niveau5#03.21Z "Aquaculture en mer"
* $TRE-R75-InseeNAFrev2Niveau5#03.22Z "Aquaculture en eau douce"
* $TRE-R75-InseeNAFrev2Niveau5#05.10Z "Extraction de houille"
* $TRE-R75-InseeNAFrev2Niveau5#05.20Z "Extraction de lignite"
* $TRE-R75-InseeNAFrev2Niveau5#06.10Z "Extraction de pétrole brut"
* $TRE-R75-InseeNAFrev2Niveau5#06.20Z "Extraction de gaz naturel"
* $TRE-R75-InseeNAFrev2Niveau5#07.10Z "Extraction de minerais de fer"
* $TRE-R75-InseeNAFrev2Niveau5#07.21Z "Extraction de minerais d'uranium et de thorium"
* $TRE-R75-InseeNAFrev2Niveau5#07.29Z "Extraction d'autres minerais de métaux non ferreux"
* $TRE-R75-InseeNAFrev2Niveau5#08.11Z "Extraction pierres ornement. construc. calcaire industriel, gypse"
* $TRE-R75-InseeNAFrev2Niveau5#08.12Z "Exploit gravieres & sablieres, extraction argiles & kaolin"
* $TRE-R75-InseeNAFrev2Niveau5#08.91Z "Extraction des minéraux chimiques et d'engrais minéraux"
* $TRE-R75-InseeNAFrev2Niveau5#08.92Z "Extraction de tourbe"
* $TRE-R75-InseeNAFrev2Niveau5#08.93Z "Production de sel"
* $TRE-R75-InseeNAFrev2Niveau5#08.99Z "Autres activités extractives n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#09.10Z "Activités de soutien à l'extraction d'hydrocarbures"
* $TRE-R75-InseeNAFrev2Niveau5#09.90Z "Activités de soutien aux autres industries extractives"
* $TRE-R75-InseeNAFrev2Niveau5#10.11Z "Transformation et conservation de la viande de boucherie"
* $TRE-R75-InseeNAFrev2Niveau5#10.12Z "Transformation et conservation de la viande de volaille"
* $TRE-R75-InseeNAFrev2Niveau5#10.13A "Préparation industrielle de produits à base de viande"
* $TRE-R75-InseeNAFrev2Niveau5#10.13B "Charcuterie"
* $TRE-R75-InseeNAFrev2Niveau5#10.20Z "Transform. & conserv. poisson, crustacés & mollusques"
* $TRE-R75-InseeNAFrev2Niveau5#10.31Z "Transformation et conservation de pommes de terre"
* $TRE-R75-InseeNAFrev2Niveau5#10.32Z "Préparation de jus de fruits et légumes"
* $TRE-R75-InseeNAFrev2Niveau5#10.39A "Autre transformation et conservation de légumes"
* $TRE-R75-InseeNAFrev2Niveau5#10.39B "Transformation et conservation de fruits"
* $TRE-R75-InseeNAFrev2Niveau5#10.41A "Fabrication d'huiles et graisses brutes"
* $TRE-R75-InseeNAFrev2Niveau5#10.41B "Fabrication d'huiles et graisses raffinées"
* $TRE-R75-InseeNAFrev2Niveau5#10.42Z "Fabrication de margarine et graisses comestibles similaires"
* $TRE-R75-InseeNAFrev2Niveau5#10.51A "Fabrication de lait liquide et de produits frais"
* $TRE-R75-InseeNAFrev2Niveau5#10.51B "Fabrication de beurre"
* $TRE-R75-InseeNAFrev2Niveau5#10.51C "Fabrication de fromage"
* $TRE-R75-InseeNAFrev2Niveau5#10.51D "Fabrication d'autres produits laitiers"
* $TRE-R75-InseeNAFrev2Niveau5#10.52Z "Fabrication de glaces et sorbets"
* $TRE-R75-InseeNAFrev2Niveau5#10.61A "Meunerie"
* $TRE-R75-InseeNAFrev2Niveau5#10.61B "Autres activités du travail des grains"
* $TRE-R75-InseeNAFrev2Niveau5#10.62Z "Fabrication de produits amylacés"
* $TRE-R75-InseeNAFrev2Niveau5#10.71A "Fabrication industrielle de pain et de pâtisserie fraîche"
* $TRE-R75-InseeNAFrev2Niveau5#10.71B "Cuisson de produits de boulangerie"
* $TRE-R75-InseeNAFrev2Niveau5#10.71C "Boulangerie et boulangerie-pâtisserie"
* $TRE-R75-InseeNAFrev2Niveau5#10.71D "Pâtisserie"
* $TRE-R75-InseeNAFrev2Niveau5#10.72Z "Fabrication de biscuits, biscottes et pâtisseries de conservation"
* $TRE-R75-InseeNAFrev2Niveau5#10.73Z "Fabrication de pâtes alimentaires"
* $TRE-R75-InseeNAFrev2Niveau5#10.81Z "Fabrication de sucre"
* $TRE-R75-InseeNAFrev2Niveau5#10.82Z "Fabrication de cacao, chocolat et de produits de confiserie"
* $TRE-R75-InseeNAFrev2Niveau5#10.83Z "Transformation du thé et du café"
* $TRE-R75-InseeNAFrev2Niveau5#10.84Z "Fabrication de condiments et assaisonnements"
* $TRE-R75-InseeNAFrev2Niveau5#10.85Z "Fabrication de plats préparés"
* $TRE-R75-InseeNAFrev2Niveau5#10.86Z "Fabrication d'aliments homogénéisés et diététiques"
* $TRE-R75-InseeNAFrev2Niveau5#10.89Z "Fabrication d'autres produits alimentaires n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#10.91Z "Fabrication d'aliments pour animaux de ferme"
* $TRE-R75-InseeNAFrev2Niveau5#10.92Z "Fabrication d'aliments pour animaux de compagnie"
* $TRE-R75-InseeNAFrev2Niveau5#11.01Z "Production de boissons alcooliques distillées"
* $TRE-R75-InseeNAFrev2Niveau5#11.02A "Fabrication de vins effervescents"
* $TRE-R75-InseeNAFrev2Niveau5#11.02B "Vinification"
* $TRE-R75-InseeNAFrev2Niveau5#11.03Z "Fabrication de cidre et de vins de fruits"
* $TRE-R75-InseeNAFrev2Niveau5#11.04Z "Production d'autres boissons fermentées non distillées"
* $TRE-R75-InseeNAFrev2Niveau5#11.05Z "Fabrication de bière"
* $TRE-R75-InseeNAFrev2Niveau5#11.06Z "Fabrication de malt"
* $TRE-R75-InseeNAFrev2Niveau5#11.07A "Industrie des eaux de table"
* $TRE-R75-InseeNAFrev2Niveau5#11.07B "Production de boissons rafraîchissantes"
* $TRE-R75-InseeNAFrev2Niveau5#12.00Z "Fabrication de produits à base de tabac"
* $TRE-R75-InseeNAFrev2Niveau5#13.10Z "Préparation de fibres textiles et filature"
* $TRE-R75-InseeNAFrev2Niveau5#13.20Z "Tissage"
* $TRE-R75-InseeNAFrev2Niveau5#13.30Z "Ennoblissement textile"
* $TRE-R75-InseeNAFrev2Niveau5#13.91Z "Fabrication d'étoffes à mailles"
* $TRE-R75-InseeNAFrev2Niveau5#13.92Z "Fabrication d'articles textiles, sauf habillement"
* $TRE-R75-InseeNAFrev2Niveau5#13.93Z "Fabrication de tapis et moquettes"
* $TRE-R75-InseeNAFrev2Niveau5#13.94Z "Fabrication de ficelles, cordes et filets"
* $TRE-R75-InseeNAFrev2Niveau5#13.95Z "Fabrication de non-tissés, sauf habillement"
* $TRE-R75-InseeNAFrev2Niveau5#13.96Z "Fabrication d'autres textiles techniques et industriels"
* $TRE-R75-InseeNAFrev2Niveau5#13.99Z "Fabrication d'autres textiles n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#14.11Z "Fabrication de vêtements en cuir"
* $TRE-R75-InseeNAFrev2Niveau5#14.12Z "Fabrication de vêtements de travail"
* $TRE-R75-InseeNAFrev2Niveau5#14.13Z "Fabrication de vêtements de dessus"
* $TRE-R75-InseeNAFrev2Niveau5#14.14Z "Fabrication de vêtements de dessous"
* $TRE-R75-InseeNAFrev2Niveau5#14.19Z "Fabrication d'autres vêtements et accessoires"
* $TRE-R75-InseeNAFrev2Niveau5#14.20Z "Fabrication d'articles en fourrure"
* $TRE-R75-InseeNAFrev2Niveau5#14.31Z "Fabrication d'articles chaussants à mailles"
* $TRE-R75-InseeNAFrev2Niveau5#14.39Z "Fabrication d'autres articles à mailles"
* $TRE-R75-InseeNAFrev2Niveau5#15.11Z "Apprêt, tannage des cuirs - préparation et teinture des fourrures"
* $TRE-R75-InseeNAFrev2Niveau5#15.12Z "Fabrication d'articles de voyage, de maroquinerie et de sellerie"
* $TRE-R75-InseeNAFrev2Niveau5#15.20Z "Fabrication de chaussures"
* $TRE-R75-InseeNAFrev2Niveau5#16.10A "Sciage et rabotage du bois, hors imprégnation"
* $TRE-R75-InseeNAFrev2Niveau5#16.10B "Imprégnation du bois"
* $TRE-R75-InseeNAFrev2Niveau5#16.21Z "Fabrication de placage et de panneaux de bois"
* $TRE-R75-InseeNAFrev2Niveau5#16.22Z "Fabrication de parquets assemblés"
* $TRE-R75-InseeNAFrev2Niveau5#16.23Z "Fabrication de charpentes et d'autres menuiseries"
* $TRE-R75-InseeNAFrev2Niveau5#16.24Z "Fabrication d'emballages en bois"
* $TRE-R75-InseeNAFrev2Niveau5#16.29Z "Fabrication objets divers en bois, liège, vannerie et sparterie"
* $TRE-R75-InseeNAFrev2Niveau5#17.11Z "Fabrication de pâte à papier"
* $TRE-R75-InseeNAFrev2Niveau5#17.12Z "Fabrication de papier et de carton"
* $TRE-R75-InseeNAFrev2Niveau5#17.21A "Fabrication de carton ondulé"
* $TRE-R75-InseeNAFrev2Niveau5#17.21B "Fabrication de cartonnages"
* $TRE-R75-InseeNAFrev2Niveau5#17.21C "Fabrication d'emballages en papier"
* $TRE-R75-InseeNAFrev2Niveau5#17.22Z "Fabrication d'articles en papier à usage sanitaire ou domestique"
* $TRE-R75-InseeNAFrev2Niveau5#17.23Z "Fabrication d'articles de papeterie"
* $TRE-R75-InseeNAFrev2Niveau5#17.24Z "Fabrication de papiers peints"
* $TRE-R75-InseeNAFrev2Niveau5#17.29Z "Fabrication d'autres articles en papier ou en carton"
* $TRE-R75-InseeNAFrev2Niveau5#18.11Z "Imprimerie de journaux"
* $TRE-R75-InseeNAFrev2Niveau5#18.12Z "Autre imprimerie (labeur)"
* $TRE-R75-InseeNAFrev2Niveau5#18.13Z "Activités de pré-presse"
* $TRE-R75-InseeNAFrev2Niveau5#18.14Z "Reliure et activités connexes"
* $TRE-R75-InseeNAFrev2Niveau5#18.20Z "Reproduction d'enregistrements"
* $TRE-R75-InseeNAFrev2Niveau5#19.10Z "Cokéfaction"
* $TRE-R75-InseeNAFrev2Niveau5#19.20Z "Raffinage du pétrole"
* $TRE-R75-InseeNAFrev2Niveau5#20.11Z "Fabrication de gaz industriels"
* $TRE-R75-InseeNAFrev2Niveau5#20.12Z "Fabrication de colorants et de pigments"
* $TRE-R75-InseeNAFrev2Niveau5#20.13A "Enrichissement et retraitement de matières nucléaires"
* $TRE-R75-InseeNAFrev2Niveau5#20.13B "Fabric. d'autres produits chimiques inorganiques de base n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#20.14Z "Fabrication d'autres produits chimiques organiques de base"
* $TRE-R75-InseeNAFrev2Niveau5#20.15Z "Fabrication de produits azotés et d'engrais"
* $TRE-R75-InseeNAFrev2Niveau5#20.16Z "Fabrication de matières plastiques de base"
* $TRE-R75-InseeNAFrev2Niveau5#20.17Z "Fabrication de caoutchouc synthétique"
* $TRE-R75-InseeNAFrev2Niveau5#20.20Z "Fabrication de pesticides et d'autres produits agrochimiques"
* $TRE-R75-InseeNAFrev2Niveau5#20.30Z "Fabrication de peintures, vernis, encres et mastics"
* $TRE-R75-InseeNAFrev2Niveau5#20.41Z "Fabrication de savons, détergents et produits d'entretien"
* $TRE-R75-InseeNAFrev2Niveau5#20.42Z "Fabrication de parfums et de produits pour la toilette"
* $TRE-R75-InseeNAFrev2Niveau5#20.51Z "Fabrication de produits explosifs"
* $TRE-R75-InseeNAFrev2Niveau5#20.52Z "Fabrication de colles"
* $TRE-R75-InseeNAFrev2Niveau5#20.53Z "Fabrication d'huiles essentielles"
* $TRE-R75-InseeNAFrev2Niveau5#20.59Z "Fabrication d'autres produits chimiques n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#20.60Z "Fabrication de fibres artificielles ou synthétiques"
* $TRE-R75-InseeNAFrev2Niveau5#21.10Z "Fabrication de produits pharmaceutiques de base"
* $TRE-R75-InseeNAFrev2Niveau5#21.20Z "Fabrication de préparations pharmaceutiques"
* $TRE-R75-InseeNAFrev2Niveau5#22.11Z "Fabrication et rechapage de pneumatiques"
* $TRE-R75-InseeNAFrev2Niveau5#22.19Z "Fabrication d'autres articles en caoutchouc"
* $TRE-R75-InseeNAFrev2Niveau5#22.21Z "Fabrication plaques, feuilles, tubes et profilés en plastique"
* $TRE-R75-InseeNAFrev2Niveau5#22.22Z "Fabrication d'emballages en matières plastiques"
* $TRE-R75-InseeNAFrev2Niveau5#22.23Z "Fabrication d'éléments matières plastiques pour la construction"
* $TRE-R75-InseeNAFrev2Niveau5#22.29A "Fabrication de pièces techniques à base de matières plastiques"
* $TRE-R75-InseeNAFrev2Niveau5#22.29B "Fabrication produits de consommation courante en plastique"
* $TRE-R75-InseeNAFrev2Niveau5#23.11Z "Fabrication de verre plat"
* $TRE-R75-InseeNAFrev2Niveau5#23.12Z "Façonnage et transformation du verre plat"
* $TRE-R75-InseeNAFrev2Niveau5#23.13Z "Fabrication de verre creux"
* $TRE-R75-InseeNAFrev2Niveau5#23.14Z "Fabrication de fibres de verre"
* $TRE-R75-InseeNAFrev2Niveau5#23.19Z "Fabrication & façonnage autres articles verre yc verre technique"
* $TRE-R75-InseeNAFrev2Niveau5#23.20Z "Fabrication de produits réfractaires"
* $TRE-R75-InseeNAFrev2Niveau5#23.31Z "Fabrication de carreaux en céramique"
* $TRE-R75-InseeNAFrev2Niveau5#23.32Z "Fabrication briques tuiles & prod. de construction en terre cuite"
* $TRE-R75-InseeNAFrev2Niveau5#23.41Z "Fabrication d'articles céramiques à usage domestique, ornemental"
* $TRE-R75-InseeNAFrev2Niveau5#23.42Z "Fabrication d'appareils sanitaires en céramique"
* $TRE-R75-InseeNAFrev2Niveau5#23.43Z "Fabrication d'isolateurs et pièces isolantes en céramique"
* $TRE-R75-InseeNAFrev2Niveau5#23.44Z "Fabrication d'autres produits céramiques à usage technique"
* $TRE-R75-InseeNAFrev2Niveau5#23.49Z "Fabrication d'autres produits céramiques"
* $TRE-R75-InseeNAFrev2Niveau5#23.51Z "Fabrication de ciment"
* $TRE-R75-InseeNAFrev2Niveau5#23.52Z "Fabrication de chaux et plâtre"
* $TRE-R75-InseeNAFrev2Niveau5#23.61Z "Fabrication d'éléments en béton pour la construction"
* $TRE-R75-InseeNAFrev2Niveau5#23.62Z "Fabrication d'éléments en plâtre pour la construction"
* $TRE-R75-InseeNAFrev2Niveau5#23.63Z "Fabrication de béton prêt à l'emploi"
* $TRE-R75-InseeNAFrev2Niveau5#23.64Z "Fabrication de mortiers et bétons secs"
* $TRE-R75-InseeNAFrev2Niveau5#23.65Z "Fabrication d'ouvrages en fibre-ciment"
* $TRE-R75-InseeNAFrev2Niveau5#23.69Z "Fabrication d'autres ouvrages en béton, en ciment ou en plâtre"
* $TRE-R75-InseeNAFrev2Niveau5#23.70Z "Taille, façonnage et finissage de pierres"
* $TRE-R75-InseeNAFrev2Niveau5#23.91Z "Fabrication de produits abrasifs"
* $TRE-R75-InseeNAFrev2Niveau5#23.99Z "Fabrication d'autres produits minéraux non métalliques n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#24.10Z "Sidérurgie"
* $TRE-R75-InseeNAFrev2Niveau5#24.20Z "Fabric. tubes, tuyaux, profilés creux & accessoir. corresp. acier"
* $TRE-R75-InseeNAFrev2Niveau5#24.31Z "Étirage à froid de barres"
* $TRE-R75-InseeNAFrev2Niveau5#24.32Z "Laminage à froid de feuillards"
* $TRE-R75-InseeNAFrev2Niveau5#24.33Z "Profilage à froid par formage ou pliage"
* $TRE-R75-InseeNAFrev2Niveau5#24.34Z "Tréfilage à froid"
* $TRE-R75-InseeNAFrev2Niveau5#24.41Z "Production de métaux précieux"
* $TRE-R75-InseeNAFrev2Niveau5#24.42Z "Métallurgie de l'aluminium"
* $TRE-R75-InseeNAFrev2Niveau5#24.43Z "Métallurgie du plomb, du zinc ou de l'étain"
* $TRE-R75-InseeNAFrev2Niveau5#24.44Z "Métallurgie du cuivre"
* $TRE-R75-InseeNAFrev2Niveau5#24.45Z "Métallurgie des autres métaux non ferreux"
* $TRE-R75-InseeNAFrev2Niveau5#24.46Z "Élaboration et transformation de matières nucléaires"
* $TRE-R75-InseeNAFrev2Niveau5#24.51Z "Fonderie de fonte"
* $TRE-R75-InseeNAFrev2Niveau5#24.52Z "Fonderie d'acier"
* $TRE-R75-InseeNAFrev2Niveau5#24.53Z "Fonderie de métaux légers"
* $TRE-R75-InseeNAFrev2Niveau5#24.54Z "Fonderie d'autres métaux non ferreux"
* $TRE-R75-InseeNAFrev2Niveau5#25.11Z "Fabrication de structures métalliques et de parties de structures"
* $TRE-R75-InseeNAFrev2Niveau5#25.12Z "Fabrication de portes et fenêtres en métal"
* $TRE-R75-InseeNAFrev2Niveau5#25.21Z "Fabrication radiateurs et chaudières pour le chauffage central"
* $TRE-R75-InseeNAFrev2Niveau5#25.29Z "Fabrication d'autres réservoirs, citernes, conteneurs métalliques"
* $TRE-R75-InseeNAFrev2Niveau5#25.30Z "Fabric. générateurs vapeur sf chaudières pour chauffage central"
* $TRE-R75-InseeNAFrev2Niveau5#25.40Z "Fabrication d'armes et de munitions"
* $TRE-R75-InseeNAFrev2Niveau5#25.50A "Forge, estampage, matriçage - métallurgie des poudres"
* $TRE-R75-InseeNAFrev2Niveau5#25.50B "Découpage, emboutissage"
* $TRE-R75-InseeNAFrev2Niveau5#25.61Z "Traitement et revêtement des métaux"
* $TRE-R75-InseeNAFrev2Niveau5#25.62A "Décolletage"
* $TRE-R75-InseeNAFrev2Niveau5#25.62B "Mécanique industrielle"
* $TRE-R75-InseeNAFrev2Niveau5#25.71Z "Fabrication de coutellerie"
* $TRE-R75-InseeNAFrev2Niveau5#25.72Z "Fabrication de serrures et de ferrures"
* $TRE-R75-InseeNAFrev2Niveau5#25.73A "Fabrication de moules et modèles"
* $TRE-R75-InseeNAFrev2Niveau5#25.73B "Fabrication d'autres outillages"
* $TRE-R75-InseeNAFrev2Niveau5#25.91Z "Fabrication de fûts et emballages métalliques similaires"
* $TRE-R75-InseeNAFrev2Niveau5#25.92Z "Fabrication d'emballages métalliques légers"
* $TRE-R75-InseeNAFrev2Niveau5#25.93Z "Fabrication d'articles en fils métalliques, chaînes et ressorts"
* $TRE-R75-InseeNAFrev2Niveau5#25.94Z "Fabrication de vis et de boulons"
* $TRE-R75-InseeNAFrev2Niveau5#25.99A "Fabrication d'articles métalliques ménagers"
* $TRE-R75-InseeNAFrev2Niveau5#25.99B "Fabrication d'autres articles métalliques"
* $TRE-R75-InseeNAFrev2Niveau5#26.11Z "Fabrication de composants électroniques"
* $TRE-R75-InseeNAFrev2Niveau5#26.12Z "Fabrication de cartes électroniques assemblées"
* $TRE-R75-InseeNAFrev2Niveau5#26.20Z "Fabrication d'ordinateurs et d'équipements périphériques"
* $TRE-R75-InseeNAFrev2Niveau5#26.30Z "Fabrication d'équipements de communication"
* $TRE-R75-InseeNAFrev2Niveau5#26.40Z "Fabrication de produits électroniques grand public"
* $TRE-R75-InseeNAFrev2Niveau5#26.51A "Fabrication d'équipements d'aide à la navigation"
* $TRE-R75-InseeNAFrev2Niveau5#26.51B "Fabrication d'instrumentation scientifique et technique"
* $TRE-R75-InseeNAFrev2Niveau5#26.52Z "Horlogerie"
* $TRE-R75-InseeNAFrev2Niveau5#26.60Z "Fab. éqpts d'irradiation médic. électromédic. & électrothérapeut."
* $TRE-R75-InseeNAFrev2Niveau5#26.70Z "Fabrication de matériels optique et photographique"
* $TRE-R75-InseeNAFrev2Niveau5#26.80Z "Fabrication de supports magnétiques et optiques"
* $TRE-R75-InseeNAFrev2Niveau5#27.11Z "Fabrication de moteurs, génératrices, transformateurs électriques"
* $TRE-R75-InseeNAFrev2Niveau5#27.12Z "Fabrication de matériel de distribution et de commande électrique"
* $TRE-R75-InseeNAFrev2Niveau5#27.20Z "Fabrication de piles et d'accumulateurs électriques"
* $TRE-R75-InseeNAFrev2Niveau5#27.31Z "Fabrication de câbles de fibres optiques"
* $TRE-R75-InseeNAFrev2Niveau5#27.32Z "Fabrication d'autres fils et câbles électroniques ou électriques"
* $TRE-R75-InseeNAFrev2Niveau5#27.33Z "Fabrication de matériel d'installation électrique"
* $TRE-R75-InseeNAFrev2Niveau5#27.40Z "Fabrication d'appareils d'éclairage électrique"
* $TRE-R75-InseeNAFrev2Niveau5#27.51Z "Fabrication d'appareils électroménagers"
* $TRE-R75-InseeNAFrev2Niveau5#27.52Z "Fabrication d'appareils ménagers non électriques"
* $TRE-R75-InseeNAFrev2Niveau5#27.90Z "Fabrication d'autres matériels électriques"
* $TRE-R75-InseeNAFrev2Niveau5#28.11Z "Fabrication moteurs & turbines sf moteurs d'avions & de véhicules"
* $TRE-R75-InseeNAFrev2Niveau5#28.12Z "Fabrication d'équipements hydrauliques et pneumatiques"
* $TRE-R75-InseeNAFrev2Niveau5#28.13Z "Fabrication d'autres pompes et compresseurs"
* $TRE-R75-InseeNAFrev2Niveau5#28.14Z "Fabrication d'autres articles de robinetterie"
* $TRE-R75-InseeNAFrev2Niveau5#28.15Z "Fabrication d'engrenages et d'organes mécaniques de transmission"
* $TRE-R75-InseeNAFrev2Niveau5#28.21Z "Fabrication de fours et brûleurs"
* $TRE-R75-InseeNAFrev2Niveau5#28.22Z "Fabrication de matériel de levage et de manutention"
* $TRE-R75-InseeNAFrev2Niveau5#28.23Z "Fab. machines équipts bureau (sf ordinateurs & équipts périph.)"
* $TRE-R75-InseeNAFrev2Niveau5#28.24Z "Fabrication d'outillage portatif à moteur incorporé"
* $TRE-R75-InseeNAFrev2Niveau5#28.25Z "Fabrication équipements aérauliques et frigorifiques industriels"
* $TRE-R75-InseeNAFrev2Niveau5#28.29A "Fabrication équipts emballage, conditionnement & pesage"
* $TRE-R75-InseeNAFrev2Niveau5#28.29B "Fabrication d'autres machines d'usage général"
* $TRE-R75-InseeNAFrev2Niveau5#28.30Z "Fabrication de machines agricoles et forestières"
* $TRE-R75-InseeNAFrev2Niveau5#28.41Z "Fabrication de machines-outils pour le travail des métaux"
* $TRE-R75-InseeNAFrev2Niveau5#28.49Z "Fabrication d'autres machines-outils"
* $TRE-R75-InseeNAFrev2Niveau5#28.91Z "Fabrication de machines pour la métallurgie"
* $TRE-R75-InseeNAFrev2Niveau5#28.92Z "Fabrication de machines pour l'extraction ou la construction"
* $TRE-R75-InseeNAFrev2Niveau5#28.93Z "Fabrication de machines pour l'industrie agro-alimentaire"
* $TRE-R75-InseeNAFrev2Niveau5#28.94Z "Fabrication de machines pour les industries textiles"
* $TRE-R75-InseeNAFrev2Niveau5#28.95Z "Fabrication de machines pour les industries du papier et carton"
* $TRE-R75-InseeNAFrev2Niveau5#28.96Z "Fabric. machines pour le travail du caoutchouc ou des plastiques"
* $TRE-R75-InseeNAFrev2Niveau5#28.99A "Fabrication de machines d'imprimerie"
* $TRE-R75-InseeNAFrev2Niveau5#28.99B "Fabrication d'autres machines spécialisées"
* $TRE-R75-InseeNAFrev2Niveau5#29.10Z "Construction de véhicules automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#29.20Z "Fabrication de carrosseries et remorques"
* $TRE-R75-InseeNAFrev2Niveau5#29.31Z "Fabrication équipements électriques et électroniques automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#29.32Z "Fabrication d'autres équipements automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#30.11Z "Construction de navires et de structures flottantes"
* $TRE-R75-InseeNAFrev2Niveau5#30.12Z "Construction de bateaux de plaisance"
* $TRE-R75-InseeNAFrev2Niveau5#30.20Z "Construction locomotives & autre matériel ferroviaire roulant"
* $TRE-R75-InseeNAFrev2Niveau5#30.30Z "Construction aéronautique et spatiale"
* $TRE-R75-InseeNAFrev2Niveau5#30.40Z "Construction de véhicules militaires de combat"
* $TRE-R75-InseeNAFrev2Niveau5#30.91Z "Fabrication de motocycles"
* $TRE-R75-InseeNAFrev2Niveau5#30.92Z "Fabrication de bicyclettes et de véhicules pour invalides"
* $TRE-R75-InseeNAFrev2Niveau5#30.99Z "Fabrication d'autres équipements de transport n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#31.01Z "Fabrication de meubles de bureau et de magasin"
* $TRE-R75-InseeNAFrev2Niveau5#31.02Z "Fabrication de meubles de cuisine"
* $TRE-R75-InseeNAFrev2Niveau5#31.03Z "Fabrication de matelas"
* $TRE-R75-InseeNAFrev2Niveau5#31.09A "Fabrication de sièges d'ameublement d'intérieur"
* $TRE-R75-InseeNAFrev2Niveau5#31.09B "Fabrication autres meubles & industries connexes de l'ameublement"
* $TRE-R75-InseeNAFrev2Niveau5#32.11Z "Frappe de monnaie"
* $TRE-R75-InseeNAFrev2Niveau5#32.12Z "Fabrication d'articles de joaillerie et bijouterie"
* $TRE-R75-InseeNAFrev2Niveau5#32.13Z "Fabrication articles bijouterie fantaisie & articles similaires"
* $TRE-R75-InseeNAFrev2Niveau5#32.20Z "Fabrication d'instruments de musique"
* $TRE-R75-InseeNAFrev2Niveau5#32.30Z "Fabrication d'articles de sport"
* $TRE-R75-InseeNAFrev2Niveau5#32.40Z "Fabrication de jeux et jouets"
* $TRE-R75-InseeNAFrev2Niveau5#32.50A "Fabrication de matériel médico-chirurgical et dentaire"
* $TRE-R75-InseeNAFrev2Niveau5#32.50B "Fabrication de lunettes"
* $TRE-R75-InseeNAFrev2Niveau5#32.91Z "Fabrication d'articles de brosserie"
* $TRE-R75-InseeNAFrev2Niveau5#32.99Z "Autres activités manufacturières n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#33.11Z "Réparation d'ouvrages en métaux"
* $TRE-R75-InseeNAFrev2Niveau5#33.12Z "Réparation de machines et équipements mécaniques"
* $TRE-R75-InseeNAFrev2Niveau5#33.13Z "Réparation de matériels électroniques et optiques"
* $TRE-R75-InseeNAFrev2Niveau5#33.14Z "Réparation d'équipements électriques"
* $TRE-R75-InseeNAFrev2Niveau5#33.15Z "Réparation et maintenance navale"
* $TRE-R75-InseeNAFrev2Niveau5#33.16Z "Réparation et maintenance d'aéronefs et d'engins spatiaux"
* $TRE-R75-InseeNAFrev2Niveau5#33.17Z "Réparation et maintenance d'autres équipements de transport"
* $TRE-R75-InseeNAFrev2Niveau5#33.19Z "Réparation d'autres équipements"
* $TRE-R75-InseeNAFrev2Niveau5#33.20A "Installation structures métalliques, chaudronnées et tuyauterie"
* $TRE-R75-InseeNAFrev2Niveau5#33.20B "Installation de machines et équipements mécaniques"
* $TRE-R75-InseeNAFrev2Niveau5#33.20C "Concept. d'ens. & assembl s-site d'éqpts ctrle des processus ind."
* $TRE-R75-InseeNAFrev2Niveau5#33.20D "Instal. éqpts électriq, mat. électro. et optiq. ou aut. matériels"
* $TRE-R75-InseeNAFrev2Niveau5#35.11Z "Production d'électricité"
* $TRE-R75-InseeNAFrev2Niveau5#35.12Z "Transport d'électricité"
* $TRE-R75-InseeNAFrev2Niveau5#35.13Z "Distribution d'électricité"
* $TRE-R75-InseeNAFrev2Niveau5#35.14Z "Commerce d'électricité"
* $TRE-R75-InseeNAFrev2Niveau5#35.21Z "Production de combustibles gazeux"
* $TRE-R75-InseeNAFrev2Niveau5#35.22Z "Distribution de combustibles gazeux par conduites"
* $TRE-R75-InseeNAFrev2Niveau5#35.23Z "Commerce de combustibles gazeux par conduites"
* $TRE-R75-InseeNAFrev2Niveau5#35.30Z "Production et distribution de vapeur et d'air conditionné"
* $TRE-R75-InseeNAFrev2Niveau5#36.00Z "Captage, traitement et distribution d'eau"
* $TRE-R75-InseeNAFrev2Niveau5#37.00Z "Collecte et traitement des eaux usées"
* $TRE-R75-InseeNAFrev2Niveau5#38.11Z "Collecte des déchets non dangereux"
* $TRE-R75-InseeNAFrev2Niveau5#38.12Z "Collecte des déchets dangereux"
* $TRE-R75-InseeNAFrev2Niveau5#38.21Z "Traitement et élimination des déchets non dangereux"
* $TRE-R75-InseeNAFrev2Niveau5#38.22Z "Traitement et élimination des déchets dangereux"
* $TRE-R75-InseeNAFrev2Niveau5#38.31Z "Démantèlement d'épaves"
* $TRE-R75-InseeNAFrev2Niveau5#38.32Z "Récupération de déchets triés"
* $TRE-R75-InseeNAFrev2Niveau5#39.00Z "Dépollution et autres services de gestion des déchets"
* $TRE-R75-InseeNAFrev2Niveau5#41.10A "Promotion immobilière de logements"
* $TRE-R75-InseeNAFrev2Niveau5#41.10B "Promotion immobilière de bureaux"
* $TRE-R75-InseeNAFrev2Niveau5#41.10C "Promotion immobilière d'autres bâtiments"
* $TRE-R75-InseeNAFrev2Niveau5#41.10D "Supports juridiques de programmes"
* $TRE-R75-InseeNAFrev2Niveau5#41.20A "Construction de maisons individuelles"
* $TRE-R75-InseeNAFrev2Niveau5#41.20B "Construction d'autres bâtiments"
* $TRE-R75-InseeNAFrev2Niveau5#42.11Z "Construction de routes et autoroutes"
* $TRE-R75-InseeNAFrev2Niveau5#42.12Z "Construction de voies ferrées de surface et souterraines"
* $TRE-R75-InseeNAFrev2Niveau5#42.13A "Construction d'ouvrages d'art"
* $TRE-R75-InseeNAFrev2Niveau5#42.13B "Construction et entretien de tunnels"
* $TRE-R75-InseeNAFrev2Niveau5#42.21Z "Construction de réseaux pour fluides"
* $TRE-R75-InseeNAFrev2Niveau5#42.22Z "Construction de réseaux électriques et de télécommunications"
* $TRE-R75-InseeNAFrev2Niveau5#42.91Z "Construction d'ouvrages maritimes et fluviaux"
* $TRE-R75-InseeNAFrev2Niveau5#42.99Z "Construction d'autres ouvrages de génie civil n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#43.11Z "Travaux de démolition"
* $TRE-R75-InseeNAFrev2Niveau5#43.12A "Travaux de terrassement courants et travaux préparatoires"
* $TRE-R75-InseeNAFrev2Niveau5#43.12B "Travaux de terrassement spécialisés ou de grande masse"
* $TRE-R75-InseeNAFrev2Niveau5#43.13Z "Forages et sondages"
* $TRE-R75-InseeNAFrev2Niveau5#43.21A "Travaux d'installation électrique dans tous locaux"
* $TRE-R75-InseeNAFrev2Niveau5#43.21B "Travaux d'installation électrique sur la voie publique"
* $TRE-R75-InseeNAFrev2Niveau5#43.22A "Travaux d'installation d'eau et de gaz en tous locaux"
* $TRE-R75-InseeNAFrev2Niveau5#43.22B "Travaux d'installation équipements thermiques et climatisation"
* $TRE-R75-InseeNAFrev2Niveau5#43.29A "Travaux d'isolation"
* $TRE-R75-InseeNAFrev2Niveau5#43.29B "Autres travaux d'installation n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#43.31Z "Travaux de plâtrerie"
* $TRE-R75-InseeNAFrev2Niveau5#43.32A "Travaux de menuiserie bois et PVC"
* $TRE-R75-InseeNAFrev2Niveau5#43.32B "Travaux de menuiserie métallique et serrurerie"
* $TRE-R75-InseeNAFrev2Niveau5#43.32C "Agencement de lieux de vente"
* $TRE-R75-InseeNAFrev2Niveau5#43.33Z "Travaux de revêtement des sols et des murs"
* $TRE-R75-InseeNAFrev2Niveau5#43.34Z "Travaux de peinture et vitrerie"
* $TRE-R75-InseeNAFrev2Niveau5#43.39Z "Autres travaux de finition"
* $TRE-R75-InseeNAFrev2Niveau5#43.91A "Travaux de charpente"
* $TRE-R75-InseeNAFrev2Niveau5#43.91B "Travaux de couverture par éléments"
* $TRE-R75-InseeNAFrev2Niveau5#43.99A "Travaux d'étanchéification"
* $TRE-R75-InseeNAFrev2Niveau5#43.99B "Travaux de montage de structures métalliques"
* $TRE-R75-InseeNAFrev2Niveau5#43.99C "Travaux de maçonnerie générale et gros oeuvre de bâtiment"
* $TRE-R75-InseeNAFrev2Niveau5#43.99D "Autres travaux spécialisés de construction"
* $TRE-R75-InseeNAFrev2Niveau5#43.99E "Location avec opérateur de matériel de construction"
* $TRE-R75-InseeNAFrev2Niveau5#45.11Z "Commerce de voitures et de véhicules automobiles légers"
* $TRE-R75-InseeNAFrev2Niveau5#45.19Z "Commerce d'autres véhicules automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#45.20A "Entretien et réparation de véhicules automobiles légers"
* $TRE-R75-InseeNAFrev2Niveau5#45.20B "Entretien et réparation d'autres véhicules automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#45.31Z "Commerce de gros d'équipements automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#45.32Z "Commerce de détail d'équipements automobiles"
* $TRE-R75-InseeNAFrev2Niveau5#45.40Z "Commerce et réparation de motocycles"
* $TRE-R75-InseeNAFrev2Niveau5#46.11Z "Interm. du comm. en m.p. agricoles & textiles, animaux vivants"
* $TRE-R75-InseeNAFrev2Niveau5#46.12A "Centrales d'achat de carburant"
* $TRE-R75-InseeNAFrev2Niveau5#46.12B "Autres interm. comm. combustibles métaux minéraux prod. chimiques"
* $TRE-R75-InseeNAFrev2Niveau5#46.13Z "Intermédiaires du commerce en bois et matériaux de construction"
* $TRE-R75-InseeNAFrev2Niveau5#46.14Z "Interm. comm. machines, équipts industriels, navires et avions"
* $TRE-R75-InseeNAFrev2Niveau5#46.15Z "Interm. comm. en meubles, articles de ménage et quincaillerie"
* $TRE-R75-InseeNAFrev2Niveau5#46.16Z "Interm. comm. textiles, habillt, fourrures, chaussures & art cuir"
* $TRE-R75-InseeNAFrev2Niveau5#46.17A "Centrales d'achat alimentaires"
* $TRE-R75-InseeNAFrev2Niveau5#46.17B "Autres intermédiaires du commerce en denrées, boissons et tabac"
* $TRE-R75-InseeNAFrev2Niveau5#46.18Z "Interm. spécialisés commerce d'autres produits spécifiques"
* $TRE-R75-InseeNAFrev2Niveau5#46.19A "Centrales d'achat non alimentaires"
* $TRE-R75-InseeNAFrev2Niveau5#46.19B "Autres intermédiaires du commerce en produits divers"
* $TRE-R75-InseeNAFrev2Niveau5#46.21Z "Comm. de gros céréales, tabac non manuf. et aliments pour bétail"
* $TRE-R75-InseeNAFrev2Niveau5#46.22Z "Commerce de gros (commerce interentreprises) de fleurs et plantes"
* $TRE-R75-InseeNAFrev2Niveau5#46.23Z "Commerce de gros (commerce interentreprises) d'animaux vivants"
* $TRE-R75-InseeNAFrev2Niveau5#46.24Z "Commerce de gros (commerce interentreprises) de cuirs et peaux"
* $TRE-R75-InseeNAFrev2Niveau5#46.31Z "Commerce de gros (commerce interentreprises) de fruits et légumes"
* $TRE-R75-InseeNAFrev2Niveau5#46.32A "Commerce de gros de viandes de boucherie"
* $TRE-R75-InseeNAFrev2Niveau5#46.32B "Commerce de gros de produits à base de viande"
* $TRE-R75-InseeNAFrev2Niveau5#46.32C "Commerce de gros de volailles et gibier"
* $TRE-R75-InseeNAFrev2Niveau5#46.33Z "Com. gros produits laitiers, oeufs, huiles & mat. grasses comest."
* $TRE-R75-InseeNAFrev2Niveau5#46.34Z "Commerce de gros (commerce interentreprises) de boissons"
* $TRE-R75-InseeNAFrev2Niveau5#46.35Z "Commerce de gros de produits à base de tabac"
* $TRE-R75-InseeNAFrev2Niveau5#46.36Z "Commerce de gros de sucre, chocolat et confiserie"
* $TRE-R75-InseeNAFrev2Niveau5#46.37Z "Commerce de gros de café, thé, cacao et épices"
* $TRE-R75-InseeNAFrev2Niveau5#46.38A "Commerce de gros de poissons, crustacés et mollusques"
* $TRE-R75-InseeNAFrev2Niveau5#46.38B "Commerce de gros alimentaire spécialisé divers"
* $TRE-R75-InseeNAFrev2Niveau5#46.39A "Commerce de gros (commerce interentreprises) de produits surgelés"
* $TRE-R75-InseeNAFrev2Niveau5#46.39B "Commerce de gros alimentaire non spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#46.41Z "Commerce de gros (commerce interentreprises) de textiles"
* $TRE-R75-InseeNAFrev2Niveau5#46.42Z "Commerce de gros d'habillement et de chaussures"
* $TRE-R75-InseeNAFrev2Niveau5#46.43Z "Commerce de gros d'appareils électroménagers"
* $TRE-R75-InseeNAFrev2Niveau5#46.44Z "Commerce de gros de vaisselle, verrerie et produits d'entretien"
* $TRE-R75-InseeNAFrev2Niveau5#46.45Z "Commerce de gros de parfumerie et de produits de beauté"
* $TRE-R75-InseeNAFrev2Niveau5#46.46Z "Commerce de gros de produits pharmaceutiques"
* $TRE-R75-InseeNAFrev2Niveau5#46.47Z "Commerce de gros de meubles, de tapis et d'appareils d'éclairage"
* $TRE-R75-InseeNAFrev2Niveau5#46.48Z "Commerce de gros d'articles d'horlogerie et de bijouterie"
* $TRE-R75-InseeNAFrev2Niveau5#46.49Z "Commerce de gros d'autres biens domestiques"
* $TRE-R75-InseeNAFrev2Niveau5#46.51Z "Comm. de gros d'ordinat., d'éqpts informatiq. périph. & logiciels"
* $TRE-R75-InseeNAFrev2Niveau5#46.52Z "Comm. de gros d'éqpts et composants électroniques et de télécomm."
* $TRE-R75-InseeNAFrev2Niveau5#46.61Z "Commerce de gros (commerce interentreprises) de matériel agricole"
* $TRE-R75-InseeNAFrev2Niveau5#46.62Z "Commerce de gros (commerce interentreprises) de machines-outils"
* $TRE-R75-InseeNAFrev2Niveau5#46.63Z "Comm de gros de machines pour l'extrac, la constr, le génie civil"
* $TRE-R75-InseeNAFrev2Niveau5#46.64Z "Comm. gros (interentr.) machines pour industrie textile & habill."
* $TRE-R75-InseeNAFrev2Niveau5#46.65Z "Commerce de gros de mobilier de bureau"
* $TRE-R75-InseeNAFrev2Niveau5#46.66Z "Commerce de gros d'autres machines et équipements de bureau"
* $TRE-R75-InseeNAFrev2Niveau5#46.69A "Commerce de gros de matériel électrique"
* $TRE-R75-InseeNAFrev2Niveau5#46.69B "Commerce de gros de fournitures et équipements industriels divers"
* $TRE-R75-InseeNAFrev2Niveau5#46.69C "Comm. gros de fournitures & équipts divers pour commerces & sces"
* $TRE-R75-InseeNAFrev2Niveau5#46.71Z "Commerce de gros de combustibles et de produits annexes"
* $TRE-R75-InseeNAFrev2Niveau5#46.72Z "Commerce de gros de minerais et métaux"
* $TRE-R75-InseeNAFrev2Niveau5#46.73A "Commerce de gros de bois et de matériaux de construction"
* $TRE-R75-InseeNAFrev2Niveau5#46.73B "Commerce de gros d'appareils sanitaires et produits de décoration"
* $TRE-R75-InseeNAFrev2Niveau5#46.74A "Commerce de gros (commerce interentreprises) de quincaillerie"
* $TRE-R75-InseeNAFrev2Niveau5#46.74B "Commerce de gros de fournitures pour la plomberie et le chauffage"
* $TRE-R75-InseeNAFrev2Niveau5#46.75Z "Commerce de gros de produits chimiques"
* $TRE-R75-InseeNAFrev2Niveau5#46.76Z "Commerce de gros d'autres produits intermédiaires"
* $TRE-R75-InseeNAFrev2Niveau5#46.77Z "Commerce de gros (commerce interentreprises) de déchets et débris"
* $TRE-R75-InseeNAFrev2Niveau5#46.90Z "Commerce de gros (commerce interentreprises) non spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.11A "Commerce de détail de produits surgelés"
* $TRE-R75-InseeNAFrev2Niveau5#47.11B "Commerce d'alimentation générale"
* $TRE-R75-InseeNAFrev2Niveau5#47.11C "Supérettes"
* $TRE-R75-InseeNAFrev2Niveau5#47.11D "Supermarchés"
* $TRE-R75-InseeNAFrev2Niveau5#47.11E "Magasins multi-commerces"
* $TRE-R75-InseeNAFrev2Niveau5#47.11F "Hypermarchés"
* $TRE-R75-InseeNAFrev2Niveau5#47.19A "Grands magasins"
* $TRE-R75-InseeNAFrev2Niveau5#47.19B "Autres commerces de détail en magasin non spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.21Z "Commerce de détail de fruits et légumes en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.22Z "Comm. détail viandes & produits à base de viande (magas. spéc.)"
* $TRE-R75-InseeNAFrev2Niveau5#47.23Z "Comm. détail poissons crustacés & mollusques (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.24Z "Comm. détail pain pâtisserie & confiserie (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.25Z "Commerce de détail de boissons en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.26Z "Comm. détail de produits à base de tabac en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.29Z "Autres commerces de détail alimentaires en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.30Z "Commerce de détail de carburants en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.41Z "Comm. détail ordinateurs unités périph. & logiciels (magas. spéc)"
* $TRE-R75-InseeNAFrev2Niveau5#47.42Z "Comm. détail matériels télécommunication (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.43Z "Commerce de détail de matériels audio-vidéo en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.51Z "Commerce de détail de textiles en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.52A "Comm. détail de quincaillerie, peintures et verres (mag.< 400 m2)"
* $TRE-R75-InseeNAFrev2Niveau5#47.52B "Comm. détail de quincaillerie, peintures et verres (mag.> 400 m2)"
* $TRE-R75-InseeNAFrev2Niveau5#47.53Z "Comm. détail tapis, moquettes & revêts murs & sols (magas. spéc.)"
* $TRE-R75-InseeNAFrev2Niveau5#47.54Z "Commerce de détail appareils électroménagers (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.59A "Commerce de détail de meubles"
* $TRE-R75-InseeNAFrev2Niveau5#47.59B "Commerce de détail d'autres équipements du foyer"
* $TRE-R75-InseeNAFrev2Niveau5#47.61Z "Commerce de détail de livres en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.62Z "Commerce de détail de journaux et papeterie en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.63Z "Comm. détail enreg. musicaux & vidéo (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.64Z "Commerce de détail d'articles de sport en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.65Z "Commerce de détail de jeux et jouets en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.71Z "Commerce de détail d'habillement en magasin spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.72A "Commerce de détail de la chaussure"
* $TRE-R75-InseeNAFrev2Niveau5#47.72B "Commerce de détail de maroquinerie et d'articles de voyage"
* $TRE-R75-InseeNAFrev2Niveau5#47.73Z "Commerce de détail produits pharmaceutiques (magasin spécialisé)"
* $TRE-R75-InseeNAFrev2Niveau5#47.74Z "Comm. détail d'articles médicaux & orthopédiques en magasin spéc."
* $TRE-R75-InseeNAFrev2Niveau5#47.75Z "Comm. détail de parfumerie & produits de beauté en magasin spéc."
* $TRE-R75-InseeNAFrev2Niveau5#47.76Z "Comm. dét. fleurs, plantes, etc, animaux de cie et leurs aliments"
* $TRE-R75-InseeNAFrev2Niveau5#47.77Z "Comm. détail d'articles horlogerie & bijouterie (magas. spéc.)"
* $TRE-R75-InseeNAFrev2Niveau5#47.78A "Commerces de détail d'optique"
* $TRE-R75-InseeNAFrev2Niveau5#47.78B "Commerces de détail de charbons et combustibles"
* $TRE-R75-InseeNAFrev2Niveau5#47.78C "Autres commerces de détail spécialisés divers"
* $TRE-R75-InseeNAFrev2Niveau5#47.79Z "Commerce de détail de biens d'occasion en magasin"
* $TRE-R75-InseeNAFrev2Niveau5#47.81Z "Commerce de détail alimentaire sur éventaires et marchés"
* $TRE-R75-InseeNAFrev2Niveau5#47.82Z "Comm. détail textiles habillt & chaussures s-éventaires & marchés"
* $TRE-R75-InseeNAFrev2Niveau5#47.89Z "Autres commerces de détail sur éventaires et marchés"
* $TRE-R75-InseeNAFrev2Niveau5#47.91A "Vente à distance sur catalogue général"
* $TRE-R75-InseeNAFrev2Niveau5#47.91B "Vente à distance sur catalogue spécialisé"
* $TRE-R75-InseeNAFrev2Niveau5#47.99A "Vente à domicile"
* $TRE-R75-InseeNAFrev2Niveau5#47.99B "Vente par automate, aut. com. dét. hors mag., éventaire ou marché"
* $TRE-R75-InseeNAFrev2Niveau5#49.10Z "Transport ferroviaire interurbain de voyageurs"
* $TRE-R75-InseeNAFrev2Niveau5#49.20Z "Transports ferroviaires de fret"
* $TRE-R75-InseeNAFrev2Niveau5#49.31Z "Transports urbains et suburbains de voyageurs"
* $TRE-R75-InseeNAFrev2Niveau5#49.32Z "Transports de voyageurs par taxis"
* $TRE-R75-InseeNAFrev2Niveau5#49.39A "Transports routiers réguliers de voyageurs"
* $TRE-R75-InseeNAFrev2Niveau5#49.39B "Autres transports routiers de voyageurs"
* $TRE-R75-InseeNAFrev2Niveau5#49.39C "Téléphériques et remontées mécaniques"
* $TRE-R75-InseeNAFrev2Niveau5#49.41A "Transports routiers de fret interurbains"
* $TRE-R75-InseeNAFrev2Niveau5#49.41B "Transports routiers de fret de proximité"
* $TRE-R75-InseeNAFrev2Niveau5#49.41C "Location de camions avec chauffeur"
* $TRE-R75-InseeNAFrev2Niveau5#49.42Z "Services de déménagement"
* $TRE-R75-InseeNAFrev2Niveau5#49.50Z "Transports par conduites"
* $TRE-R75-InseeNAFrev2Niveau5#50.10Z "Transports maritimes et côtiers de passagers"
* $TRE-R75-InseeNAFrev2Niveau5#50.20Z "Transports maritimes et côtiers de fret"
* $TRE-R75-InseeNAFrev2Niveau5#50.30Z "Transports fluviaux de passagers"
* $TRE-R75-InseeNAFrev2Niveau5#50.40Z "Transports fluviaux de fret"
* $TRE-R75-InseeNAFrev2Niveau5#51.10Z "Transports aériens de passagers"
* $TRE-R75-InseeNAFrev2Niveau5#51.21Z "Transports aériens de fret"
* $TRE-R75-InseeNAFrev2Niveau5#51.22Z "Transports spatiaux"
* $TRE-R75-InseeNAFrev2Niveau5#52.10A "Entreposage et stockage frigorifique"
* $TRE-R75-InseeNAFrev2Niveau5#52.10B "Entreposage et stockage non frigorifique"
* $TRE-R75-InseeNAFrev2Niveau5#52.21Z "Services auxiliaires des transports terrestres"
* $TRE-R75-InseeNAFrev2Niveau5#52.22Z "Services auxiliaires des transports par eau"
* $TRE-R75-InseeNAFrev2Niveau5#52.23Z "Services auxiliaires des transports aériens"
* $TRE-R75-InseeNAFrev2Niveau5#52.24A "Manutention portuaire"
* $TRE-R75-InseeNAFrev2Niveau5#52.24B "Manutention non portuaire"
* $TRE-R75-InseeNAFrev2Niveau5#52.29A "Messagerie, fret express"
* $TRE-R75-InseeNAFrev2Niveau5#52.29B "Affrètement et organisation des transports"
* $TRE-R75-InseeNAFrev2Niveau5#53.10Z "Activ. poste dans le cadre d'une obligation de service universel"
* $TRE-R75-InseeNAFrev2Niveau5#53.20Z "Autres activités de poste et de courrier"
* $TRE-R75-InseeNAFrev2Niveau5#55.10Z "Hôtels et hébergement similaire"
* $TRE-R75-InseeNAFrev2Niveau5#55.20Z "Hébergement touristique et autre hébergement de courte durée"
* $TRE-R75-InseeNAFrev2Niveau5#55.30Z "Terrains de camping et parcs pour caravanes, véhicules de loisirs"
* $TRE-R75-InseeNAFrev2Niveau5#55.90Z "Autres hébergements"
* $TRE-R75-InseeNAFrev2Niveau5#56.10A "Restauration traditionnelle"
* $TRE-R75-InseeNAFrev2Niveau5#56.10B "Cafétérias et autres libres-services"
* $TRE-R75-InseeNAFrev2Niveau5#56.10C "Restauration de type rapide"
* $TRE-R75-InseeNAFrev2Niveau5#56.21Z "Services des traiteurs"
* $TRE-R75-InseeNAFrev2Niveau5#56.29A "Restauration collective sous contrat"
* $TRE-R75-InseeNAFrev2Niveau5#56.29B "Autres services de restauration n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#56.30Z "Débits de boissons"
* $TRE-R75-InseeNAFrev2Niveau5#58.11Z "Édition de livres"
* $TRE-R75-InseeNAFrev2Niveau5#58.12Z "Édition de répertoires et de fichiers d'adresses"
* $TRE-R75-InseeNAFrev2Niveau5#58.13Z "Édition de journaux"
* $TRE-R75-InseeNAFrev2Niveau5#58.14Z "Édition de revues et périodiques"
* $TRE-R75-InseeNAFrev2Niveau5#58.19Z "Autres activités d'édition"
* $TRE-R75-InseeNAFrev2Niveau5#58.21Z "Édition de jeux électroniques"
* $TRE-R75-InseeNAFrev2Niveau5#58.29A "Édition de logiciels système et de réseau"
* $TRE-R75-InseeNAFrev2Niveau5#58.29B "Edition de logiciels outils de développement et de langages"
* $TRE-R75-InseeNAFrev2Niveau5#58.29C "Edition de logiciels applicatifs"
* $TRE-R75-InseeNAFrev2Niveau5#59.11A "Production de films et de programmes pour la télévision"
* $TRE-R75-InseeNAFrev2Niveau5#59.11B "Production de films institutionnels et publicitaires"
* $TRE-R75-InseeNAFrev2Niveau5#59.11C "Production de films pour le cinéma"
* $TRE-R75-InseeNAFrev2Niveau5#59.12Z "Post-production films cinématograph. vidéo & prog. de télévision"
* $TRE-R75-InseeNAFrev2Niveau5#59.13A "Distribution de films cinématographiques"
* $TRE-R75-InseeNAFrev2Niveau5#59.13B "Edition et distribution vidéo"
* $TRE-R75-InseeNAFrev2Niveau5#59.14Z "Projection de films cinématographiques"
* $TRE-R75-InseeNAFrev2Niveau5#59.20Z "Enregistrement sonore et édition musicale"
* $TRE-R75-InseeNAFrev2Niveau5#60.10Z "Édition et diffusion de programmes radio"
* $TRE-R75-InseeNAFrev2Niveau5#60.20A "Edition de chaînes généralistes"
* $TRE-R75-InseeNAFrev2Niveau5#60.20B "Edition de chaînes thématiques"
* $TRE-R75-InseeNAFrev2Niveau5#61.10Z "Télécommunications filaires"
* $TRE-R75-InseeNAFrev2Niveau5#61.20Z "Télécommunications sans fil"
* $TRE-R75-InseeNAFrev2Niveau5#61.30Z "Télécommunications par satellite"
* $TRE-R75-InseeNAFrev2Niveau5#61.90Z "Autres activités de télécommunication"
* $TRE-R75-InseeNAFrev2Niveau5#62.01Z "Programmation informatique"
* $TRE-R75-InseeNAFrev2Niveau5#62.02A "Conseil en systèmes et logiciels informatiques"
* $TRE-R75-InseeNAFrev2Niveau5#62.02B "Tierce maintenance de systèmes et d'applications informatiques"
* $TRE-R75-InseeNAFrev2Niveau5#62.03Z "Gestion d'installations informatiques"
* $TRE-R75-InseeNAFrev2Niveau5#62.09Z "Autres activités informatiques"
* $TRE-R75-InseeNAFrev2Niveau5#63.11Z "Traitement de données, hébergement et activités connexes"
* $TRE-R75-InseeNAFrev2Niveau5#63.12Z "Portails Internet"
* $TRE-R75-InseeNAFrev2Niveau5#63.91Z "Activités des agences de presse"
* $TRE-R75-InseeNAFrev2Niveau5#63.99Z "Autres services d'information n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#64.11Z "Activités de banque centrale"
* $TRE-R75-InseeNAFrev2Niveau5#64.19Z "Autres intermédiations monétaires"
* $TRE-R75-InseeNAFrev2Niveau5#64.20Z "Activités des sociétés holding"
* $TRE-R75-InseeNAFrev2Niveau5#64.30Z "Fonds de placement et entités financières similaires"
* $TRE-R75-InseeNAFrev2Niveau5#64.91Z "Crédit-bail"
* $TRE-R75-InseeNAFrev2Niveau5#64.92Z "Autre distribution de crédit"
* $TRE-R75-InseeNAFrev2Niveau5#64.99Z "Autres activ. serv. financiers sf assurance & c. de retraite, nca"
* $TRE-R75-InseeNAFrev2Niveau5#65.11Z "Assurance vie"
* $TRE-R75-InseeNAFrev2Niveau5#65.12Z "Autres assurances"
* $TRE-R75-InseeNAFrev2Niveau5#65.20Z "Réassurance"
* $TRE-R75-InseeNAFrev2Niveau5#65.30Z "Caisses de retraite"
* $TRE-R75-InseeNAFrev2Niveau5#66.11Z "Administration de marchés financiers"
* $TRE-R75-InseeNAFrev2Niveau5#66.12Z "Courtage de valeurs mobilières et de marchandises"
* $TRE-R75-InseeNAFrev2Niveau5#66.19A "Supports juridiques de gestion de patrimoine mobilier"
* $TRE-R75-InseeNAFrev2Niveau5#66.19B "Aut. activ. auxil. serv. financ., hors assur. & caisse retr. nca."
* $TRE-R75-InseeNAFrev2Niveau5#66.21Z "Évaluation des risques et dommages"
* $TRE-R75-InseeNAFrev2Niveau5#66.22Z "Activités des agents et courtiers d'assurances"
* $TRE-R75-InseeNAFrev2Niveau5#66.29Z "Aut. activités auxiliaires d'assurance et de caisses de retraite"
* $TRE-R75-InseeNAFrev2Niveau5#66.30Z "Gestion de fonds"
* $TRE-R75-InseeNAFrev2Niveau5#68.10Z "Activités des marchands de biens immobiliers"
* $TRE-R75-InseeNAFrev2Niveau5#68.20A "Location de logements"
* $TRE-R75-InseeNAFrev2Niveau5#68.20B "Location de terrains et d'autres biens immobiliers"
* $TRE-R75-InseeNAFrev2Niveau5#68.31Z "Agences immobilières"
* $TRE-R75-InseeNAFrev2Niveau5#68.32A "Administration d'immeubles et autres biens immobiliers"
* $TRE-R75-InseeNAFrev2Niveau5#68.32B "Supports juridiques de gestion de patrimoine immobilier"
* $TRE-R75-InseeNAFrev2Niveau5#69.10Z "Activités juridiques"
* $TRE-R75-InseeNAFrev2Niveau5#69.20Z "Activités comptables"
* $TRE-R75-InseeNAFrev2Niveau5#70.10Z "Activités des sièges sociaux"
* $TRE-R75-InseeNAFrev2Niveau5#70.21Z "Conseil en relations publiques et communication"
* $TRE-R75-InseeNAFrev2Niveau5#70.22Z "Conseil pour les affaires et autres conseils de gestion"
* $TRE-R75-InseeNAFrev2Niveau5#71.11Z "Activités d'architecture"
* $TRE-R75-InseeNAFrev2Niveau5#71.12A "Activité des géomètres"
* $TRE-R75-InseeNAFrev2Niveau5#71.12B "Ingénierie, études techniques"
* $TRE-R75-InseeNAFrev2Niveau5#71.20A "Contrôle technique automobile"
* $TRE-R75-InseeNAFrev2Niveau5#71.20B "Analyses, essais et inspections techniques"
* $TRE-R75-InseeNAFrev2Niveau5#72.11Z "Recherche-développement en biotechnologie"
* $TRE-R75-InseeNAFrev2Niveau5#72.19Z "Recherche-développement : autres sciences physiques et naturelles"
* $TRE-R75-InseeNAFrev2Niveau5#72.20Z "Recherche-développement en sciences humaines et sociales"
* $TRE-R75-InseeNAFrev2Niveau5#73.11Z "Activités des agences de publicité"
* $TRE-R75-InseeNAFrev2Niveau5#73.12Z "Régie publicitaire de médias"
* $TRE-R75-InseeNAFrev2Niveau5#73.20Z "Études de marché et sondages"
* $TRE-R75-InseeNAFrev2Niveau5#74.10Z "Activités spécialisées de design"
* $TRE-R75-InseeNAFrev2Niveau5#74.20Z "Activités photographiques"
* $TRE-R75-InseeNAFrev2Niveau5#74.30Z "Traduction et interprétation"
* $TRE-R75-InseeNAFrev2Niveau5#74.90A "Activité des économistes de la construction"
* $TRE-R75-InseeNAFrev2Niveau5#74.90B "Activités spécialisées, scientifiques et techniques diverses"
* $TRE-R75-InseeNAFrev2Niveau5#75.00Z "Activités vétérinaires"
* $TRE-R75-InseeNAFrev2Niveau5#77.11A "Location de courte durée voitures & véhicules auto. légers"
* $TRE-R75-InseeNAFrev2Niveau5#77.11B "Location de longue durée voitures & véhicules automobiles légers"
* $TRE-R75-InseeNAFrev2Niveau5#77.12Z "Location et location-bail de camions"
* $TRE-R75-InseeNAFrev2Niveau5#77.21Z "Location et location-bail d'articles de loisirs et de sport"
* $TRE-R75-InseeNAFrev2Niveau5#77.22Z "Location de vidéocassettes et disques vidéo"
* $TRE-R75-InseeNAFrev2Niveau5#77.29Z "Location et location-bail autres biens personnels et domestiques"
* $TRE-R75-InseeNAFrev2Niveau5#77.31Z "Location et location-bail de machines et équipements agricoles"
* $TRE-R75-InseeNAFrev2Niveau5#77.32Z "Location et location-bail machines & équipts pour la construction"
* $TRE-R75-InseeNAFrev2Niveau5#77.33Z "Location et location-bail machines bureau & matériel informatique"
* $TRE-R75-InseeNAFrev2Niveau5#77.34Z "Location et location-bail de matériels de transport par eau"
* $TRE-R75-InseeNAFrev2Niveau5#77.35Z "Location et location-bail de matériels de transport aérien"
* $TRE-R75-InseeNAFrev2Niveau5#77.39Z "Location et location-bail machines, équipements et biens divers"
* $TRE-R75-InseeNAFrev2Niveau5#77.40Z "Loc-bail de propriété intell. & sf oeuvres soumises à copyright"
* $TRE-R75-InseeNAFrev2Niveau5#78.10Z "Activités des agences de placement de main-d'oeuvre"
* $TRE-R75-InseeNAFrev2Niveau5#78.20Z "Activités des agences de travail temporaire"
* $TRE-R75-InseeNAFrev2Niveau5#78.30Z "Autre mise à disposition de ressources humaines"
* $TRE-R75-InseeNAFrev2Niveau5#79.11Z "Activités des agences de voyage"
* $TRE-R75-InseeNAFrev2Niveau5#79.12Z "Activités des voyagistes"
* $TRE-R75-InseeNAFrev2Niveau5#79.90Z "Autres services de réservation et activités connexes"
* $TRE-R75-InseeNAFrev2Niveau5#80.10Z "Activités de sécurité privée"
* $TRE-R75-InseeNAFrev2Niveau5#80.20Z "Activités liées aux systèmes de sécurité"
* $TRE-R75-InseeNAFrev2Niveau5#80.30Z "Activités d'enquête"
* $TRE-R75-InseeNAFrev2Niveau5#81.10Z "Activités combinées de soutien lié aux bâtiments"
* $TRE-R75-InseeNAFrev2Niveau5#81.21Z "Nettoyage courant des bâtiments"
* $TRE-R75-InseeNAFrev2Niveau5#81.22Z "Autres activités nettoyage des bâtiments et nettoyage industriel"
* $TRE-R75-InseeNAFrev2Niveau5#81.29A "Désinfection, désinsectisation, dératisation"
* $TRE-R75-InseeNAFrev2Niveau5#81.29B "Autres activités de nettoyage n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#81.30Z "Services d'aménagement paysager"
* $TRE-R75-InseeNAFrev2Niveau5#82.11Z "Services administratifs combinés de bureau"
* $TRE-R75-InseeNAFrev2Niveau5#82.19Z "Photocopie prépa. documents & aut. activ. spéc. soutien de bureau"
* $TRE-R75-InseeNAFrev2Niveau5#82.20Z "Activités de centres d'appels"
* $TRE-R75-InseeNAFrev2Niveau5#82.30Z "Organisation de foires, salons professionnels et congrès"
* $TRE-R75-InseeNAFrev2Niveau5#82.91Z "Activ. de recouvrement factures & d'info. financ. s-la clientèle"
* $TRE-R75-InseeNAFrev2Niveau5#82.92Z "Activités de conditionnement"
* $TRE-R75-InseeNAFrev2Niveau5#82.99Z "Autres activités de soutien aux entreprises n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#84.11Z "Administration publique générale"
* $TRE-R75-InseeNAFrev2Niveau5#84.12Z "Adm. pub. tutelle santé form. cult. & social (aut que sécu. soc.)"
* $TRE-R75-InseeNAFrev2Niveau5#84.13Z "Administration publique (tutelle) des activités économiques"
* $TRE-R75-InseeNAFrev2Niveau5#84.21Z "Affaires étrangères"
* $TRE-R75-InseeNAFrev2Niveau5#84.22Z "Défense"
* $TRE-R75-InseeNAFrev2Niveau5#84.23Z "Justice"
* $TRE-R75-InseeNAFrev2Niveau5#84.24Z "Activités d'ordre public et de sécurité"
* $TRE-R75-InseeNAFrev2Niveau5#84.25Z "Services du feu et de secours"
* $TRE-R75-InseeNAFrev2Niveau5#84.30A "Activités générales de sécurité sociale"
* $TRE-R75-InseeNAFrev2Niveau5#84.30B "Gestion des retraites complémentaires"
* $TRE-R75-InseeNAFrev2Niveau5#84.30C "Distribution sociale de revenus"
* $TRE-R75-InseeNAFrev2Niveau5#85.10Z "Enseignement pré-primaire"
* $TRE-R75-InseeNAFrev2Niveau5#85.20Z "Enseignement primaire"
* $TRE-R75-InseeNAFrev2Niveau5#85.31Z "Enseignement secondaire général"
* $TRE-R75-InseeNAFrev2Niveau5#85.32Z "Enseignement secondaire technique ou professionnel"
* $TRE-R75-InseeNAFrev2Niveau5#85.41Z "Enseignement post-secondaire non supérieur"
* $TRE-R75-InseeNAFrev2Niveau5#85.42Z "Enseignement supérieur"
* $TRE-R75-InseeNAFrev2Niveau5#85.51Z "Enseignement de disciplines sportives et d'activités de loisirs"
* $TRE-R75-InseeNAFrev2Niveau5#85.52Z "Enseignement culturel"
* $TRE-R75-InseeNAFrev2Niveau5#85.53Z "Enseignement de la conduite"
* $TRE-R75-InseeNAFrev2Niveau5#85.59A "Formation continue d'adultes"
* $TRE-R75-InseeNAFrev2Niveau5#85.59B "Autres enseignements"
* $TRE-R75-InseeNAFrev2Niveau5#85.60Z "Activités de soutien à l'enseignement"
* $TRE-R75-InseeNAFrev2Niveau5#86.10Z "Activités hospitalières"
* $TRE-R75-InseeNAFrev2Niveau5#86.21Z "Activité des médecins généralistes"
* $TRE-R75-InseeNAFrev2Niveau5#86.22A "Activités de radiodiagnostic et de radiothérapie"
* $TRE-R75-InseeNAFrev2Niveau5#86.22B "Activités chirurgicales"
* $TRE-R75-InseeNAFrev2Niveau5#86.22C "Autres activités des médecins spécialistes"
* $TRE-R75-InseeNAFrev2Niveau5#86.23Z "Pratique dentaire"
* $TRE-R75-InseeNAFrev2Niveau5#86.90A "Ambulances"
* $TRE-R75-InseeNAFrev2Niveau5#86.90B "Laboratoires d'analyses médicales"
* $TRE-R75-InseeNAFrev2Niveau5#86.90C "Centres de collecte et banques d'organes"
* $TRE-R75-InseeNAFrev2Niveau5#86.90D "Activités des infirmiers et des sages-femmes"
* $TRE-R75-InseeNAFrev2Niveau5#86.90E "Activité profess. rééducation appareillage & pédicures-podologues"
* $TRE-R75-InseeNAFrev2Niveau5#86.90F "Activités de santé humaine non classées ailleurs"
* $TRE-R75-InseeNAFrev2Niveau5#87.10A "Hébergement médicalisé pour personnes âgées"
* $TRE-R75-InseeNAFrev2Niveau5#87.10B "Hébergement médicalisé pour enfants handicapés"
* $TRE-R75-InseeNAFrev2Niveau5#87.10C "Héberg. médicalisé adultes handicapés & autre héberg. médicalisé"
* $TRE-R75-InseeNAFrev2Niveau5#87.20A "Hébergement social pour handicapés mentaux et malades mentaux"
* $TRE-R75-InseeNAFrev2Niveau5#87.20B "Hébergement social pour toxicomanes"
* $TRE-R75-InseeNAFrev2Niveau5#87.30A "Hébergement social pour personnes âgées"
* $TRE-R75-InseeNAFrev2Niveau5#87.30B "Hébergement social pour handicapés physiques"
* $TRE-R75-InseeNAFrev2Niveau5#87.90A "Hébergement social pour enfants en difficultés"
* $TRE-R75-InseeNAFrev2Niveau5#87.90B "Hébergement social pour adultes, familles en difficultés et autre"
* $TRE-R75-InseeNAFrev2Niveau5#88.10A "Aide à domicile"
* $TRE-R75-InseeNAFrev2Niveau5#88.10B "Accueil accompagn. sans héberg. adultes handicapés ou pers. âgées"
* $TRE-R75-InseeNAFrev2Niveau5#88.10C "Aide par le travail"
* $TRE-R75-InseeNAFrev2Niveau5#88.91A "Accueil de jeunes enfants"
* $TRE-R75-InseeNAFrev2Niveau5#88.91B "Accueil ou accompagnement sans hébergement d'enfants handicapés"
* $TRE-R75-InseeNAFrev2Niveau5#88.99A "Aut. accueil ou accompgnt sans hébergt d'enfants et adolescents"
* $TRE-R75-InseeNAFrev2Niveau5#88.99B "Action sociale sans hébergement n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#90.01Z "Arts du spectacle vivant"
* $TRE-R75-InseeNAFrev2Niveau5#90.02Z "Activités de soutien au spectacle vivant"
* $TRE-R75-InseeNAFrev2Niveau5#90.03A "Création artistique relevant des arts plastiques"
* $TRE-R75-InseeNAFrev2Niveau5#90.03B "Autre création artistique"
* $TRE-R75-InseeNAFrev2Niveau5#90.04Z "Gestion de salles de spectacles"
* $TRE-R75-InseeNAFrev2Niveau5#91.01Z "Gestion des bibliothèques et des archives"
* $TRE-R75-InseeNAFrev2Niveau5#91.02Z "Gestion des musées"
* $TRE-R75-InseeNAFrev2Niveau5#91.03Z "Gestion sites monuments historiques & attractions tourist. simil."
* $TRE-R75-InseeNAFrev2Niveau5#91.04Z "Gest. des jardins botaniques et zoolog. et des réserv. naturelles"
* $TRE-R75-InseeNAFrev2Niveau5#92.00Z "Organisation de jeux de hasard et d'argent"
* $TRE-R75-InseeNAFrev2Niveau5#93.11Z "Gestion d'installations sportives"
* $TRE-R75-InseeNAFrev2Niveau5#93.12Z "Activités de clubs de sports"
* $TRE-R75-InseeNAFrev2Niveau5#93.13Z "Activités des centres de culture physique"
* $TRE-R75-InseeNAFrev2Niveau5#93.19Z "Autres activités liées au sport"
* $TRE-R75-InseeNAFrev2Niveau5#93.21Z "Activités des parcs d'attractions et parcs à thèmes"
* $TRE-R75-InseeNAFrev2Niveau5#93.29Z "Autres activités récréatives et de loisirs"
* $TRE-R75-InseeNAFrev2Niveau5#94.11Z "Activités des organisations patronales et consulaires"
* $TRE-R75-InseeNAFrev2Niveau5#94.12Z "Activités des organisations professionnelles"
* $TRE-R75-InseeNAFrev2Niveau5#94.20Z "Activités des syndicats de salariés"
* $TRE-R75-InseeNAFrev2Niveau5#94.91Z "Activités des organisations religieuses"
* $TRE-R75-InseeNAFrev2Niveau5#94.92Z "Activités des organisations politiques"
* $TRE-R75-InseeNAFrev2Niveau5#94.99Z "Autres organisations fonctionnant par adhésion volontaire"
* $TRE-R75-InseeNAFrev2Niveau5#95.11Z "Réparation d'ordinateurs et d'équipements périphériques"
* $TRE-R75-InseeNAFrev2Niveau5#95.12Z "Réparation d'équipements de communication"
* $TRE-R75-InseeNAFrev2Niveau5#95.21Z "Réparation de produits électroniques grand public"
* $TRE-R75-InseeNAFrev2Niveau5#95.22Z "Réparation appareils électromén. & équipts maison & jardin"
* $TRE-R75-InseeNAFrev2Niveau5#95.23Z "Réparation de chaussures et d'articles en cuir"
* $TRE-R75-InseeNAFrev2Niveau5#95.24Z "Réparation de meubles et d'équipements du foyer"
* $TRE-R75-InseeNAFrev2Niveau5#95.25Z "Réparation d'articles d'horlogerie et de bijouterie"
* $TRE-R75-InseeNAFrev2Niveau5#95.29Z "Réparation d'autres biens personnels et domestiques"
* $TRE-R75-InseeNAFrev2Niveau5#96.01A "Blanchisserie-teinturerie de gros"
* $TRE-R75-InseeNAFrev2Niveau5#96.01B "Blanchisserie-teinturerie de détail"
* $TRE-R75-InseeNAFrev2Niveau5#96.02A "Coiffure"
* $TRE-R75-InseeNAFrev2Niveau5#96.02B "Soins de beauté"
* $TRE-R75-InseeNAFrev2Niveau5#96.03Z "Services funéraires"
* $TRE-R75-InseeNAFrev2Niveau5#96.04Z "Entretien corporel"
* $TRE-R75-InseeNAFrev2Niveau5#96.09Z "Autres services personnels n.c.a."
* $TRE-R75-InseeNAFrev2Niveau5#97.00Z "Activités des ménages : employeurs de personnel domestique"
* $TRE-R75-InseeNAFrev2Niveau5#98.10Z "Activ. indifférenciées ménages : producteurs biens (usage propre)"
* $TRE-R75-InseeNAFrev2Niveau5#98.20Z "Activ. indifférenciées ménages : produc. services (usage propre)"
* $TRE-R75-InseeNAFrev2Niveau5#99.00Z "Activités des organisations et organismes extraterritoriaux"