ValueSet: JDV_J76_DisciplineAutorisation_RASS
Id: JDV-J76-DisciplineAutorisation-RASS
Description: "Discipline à laquelle l'autorisation d'exercice est restreinte dans le RASS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:06:56.246+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J76-DisciplineAutorisation-RASS/FHIR/JDV-J76-DisciplineAutorisation-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.144"
* ^version = "20200424120000"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R18-DisciplineAutorisation#DAUT01 "Biologie médicale"
* $TRE-R18-DisciplineAutorisation#DAUT02 "Chirurgie générale"
* $TRE-R18-DisciplineAutorisation#DAUT03 "Chirurgie infantile"
* $TRE-R18-DisciplineAutorisation#DAUT04 "Chirurgie maxillo-faciale et Stomatologie"
* $TRE-R18-DisciplineAutorisation#DAUT05 "Chirurgie orthopédique et Traumatologie"
* $TRE-R18-DisciplineAutorisation#DAUT06 "Chirurgie plastique, reconstructrice et esthétique"
* $TRE-R18-DisciplineAutorisation#DAUT07 "Chirurgie thoracique et cardio-vasculaire"
* $TRE-R18-DisciplineAutorisation#DAUT08 "Chirurgie urologique"
* $TRE-R18-DisciplineAutorisation#DAUT09 "Chirurgie vasculaire"
* $TRE-R18-DisciplineAutorisation#DAUT10 "Chirurgie viscérale et digestive"
* $TRE-R18-DisciplineAutorisation#DAUT11 "Gynécologie-obstétrique"
* $TRE-R18-DisciplineAutorisation#DAUT12 "Neurochirurgie"
* $TRE-R18-DisciplineAutorisation#DAUT13 "Ophtalmologie"
* $TRE-R18-DisciplineAutorisation#DAUT14 "Oto-rhino-laryngologie et Chirurgie cervico-faciale"
* $TRE-R18-DisciplineAutorisation#DAUT15 "Anatomie et Cytologie pathologiques"
* $TRE-R18-DisciplineAutorisation#DAUT16 "Anesthésie et Réanimation"
* $TRE-R18-DisciplineAutorisation#DAUT17 "Cardiologie et Maladies vasculaires"
* $TRE-R18-DisciplineAutorisation#DAUT18 "Dermatologie et Vénéréologie"
* $TRE-R18-DisciplineAutorisation#DAUT19 "Endocrinologie et Métabolisme"
* $TRE-R18-DisciplineAutorisation#DAUT20 "Gastro-entérologie et Hépatologie"
* $TRE-R18-DisciplineAutorisation#DAUT21 "Génétique médicale"
* $TRE-R18-DisciplineAutorisation#DAUT22 "Gériatrie"
* $TRE-R18-DisciplineAutorisation#DAUT23 "Gynécologie médicale"
* $TRE-R18-DisciplineAutorisation#DAUT24 "Hématologie"
* $TRE-R18-DisciplineAutorisation#DAUT25 "Médecine d'urgence"
* $TRE-R18-DisciplineAutorisation#DAUT26 "Médecine générale"
* $TRE-R18-DisciplineAutorisation#DAUT27 "Médecine interne"
* $TRE-R18-DisciplineAutorisation#DAUT28 "Médecine nucléaire"
* $TRE-R18-DisciplineAutorisation#DAUT29 "Médecine physique et de réadaptation"
* $TRE-R18-DisciplineAutorisation#DAUT30 "Néphrologie"
* $TRE-R18-DisciplineAutorisation#DAUT31 "Neurologie"
* $TRE-R18-DisciplineAutorisation#DAUT32 "Oncologie"
* $TRE-R18-DisciplineAutorisation#DAUT33 "Pédiatrie"
* $TRE-R18-DisciplineAutorisation#DAUT34 "Pneumologie"
* $TRE-R18-DisciplineAutorisation#DAUT35 "Psychiatrie"
* $TRE-R18-DisciplineAutorisation#DAUT36 "Radiodiagnostic et Imagerie médicale"
* $TRE-R18-DisciplineAutorisation#DAUT37 "Réanimation médicale"
* $TRE-R18-DisciplineAutorisation#DAUT38 "Rhumatologie"
* $TRE-R18-DisciplineAutorisation#DAUT39 "Santé publique et Médecine sociale"
* $TRE-R18-DisciplineAutorisation#DAUT40 "Médecine du travail"
* $TRE-R18-DisciplineAutorisation#DAUT41 "Stomatologie"