ValueSet: JDV_J13_ResponsableConsent_CISIS
Id: JDV-J13-ResponsableConsent-CISIS
Description: "Responsable consentement - CI-SIS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:05:09.608+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J13-ResponsableConsent-CISIS/FHIR/JDV-J13-ResponsableConsent-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.23"
* ^version = "20200424120000"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R216-HL7RoleCode#MTH "Mère"
* $TRE-R216-HL7RoleCode#FTH "Père"
* $TRE-R216-HL7RoleCode#STPMTH "Belle-mère - épouse du père ou de la mère"
* $TRE-R216-HL7RoleCode#STPFTH "Beau-père - époux du père ou de la mère"
* $TRE-R216-HL7RoleCode#GRMTH "Grand-mère"
* $TRE-R216-HL7RoleCode#GRFTH "Grand-père"
* $TRE-R216-HL7RoleCode#GGRMTH "Arrière-grand-mère"
* $TRE-R216-HL7RoleCode#GGRFTH "Arrière-grand-père"
* $TRE-R216-HL7RoleCode#DAU "Fille biologique"
* $TRE-R216-HL7RoleCode#SON "Fils biologique"
* $TRE-R216-HL7RoleCode#BRO "Frère"
* $TRE-R216-HL7RoleCode#SIS "Soeur"
* $TRE-R216-HL7RoleCode#GRNDDAU "Petite-fille"
* $TRE-R216-HL7RoleCode#GRNDSO "Petit-fils"
* $TRE-R216-HL7RoleCode#UNCLE "Oncle"
* $TRE-R216-HL7RoleCode#AUNT "Tante"
* $TRE-R216-HL7RoleCode#SPS "Epoux ou épouse"
* $TRE-R216-HL7RoleCode#DOMPART "Concubin(e) ou partenaire PACS"
* $TRE-R216-HL7RoleCode#EXT "Autre membre de la famille sans lien génétique direct"
* $TRE-R216-HL7RoleCode#RESPRSN "Responsable légal non membre de la famille"
* $TRE-R216-HL7RoleCode#DAUC "Fille"
* $TRE-R216-HL7RoleCode#SONC "Fils"
* $TRE-R219-AutreResponsableConsent#PATIENT "Patient"