ValueSet: JDV_J56_AuthorSpecialty_DMP
Id: JDV-J56-AuthorSpecialty-DMP
Description: "Jeu de valeurs pour authorSpecialty"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:06:44.061+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-01-18T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J56-AuthorSpecialty-DMP/FHIR/JDV-J56-AuthorSpecialty-DMP"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.1"
* ^version = "20240927120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-09-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-A00-ProducteurDocNonPS#ALIM_AM "Alimentation automatique à partir du Système d'Information de l'Assurance Maladie"
* $TRE-A00-ProducteurDocNonPS#DISPOSITIF "Dispositif médical"
* $TRE-A00-ProducteurDocNonPS#EXP_PATIENT "Expression personnelle du patient"
* $TRE-A00-ProducteurDocNonPS#SECRETARIAT_MEDICAL "Secrétariat médical"
* $TRE-A00-ProducteurDocNonPS#AUTOMATE "Automate"
* $TRE-A00-ProducteurDocNonPS#SNR "Service numérique référencé"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10 "Médecin"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/PAC00 "Médecin - Qualification Praticien adjoint contractuel (PAC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM01 "Médecin - Anatomie et Cytologie pathologiques (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM02 "Médecin - Anesthésie-réanimation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM03 "Médecin - Biologie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM04 "Médecin - Cardiologie et maladies vasculaires (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM05 "Médecin - Chirurgie générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM06 "Médecin - Chirurgie maxillo-faciale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM07 "Médecin - Chirurgie maxillo-faciale et Stomatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM08 "Médecin - Chirurgie orthopédique et Traumatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM09 "Médecin - Chirurgie infantile (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM10 "Médecin - Chirurgie plastique reconstruct et esthétique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM11 "Médecin - Chirurgie thoracique et cardio-vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM12 "Médecin - Chirurgie urologique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM13 "Médecin - Chirurgie vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM14 "Médecin - Chirurgie viscérale et digestive (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM15 "Médecin - Dermatologie et Vénéréologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM16 "Médecin - Endocrinologie et métabolisme (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM17 "Médecin - Génétique médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM18 "Médecin - Gériatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM19 "Médecin - Gynécologie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM20 "Médecin - Gynécologie-obstétrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM21 "Médecin - Hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM22 "Médecin - Hématologie, opt Maladie du sang (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM23 "Médecin - Hématologie, opt Onco-hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM24 "Médecin - Gastro-entérologie et hépatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM25 "Médecin - Médecine du travail (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM26 "Médecin - Qualifié en Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM27 "Médecin - Médecine interne (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM28 "Médecin - Médecine nucléaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM29 "Médecin - Médecine physique et réadaptation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM30 "Médecin - Néphrologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM31 "Médecin - Neuro-chirurgie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM32 "Médecin - Neurologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM33 "Médecin - Neuro-psychiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM34 "Médecin - ORL et Chirurgie cervico-faciale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM35 "Médecin - Oncologie, opt Onco-hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM36 "Médecin - Oncologie, opt médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM37 "Médecin - Oncologie, opt radiothérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM38 "Médecin - Ophtalmologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM39 "Médecin - Oto-rhino-laryngologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM40 "Médecin - Pédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM41 "Médecin - Pneumologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM42 "Médecin - Psychiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM43 "Médecin - Psychiatrie, opt enfant et adolescent (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM44 "Médecin - Radio-diagnostic (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM45 "Médecin - Radio-thérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM46 "Médecin - Médecine intensive-réanimation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM47 "Médecin - Recherche médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM48 "Médecin - Rhumatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM49 "Médecin - Santé publique et Médecine sociale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM50 "Médecin - Stomatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM51 "Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-obs (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM52 "Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-méd (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM53 "Médecin - Spécialiste en Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM54 "Médecin - Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM55 "Médecin - Radio-diagnostic et Radio-Thérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM56 "Médecin - Chirurgie orale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM57 "Médecin - Allergologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM58 "Médecin - Maladies infectieuses et tropicales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM59 "Médecin - Médecine d'urgence (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM60 "Médecin - Médecine légale et expertises médicales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM61 "Médecin - Médecine vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM62 "Médecin - Endocrinologie, diabétologie, nutrition (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM63 "Médecin - Biologie médicale option biologie générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM64 "Médecin - Biologie médicale option médecine moléculaire, génétique et pharmacologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM65 "Médecin - Biologie médicale option hématologie et immunologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM66 "Médecin - Biologie médicale option agents infectieux (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM67 "Médecin - Biologie médicale option biologie de la reproduction (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM68 "Médecin - Chirurgie maxillo-faciale (réforme 2017) (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM69 "Médecin - Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM70 "Médecin - Chirurgie pédiatrique option orthopédie pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM71 "Médecin - Hématologie (réforme 2017) (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM72 "Médecin - Médecine interne et immunologie clinique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM73 "Médecin - Médecine cardiovasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM74 "Médecin - Radiologie et imagerie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM75 "Médecin - Santé publique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM76 "Médecin - Anesthésie-réanimation option anesthésie-pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM77 "Médecin - Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM78 "Médecin - Chirurgie viscérale et digestive option endoscopie chirurgicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM79 "Médecin - Médecine cardiovasculaire option cardiologie interventionnelle (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM80 "Médecin - Médecine cardiovasculaire option imagerie cardio d'expert (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM81 "Médecin - Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM82 "Médecin - Médecine intensive-réanimation option réanimation pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM83 "Médecin - Néphrologie option soins intensifs néphrologiques (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM84 "Médecin - Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM85 "Médecin - Ophtalmo option chirurgie ophtalmopédiatrique et strabologique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM86 "Médecin - ORL et chirurgie cervico-faciale option audiophonologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM87 "Médecin - Pédiatrie option néonatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM88 "Médecin - Pédiatrie option neuropédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM89 "Médecin - Pédiatrie option pneumopédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM90 "Médecin - Pédiatrie option réanimation pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM91 "Médecin - Pneumologie option soins intensifs respiratoires (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM92 "Médecin - Psychiatrie option enfant et adolescent (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM93 "Médecin - Psychiatrie option psychiatrie personne âgée (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM94 "Médecin - Radiologie imagerie médicale option radiologie interventionnelle avancée (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM95 "Médecin - Santé publique option administration de la santé (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX22 "Médecin - Gynécologie médicale et obstétrique (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX24 "Médecin - Gynécologie médicale (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX26 "Médecin - Obstétrique (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX64 "Médecin - Urologie (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH01 "Médecin - Anatomie et cytologie pathologiques (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH02 "Médecin - Anesthésie-réanimation (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH03 "Médecin - Bactériologie-virologie, hygiène hosp (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH04 "Médecin - Biochimie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH05 "Médecin - Biologie cellulaire, histologie, bio du dév (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH06 "Médecin - Biologie médicale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH07 "Médecin - Biophysique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH08 "Médecin - Oncologie médicale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH09 "Médecin - Cardiologie et maladies vasculaires (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH10 "Médecin - Chirurgie générale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH11 "Médecin - Chirurgie viscérale et digestive (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH12 "Médecin - Chirurgie infantile (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH13 "Médecin - Chirurgie maxillo-faciale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH14 "Médecin - Chirurgie orthopédique et Traumatologique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH15 "Médecin - Chirurgie plast reconstruct, esthétique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH16 "Médecin - Chirurgie thoracique et cardio-vasculaire (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH17 "Médecin - Chirurgie urologique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH18 "Médecin - Chirurgie vasculaire (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH19 "Médecin - Dermatologie et Vénéréologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH20 "Médecin - Endocrinologie et Métabolisme (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH21 "Médecin - Santé publique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH22 "Médecin - Explorations fonctionnelles (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH23 "Médecin - Gastro-entérologie et Hépatologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH24 "Médecin - Génétique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH25 "Médecin - Génétique médicale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH26 "Médecin - Gynécologie et Obstétrique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH27 "Médecin - Hématologie biologique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH28 "Médecin - Hématologie clinique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH29 "Médecin - Hémobiologie-transfusion (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH30 "Médecin - Hygiène hospitalière (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH31 "Médecin - Immunologie biologique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH32 "Médecin - Immunologie clinique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH33 "Médecin - Maladies infectieuses, maladies tropicales (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH34 "Médecin - Médecine de la repro et Gynécologie médicale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH35 "Médecin - Médecine du travail (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH36 "Médecin - Médecine d'urgence (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH37 "Médecin - Médecine générale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH38 "Médecin - Gériatrie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH39 "Médecin - Médecine interne (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH40 "Médecin - Médecine légale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH41 "Médecin - Médecine nucléaire (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH42 "Médecin - Médecine physique et de réadaptation (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH43 "Médecin - Néphrologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH44 "Médecin - neuro-chirurgie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH45 "Médecin - Neurologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH46 "Médecin - Odontologie polyvalente (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH47 "Médecin - Ophtalmologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH48 "Médecin - Oto-rhino-laryngologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH49 "Médecin - Parasitologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH50 "Médecin - Pédiatrie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH51 "Médecin - Pharmacie polyvalente et Pharmacie hosp (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH52 "Médecin - Pharmacologie clinique et Toxicologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH53 "Médecin - Pneumologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH54 "Médecin - Psychiatrie polyvalente (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH55 "Médecin - Radiologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH56 "Médecin - Oncologie radiothérapique (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH57 "Médecin - Réanimation médicale (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH58 "Médecin - Rhumatologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH59 "Médecin - Stomatologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SCH60 "Médecin - Toxicologie et Pharmacologie (SCH)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C01 "Médecin - Anatomie et Cytologie pathologiques humaines (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C03 "Médecin - Anesthésie-réanimation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C05 "Médecin - Médecine appliquée aux sports (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C07 "Médecin - Cardiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C09 "Médecin - Chirurgie plast reconstruct, esthétique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C10 "Médecin - Chirurgie maxillo-faciale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C11 "Médecin - Chirurgie thoracique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C12 "Médecin - Chirurgie orthopédique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C13 "Médecin - Urologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C15 "Médecin - Dermato-vénéréologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C20 "Médecin - Hémobiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C23 "Médecin - Gynécologie médicale et Obstétrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C25 "Médecin - Gynécologie médicale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C27 "Médecin - Obstétrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C29 "Médecin - Maladies de l'appareil digestif (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C30 "Médecin - Néphrologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C31 "Médecin - Médecine exotique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C33 "Médecin - Allergologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C34 "Médecin - Angéiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C35 "Médecin - Cancérologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C36 "Médecin - Diabétologie-nutrition (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C37 "Médecin - Endocrinologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C38 "Médecin - Maladies du sang (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C39 "Médecin - Réanimation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C40 "Médecin - Médecine légale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C41 "Médecin - Médecine du travail (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C43 "Médecin - Neurologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C45 "Médecin - Neuro-chirurgie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C47 "Médecin - Neuro-psychiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C51 "Médecin - Pédiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C52 "Médecin - Phoniatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C54 "Médecin - Pneumologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C57 "Médecin - Psychiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C58 "Médecin - Psychiatrie, opt enfant et adolescent (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C60 "Médecin - Médecine physique et réadaptation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C62 "Médecin - Rhumatologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C68 "Médecin - Chirurgie pédiatrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C69 "Médecin - Médecine nucléaire (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C71 "Médecin - Médecine thermale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C72 "Médecin - Génétique médicale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C75 "Médecin - Endocrinologie et Maladies métaboliques (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C76 "Médecin - Orthopédie dento-maxillo-faciale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C83 "Médecin - Chirurgie face et cou (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA01 "Médecin - Addictologie clinique (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA02 "Médecin - Aide médicale urgente (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA03 "Médecin - Allergologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA04 "Médecin - Angéiologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA05 "Médecin - Evaluation et traitement de la douleur (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA06 "Médecin - Gérontologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA07 "Médecin - Hydrologie et climatologie médicales (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA08 "Médecin - Médecine aérospatiale (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA09 "Médecin - Médecine de catastrophe (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA10 "Médecin - Médecine et biologie du sport (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA11 "Médecin - Médecine de travail, prév risques prof (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA12 "Médecin - Médecine pénitentiaire (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA13 "Médecin - Médecine tropicale (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA14 "Médecin - Pratiques médico-judiciaires (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA15 "Médecin - Technologie transfusionnelle (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA16 "Médecin - Toxicomanies et Alcoologies (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM200 "Médecin - Addictologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM201 "Médecin - Allergologie et Immunologie clinique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM202 "Médecin - Andrologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM203 "Médecin - Biochimie hormonale et métabolique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM204 "Médecin - Biologie des agents infectieux (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM205 "Médecin - Biologie moléculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM206 "Médecin - Cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM207 "Médecin - Chirurgie de la face et du cou (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM208 "Médecin - Chirurgie plastique et reconstructrice (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM209 "Médecin - Chirurgie vasculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM210 "Médecin - Cytogénétique humaine (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM211 "Médecin - Dermatopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM212 "Médecin - Foetopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM213 "Médecin - Gériatrie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM214 "Médecin - Hématologie biologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM215 "Médecin - Hématologie maladies du sang (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM216 "Médecin - Hémobiologie-transfusion (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM217 "Médecin - Immunologie et Immunopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM218 "Médecin - Médecine de la reproduction (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM219 "Médecin - Médecine du sport (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM220 "Médecin - Médecine d'urgence (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM221 "Médecin - Médecine légale et Expertises médicales (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM222 "Médecin - Médecine nucléaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM223 "Médecin - Médecine vasculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM224 "Médecin - Néonatalogie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM225 "Médecin - Neuropathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM226 "Médecin - Nutrition (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM227 "Médecin - Orthopédie dento-maxillo-faciale (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM228 "Médecin - Pathologie infect et trop, clin et bio (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM229 "Médecin - Pharmacocinétique et Métabolisme des méd (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM230 "Médecin - Pharmacologie clin et Eval thérapeutiq (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM231 "Médecin - Psychiatrie de l'enfant et de l'ado (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM232 "Médecin - Radiopharmacie et radiobiologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM233 "Médecin - Réanimation médicale (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM234 "Médecin - Toxicologie biologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM235 "Médecin - Médecine de la douleur et Méd palliative (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM236 "Médecin - Cancérologie, opt Trait méd des cancers (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM237 "Médecin - Cancérologie, opt Chir cancérologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM238 "Médecin - Cancérologie, opt Réseaux cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM239 "Médecin - Cancérologie, opt Biologie cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM240 "Médecin - Cancérologie, opt Imagerie cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21 "Pharmacien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/A "Pharmacien titulaire d'officine"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/B "Pharmacien d'entreprise - industrie"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/C "Pharmacien d'entreprise - distribution"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/D "Pharmacien adjoint, remplaçant ou gérant"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/DA "Pharmacien adjoint"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/DM "Pharmacien mutualiste ou minier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/E "Pharmacien d'Outre-Mer"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EA "Pharmacien titulaire d'officine - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EB "Pharmacien d'entreprise - industrie - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EC "Pharmacien d'entreprise - distribution - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/ED "Pharmacien adjoint - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EG "Pharmacien biologiste - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EH "Pharmacien d'un établissement de santé - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/G "Pharmacien biologiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/H "Pharmacien d'établissement de santé"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/M "Pharmacien militaire"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_26 "Audioprothésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_28 "Opticien-Lunetier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_31 "Assistant dentaire"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_32 "Physicien médical"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_35 "Aide-soignant"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_36 "Ambulancier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_37 "Auxiliaire de puériculture"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_38 "Préparateur en pharmacie hospitalière"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_39 "Préparateur en pharmacie"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40 "Chirurgien-Dentiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD01 "Chirurgien-Dentiste - Orthopédie dento-faciale (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD02 "Chirurgien-Dentiste - Chirurgie orale (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD03 "Chirurgien-Dentiste - Médecine bucco-dentaire (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_50 "Sage-Femme"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60 "Infirmier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI01 "Infirmier - Exercice infirmier en pratique avancée pathologies chroniques stabilisées (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI02 "Infirmier - Exercice infirmier en pratique avancée oncologie et hémato-oncologie (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI03 "Infirmier - Exercice infirmier en pratique avancée maladie rénale chronique, dialyse et transplantation rénale (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI05 "Infirmier - Exercice infirmier en pratique avancée urgences (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI04 "Infirmier - Exercice infirmier en pratique avancée santé mentale (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_69 "Infirmier psychiatrique"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_70 "Masseur-Kinésithérapeute"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_80 "Pédicure-Podologue"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_81 "Orthoprothésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_82 "Podo-Orthésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_83 "Orthopédiste-Orthésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_84 "Oculariste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_85 "Epithésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_86 "Technicien de laboratoire médical"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_91 "Orthophoniste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_92 "Orthoptiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_94 "Ergothérapeute"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_95 "Diététicien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_96 "Psychomotricien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_98 "Manipulateur ERM"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_10 "Médecin en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_21 "Pharmacien en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_40 "Chirurgien-Dentiste en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_50 "Sage-Femme en formation"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R95-UsagerTitre#97 "Conseiller en génétique"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R94-ProfessionSocial#42 "Auxiliaire de vie sociale"
* $TRE-R94-ProfessionSocial#43 "Technicien de l'intervention sociale et familiale"
* $TRE-R94-ProfessionSocial#44 "Conseiller en économie sociale et familiale"
* $TRE-R94-ProfessionSocial#45 "Médiateur familial"
* $TRE-R94-ProfessionSocial#46 "Assistant familial"
* $TRE-R94-ProfessionSocial#47 "Aide médico-psychologique (AMP)"
* $TRE-R94-ProfessionSocial#48 "Moniteur éducateur"
* $TRE-R94-ProfessionSocial#49 "Educateur de jeunes enfants"
* $TRE-R94-ProfessionSocial#51 "Educateur spécialisé"
* $TRE-R94-ProfessionSocial#52 "Educateur technique spécialisé"
* $TRE-R94-ProfessionSocial#53 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie (officine)"
* $TRE-R85-RolePriseCharge#318 "Auxiliaire de vie sociale"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#323 "Aide médico-psychologique (AMP)"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#331 "Secrétaire médicale"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#350 "Aide à domicile"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE-R85-RolePriseCharge#352 "Autre salarié de la structure sociale"
* $TRE-R85-RolePriseCharge#353 "Membre de l'équipe de soins"