ValueSet: JDV_J75_TypeAutorisation_RASS
Id: JDV-J75-TypeAutorisation-RASS
Description: "Type d'autorisation d'exercice pour accès à l'exercice de la profession du RASS"
* ^meta.versionId = "11"
* ^meta.lastUpdated = "2026-07-06T19:06:55.651+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J75-TypeAutorisation-RASS/FHIR/JDV-J75-TypeAutorisation-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.143"
* ^version = "20250523120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-05-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R17-TypeAutorisation#AM00 "Autre type d'autorisation"
* $TRE-R17-TypeAutorisation#AM01 "Autorisation de plein exercice"
* $TRE-R17-TypeAutorisation#AM02 "Autorisation ministérielle d'exercice en qualité de PAC"
* $TRE-R17-TypeAutorisation#AM03 "Autorisation d'exercice limité à un seul hôpital"
* $TRE-R17-TypeAutorisation#AM04 "Autorisation Propharmacie"
* $TRE-R17-TypeAutorisation#AM05 "Directeur de laboratoire (scientifique, médecin, pharmacien)"
* $TRE-R17-TypeAutorisation#AM08 "Pays avec convention inter-état"
* $TRE-R17-TypeAutorisation#AM09 "Code de la santé"
* $TRE-R17-TypeAutorisation#AM10 "Traité de Rome"
* $TRE-R17-TypeAutorisation#AM11 "Nombre par arrête (NPA art L 4111-2 1 et 1bis du CSP)"
* $TRE-R17-TypeAutorisation#AM12 "Loi Hôpital, patients, santé et territoires (HPST) du 21 Juillet 2009"
* $TRE-R17-TypeAutorisation#AM13 "Hôpital Américain exclusivement"
* $TRE-R17-TypeAutorisation#AM14 "Arrangement France-Québec (art L 4111-3-1 CSP)"
* $TRE-R17-TypeAutorisation#AM15 "Article L 4131-1-1 du CSP"
* $TRE-R17-TypeAutorisation#AM16 "Arabie Saoudite décret n°2012-1123 du 03-10-2012"
* $TRE-R17-TypeAutorisation#AM17 "Emirats Arabes Unis décret n°2012-863 du 5-07-2012"
* $TRE-R17-TypeAutorisation#AMGP "En cours de validation au Guichet principal"
* $TRE-R17-TypeAutorisation#AM18 "Autorisation de l'Agence régionale de santé (ARS)"
* $TRE-R17-TypeAutorisation#AM20 "Autorisation de la Direction régionale de l'économie, de l'emploi, du travail et des solidarités (DREETS)"
* $TRE-R17-TypeAutorisation#AM21 "Autorisation DGARS Guadeloupe, Guyane, Martinique ou préfet SPM (art. L4131-5 et L4221-14-3)"
* $TRE-R17-TypeAutorisation#AM22 "Agrément de la Caisse Régionale d'Assurance Maladie"
* $TRE-R17-TypeAutorisation#AM23 "Agrément du Ministère des anciens combattants"
* $TRE-R17-TypeAutorisation#AM24 "Exerce comme technicien de laboratoire avant le 08/11/1976"
* $TRE-R17-TypeAutorisation#AM25 "Exerce comme technicien de laboratoire au 29/11/1997"
* $TRE-R17-TypeAutorisation#AM26 "Exerce comme technicien de laboratoire au 30/05/2013"
* $TRE-R17-TypeAutorisation#AM27 "Autorisation d'exercice pour diplôme de l'UE/EEE"
* $TRE-R17-TypeAutorisation#AM28 "Autorisation d'user du titre d'Ostéopathe"
* $TRE-R17-TypeAutorisation#AM29 "Autorisation d'user du titre de diététicien, décision administrative en 1986"
* $TRE-R17-TypeAutorisation#AM30 "Autorisation d'user du titre de diététicien, emploi permanent en 1986"
* $TRE-R17-TypeAutorisation#AM31 "Autorisation d'exercice de psychologue diplôme étranger"
* $TRE-R17-TypeAutorisation#AM32 "Autorisation préfectorale d'exercice de psychologue décret 90-259"
* $TRE-R17-TypeAutorisation#AM33 "Docteur en médecine spécialité psychiatrie"
* $TRE-R17-TypeAutorisation#AM34 "Diplôme, certificat ou titre permettant d'exercer la médecine en France"
* $TRE-R17-TypeAutorisation#AM35 "Autorisation d'user du titre de Chiropraxie"
* $TRE-R17-TypeAutorisation#AM36 "Autorisation d'exercice d'épithésiste pour chirurgien-dentiste"
* $TRE-R17-TypeAutorisation#AM37 "Autorisation d'exercice d'épithésiste pour médecin stomatologue ou chirurgie maxillo-faciale"
* $TRE-R17-TypeAutorisation#AM38 "Arrêté de Nomination de Manipulateur d'Electro-Radiologie du Secteur Public"
* $TRE-R17-TypeAutorisation#AM39 "Docteur en médecine + formation + stage"
* $TRE-R17-TypeAutorisation#AM40 "Autorisation d'exercice temporaire Nouvelle-Calédonie (loi du pays n°2023-8)"
* $TRE-R17-TypeAutorisation#AM41 "Agrément de radiophysicien avant le 28/11/2004"
* $TRE-R17-TypeAutorisation#AM42 "Autorisation d'user du titre de Psychothérapeute"