ValueSet: JDV_J232_Competence_ROR
Id: JDV-J232-Competence-ROR
Description: "Compétence"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:06:06.002+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J232-Competence-ROR/FHIR/JDV-J232-Competence-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.63"
* ^version = "20240628120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-06-28T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R39-Competence#C01 "Anatomie et Cytologie pathologiques humaines (C)"
* $TRE-R39-Competence#C03 "Anesthésie-réanimation (C)"
* $TRE-R39-Competence#C05 "Médecine appliquée aux sports (C)"
* $TRE-R39-Competence#C07 "Cardiologie (C)"
* $TRE-R39-Competence#C09 "Chirurgie plastique, reconstructrice et esthétique (C)"
* $TRE-R39-Competence#C10 "Chirurgie maxillo-faciale (C)"
* $TRE-R39-Competence#C11 "Chirurgie thoracique (C)"
* $TRE-R39-Competence#C12 "Chirurgie orthopédique (C)"
* $TRE-R39-Competence#C13 "Urologie (C)"
* $TRE-R39-Competence#C15 "Dermato-vénéréologie (C)"
* $TRE-R39-Competence#C20 "Hémobiologie (C)"
* $TRE-R39-Competence#C23 "Gynécologie médicale et Obstétrique (C)"
* $TRE-R39-Competence#C25 "Gynécologie médicale (C)"
* $TRE-R39-Competence#C27 "Obstétrique (C)"
* $TRE-R39-Competence#C29 "Maladies de l'appareil digestif (C)"
* $TRE-R39-Competence#C30 "Néphrologie (C)"
* $TRE-R39-Competence#C31 "Médecine exotique (C)"
* $TRE-R39-Competence#C33 "Allergologie (C)"
* $TRE-R39-Competence#C34 "Angéiologie (C)"
* $TRE-R39-Competence#C35 "Cancérologie (C)"
* $TRE-R39-Competence#C36 "Diabétologie-nutrition (C)"
* $TRE-R39-Competence#C37 "Endocrinologie (C)"
* $TRE-R39-Competence#C38 "Maladies du sang (C)"
* $TRE-R39-Competence#C39 "Réanimation (C)"
* $TRE-R39-Competence#C40 "Médecine légale (C)"
* $TRE-R39-Competence#C41 "Médecine du travail (C)"
* $TRE-R39-Competence#C43 "Neurologie (C)"
* $TRE-R39-Competence#C45 "Neuro-chirurgie (C)"
* $TRE-R39-Competence#C47 "Neuro-psychiatrie (C)"
* $TRE-R39-Competence#C51 "Pédiatrie (C)"
* $TRE-R39-Competence#C52 "Phoniatrie (C)"
* $TRE-R39-Competence#C54 "Pneumologie (C)"
* $TRE-R39-Competence#C57 "Psychiatrie (C)"
* $TRE-R39-Competence#C58 "Psychiatrie, option enfant et adolescent (C)"
* $TRE-R39-Competence#C60 "Médecine physique et de réadaptation (C)"
* $TRE-R39-Competence#C62 "Rhumatologie (C)"
* $TRE-R39-Competence#C68 "Chirurgie pédiatrique (C)"
* $TRE-R39-Competence#C69 "Médecine nucléaire (C)"
* $TRE-R39-Competence#C71 "Médecine thermale (C)"
* $TRE-R39-Competence#C72 "Génétique médicale (C)"
* $TRE-R39-Competence#C75 "Endocrinologie et Maladies métaboliques (C)"
* $TRE-R39-Competence#C76 "Orthopédie dento-maxillo-faciale (C)"
* $TRE-R39-Competence#C83 "Chirurgie de la face et du cou (C)"