ValueSet: JDV_J55_CategorieEG_ROR
Id: JDV-J55-CategorieEG-ROR
Description: "Catégories d'établissements FINESS ou hors FINESS et secteurs d'activité des cabinets"
* ^meta.versionId = "22"
* ^meta.lastUpdated = "2026-07-06T19:06:41.659+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-01-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J55-CategorieEG-ROR/FHIR/JDV-J55-CategorieEG-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.65"
* ^version = "20260505120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-05-05T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R66-CategorieEtablissement#101 "Centre hospitalier régional (CHR)"
* $TRE-R66-CategorieEtablissement#106 "Centre hospitalier (ex Hôpital local)"
* $TRE-R66-CategorieEtablissement#109 "Etablissement de santé privé autorisé en soins de suite et de réadaptation (SSR)"
* $TRE-R66-CategorieEtablissement#114 "Hôpital des armées"
* $TRE-R66-CategorieEtablissement#115 "Etablissement de soins du Service de santé des armées (SSA)"
* $TRE-R66-CategorieEtablissement#122 "Etablissement de soins obstétriques et chirurgico-gynécologiques"
* $TRE-R66-CategorieEtablissement#124 "Centre de santé"
* $TRE-R66-CategorieEtablissement#126 "Etablissement thermal"
* $TRE-R66-CategorieEtablissement#127 "Hospitalisation à domicile (HAD)"
* $TRE-R66-CategorieEtablissement#128 "Etablissement de soins chirurgicaux"
* $TRE-R66-CategorieEtablissement#129 "Etablissement de soins médicaux"
* $TRE-R66-CategorieEtablissement#130 "Centre de soins médicaux"
* $TRE-R66-CategorieEtablissement#131 "Centre de lutte contre cancer"
* $TRE-R66-CategorieEtablissement#132 "Etablissement de transfusion sanguine"
* $TRE-R66-CategorieEtablissement#141 "Centre de dialyse"
* $TRE-R66-CategorieEtablissement#142 "Dispensaire antituberculeux"
* $TRE-R66-CategorieEtablissement#143 "Centre de vaccination BCG"
* $TRE-R66-CategorieEtablissement#146 "Structure d'alternative à la dialyse en centre"
* $TRE-R66-CategorieEtablissement#156 "Centre médico-psychologique (CMP)"
* $TRE-R66-CategorieEtablissement#161 "Maison de santé pour maladies mentales"
* $TRE-R66-CategorieEtablissement#165 "Appartement de coordination thérapeutique (ACT)"
* $TRE-R66-CategorieEtablissement#166 "Centre Parents-Enfants de moins de 3 ans"
* $TRE-R66-CategorieEtablissement#172 "Pouponnière à caractère social"
* $TRE-R66-CategorieEtablissement#175 "Foyer de l'enfance"
* $TRE-R66-CategorieEtablissement#176 "Village d'enfants"
* $TRE-R66-CategorieEtablissement#177 "Maison d'enfants à caractère social"
* $TRE-R66-CategorieEtablissement#178 "Centre d'accueil et d'accompagnement à la réduction des risques pour usagers de drogues (CAARUD)"
* $TRE-R66-CategorieEtablissement#180 "Lits halte soins santé (LHSS)"
* $TRE-R66-CategorieEtablissement#182 "Service d'éducation spéciale et de soins à domicile (SESSAD)"
* $TRE-R66-CategorieEtablissement#183 "Institut médico-éducatif (IME)"
* $TRE-R66-CategorieEtablissement#186 "Institut thérapeutique éducatif et pédagogique (ITEP)"
* $TRE-R66-CategorieEtablissement#188 "Etablissement pour enfants ou adolescents polyhandicapés"
* $TRE-R66-CategorieEtablissement#189 "Centre médico-psycho-pédagogique (CMPP)"
* $TRE-R66-CategorieEtablissement#190 "Centre action médico-sociale précoce (CAMSP)"
* $TRE-R66-CategorieEtablissement#192 "Institut d'éducation motrice"
* $TRE-R66-CategorieEtablissement#194 "Institut pour déficients visuels"
* $TRE-R66-CategorieEtablissement#195 "Institut pour déficients auditifs"
* $TRE-R66-CategorieEtablissement#196 "Institut d'éducation sensorielle sourd-aveugle"
* $TRE-R66-CategorieEtablissement#197 "Centre de soins d'accompagnement et de prévention en addictologie (CSAPA)"
* $TRE-R66-CategorieEtablissement#198 "Établissement et Service de Préorientation"
* $TRE-R66-CategorieEtablissement#202 "Résidences autonomie"
* $TRE-R66-CategorieEtablissement#207 "Centre de jour pour personnes âgées"
* $TRE-R66-CategorieEtablissement#209 "Service autonomie aide et soins (SAAS)"
* $TRE-R66-CategorieEtablissement#213 "Lits d'accueil médicalisés (L.A.M.)"
* $TRE-R66-CategorieEtablissement#214 "Centre d'hébergement et de réinsertion sociale (CHRS)"
* $TRE-R66-CategorieEtablissement#216 "Résidence Hôtelière à Vocation Sociale (R.H.V.S)"
* $TRE-R66-CategorieEtablissement#219 "Autre centre d'accueil"
* $TRE-R66-CategorieEtablissement#221 "Bureau d'aide psychologique universitaire (BAPU)"
* $TRE-R66-CategorieEtablissement#223 "Protection maternelle et infantile (PMI)"
* $TRE-R66-CategorieEtablissement#224 "Etablissement de consultation pré et post-natale"
* $TRE-R66-CategorieEtablissement#228 "Centre de santé sexuelle"
* $TRE-R66-CategorieEtablissement#230 "Etablissement consultation protection infantile"
* $TRE-R66-CategorieEtablissement#231 "Espaces de vie affective, relationnelle et sexuelle (EVARS)"
* $TRE-R66-CategorieEtablissement#236 "Service de placement familial (SPF)"
* $TRE-R66-CategorieEtablissement#238 "Centre d'accueil familial spécialisé"
* $TRE-R66-CategorieEtablissement#241 "Établissement de Placement"
* $TRE-R66-CategorieEtablissement#242 "Service d'Activité de Jour"
* $TRE-R66-CategorieEtablissement#246 "Etablissement et service d'aide par le travail (ESAT)"
* $TRE-R66-CategorieEtablissement#247 "Entreprise adaptée"
* $TRE-R66-CategorieEtablissement#249 "Établissement et Service de Réadaptation Professionnelle"
* $TRE-R66-CategorieEtablissement#252 "Foyer d'hébergement d'adultes handicapés"
* $TRE-R66-CategorieEtablissement#253 "Foyer d'accueil polyvalent pour adultes handicapés"
* $TRE-R66-CategorieEtablissement#255 "Maison d'accueil spécialisée (MAS)"
* $TRE-R66-CategorieEtablissement#256 "Foyer de travailleurs migrants non transformé en résidence sociale"
* $TRE-R66-CategorieEtablissement#257 "Foyers de jeunes travailleurs"
* $TRE-R66-CategorieEtablissement#258 "Maison relais, Pension de famille"
* $TRE-R66-CategorieEtablissement#259 "Autres résidences sociales"
* $TRE-R66-CategorieEtablissement#266 "Dispensaire antivénérien"
* $TRE-R66-CategorieEtablissement#267 "Dispensaire antihansénien"
* $TRE-R66-CategorieEtablissement#268 "Centre médico-scolaire"
* $TRE-R66-CategorieEtablissement#269 "Centre de médecine universitaire"
* $TRE-R66-CategorieEtablissement#270 "Centre de médecine sportive"
* $TRE-R66-CategorieEtablissement#271 "Maison d'accueil Hospitalière"
* $TRE-R66-CategorieEtablissement#286 "Service de prévention spécialisée"
* $TRE-R66-CategorieEtablissement#292 "Centre hospitalier spécialisé de lutte contre les maladies mentales"
* $TRE-R66-CategorieEtablissement#294 "Centre de consultations cancer"
* $TRE-R66-CategorieEtablissement#295 "Service AEMO et AED"
* $TRE-R66-CategorieEtablissement#300 "Ecole formant aux professions sanitaires"
* $TRE-R66-CategorieEtablissement#330 "Ecole formant aux professions sociales"
* $TRE-R66-CategorieEtablissement#340 "Service mandataire judiciaire à la protection des majeurs"
* $TRE-R66-CategorieEtablissement#341 "Service dédié aux mesures d'accompagnement social personnalisé"
* $TRE-R66-CategorieEtablissement#342 "Service d'information et de soutien aux tuteurs familiaux"
* $TRE-R66-CategorieEtablissement#344 "Service délégué aux prestations familiales"
* $TRE-R66-CategorieEtablissement#347 "Centre d'examens de santé"
* $TRE-R66-CategorieEtablissement#354 "Service de soins infirmiers à domicile (SSIAD)"
* $TRE-R66-CategorieEtablissement#355 "Centre hospitalier (CH)"
* $TRE-R66-CategorieEtablissement#362 "Etablissement de soins longue durée"
* $TRE-R66-CategorieEtablissement#365 "Etablissement de soins pluridisciplinaire"
* $TRE-R66-CategorieEtablissement#366 "Atelier thérapeutique"
* $TRE-R66-CategorieEtablissement#370 "Etablissement Expérimental pour personnes handicapées"
* $TRE-R66-CategorieEtablissement#374 "Ecole nationale de santé publique (ENSP)"
* $TRE-R66-CategorieEtablissement#377 "Etablissement expérimental pour enfance handicapée"
* $TRE-R66-CategorieEtablissement#378 "Etablissement expérimental enfance protégée"
* $TRE-R66-CategorieEtablissement#379 "Etablissement expérimental pour adultes handicapés"
* $TRE-R66-CategorieEtablissement#380 "Etablissement expérimental autres adultes"
* $TRE-R66-CategorieEtablissement#381 "Etablissement expérimental pour personnes âgées"
* $TRE-R66-CategorieEtablissement#382 "Foyer de vie pour adultes handicapés"
* $TRE-R66-CategorieEtablissement#390 "Etablissement d'accueil temporaire d'enfants handicapés"
* $TRE-R66-CategorieEtablissement#395 "Etablissement d'accueil temporaire pour adultes handicapés"
* $TRE-R66-CategorieEtablissement#396 "Foyer d'hébergement pour enfants et adolescents handicapés"
* $TRE-R66-CategorieEtablissement#402 "Jardin d'enfants spécialisé"
* $TRE-R66-CategorieEtablissement#411 "Intermédiaire de placement social"
* $TRE-R66-CategorieEtablissement#412 "Appartement thérapeutique"
* $TRE-R66-CategorieEtablissement#415 "Service médico-psychologique régional (SMPR)"
* $TRE-R66-CategorieEtablissement#422 "Traitements spécialisés à domicile"
* $TRE-R66-CategorieEtablissement#425 "Centre d'accueil thérapeutique à temps partiel (CATTP)"
* $TRE-R66-CategorieEtablissement#426 "Syndicat inter hospitalier (SIH)"
* $TRE-R66-CategorieEtablissement#430 "Centre postcure pour malades mentaux"
* $TRE-R66-CategorieEtablissement#433 "Etablissement sanitaire des prisons"
* $TRE-R66-CategorieEtablissement#436 "Ecoles formant aux professions sanitaires et sociales"
* $TRE-R66-CategorieEtablissement#437 "Foyer d'accueil médicalisé pour adultes handicapés (FAM)"
* $TRE-R66-CategorieEtablissement#438 "Centre de médecine collective"
* $TRE-R66-CategorieEtablissement#439 "Centre de santé polyvalent"
* $TRE-R66-CategorieEtablissement#440 "Service d'Investigation Educative"
* $TRE-R66-CategorieEtablissement#441 "Service d'Intervention Educative en Milieu Ouvert"
* $TRE-R66-CategorieEtablissement#442 "Centre provisoire d'hébergement"
* $TRE-R66-CategorieEtablissement#443 "Centre d'accueil de demandeurs d'asile (CADA)"
* $TRE-R66-CategorieEtablissement#444 "Centre de crise et d'accueil permanent"
* $TRE-R66-CategorieEtablissement#445 "Service d'accompagnement médico-social pour adultes handicapés"
* $TRE-R66-CategorieEtablissement#446 "Service d'accompagnement à la vie sociale (SAVS)"
* $TRE-R66-CategorieEtablissement#448 "Etablissement d'Accueil Médicalisé en tout ou partie personnes handicapées"
* $TRE-R66-CategorieEtablissement#449 "Etablissement d'Accueil Non Médicalisé pour personnes handicapées"
* $TRE-R66-CategorieEtablissement#460 "Service autonomie aide (SAA)"
* $TRE-R66-CategorieEtablissement#461 "Centres de ressources SAI (sans aucune indication)"
* $TRE-R66-CategorieEtablissement#462 "Lieux de Vie et d'Accueil"
* $TRE-R66-CategorieEtablissement#463 "Centre local d'information et de coordination de personnes âgées"
* $TRE-R66-CategorieEtablissement#464 "Unité d'évaluation, de réentraînement et d'orientation sociale et-ou professionnelle"
* $TRE-R66-CategorieEtablissement#500 "Etablissement d'hébergement pour personnes âgées dépendantes"
* $TRE-R66-CategorieEtablissement#501 "EHPA percevant des crédits d'assurance maladie"
* $TRE-R66-CategorieEtablissement#502 "EHPA ne percevant pas des crédits d'assurance maladie"
* $TRE-R66-CategorieEtablissement#603 "Maison de santé (L6223-3)"
* $TRE-R66-CategorieEtablissement#604 "Communauté Professionnelle Territoriale de Santé (CPTS)"
* $TRE-R66-CategorieEtablissement#606 "Dispositif d'appui à la coordination (DAC)"
* $TRE-R66-CategorieEtablissement#608 "Equipe mobile médico-sociale précarité (EMMSP)"
* $TRE-R66-CategorieEtablissement#609 "Maison Départementale pour Personnes Handicapées (MDPH)"
* $TRE-R66-CategorieEtablissement#610 "Laboratoire d'analyses"
* $TRE-R66-CategorieEtablissement#611 "Laboratoire de biologie médicale (LBM)"
* $TRE-R66-CategorieEtablissement#612 "Autre laboratoire de biologie médicale sans FSE"
* $TRE-R66-CategorieEtablissement#614 "Dispositif Spécifique Régional du Cancer (DSRC)"
* $TRE-R66-CategorieEtablissement#616 "Services de Prévention et de Santé au Travail (SPST)"
* $TRE-R66-CategorieEtablissement#617 "Lieu de soins non programmés"
* $TRE-R66-CategorieEtablissement#618 "Autre structure de soins non programmés (SNP)"
* $TRE-R66-CategorieEtablissement#620 "Pharmacie d'officine"
* $TRE-R66-CategorieEtablissement#624 "Laboratoire pharmaceutique préparant et délivrant des allergènes"
* $TRE-R66-CategorieEtablissement#627 "Propharmacie"
* $TRE-R66-CategorieEtablissement#628 "Pharmacie minière"
* $TRE-R66-CategorieEtablissement#629 "Pharmacie mutualiste"
* $TRE-R66-CategorieEtablissement#630 "Installation autonome de chirurgie esthétique"
* $TRE-R66-CategorieEtablissement#631 "Maisons de naissance"
* $TRE-R66-CategorieEtablissement#632 "Structure Dispensatrice à domicile d'Oxygène à usage médical"
* $TRE-R66-CategorieEtablissement#633 "Structure Expérimentale en Santé"
* $TRE-R66-CategorieEtablissement#636 "Centre de soins et de prévention"
* $TRE-R66-CategorieEtablissement#637 "Centre de Lutte Antituberculeuse (CLAT)"
* $TRE-R66-CategorieEtablissement#638 "Centre gratuit d'information de dépistage et de diagnostic (CeGIDD)"
* $TRE-R66-CategorieEtablissement#639 "Sociétés de téléconsultation (STLC)"
* $TRE-R66-CategorieEtablissement#640 "Service d'aide et d'accompagnement à domicile aux familles (SAADF)"
* $TRE-R66-CategorieEtablissement#642 "Services départementaux d'incendie et de secours"
* $TRE-R66-CategorieEtablissement#643 "Service d'évaluation de la minorité et de l'isolement pour les personnes se déclarant mineures (SEMIPM)"
* $TRE-R66-CategorieEtablissement#644 "Etablissement de mise à l'abri pour les personnes se déclarant mineures non accompagnées (EMAMNA)"
* $TRE-R66-CategorieEtablissement#641 "Antenne de Pharmacie d'officine"
* $TRE-R66-CategorieEtablissement#645 "Centre de Vaccination"
* $TRE-R66-CategorieEtablissement#646 "Centre de Vaccination Internationale"
* $TRE-R66-CategorieEtablissement#647 "Equipe de Soins Spécialisés"
* $TRE-R66-CategorieEtablissement#648 "Structure qui contribue au Service d'Accès aux Soins"
* $TRE-R66-CategorieEtablissement#649 "Centre de santé et de médiation en santé sexuelle"
* $TRE-R66-CategorieEtablissement#650 "Dispositifs Spécifiques Régionaux en périnatalité"
* $TRE-R66-CategorieEtablissement#695 "Groupement de coopération sanitaire de moyens - Exploitant"
* $TRE-R66-CategorieEtablissement#696 "Groupement de coopération sanitaire de moyens"
* $TRE-R66-CategorieEtablissement#697 "Groupement de coopération sanitaire, Etablissement de santé"
* $TRE-R66-CategorieEtablissement#698 "Autre établissement relevant de la loi hospitalière"
* $TRE-R66-CategorieEtablissement#699 "Entité ayant autorisation"
* $TRE-R66-CategorieEtablissement#700 "Maison sport-santé"
* $TRE-R66-CategorieEtablissement#701 "Maison des adolescents (MDA)"
* $TRE-R66-CategorieEtablissement#702 "Point Accueil Ecoute Jeunes (PAEJ)"
* $TRE-R66-CategorieEtablissement#703 "Espace Santé Jeunes (ESJ)"
* $TRE-R66-CategorieEtablissement#704 "Autre service territorial"
* $TRE-R66-CategorieEtablissement#705 "Groupe d’Entraide Mutuelle (GEM)"
* $TRE-R02-SecteurActivite#SA05 "Centre de santé"
* $TRE-R02-SecteurActivite#SA07 "Cabinet individuel"
* $TRE-R02-SecteurActivite#SA08 "Cabinet de groupe"
* $TRE-R02-SecteurActivite#SA09 "Exercice en société"