ValueSet: JDV_J134_FormeActivite_RASS
Id: JDV-J134-FormeActivite-RASS
Description: "Type d'organisation de prise en charge du RASS"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:05:06.306+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-11-27T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J134-FormeActivite-RASS/FHIR/JDV-J134-FormeActivite-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.220"
* ^version = "20240628120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-06-28T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R276-FormeActivite#00 "Pas de forme"
* $TRE-R276-FormeActivite#01 "Hospitalisation complète (24 heures consécutives ou plus)"
* $TRE-R276-FormeActivite#02 "Hospitalisation à temps partiel de jour ou de nuit"
* $TRE-R276-FormeActivite#03 "Hospitalisation à temps partiel de jour"
* $TRE-R276-FormeActivite#04 "Hospitalisation à temps partiel de nuit"
* $TRE-R276-FormeActivite#05 "Hospitalisation à domicile (au domicile du patient)"
* $TRE-R276-FormeActivite#06 "Anesthésie ambulatoire"
* $TRE-R276-FormeActivite#07 "Chirurgie ambulatoire"
* $TRE-R276-FormeActivite#08 "Consultation extérieure indifférenciée"
* $TRE-R276-FormeActivite#09 "Placement familial thérapeutique"
* $TRE-R276-FormeActivite#10 "Appartement thérapeutique"
* $TRE-R276-FormeActivite#11 "Centre postcure"
* $TRE-R276-FormeActivite#12 "Centre de crise"
* $TRE-R276-FormeActivite#13 "Saisonnier"
* $TRE-R276-FormeActivite#14 "Non saisonnier"
* $TRE-R276-FormeActivite#15 "Forme non précisée"
* $TRE-R276-FormeActivite#20 "Personne décédée présentant un arrêt cardiaque et respiratoire persistant"
* $TRE-R276-FormeActivite#21 "Personne décédée assist par ventil mécanique avec une fonct hémodynamique"
* $TRE-R276-FormeActivite#22 "Personne vivante"
* $TRE-R276-FormeActivite#24 "Centre correspondant"
* $TRE-R276-FormeActivite#25 "Centre de référence"
* $TRE-R276-FormeActivite#27 "Consultations gériatriques avancées"
* $TRE-R276-FormeActivite#28 "Equipe mobile"
* $TRE-R276-FormeActivite#30 "Centre"
* $TRE-R276-FormeActivite#31 "Centre ressources"
* $TRE-R276-FormeActivite#32 "Centre spécialisé"
* $TRE-R276-FormeActivite#33 "CMP"
* $TRE-R276-FormeActivite#34 "Consultations"
* $TRE-R276-FormeActivite#35 "Consultations mémoire"
* $TRE-R276-FormeActivite#36 "Equipe de liaison"
* $TRE-R276-FormeActivite#37 "H.A.D."
* $TRE-R276-FormeActivite#38 "Ligne d'astreinte PDSES Nuit totale"
* $TRE-R276-FormeActivite#39 "Ligne d'astreinte PDSES Première partie de nuit"
* $TRE-R276-FormeActivite#40 "Ligne de garde PDSES Nuit totale"
* $TRE-R276-FormeActivite#41 "Pôle d'évaluation"
* $TRE-R276-FormeActivite#42 "Unité d'hébergement renforcée (UHR)"
* $TRE-R276-FormeActivite#44 "Consultations d'évaluation pluri professionnelles post AVC"
* $TRE-R276-FormeActivite#47 "Ligne de garde PDSES première partie de nuit"
* $TRE-R276-FormeActivite#48 "Ligne d'astreinte PDSES Week-end et jours fériés"
* $TRE-R276-FormeActivite#49 "Ligne d'astreinte PDSES Première partie de nuit en semaine (Lundi au vendredi)"