ValueSet: JDV_J216_DroitExerciceCompl_ROR
Id: JDV-J216-DroitExerciceCompl-ROR
Description: "Droit d'exercice complémentaire"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:05:57.824+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J216-DroitExerciceCompl-ROR/FHIR/JDV-J216-DroitExerciceCompl-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.48"
* ^version = "20220826120000"
* ^status = #active
* ^experimental = false
* ^date = "2022-08-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R97-DroitExerciceCompl#DEC01 "Addictologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC02 "Allergologie et Immunologie clinique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC03 "Andrologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC04 "Cancérologie, option traitements médicaux des cancers (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC05 "Cancérologie, option chirurgie cancérologique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC06 "Cancérologie, option réseaux de cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC07 "Cancérologie, option biologie en cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC08 "Cancérologie, option imagerie en cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC09 "Dermatopathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC10 "Foetopathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC11 "Hémobiologie et Transfusion (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC12 "Médecine de la douleur et Médecine palliative (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC13 "Médecine de la reproduction (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC14 "Médecine d'urgence (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC15 "Médecine du sport (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC16 "Médecine légale et Expertises médicales (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC17 "Médecine vasculaire (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC18 "Néonatologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC19 "Neuropathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC20 "Nutrition (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC21 "Orthopédie dento-maxillo-faciale (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC22 "Pathologie infectieuse et tropicale, clinique et biologique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC23 "Pharmacologie clinique et Evaluation des thérapeutiques (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC24 "Psychiatrie de l'enfant et de l'adolescent (DEC)"