ValueSet: JDV_J259_ModeFixationTarifaire_RASS
Id: JDV-J259-ModeFixationTarifaire-RASS
Description: "Mode de fixation tarifaire du RASS"
* ^meta.versionId = "4"
* ^meta.lastUpdated = "2026-07-06T19:06:23.937+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2024-09-27T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J259-ModeFixationTarifaire-RASS/FHIR/JDV-J259-ModeFixationTarifaire-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.283"
* ^version = "20251222120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-12-22T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R74-ModeFixationTarifaire#01 "Etablissement Tarif Libre"
* $TRE-R74-ModeFixationTarifaire#02 "Autorité Ministérielle"
* $TRE-R74-ModeFixationTarifaire#03 "ARS établissements publics de santé dotation globale"
* $TRE-R74-ModeFixationTarifaire#04 "ARS établissements PSPH dotation globale"
* $TRE-R74-ModeFixationTarifaire#05 "ARS établissements médico-sociaux non financés par dotation globale"
* $TRE-R74-ModeFixationTarifaire#06 "Tarif d'autorité"
* $TRE-R74-ModeFixationTarifaire#07 "ARS établissements de santé non financés par dotation globale"
* $TRE-R74-ModeFixationTarifaire#08 "Président du Conseil Départemental ou métropole"
* $TRE-R74-ModeFixationTarifaire#09 "ARS PCD mixte (2 arrêtés), habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#10 "Autorité Conjointe Préfet ou ARS/PCD ou métropole (1 arrêté)"
* $TRE-R74-ModeFixationTarifaire#11 "Tarifs ARS, PCD, hébergement libre"
* $TRE-R74-ModeFixationTarifaire#14 "Organismes Nationaux de Sécurité Sociale"
* $TRE-R74-ModeFixationTarifaire#15 "ARS privé hors PSPH sous dotation globale"
* $TRE-R74-ModeFixationTarifaire#17 "Autorité mixte ARS PCD dotation globale"
* $TRE-R74-ModeFixationTarifaire#21 "ARS PCD mixte, Accueil de jour PA, HAS"
* $TRE-R74-ModeFixationTarifaire#22 "Autorité mixte ARS PCD ESLD tripartite DG global"
* $TRE-R74-ModeFixationTarifaire#23 "Autorité mixte ARS PCD ESLD tripartite DG partielle"
* $TRE-R74-ModeFixationTarifaire#25 "ARS PCD mixte, Accueil de jour PA, nHAS, hébergement libre"
* $TRE-R74-ModeFixationTarifaire#30 "Préfet de région établissements et services sociaux"
* $TRE-R74-ModeFixationTarifaire#31 "Président Conseil Départemental-Subvention"
* $TRE-R74-ModeFixationTarifaire#32 "Echelle tarifaire publique"
* $TRE-R74-ModeFixationTarifaire#33 "Echelle tarifaire privée"
* $TRE-R74-ModeFixationTarifaire#34 "ARS - DG dotation globale"
* $TRE-R74-ModeFixationTarifaire#35 "Préfet de département Subvention"
* $TRE-R74-ModeFixationTarifaire#36 "Tarifs conventionnels assurance maladie"
* $TRE-R74-ModeFixationTarifaire#38 "Régime spécial de prévoyance"
* $TRE-R74-ModeFixationTarifaire#40 "ARS-PCD, Tarif global, habilité aide sociale, recours PUI"
* $TRE-R74-ModeFixationTarifaire#41 "ARS-PCD, Tarif global, habilité aide sociale sans PUI"
* $TRE-R74-ModeFixationTarifaire#42 "ARS-PCD, Tarif global, non habilité aide sociale, recours PUI"
* $TRE-R74-ModeFixationTarifaire#43 "ARS-PCD, Tarif global, non habilité aide sociale sans PUI"
* $TRE-R74-ModeFixationTarifaire#44 "ARS-PCD, Tarif partiel, habilité aide sociale, recours PUI"
* $TRE-R74-ModeFixationTarifaire#45 "ARS-PCD, Tarif partiel, habilité aide sociale sans PUI"
* $TRE-R74-ModeFixationTarifaire#46 "ARS-PCD, Tarif partiel, non habilité aide sociale, recours PUI"
* $TRE-R74-ModeFixationTarifaire#47 "ARS-PCD, Tarif partiel, non habilité aide sociale sans PUI"
* $TRE-R74-ModeFixationTarifaire#48 "ARS-PCD, EHPA, dotation globale de soins, habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#49 "ARS-PCD, EHPA, dotation globale de soins, non habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#50 "ARS-PCD, PUV, forfait soins, habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#51 "ARS-PCD, PUV, forfait soins, non habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#52 "ARS-PCD, LF, forfait soins, habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#53 "ARS-PCD, LF, forfait soins, non habilité aide sociale"
* $TRE-R74-ModeFixationTarifaire#54 "Tarif AM - Services de Soins Infirmiers A Domicile"
* $TRE-R74-ModeFixationTarifaire#55 "ARS-PCD, PUV, convention SSIAD, non habilité à l'aide social"
* $TRE-R74-ModeFixationTarifaire#56 "ARS-PCD, PUV, convention SSIAD, habilité à l'aide sociale"
* $TRE-R74-ModeFixationTarifaire#57 "Dotation globale de soins ARS et hébergement prix de journée PCD – sous CPOM"
* $TRE-R74-ModeFixationTarifaire#58 "ARS dotation forfait ou prix de journée globalisé hors CPOM"
* $TRE-R74-ModeFixationTarifaire#99 "Indéterminé"