ValueSet: JDV_J226_ModaliteAccueil_ROR
Id: JDV-J226-ModaliteAccueil-ROR
Description: "Modalité d'accueil"
* ^meta.versionId = "20"
* ^meta.lastUpdated = "2026-07-29T08:04:53.260+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J226-ModaliteAccueil-ROR/FHIR/JDV-J226-ModaliteAccueil-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.58"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R338-ModaliteAccueil#01 "Accueil séquentiel accepté"
* $TRE-R338-ModaliteAccueil#02 "Prise en charge directe SMUR"
* $TRE-R338-ModaliteAccueil#03 "En présentiel"
* $TRE-R338-ModaliteAccueil#04 "Téléconsultation"
* $TRE-R338-ModaliteAccueil#05 "Visite à domicile"
* $TRE-R338-ModaliteAccueil#06 "Prise en charge sans rendez-vous"
* $TRE-R338-ModaliteAccueil#07 "Accueil anonyme"
* $TRE-R338-ModaliteAccueil#08 "Accueil réservé aux femmes"
* $TRE-R338-ModaliteAccueil#09 "Participation aux gardes/astreintes"
* $TRE-R338-ModaliteAccueil#10 "Téléexpertise en moins de 24h"
* $TRE-R338-ModaliteAccueil#11 "Téléexpertise en moins de 7 jours"
* $TRE-R338-ModaliteAccueil#13 "Admission directe non programmée - personne âgée (PA)"
* $TRE-R338-ModaliteAccueil#14 "Télésoin"
* $TRE-R338-ModaliteAccueil#15 "Consultation dans des locaux dédiés - personnes en situation de handicap (PH)"
* $TRE-R338-ModaliteAccueil#16 "Consultation sans locaux dédiés - personnes en situation de handicap (PH)"
* $TRE-R338-ModaliteAccueil#17 "HandiBloc"
* $TRE-R338-ModaliteAccueil#18 "Intra-hospitalier (dont équipe de liaison)"
* $TRE-R338-ModaliteAccueil#19 "Extra-hospitalier"
* $TRE-R338-ModaliteAccueil#20 "Accueil en unité protégée"
* $TRE-R338-ModaliteAccueil#21 "Accueil saisonnier possible"
* $TRE-R338-ModaliteAccueil#22 "Accueil saisonnier uniquement"
* $TRE-R338-ModaliteAccueil#23 "Autodialyse simple"
* $TRE-R338-ModaliteAccueil#24 "Autodialyse assistée"
* $TRE-R338-ModaliteAccueil#25 "Relayage courte durée (quelques heures par jour)"
* $TRE-R338-ModaliteAccueil#26 "Relayage longue durée (sur plusieurs jours)"
* $TRE-R338-ModaliteAccueil#27 "Soins à domicile"