ValueSet: JDV_J115_Langue_ENREG
Id: JDV-J115-Langue-ENREG
Description: "Langue pour ENREG"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:04:54.348+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-05-29T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J115-Langue-ENREG/FHIR/JDV-J115-Langue-ENREG"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.186"
* ^version = "20240927120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-09-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-G00-Langue#aa "afar"
* $TRE-G00-Langue#ab "abkhaze, abkhazien"
* $TRE-G00-Langue#ae "avestique"
* $TRE-G00-Langue#af "afrikaans"
* $TRE-G00-Langue#ak "akan"
* $TRE-G00-Langue#am "amharique"
* $TRE-G00-Langue#an "aragonais"
* $TRE-G00-Langue#ar "arabe"
* $TRE-G00-Langue#as "assamais"
* $TRE-G00-Langue#av "avar"
* $TRE-G00-Langue#ay "aymara"
* $TRE-G00-Langue#az "azéri, azerbaïdjanais"
* $TRE-G00-Langue#ba "bachkir, bashkir"
* $TRE-G00-Langue#be "biélorusse"
* $TRE-G00-Langue#bg "bulgare"
* $TRE-G00-Langue#bh "bihari"
* $TRE-G00-Langue#bi "bichlamar, bislama"
* $TRE-G00-Langue#bm "bambara"
* $TRE-G00-Langue#bn "bengali"
* $TRE-G00-Langue#bo "tibétain"
* $TRE-G00-Langue#br "breton"
* $TRE-G00-Langue#bs "bosniaque"
* $TRE-G00-Langue#ca "catalan, valencien"
* $TRE-G00-Langue#ce "tchétchène"
* $TRE-G00-Langue#ch "chamorro"
* $TRE-G00-Langue#co "corse"
* $TRE-G00-Langue#cr "cree"
* $TRE-G00-Langue#cs "tchèque"
* $TRE-G00-Langue#cu "slavon d'église, slavon liturgique, vieux slave, vieux bulgare"
* $TRE-G00-Langue#cv "tchouvache"
* $TRE-G00-Langue#cy "gallois"
* $TRE-G00-Langue#da "danois"
* $TRE-G00-Langue#de "allemand"
* $TRE-G00-Langue#dv "maldivien"
* $TRE-G00-Langue#dz "dzongkha, bhoutani"
* $TRE-G00-Langue#ee "éwé"
* $TRE-G00-Langue#el "grec moderne (après 1453)"
* $TRE-G00-Langue#en "anglais"
* $TRE-G00-Langue#eo "espéranto"
* $TRE-G00-Langue#es "espagnol, castillan"
* $TRE-G00-Langue#et "estonien"
* $TRE-G00-Langue#eu "basque"
* $TRE-G00-Langue#fa "farsi, persan"
* $TRE-G00-Langue#ff "peul"
* $TRE-G00-Langue#fi "finnois"
* $TRE-G00-Langue#fj "fidjien"
* $TRE-G00-Langue#fo "féroïen"
* $TRE-G00-Langue#fy "frison"
* $TRE-G00-Langue#ga "irlandais"
* $TRE-G00-Langue#gd "gaélique, gaélique écossais"
* $TRE-G00-Langue#gl "galicien"
* $TRE-G00-Langue#gn "guarani"
* $TRE-G00-Langue#gu "gujarati, goudjrati"
* $TRE-G00-Langue#gv "mannois, manx"
* $TRE-G00-Langue#ha "haoussa"
* $TRE-G00-Langue#he "hébreu"
* $TRE-G00-Langue#hi "hindi"
* $TRE-G00-Langue#ho "hiri motu"
* $TRE-G00-Langue#hr "croate"
* $TRE-G00-Langue#ht "créole haïtien"
* $TRE-G00-Langue#hu "hongrois"
* $TRE-G00-Langue#hy "arménien"
* $TRE-G00-Langue#hz "herero"
* $TRE-G00-Langue#ia "interlingua (langue auxiliaire internationale)"
* $TRE-G00-Langue#id "indonésien"
* $TRE-G00-Langue#ie "interlingue"
* $TRE-G00-Langue#ig "igbo"
* $TRE-G00-Langue#ii "Sichuan Yi"
* $TRE-G00-Langue#ik "inupiaq"
* $TRE-G00-Langue#io "ido"
* $TRE-G00-Langue#is "islandais"
* $TRE-G00-Langue#it "italien"
* $TRE-G00-Langue#iu "inuktitut"
* $TRE-G00-Langue#ja "japonais"
* $TRE-G00-Langue#jv "javanais"
* $TRE-G00-Langue#ka "géorgien"
* $TRE-G00-Langue#kg "kongo"
* $TRE-G00-Langue#ki "kikuyu"
* $TRE-G00-Langue#kj "kwanyama, kuanyama"
* $TRE-G00-Langue#kk "kazakh"
* $TRE-G00-Langue#kl "groenlandais"
* $TRE-G00-Langue#km "khmer, cambodgien"
* $TRE-G00-Langue#kn "kannada"
* $TRE-G00-Langue#ko "coréen"
* $TRE-G00-Langue#kr "kanouri"
* $TRE-G00-Langue#ks "kashmiri"
* $TRE-G00-Langue#ku "kurde"
* $TRE-G00-Langue#kv "komi"
* $TRE-G00-Langue#kw "cornique"
* $TRE-G00-Langue#ky "kirghize"
* $TRE-G00-Langue#la "latin"
* $TRE-G00-Langue#lb "luxembourgeois"
* $TRE-G00-Langue#lg "louganda, ganda"
* $TRE-G00-Langue#li "limbourgeois"
* $TRE-G00-Langue#ln "lingala"
* $TRE-G00-Langue#lo "laotien, lao"
* $TRE-G00-Langue#ls "langue des signes française"
* $TRE-G00-Langue#lt "lituanien"
* $TRE-G00-Langue#lu "luba-katanga"
* $TRE-G00-Langue#lv "letton"
* $TRE-G00-Langue#mg "malgache"
* $TRE-G00-Langue#mh "marshall"
* $TRE-G00-Langue#mi "maori"
* $TRE-G00-Langue#mk "macédonien"
* $TRE-G00-Langue#ml "malayalam"
* $TRE-G00-Langue#mn "mongol"
* $TRE-G00-Langue#mo "moldave"
* $TRE-G00-Langue#mr "marathe"
* $TRE-G00-Langue#ms "malais"
* $TRE-G00-Langue#mt "maltais"
* $TRE-G00-Langue#my "birman"
* $TRE-G00-Langue#na "nauri"
* $TRE-G00-Langue#nb "norvégien bokmål"
* $TRE-G00-Langue#nd "ndébélé du Nord"
* $TRE-G00-Langue#ne "népalais"
* $TRE-G00-Langue#ng "ndonga"
* $TRE-G00-Langue#nl "néerlandais"
* $TRE-G00-Langue#nn "norvégien nynorsk"
* $TRE-G00-Langue#no "norvégien"
* $TRE-G00-Langue#nr "ndébélé du Sud"
* $TRE-G00-Langue#nv "navaho"
* $TRE-G00-Langue#ny "chichewa, chewa, nyanja"
* $TRE-G00-Langue#oc "occitan, provençal (après 1500)"
* $TRE-G00-Langue#oj "ojibwa"
* $TRE-G00-Langue#om "oromo, afan oromo, galla"
* $TRE-G00-Langue#or "oriya"
* $TRE-G00-Langue#os "ossète"
* $TRE-G00-Langue#pa "punjabi, panjabi, pendjabi"
* $TRE-G00-Langue#pi "pali"
* $TRE-G00-Langue#pl "polonais"
* $TRE-G00-Langue#ps "pachto, pashto, pushto"
* $TRE-G00-Langue#pt "portugais"
* $TRE-G00-Langue#qu "quechua, quichua"
* $TRE-G00-Langue#rc "créole réunionnais"
* $TRE-G00-Langue#rm "rhéto-roman"
* $TRE-G00-Langue#rn "kirundi, rundi"
* $TRE-G00-Langue#ro "roumain"
* $TRE-G00-Langue#ru "russe"
* $TRE-G00-Langue#rw "kinyarwanda, rwanda"
* $TRE-G00-Langue#sa "sanskrit"
* $TRE-G00-Langue#sc "sarde"
* $TRE-G00-Langue#sd "sindhi"
* $TRE-G00-Langue#se "sami du Nord"
* $TRE-G00-Langue#sg "sango"
* $TRE-G00-Langue#sh "serbo-croate"
* $TRE-G00-Langue#si "singhalais"
* $TRE-G00-Langue#sk "slovaque"
* $TRE-G00-Langue#sl "slovène"
* $TRE-G00-Langue#sm "samoan"
* $TRE-G00-Langue#sn "shona"
* $TRE-G00-Langue#so "somali"
* $TRE-G00-Langue#sq "albanais"
* $TRE-G00-Langue#sr "serbe"
* $TRE-G00-Langue#ss "swazi, swati, siswati"
* $TRE-G00-Langue#st "sesotho, sotho du Sud"
* $TRE-G00-Langue#su "soundanais"
* $TRE-G00-Langue#sv "suédois"
* $TRE-G00-Langue#sw "swahili"
* $TRE-G00-Langue#ta "tamoul, tamil"
* $TRE-G00-Langue#te "télougou"
* $TRE-G00-Langue#tg "tadjik"
* $TRE-G00-Langue#th "thaï"
* $TRE-G00-Langue#ti "tigrigna"
* $TRE-G00-Langue#tk "turkmène"
* $TRE-G00-Langue#tl "tagal, tagalog"
* $TRE-G00-Langue#tn "setchwana, tswana"
* $TRE-G00-Langue#to "tonga (îles Tonga)"
* $TRE-G00-Langue#tr "turc"
* $TRE-G00-Langue#ts "tsonga"
* $TRE-G00-Langue#tt "tatar"
* $TRE-G00-Langue#tw "twi"
* $TRE-G00-Langue#ty "tahitien"
* $TRE-G00-Langue#ug "ouïgour"
* $TRE-G00-Langue#uk "ukrainien"
* $TRE-G00-Langue#ur "ourdou"
* $TRE-G00-Langue#uz "ouszbek"
* $TRE-G00-Langue#ve "venda"
* $TRE-G00-Langue#vi "vietnamien"
* $TRE-G00-Langue#vo "volapük"
* $TRE-G00-Langue#wa "wallon"
* $TRE-G00-Langue#wo "wolof"
* $TRE-G00-Langue#xh "xhosa"
* $TRE-G00-Langue#yi "yiddish"
* $TRE-G00-Langue#yo "yorouba, yoruba"
* $TRE-G00-Langue#za "zhuang, chuang"
* $TRE-G00-Langue#zh "chinois"
* $TRE-G00-Langue#zu "zoulou"