ValueSet: JDV_J199_StatutJuridique_ROR
Id: JDV-J199-StatutJuridique-ROR
Description: "Statuts juridiques provenant de FINESS et RPPS"
* ^meta.versionId = "4"
* ^meta.lastUpdated = "2026-07-06T19:05:49.546+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J199-StatutJuridique-ROR/FHIR/JDV-J199-StatutJuridique-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.31"
* ^version = "20220826120000"
* ^status = #active
* ^experimental = false
* ^date = "2022-08-26T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R72-FinessStatutJuridique#000 "En cours de vérification"
* $TRE-R72-FinessStatutJuridique#01 "Etat"
* $TRE-R72-FinessStatutJuridique#02 "Département"
* $TRE-R72-FinessStatutJuridique#03 "Commune"
* $TRE-R72-FinessStatutJuridique#04 "Région"
* $TRE-R72-FinessStatutJuridique#05 "Territoire d'Outre Mer"
* $TRE-R72-FinessStatutJuridique#06 "Autre collectivité territoriale"
* $TRE-R72-FinessStatutJuridique#07 "Métropole ou Pôle métropolitain"
* $TRE-R72-FinessStatutJuridique#08 "Centre Intercommunal d'Action Sociale"
* $TRE-R72-FinessStatutJuridique#10 "Etablissement public national d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#11 "Etablissement public départemental d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#12 "Etablissement public interdépartemental d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#13 "Etablissement public communal d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#14 "Etablissement public intercommunal d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#15 "Etablissement public régional d'hospitalisation"
* $TRE-R72-FinessStatutJuridique#16 "Syndicat interhospitalier"
* $TRE-R72-FinessStatutJuridique#17 "Centre communal d'action sociale"
* $TRE-R72-FinessStatutJuridique#18 "Etablissement social et médico-social national"
* $TRE-R72-FinessStatutJuridique#19 "Etablissement social et médico-social départemental"
* $TRE-R72-FinessStatutJuridique#20 "Etablissement social et médico-social interdépartemental"
* $TRE-R72-FinessStatutJuridique#21 "Etablissement social et médico-social communal"
* $TRE-R72-FinessStatutJuridique#22 "Etablissement social et médico-social intercommunal"
* $TRE-R72-FinessStatutJuridique#23 "Etablissement social et médico-social régional"
* $TRE-R72-FinessStatutJuridique#24 "Office public d'HLM"
* $TRE-R72-FinessStatutJuridique#25 "Caisse des écoles"
* $TRE-R72-FinessStatutJuridique#26 "Autre établissement public à caractère administratif"
* $TRE-R72-FinessStatutJuridique#27 "Etablissement public à caractère industriel ou commercial"
* $TRE-R72-FinessStatutJuridique#28 "Groupement d'intérêt public (GIP)"
* $TRE-R72-FinessStatutJuridique#29 "Groupement de coopération sanitaire (GCS) public"
* $TRE-R72-FinessStatutJuridique#30 "Groupement de coopération sociale ou médico-sociale public (GCSMS)"
* $TRE-R72-FinessStatutJuridique#40 "Régime général de sécurité sociale"
* $TRE-R72-FinessStatutJuridique#41 "Régime spécial de sécurité sociale"
* $TRE-R72-FinessStatutJuridique#42 "Institution de prévoyance"
* $TRE-R72-FinessStatutJuridique#43 "Mutualité sociale agricole (MSA)"
* $TRE-R72-FinessStatutJuridique#44 "Régime maladie des non salariés, non agricole"
* $TRE-R72-FinessStatutJuridique#45 "Régime vieillesse particulier"
* $TRE-R72-FinessStatutJuridique#46 "Autre régime de prévoyance sociale"
* $TRE-R72-FinessStatutJuridique#47 "Société mutualiste"
* $TRE-R72-FinessStatutJuridique#48 "Assurance mutuelle agricole"
* $TRE-R72-FinessStatutJuridique#49 "Autre organisme mutualiste"
* $TRE-R72-FinessStatutJuridique#50 "Comité d'entreprise ou Comité d'établissement"
* $TRE-R72-FinessStatutJuridique#51 "Syndicat"
* $TRE-R72-FinessStatutJuridique#52 "Syndicat de propriétaires"
* $TRE-R72-FinessStatutJuridique#60 "Association Loi 1901 non reconnue d'utilité publique"
* $TRE-R72-FinessStatutJuridique#61 "Association Loi 1901 reconnue d'utilité publique"
* $TRE-R72-FinessStatutJuridique#62 "Association de droit local"
* $TRE-R72-FinessStatutJuridique#63 "Fondation"
* $TRE-R72-FinessStatutJuridique#64 "Congrégation"
* $TRE-R72-FinessStatutJuridique#65 "Autre organisme privé à but non lucratif"
* $TRE-R72-FinessStatutJuridique#66 "Groupement de coopération sociale ou médico-sociale (GCSMS) privé"
* $TRE-R72-FinessStatutJuridique#70 "Personne physique"
* $TRE-R72-FinessStatutJuridique#71 "Société en nom collectif (SNC)"
* $TRE-R72-FinessStatutJuridique#72 "Société à responsabilité limitée (SARL)"
* $TRE-R72-FinessStatutJuridique#73 "Société anonyme (SA)"
* $TRE-R72-FinessStatutJuridique#74 "Société civile"
* $TRE-R72-FinessStatutJuridique#75 "Autre société"
* $TRE-R72-FinessStatutJuridique#76 "Groupement d'intérêt économique (GIE)"
* $TRE-R72-FinessStatutJuridique#77 "Autre organisme privé à caractère commercial"
* $TRE-R72-FinessStatutJuridique#78 "Entreprise unipersonnelle à responsabilité limitée (EURL)"
* $TRE-R72-FinessStatutJuridique#79 "Société civile de moyens (SCM)"
* $TRE-R72-FinessStatutJuridique#80 "Société interprofessionnelle soins ambulatoires (SISA)"
* $TRE-R72-FinessStatutJuridique#85 "Société d'exercice libéral responsabilité limitée (SELARL)"
* $TRE-R72-FinessStatutJuridique#86 "Société d'exercice libéral à forme anonyme (SELAFA)"
* $TRE-R72-FinessStatutJuridique#87 "Société d'exercice libéral commandite par actions (SELCA)"
* $TRE-R72-FinessStatutJuridique#88 "Société civile professionnelle (SCP)"
* $TRE-R72-FinessStatutJuridique#89 "Groupement de coopération sanitaire (GCS) privé"
* $TRE-R72-FinessStatutJuridique#90 "Organisme de droit étranger"
* $TRE-R72-FinessStatutJuridique#91 "Société d'exercice libéral par actions simplifiée (SELAS)"
* $TRE-R72-FinessStatutJuridique#93 "Société en commandite"
* $TRE-R72-FinessStatutJuridique#95 "Société par actions simplifiée (SAS)"
* $TRE-R72-FinessStatutJuridique#100 "Société d'exercice libéral à responsabilité limitée unipersonnelle (SELURL)"
* $TRE-R72-FinessStatutJuridique#101 "Société d'exercice libéral par actions simplifiée (SELAS)"
* $TRE-R72-FinessStatutJuridique#102 "Société d'exercice libéral par actions simplifiée unipersonnelle (SELASU)"
* $TRE-R72-FinessStatutJuridique#103 "Société en commandite simple (SCS)"
* $TRE-R72-FinessStatutJuridique#104 "Société en commandite par actions (SCA)"
* $TRE-R72-FinessStatutJuridique#105 "Société par actions simplifiée (SAS)"
* $TRE-R72-FinessStatutJuridique#106 "Société anonyme à directoire (SADI)"
* $TRE-R72-FinessStatutJuridique#107 "Société Anonyme à conseil d'administration (SACA)"
* $TRE-R72-FinessStatutJuridique#110 "Société en participation (SEP)"