ValueSet: JDV_J172_SecteurActivite_EPARS
Id: JDV-J172-SecteurActivite-EPARS
Description: "Secteur d'activité pour EPARS"
* ^meta.versionId = "12"
* ^meta.lastUpdated = "2026-07-06T19:05:34.042+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2021-06-25T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J172-SecteurActivite-EPARS/FHIR/JDV-J172-SecteurActivite-EPARS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.233"
* ^version = "20260223120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-02-23T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R02-SecteurActivite#SA01 "Etablissement public de santé"
* $TRE-R02-SecteurActivite#SA02 "Hôpital militaire du Service de santé des armées"
* $TRE-R02-SecteurActivite#SA03 "Etablissement privé PSPH"
* $TRE-R02-SecteurActivite#SA04 "Etablissement privé non PSPH"
* $TRE-R02-SecteurActivite#SA05 "Centre de santé"
* $TRE-R02-SecteurActivite#SA06 "Autre structure du Service de santé des armées"
* $TRE-R02-SecteurActivite#SA07 "Cabinet individuel"
* $TRE-R02-SecteurActivite#SA08 "Cabinet de groupe"
* $TRE-R02-SecteurActivite#SA09 "Exercice en société"
* $TRE-R02-SecteurActivite#SA10 "Transporteur sanitaire"
* $TRE-R02-SecteurActivite#SA12 "Etablissement de soins et prévention"
* $TRE-R02-SecteurActivite#SA13 "Prévention et soins en entreprise"
* $TRE-R02-SecteurActivite#SA14 "Etablissements scolaires, universitaires et de formation hors champ FINESS"
* $TRE-R02-SecteurActivite#SA15 "PMI et Planification familiale"
* $TRE-R02-SecteurActivite#SA16 "Etablissement pour personnes handicapées"
* $TRE-R02-SecteurActivite#SA17 "Etablissement pour personnes âgées"
* $TRE-R02-SecteurActivite#SA18 "Etablissement aide à la famille"
* $TRE-R02-SecteurActivite#SA19 "Etablissements FINESS de formation aux professions sanitaires et sociales"
* $TRE-R02-SecteurActivite#SA20 "Etablissement pour la protection de l'enfance"
* $TRE-R02-SecteurActivite#SA21 "Etablissement d'hébergement et de réadaptation"
* $TRE-R02-SecteurActivite#SA22 "Recherche"
* $TRE-R02-SecteurActivite#SA23 "Assurance privée"
* $TRE-R02-SecteurActivite#SA24 "Organisme de sécurité sociale"
* $TRE-R02-SecteurActivite#SA25 "Laboratoire de biologie médicale"
* $TRE-R02-SecteurActivite#SA26 "Ministère ou Service déconcentré"
* $TRE-R02-SecteurActivite#SA27 "Collectivité territoriale"
* $TRE-R02-SecteurActivite#SA28 "Association ou organisme humanitaire"
* $TRE-R02-SecteurActivite#SA29 "Laboratoire d'analyses et de biologie médicale"
* $TRE-R02-SecteurActivite#SA30 "Autre établissement sanitaire"
* $TRE-R02-SecteurActivite#SA31 "Répartition et Distribution de médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA32 "Fabrication, Exploitation et Importation de médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA33 "Pharmacie d'officine"
* $TRE-R02-SecteurActivite#SA34 "Centre de dialyse"
* $TRE-R02-SecteurActivite#SA35 "Para-pharmacie"
* $TRE-R02-SecteurActivite#SA36 "Centre anti-cancer"
* $TRE-R02-SecteurActivite#SA37 "Centre de transfusion sanguine"
* $TRE-R02-SecteurActivite#SA38 "Pharmacie minière"
* $TRE-R02-SecteurActivite#SA39 "Pharmacie mutualiste"
* $TRE-R02-SecteurActivite#SA40 "Secteur privé, praticien hospitalier"
* $TRE-R02-SecteurActivite#SA41 "Autre établissement du domaine social ou médico-social"
* $TRE-R02-SecteurActivite#SA42 "Appareillage médical"
* $TRE-R02-SecteurActivite#SA43 "Secteur non défini"
* $TRE-R02-SecteurActivite#SA44 "Recrutement ou Gestion RH"
* $TRE-R02-SecteurActivite#SA45 "Communication, Marketing, Consulting, Média"
* $TRE-R02-SecteurActivite#SA46 "Fabrication, Exploitation, Importation, Répartition, Distribution médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA47 "Incendie et secours"
* $TRE-R02-SecteurActivite#SA48 "Entreprise industrielle et tertiaire hors industrie pharmaceutique"
* $TRE-R02-SecteurActivite#SA49 "Entité Outre-Mer"
* $TRE-R02-SecteurActivite#SA50 "Permanence des soins ambulatoires hors cabinet"
* $TRE-R02-SecteurActivite#SA51 "Structure de coopération avec autorisation de soins"
* $TRE-R02-SecteurActivite#SA52 "Maison de santé ou Pôle de santé"
* $TRE-R02-SecteurActivite#SA53 "Siège administratif d'un établissement de santé"
* $TRE-R02-SecteurActivite#SA54 "Centre de dépistage et de prévention"
* $TRE-R02-SecteurActivite#SA55 "Laboratoire pharmaceutique préparant et délivrant des allergènes"
* $TRE-R02-SecteurActivite#SA56 "Propharmacie"
* $TRE-R02-SecteurActivite#SA57 "Structure de coopération avec mission de coordination de soins"
* $TRE-R02-SecteurActivite#SA58 "Entreprise de taxis"
* $TRE-R02-SecteurActivite#SA59 "Laboratoire de biologie médicale hors catégorie standard"
* $TRE-R02-SecteurActivite#SA60 "Centres médicaux SNCF"
* $TRE-R02-SecteurActivite#SA61 "Structure Dispensatrice à domicile d'Oxygène à usage médical"
* $TRE-R02-SecteurActivite#SA62 "Ordre professionnel de santé"
* $TRE-R02-SecteurActivite#SA63 "Structures de coordination et d'orientation"
* $TRE-R02-SecteurActivite#SA68 "Services départementaux d'incendie et de secours"