ValueSet: JDV_J103_TypeVoie_RASS
Id: JDV-J103-TypeVoie-RASS
Description: "Type de voie du professionnel du RASS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:04:40.537+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J103-TypeVoie-RASS/FHIR/JDV-J103-TypeVoie-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.171"
* ^version = "20200424120000"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R35-TypeVoie#ABE "Abbaye"
* $TRE-R35-TypeVoie#ACH "Ancien chemin"
* $TRE-R35-TypeVoie#AERD "Aérodrome"
* $TRE-R35-TypeVoie#AERG "Aérogare"
* $TRE-R35-TypeVoie#AERP "Aéroport"
* $TRE-R35-TypeVoie#AGL "Agglomération"
* $TRE-R35-TypeVoie#AIRE "Aire"
* $TRE-R35-TypeVoie#ALL "Allée"
* $TRE-R35-TypeVoie#ANGL "Angle"
* $TRE-R35-TypeVoie#ANSE "Anse"
* $TRE-R35-TypeVoie#ARC "Arcade"
* $TRE-R35-TypeVoie#ART "Ancienne route"
* $TRE-R35-TypeVoie#AUT "Autoroute"
* $TRE-R35-TypeVoie#AV "Avenue"
* $TRE-R35-TypeVoie#BAST "Bastion"
* $TRE-R35-TypeVoie#BCH "Bas chemin"
* $TRE-R35-TypeVoie#BCLE "Boucle"
* $TRE-R35-TypeVoie#BD "Boulevard"
* $TRE-R35-TypeVoie#BEGI "Béguinage"
* $TRE-R35-TypeVoie#BER "Berge"
* $TRE-R35-TypeVoie#BOIS "Bois"
* $TRE-R35-TypeVoie#BRE "Barrière"
* $TRE-R35-TypeVoie#BRG "Bourg"
* $TRE-R35-TypeVoie#BSTD "Bastide"
* $TRE-R35-TypeVoie#BUT "Butte"
* $TRE-R35-TypeVoie#CALE "Cale"
* $TRE-R35-TypeVoie#CAMP "Camp"
* $TRE-R35-TypeVoie#CAR "Carrefour"
* $TRE-R35-TypeVoie#CARE "Carrière"
* $TRE-R35-TypeVoie#CARR "Carré"
* $TRE-R35-TypeVoie#CAU "Carreau"
* $TRE-R35-TypeVoie#CAV "Cavée"
* $TRE-R35-TypeVoie#CCAL "Centre commercial"
* $TRE-R35-TypeVoie#CGNE "Campagne"
* $TRE-R35-TypeVoie#CHE "Chemin"
* $TRE-R35-TypeVoie#CHEM "Chemin, cheminement"
* $TRE-R35-TypeVoie#CHEZ "Chez"
* $TRE-R35-TypeVoie#CHI "Charmille"
* $TRE-R35-TypeVoie#CHL "Chalet"
* $TRE-R35-TypeVoie#CHP "Chapelle"
* $TRE-R35-TypeVoie#CHS "Chaussée"
* $TRE-R35-TypeVoie#CHT "Château"
* $TRE-R35-TypeVoie#CHV "Chemin vicinal"
* $TRE-R35-TypeVoie#CITE "Cité"
* $TRE-R35-TypeVoie#CLOI "Cloître"
* $TRE-R35-TypeVoie#CLOS "Clos"
* $TRE-R35-TypeVoie#COL "Col"
* $TRE-R35-TypeVoie#COLI "Colline"
* $TRE-R35-TypeVoie#COR "Corniche"
* $TRE-R35-TypeVoie#COTE "Cote"
* $TRE-R35-TypeVoie#COTT "Cottage"
* $TRE-R35-TypeVoie#COUR "Cour"
* $TRE-R35-TypeVoie#CPG "Camping"
* $TRE-R35-TypeVoie#CRS "Cours"
* $TRE-R35-TypeVoie#CST "Castel"
* $TRE-R35-TypeVoie#CTR "Contour"
* $TRE-R35-TypeVoie#CTRE "Centre"
* $TRE-R35-TypeVoie#DARS "Darse"
* $TRE-R35-TypeVoie#DEG "Degré"
* $TRE-R35-TypeVoie#DIG "Digue"
* $TRE-R35-TypeVoie#DOM "Domaine"
* $TRE-R35-TypeVoie#DSC "Descente"
* $TRE-R35-TypeVoie#ECL "Ecluse"
* $TRE-R35-TypeVoie#EGL "Eglise"
* $TRE-R35-TypeVoie#EN "Enceinte"
* $TRE-R35-TypeVoie#ENC "Enclos"
* $TRE-R35-TypeVoie#ENV "Enclave"
* $TRE-R35-TypeVoie#ESC "Escalier"
* $TRE-R35-TypeVoie#ESP "Esplanade"
* $TRE-R35-TypeVoie#ESPA "Espace"
* $TRE-R35-TypeVoie#ETNG "Etang"
* $TRE-R35-TypeVoie#FG "Faubourg"
* $TRE-R35-TypeVoie#FON "Fontaine"
* $TRE-R35-TypeVoie#FORM "Forum"
* $TRE-R35-TypeVoie#FORT "Fort"
* $TRE-R35-TypeVoie#FOS "Fosse"
* $TRE-R35-TypeVoie#FOYR "Foyer"
* $TRE-R35-TypeVoie#FRM "Ferme"
* $TRE-R35-TypeVoie#GAL "Galerie"
* $TRE-R35-TypeVoie#GARE "Gare"
* $TRE-R35-TypeVoie#GARN "Garenne"
* $TRE-R35-TypeVoie#GBD "Grand boulevard"
* $TRE-R35-TypeVoie#GDEN "Grand ensemble"
* $TRE-R35-TypeVoie#GPE "Groupe"
* $TRE-R35-TypeVoie#GPT "Groupement"
* $TRE-R35-TypeVoie#GR "Grand rue"
* $TRE-R35-TypeVoie#GRI "Grille"
* $TRE-R35-TypeVoie#GRIM "Grimpette"
* $TRE-R35-TypeVoie#HAM "Hameau"
* $TRE-R35-TypeVoie#HCH "Haut chemin"
* $TRE-R35-TypeVoie#HIP "Hippodrome"
* $TRE-R35-TypeVoie#HLE "Halle"
* $TRE-R35-TypeVoie#HLM "HLM"
* $TRE-R35-TypeVoie#ILE "Ile"
* $TRE-R35-TypeVoie#IMM "Immeuble"
* $TRE-R35-TypeVoie#IMP "Impasse"
* $TRE-R35-TypeVoie#JARD "Jardin"
* $TRE-R35-TypeVoie#JTE "Jetée"
* $TRE-R35-TypeVoie#LD "Lieu dit"
* $TRE-R35-TypeVoie#LEVE "Levée"
* $TRE-R35-TypeVoie#LOT "Lotissement"
* $TRE-R35-TypeVoie#MAIL "Mail"
* $TRE-R35-TypeVoie#MAN "Manoir"
* $TRE-R35-TypeVoie#MAR "Marche"
* $TRE-R35-TypeVoie#MAS "Mas"
* $TRE-R35-TypeVoie#MET "Métro"
* $TRE-R35-TypeVoie#MF "Maison forestière"
* $TRE-R35-TypeVoie#MLN "Moulin"
* $TRE-R35-TypeVoie#MTE "Montée"
* $TRE-R35-TypeVoie#MUS "Musée"
* $TRE-R35-TypeVoie#NTE "Nouvelle route"
* $TRE-R35-TypeVoie#PAE "Petite avenue"
* $TRE-R35-TypeVoie#PAL "Palais"
* $TRE-R35-TypeVoie#PARC "Parc"
* $TRE-R35-TypeVoie#PAS "Passage"
* $TRE-R35-TypeVoie#PASS "Passe"
* $TRE-R35-TypeVoie#PAT "Patio"
* $TRE-R35-TypeVoie#PAV "Pavillon"
* $TRE-R35-TypeVoie#PCH "Petit chemin"
* $TRE-R35-TypeVoie#PCHE "Porche"
* $TRE-R35-TypeVoie#PERI "Périphérique"
* $TRE-R35-TypeVoie#PIM "Petite impasse"
* $TRE-R35-TypeVoie#PKG "Parking"
* $TRE-R35-TypeVoie#PL "Place"
* $TRE-R35-TypeVoie#PLAG "Plage"
* $TRE-R35-TypeVoie#PLAN "Plan"
* $TRE-R35-TypeVoie#PLCI "Placis"
* $TRE-R35-TypeVoie#PLE "Passerelle"
* $TRE-R35-TypeVoie#PLN "Plaine"
* $TRE-R35-TypeVoie#PLT "Plateau"
* $TRE-R35-TypeVoie#PN "Passage à niveau"
* $TRE-R35-TypeVoie#PNT "Pointe"
* $TRE-R35-TypeVoie#PONT "Pont"
* $TRE-R35-TypeVoie#PORQ "Portique"
* $TRE-R35-TypeVoie#PORT "Port"
* $TRE-R35-TypeVoie#POT "Poterne"
* $TRE-R35-TypeVoie#POUR "Pourtour"
* $TRE-R35-TypeVoie#PRE "Pré"
* $TRE-R35-TypeVoie#PROM "Promenade"
* $TRE-R35-TypeVoie#PRQ "Presqu'ile"
* $TRE-R35-TypeVoie#PRT "Petite route"
* $TRE-R35-TypeVoie#PRV "Parvis"
* $TRE-R35-TypeVoie#PSTY "Péristyle"
* $TRE-R35-TypeVoie#PTA "Petite allée"
* $TRE-R35-TypeVoie#PTE "Porte"
* $TRE-R35-TypeVoie#QU "Quai"
* $TRE-R35-TypeVoie#QUA "Quartier"
* $TRE-R35-TypeVoie#R "Rue"
* $TRE-R35-TypeVoie#RAC "Raccourci"
* $TRE-R35-TypeVoie#RAID "Raidillon"
* $TRE-R35-TypeVoie#REM "Rempart"
* $TRE-R35-TypeVoie#RES "Résidence"
* $TRE-R35-TypeVoie#RLE "Ruelle"
* $TRE-R35-TypeVoie#ROC "Rocade"
* $TRE-R35-TypeVoie#ROQT "Roquet"
* $TRE-R35-TypeVoie#RPE "Rampe"
* $TRE-R35-TypeVoie#RPT "Rond point"
* $TRE-R35-TypeVoie#RTD "Rotonde"
* $TRE-R35-TypeVoie#RTE "Route"
* $TRE-R35-TypeVoie#SEN "Sentier"
* $TRE-R35-TypeVoie#SQ "Square"
* $TRE-R35-TypeVoie#STA "Station"
* $TRE-R35-TypeVoie#STDE "Stade"
* $TRE-R35-TypeVoie#TOUR "Tour"
* $TRE-R35-TypeVoie#TPL "Terre plein"
* $TRE-R35-TypeVoie#TRA "Traverse"
* $TRE-R35-TypeVoie#TRN "Terrain"
* $TRE-R35-TypeVoie#TRT "Tertre"
* $TRE-R35-TypeVoie#TSSE "Terrasse"
* $TRE-R35-TypeVoie#VAL "Vallée, vallon"
* $TRE-R35-TypeVoie#VCHE "Vieux chemin"
* $TRE-R35-TypeVoie#VEN "Venelle"
* $TRE-R35-TypeVoie#VGE "Village"
* $TRE-R35-TypeVoie#VIA "Via"
* $TRE-R35-TypeVoie#VLA "Villa"
* $TRE-R35-TypeVoie#VLGE "Village"
* $TRE-R35-TypeVoie#VOI "Voie"
* $TRE-R35-TypeVoie#VTE "Vieille route"
* $TRE-R35-TypeVoie#ZA "Zone d'activité"
* $TRE-R35-TypeVoie#ZAC "Zone d'aménagement concerté"
* $TRE-R35-TypeVoie#ZAD "Zone d'aménagement différé"
* $TRE-R35-TypeVoie#ZI "Zone industrielle"
* $TRE-R35-TypeVoie#ZONE "Zone"
* $TRE-R35-TypeVoie#ZUP "Zone à urbaniser en priorité"