ValueSet: JDV_J254_CategorieEtablissementESSMSPH
Id: JDV-J254-CategorieEtablissementESSMSPH
Description: "Liste les catégories d'établissements ESSMS (Etablissement ou Service Social ou Médico-Social) pour les personnes porteurs d'handicap"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:06:19.813+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2023-12-15T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J254-CategorieEtablissementESSMSPH/FHIR/JDV-J254-CategorieEtablissementESSMSPH"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.218"
* ^version = "20241025120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-10-25T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R66-CategorieEtablissement#182 "Service d'Éducation Spéciale et de Soins à Domicile"
* $TRE-R66-CategorieEtablissement#183 "Institut Médico-Educatif (I.M.E.)"
* $TRE-R66-CategorieEtablissement#186 "Institut Thérapeutique Éducatif et Pédagogique (I.T.E.P.)"
* $TRE-R66-CategorieEtablissement#188 "Etablissement pour Enfants ou Adolescents Polyhandicapés"
* $TRE-R66-CategorieEtablissement#189 "Centre Médico-Psycho-Pédagogique (C.M.P.P.)"
* $TRE-R66-CategorieEtablissement#192 "Institut d'éducation motrice"
* $TRE-R66-CategorieEtablissement#194 "Institut pour Déficients Visuels"
* $TRE-R66-CategorieEtablissement#195 "Institut pour Déficients Auditifs"
* $TRE-R66-CategorieEtablissement#196 "Institut d'Education Sensorielle Sourd-Aveugle"
* $TRE-R66-CategorieEtablissement#209 "Service autonomie aide et soins (SAAS)"
* $TRE-R66-CategorieEtablissement#221 "Bureau d'Aide Psychologique Universitaire (B.A.P.U.)"
* $TRE-R66-CategorieEtablissement#238 "Centre d'Accueil Familial Spécialisé"
* $TRE-R66-CategorieEtablissement#242 "Service d'Activité de Jour"
* $TRE-R66-CategorieEtablissement#255 "Maison d'Accueil Spécialisée (M.A.S.)"
* $TRE-R66-CategorieEtablissement#354 "Service de Soins Infirmiers A Domicile (S.S.I.A.D)"
* $TRE-R66-CategorieEtablissement#390 "Etablissement d'Accueil Temporaire d'Enfants Handicapés"
* $TRE-R66-CategorieEtablissement#395 "Etablissement d'Accueil Temporaire pour Adultes Handicapés"
* $TRE-R66-CategorieEtablissement#396 "Foyer Hébergement Enfants et Adolescents Handicapés"
* $TRE-R66-CategorieEtablissement#445 "Service d'accompagnement médico-social adultes handicapés"
* $TRE-R66-CategorieEtablissement#446 "Service d'Accompagnement à la Vie Sociale (S.A.V.S.)"
* $TRE-R66-CategorieEtablissement#448 "Etab.Acc.Médicalisé en tout ou partie personnes handicapées"
* $TRE-R66-CategorieEtablissement#449 "Etab.Accueil Non Médicalisé pour personnes handicapées"
* $TRE-R66-CategorieEtablissement#460 "Service autonomie aide (SAA)"
* $TRE-R66-CategorieEtablissement#640 "Service d'aide et d'accompagnement à domicile aux familles (SAADF)"