ValueSet: JDV_J220_FonctionContact_ROR
Id: JDV-J220-FonctionContact-ROR
Description: "Un titre, une position, une fonction de la personne contact dans l'organisation"
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2026-07-06T19:06:00.819+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J220-FonctionContact-ROR/FHIR/JDV-J220-FonctionContact-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.52"
* ^version = "20250131120000"
* ^status = #active
* ^experimental = false
* ^date = "2025-01-31T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R251-FonctionContact#01 "Directeur"
* $TRE-R251-FonctionContact#02 "Assistant social"
* $TRE-R251-FonctionContact#03 "Cadre de santé"
* $TRE-R251-FonctionContact#04 "Médecin coordonnateur"
* $TRE-R251-FonctionContact#05 "Secrétaire"
* $TRE-R251-FonctionContact#06 "Président de CME"
* $TRE-R251-FonctionContact#07 "Référent PDSES"
* $TRE-R251-FonctionContact#08 "Infirmier coordonnateur"
* $TRE-R251-FonctionContact#09 "Infirmier de liaison"
* $TRE-R251-FonctionContact#10 "Chef de service"
* $TRE-R251-FonctionContact#11 "Chef de pôle"
* $TRE-R251-FonctionContact#12 "Référent ROR"
* $TRE-R251-FonctionContact#13 "Référent outil d'orientation SMR"
* $TRE-R251-FonctionContact#15 "Référent direction des services informatiques"
* $TRE-R251-FonctionContact#16 "Médecin DIM"
* $TRE-R251-FonctionContact#18 "Contact gestion de cas MAIA"
* $TRE-R251-FonctionContact#19 "Contact PTA"
* $TRE-R251-FonctionContact#20 "Chef de service éducatif"
* $TRE-R251-FonctionContact#21 "Coordonnateur CLIC"
* $TRE-R251-FonctionContact#22 "Responsable d'unité"
* $TRE-R251-FonctionContact#23 "Spécialiste en hygiène prévention contrôle des Infections Associées aux Soins (IAS)"
* $TRE-R251-FonctionContact#24 "Responsable du signalement des Infections Associées aux Soins (IAS)"
* $TRE-R251-FonctionContact#25 "Référent en antibiothérapie"
* $TRE-R251-FonctionContact#26 "Coordonnateur de la gestion des risques associés aux soins"
* $TRE-R251-FonctionContact#27 "Responsable du Bed Management"
* $TRE-R251-FonctionContact#28 "Référent Handicap"