ValueSet: JDV_J19_ModePriseEnCharge_ROR
Id: JDV-J19-ModePriseEnCharge-ROR
Description: "Mode de la prise en charge - ROR"
* ^meta.versionId = "12"
* ^meta.lastUpdated = "2026-07-06T19:05:50.092+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J19-ModePriseEnCharge-ROR/FHIR/JDV-J19-ModePriseEnCharge-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.1"
* ^version = "20260629120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-06-29T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R213-ModePriseEnCharge#01 "Accueil Permanence des soins en établissement de santé"
* $TRE-R213-ModePriseEnCharge#02 "Accueil spécialisé"
* $TRE-R213-ModePriseEnCharge#09 "Chirurgie ambulatoire"
* $TRE-R213-ModePriseEnCharge#11 "Equipe mobile extra-hospitalière"
* $TRE-R213-ModePriseEnCharge#13 "Hospitalisation courte durée (UHCD)"
* $TRE-R213-ModePriseEnCharge#17 "Précarité, permanence d'accès aux soins de santé (PASS)"
* $TRE-R213-ModePriseEnCharge#20 "Soins externes et traitements ambulatoires"
* $TRE-R213-ModePriseEnCharge#27 "Régulation médicale téléphonique"
* $TRE-R213-ModePriseEnCharge#28 "Hospitalisation complète (HC)"
* $TRE-R213-ModePriseEnCharge#29 "Hospitalisation de jour (HJ)"
* $TRE-R213-ModePriseEnCharge#30 "Hospitalisation de nuit (HN)"
* $TRE-R213-ModePriseEnCharge#31 "Hospitalisation à domicile (HAD)"
* $TRE-R213-ModePriseEnCharge#32 "Consultation (CS) ou Séance"
* $TRE-R213-ModePriseEnCharge#33 "Accueil des urgences"
* $TRE-R213-ModePriseEnCharge#34 "Hospitalisation de semaine (HS)"
* $TRE-R213-ModePriseEnCharge#35 "Téléexpertise"
* $TRE-R213-ModePriseEnCharge#36 "Téléassistance"
* $TRE-R213-ModePriseEnCharge#37 "Télésurveillance médicale"
* $TRE-R213-ModePriseEnCharge#38 "Isolement de secteur (unité de cohorting)"
* $TRE-R213-ModePriseEnCharge#39 "Réunion de Concertation Pluridisciplinaire (RCP)"
* $TRE-R213-ModePriseEnCharge#40 "Réunion de Concertation Pluridisciplinaire (RCP) de recours"
* $TRE-R213-ModePriseEnCharge#41 "Accueil familial thérapeutique"
* $TRE-R213-ModePriseEnCharge#42 "Prise en charge de groupe"
* $TRE-R213-ModePriseEnCharge#46 "Hébergement (accueil jour et nuit)"
* $TRE-R213-ModePriseEnCharge#47 "Accueil de jour"
* $TRE-R213-ModePriseEnCharge#48 "Accueil de nuit"
* $TRE-R213-ModePriseEnCharge#49 "Sur les lieux de vie"
* $TRE-R213-ModePriseEnCharge#50 "Placement famille d'accueil"
* $TRE-R213-ModePriseEnCharge#52 "Equipe mobile intra-hospitalière"
* $TRE-R213-ModePriseEnCharge#53 "Equipe mobile extra et intra-hospitalière"
* $TRE-R213-ModePriseEnCharge#54 "Accueil individuel ou collectif"
* $TRE-R213-ModePriseEnCharge#55 "Plateau technique"
* $TRE-R213-ModePriseEnCharge#56 "Accueil non programmé"
* $TRE-R213-ModePriseEnCharge#57 "Centre spécialisé"
* $TRE-R213-ModePriseEnCharge#58 "Suivi ou coordination de parcours"
* $TRE-R213-ModePriseEnCharge#59 "Equipe d'intervention mobile"
* $TRE-R213-ModePriseEnCharge#60 "Dispositif expérimental"