ValueSet: JDV_J48_ProfessionNonPS_CISIS
Id: JDV-J48-ProfessionNonPS-CISIS
Description: "Jeux de Valeurs des professions/spécialités des Non Ps"
* ^meta.versionId = "8"
* ^meta.lastUpdated = "2026-07-06T19:06:37.823+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2018-03-30T12:00:00+01:00"
* ^extension.valuePeriod.end = "2024-12-13T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J48-ProfessionNonPS-CISIS/FHIR/JDV-J48-ProfessionNonPS-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.123"
* ^version = "20241213120000"
* ^status = #retired
* ^experimental = false
* ^date = "2024-12-13T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R95-UsagerTitre#97 "Conseiller en génétique"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R94-ProfessionSocial#42 "Auxiliaire de vie sociale"
* $TRE-R94-ProfessionSocial#43 "Technicien de l'intervention sociale et familiale"
* $TRE-R94-ProfessionSocial#44 "Conseiller en économie sociale et familiale"
* $TRE-R94-ProfessionSocial#45 "Médiateur familial"
* $TRE-R94-ProfessionSocial#46 "Assistant familial"
* $TRE-R94-ProfessionSocial#47 "Aide médico-psychologique (AMP)"
* $TRE-R94-ProfessionSocial#48 "Moniteur éducateur"
* $TRE-R94-ProfessionSocial#49 "Educateur de jeunes enfants"
* $TRE-R94-ProfessionSocial#51 "Educateur spécialisé"
* $TRE-R94-ProfessionSocial#52 "Educateur technique spécialisé"
* $TRE-R94-ProfessionSocial#53 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie (officine)"
* $TRE-R85-RolePriseCharge#318 "Auxiliaire de vie sociale"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#323 "Aide médico-psychologique (AMP)"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#331 "Secrétaire médicale"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#350 "Aide à domicile"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"