ValueSet: JDV_J11_RelationPatient_CISIS
Id: JDV-J11-RelationPatient-CISIS
Description: "Relation par rapport au patient - CI-SIS"
* ^meta.versionId = "5"
* ^meta.lastUpdated = "2026-07-06T19:04:56.363+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J11-RelationPatient-CISIS/FHIR/JDV-J11-RelationPatient-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.3.16"
* ^version = "20200424120000"
* ^status = #active
* ^experimental = false
* ^date = "2020-04-24T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R216-HL7RoleCode#MTH "Mère"
* $TRE-R216-HL7RoleCode#FTH "Père"
* $TRE-R216-HL7RoleCode#NMTH "Mère biologique"
* $TRE-R216-HL7RoleCode#NFTH "Père biologique"
* $TRE-R216-HL7RoleCode#STPMTH "Belle-mère - épouse du père ou de la mère"
* $TRE-R216-HL7RoleCode#STPFTH "Beau-père - époux du père ou de la mère"
* $TRE-R216-HL7RoleCode#GRMTH "Grand-mère"
* $TRE-R216-HL7RoleCode#GRFTH "Grand-père"
* $TRE-R216-HL7RoleCode#GGRMTH "Arrière-grand-mère"
* $TRE-R216-HL7RoleCode#GGRFTH "Arrière-grand-père"
* $TRE-R216-HL7RoleCode#DAU "Fille biologique"
* $TRE-R216-HL7RoleCode#SON "Fils biologique"
* $TRE-R216-HL7RoleCode#BRO "Frère"
* $TRE-R216-HL7RoleCode#SIS "Soeur"
* $TRE-R216-HL7RoleCode#HBRO "Demi-frère"
* $TRE-R216-HL7RoleCode#HSIS "Demi-soeur"
* $TRE-R216-HL7RoleCode#GRNDDAU "Petite-fille"
* $TRE-R216-HL7RoleCode#GRNDSO "Petit-fils"
* $TRE-R216-HL7RoleCode#UNCLE "Oncle"
* $TRE-R216-HL7RoleCode#AUNT "Tante"
* $TRE-R216-HL7RoleCode#NEPHEW "Neveu"
* $TRE-R216-HL7RoleCode#NIECE "Nièce"
* $TRE-R216-HL7RoleCode#HUSB "Epoux"
* $TRE-R216-HL7RoleCode#WIFE "Epouse"
* $TRE-R216-HL7RoleCode#DOMPART "Concubin(e) ou partenaire PACS"
* $TRE-R216-HL7RoleCode#ROOM "Personne vivant sous le même toit"
* $TRE-R216-HL7RoleCode#FRND "Autre proche"
* $TRE-R216-HL7RoleCode#NBOR "Voisin(e)"
* $TRE-R216-HL7RoleCode#FAMMEMB "Autre membre de la famille"
* $TRE-R216-HL7RoleCode#CHILD "Enfant"
* $TRE-R216-HL7RoleCode#COUSN "Cousin(e)"
* $TRE-R216-HL7RoleCode#SIGOTHR "Conjoint"
* $TRE-R216-HL7RoleCode#DAUC "Fille"
* $TRE-R216-HL7RoleCode#SONC "Fils"
* $TRE-R217-ProtectionJuridique#TUTEUR "Tuteur"
* $TRE-R217-ProtectionJuridique#CURATEUR "Curateur"
* $TRE-R217-ProtectionJuridique#MSVG "Mandataire de sauvegarde"