ValueSet: JDV_J66_TypeCode_DMP
Id: JDV-J66-TypeCode-DMP
Description: "Jeu de valeurs pour métadonnée typeCode DMP"
* ^meta.versionId = "9"
* ^meta.lastUpdated = "2026-07-06T19:06:51.319+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-01-18T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J66-TypeCode-DMP/FHIR/JDV-J66-TypeCode-DMP"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.7"
* ^version = "20240927120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-09-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-A05-TypeDocComplementaire#AUTORIS-SOINS "Autorisation de soins et actes non usuels sanitaires"
* $TRE-A05-TypeDocComplementaire#ATTEST-RESID "Attestation de résidence"
* $TRE-A05-TypeDocComplementaire#ATTEST-DROITS-AM "Attestation de droits à l'assurance maladie"
* $TRE-A05-TypeDocComplementaire#ATTEST-ASS-COMPL "Attestation assurance complémentaire"
* $TRE-A05-TypeDocComplementaire#ATTEST-HEBGT "Attestation d'hébergement"
* $TRE-A05-TypeDocComplementaire#BIL_AUTO "CR de bilan d'évaluation de la perte d'autonomie"
* $TRE-A05-TypeDocComplementaire#CERT_DECL "Certificat, déclaration"
* $TRE-A05-TypeDocComplementaire#DISP_AUT "Dispensation (autre)"
* $TRE-A05-TypeDocComplementaire#EXPPAT_1 "Volontés et droits du patient"
* $TRE-A05-TypeDocComplementaire#EXPPAT_2 "Autre document du patient"
* $TRE-A05-TypeDocComplementaire#EXPPAT_3 "Directives anticipées"
* $TRE-A05-TypeDocComplementaire#IMG-KOS "Reference d'objets d'un examen d'imagerie"
* $TRE-A05-TypeDocComplementaire#PROT_ALD "Protocole de soins ALD"
* $TRE-A05-TypeDocComplementaire#REMB "Données de remboursement"
* $TRE-A05-TypeDocComplementaire#SYNTH "Synthèse"
* $TRE-A05-TypeDocComplementaire#DOCPAT01 "Synthèse déposée par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT02 "Traitement ou document de soins déposé par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT03 "CR déposé par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT04 "Imagerie déposée par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT05 "CR de biologie déposé par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT06 "CR de prévention déposé par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT07 "Certificat déposé par le patient"
* $TRE-A05-TypeDocComplementaire#DOCPAT08 "Profil médical Mon espace santé"
* $TRE-A05-TypeDocComplementaire#DOCPAT09 "Document administratif déposé par le patient"
* $TRE-A05-TypeDocComplementaire#PRESC-AAT "Prescription arrêt de travail"
* $TRE-A05-TypeDocComplementaire#PRESC-BIO "Prescription d'actes de biologie médicale"
* $TRE-A05-TypeDocComplementaire#PRESC-KINE "Prescription d'actes de kinésithérapie"
* $TRE-A05-TypeDocComplementaire#PRESC-INF "Prescription d'actes infirmiers"
* $TRE-A05-TypeDocComplementaire#PRESC-PEDI "Prescription d'actes de pédicurie"
* $TRE-A05-TypeDocComplementaire#PRESC-ORTHOPHO "Prescription d'actes d'orthophonie"
* $TRE-A05-TypeDocComplementaire#PRESC-ORTHOPTIE "Prescription d'actes d'orthoptie"
* $loinc#11369-6 "Historique des vaccinations"
* $loinc#11488-4 "CR ou fiche de consultation ou de visite"
* $loinc#11490-0 "Lettre de liaison à la sortie d'un établissement de soins"
* $loinc#11502-2 "CR d'examens biologiques"
* $loinc#11505-5 "CR d'acte thérapeutique (autre)"
* $loinc#11506-3 "CR ou fiche de suivi de soins par auxiliaire médical"
* $loinc#15507-7 "CR de passage aux urgences"
* $loinc#15508-5 "CR d'accouchement"
* $loinc#18748-4 "CR d'imagerie médicale"
* $loinc#18761-7 "Note de transfert (dont lettre de liaison à l'entrée en établissement de soins)"
* $loinc#18776-5 "Plan personnalisé de soins"
* $loinc#28617-9 "Bilan bucco-dentaire"
* $loinc#28653-4 "Document du secteur social / médico-social"
* $loinc#29274-8 "Mesures de signes vitaux"
* $loinc#34112-3 "CR hospitalier (séjour)"
* $loinc#34120-6 "Bilan par professionnel de santé"
* $loinc#34133-9 "Synthèse d'épisode de soins"
* $loinc#34749-2 "CR de consultation pré-anesthésique"
* $loinc#34794-8 "CR de réunion de concertation pluridisciplinaire"
* $loinc#34842-5 "Grille d'évaluation médico-social"
* $loinc#34874-8 "CR opératoire"
* $loinc#34875-5 "Évaluation postopératoire et note de suivi"
* $loinc#47420-5 "CR de bilan fonctionnel"
* $loinc#52040-3 "Document encapsulant une image d'illustration non DICOM"
* $loinc#51969-4 "CR de génétique moléculaire"
* $loinc#55115-0 "Demande d'actes d'imagerie"
* $loinc#56445-0 "Bilan médicamenteux (Officine)"
* $loinc#57057-2 "Synthèse Salle de Naissance Mère"
* $loinc#57055-6 "Synthèse antepartum"
* $loinc#57075-4 "Synthèse Salle de Naissance Enfant"
* $loinc#57828-6 "Prescription (autre)"
* $loinc#57832-8 "Prescription de soins"
* $loinc#57833-6 "Prescription de produits de santé"
* $loinc#59283-2 "CR d'examen de l'enfant"
* $loinc#59284-0 "Attestation de consentement"
* $loinc#60280-5 "Fiche de retour du service des urgences"
* $loinc#60568-3 "CR d'anatomie et de cytologie pathologiques"
* $loinc#60591-5 "Synthèse médicale"
* $loinc#60593-1 "Dispensation médicamenteuse"
* $loinc#61357-0 "Intervention pharmaceutique"
* $loinc#67851-6 "CR d'admission"
* $loinc#68599-0 "Synthèse psychiatrique"
* $loinc#68817-6 "Bilan de santé et de prévention de l'enfant"
* $loinc#70004-7 "CR d'acte diagnostique (autre)"
* $loinc#74207-2 "Document de liaison d'urgence"
* $loinc#74465-6 "Questionnaire patient"
* $loinc#75468-9 "Renouvellement ordonnance par pharmacien correspondant"
* $loinc#75482-0 "CR d'acte thérapeutique à visée préventive"
* $loinc#75492-9 "CR d'acte diagnostique à visée préventive ou de dépistage"
* $loinc#75496-0 "Demande d'acte de télémédecine"
* $loinc#77436-4 "CR d'anesthésie"
* $loinc#77604-7 "Planification thérapeutique"
* $loinc#78341-5 "Fiche de transfert vers le service des urgences"
* $loinc#78489-2 "Synthèse Enfant en Maternité"
* $loinc#78513-9 "CR de consultation en ophtalmologie"
* $loinc#78601-2 "CR d'entretien pharmaceutique"
* $loinc#80565-5 "CR d'administration de médicaments"
* $loinc#80771-9 "Projet d'accueil individualisé"
* $loinc#80788-3 "Projet personnalisé d'accompagnement"
* $loinc#80820-4 "Formulaire de conciliation médicamenteuse (Hôpital)"
* $loinc#83836-7 "Schéma dentaire"
* $loinc#83869-8 "Plan personnalisé de prévention"
* $loinc#83901-9 "Bilan psychologique"
* $loinc#83981-1 "Lettre de liaison à la sortie d'une structure sociale ou médico-sociale"
* $loinc#85208-7 "CR de télémédecine"
* $loinc#86531-1 "Attestation de sortie"
* $loinc#87273-9 "Note de vaccination"
* $loinc#88348-8 "Lettre de liaison d'entrée en structure sociale ou médico-sociale"
* $loinc#89233-1 "CR de grossesse"
* $loinc#89235-6 "Synthèse Suites de Couches Mère"
* $loinc#89601-9 "Certificat médical"
* $loinc#93024-8 "CR de consultation pharmaceutique"
* $loinc#96349-6 "Lettre d'adressage"
* $loinc#96173-0 "Test rapide d'orientation diagnostique"
* $loinc#96874-3 "COVID-19 Attestation de vaccination"
* $loinc#101881-1 "Carte d'implant"
* $TRE-A12-NomenclatureASTM#E1762 "Full Document"