Instance: ASS-A30-TypeAutorisation-Profession-EPARS
InstanceOf: ConceptMap
Usage: #definition
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* extension[=].valuePeriod.start = "2023-03-31T12:00:00+01:00"
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/concept-bidirectional"
* extension[=].valueBoolean = false
* url = "https://mos.esante.gouv.fr/NOS/ASS_A30-TypeAutorisation-Profession-EPARS/FHIR/ASS-A30-TypeAutorisation-Profession-EPARS"
* identifier.value = "urn:oid:1.2.250.1.213.1.6.1.252"
* version = "20240628120000"
* name = "ASS_A30-TypeAutorisation-Profession-EPARS"
* status = #active
* date = "2024-06-28T12:00:00+01:00"
* description = "Table d'association entre les types d'autorisations et les professions de santé, médico-sociales ou sociales"
* group.source = "https://mos.esante.gouv.fr/NOS/JDV_J171-TypeAutorisation-EPARS/FHIR/JDV-J171-TypeAutorisation-EPARS"
* group.target = "https://mos.esante.gouv.fr/NOS/JDV_J166-Profession-EPARS/FHIR/JDV-J166-Profession-EPARS"
* group.element[0].code = #AM01
* group.element[=].target.code = #91
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #28
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #83
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #83
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM01
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #41
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #86
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #91
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #98
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #28
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM14
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM22
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM22
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM22
* group.element[=].target.code = #83
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM22
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM22
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM23
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM23
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM23
* group.element[=].target.code = #83
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM23
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM23
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM24
* group.element[=].target.code = #86
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM25
* group.element[=].target.code = #86
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM26
* group.element[=].target.code = #86
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #31
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #41
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #86
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #91
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #92
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #94
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #95
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #96
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #98
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #28
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #32
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #71
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #72
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #73
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #81
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #82
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #83
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #84
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM27
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM28
* group.element[=].target.code = #71
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM29
* group.element[=].target.code = #95
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM30
* group.element[=].target.code = #95
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM31
* group.element[=].target.code = #93
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM32
* group.element[=].target.code = #93
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM33
* group.element[=].target.code = #72
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM34
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM34
* group.element[=].target.code = #26
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM35
* group.element[=].target.code = #73
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM36
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM37
* group.element[=].target.code = #85
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM38
* group.element[=].target.code = #98
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM39
* group.element[=].target.code = #72
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM41
* group.element[=].target.code = #32
* group.element[=].target.equivalence = #equivalent