Instance: ASS-A25-PaysProvenanceISO-PaysProvenanceCOG
InstanceOf: ConceptMap
Usage: #definition
* extension[0].url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* extension[=].valuePeriod.start = "2021-03-26T12:00:00+01:00"
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/concept-bidirectional"
* extension[=].valueBoolean = true
* url = "https://mos.esante.gouv.fr/NOS/ASS_A25-PaysProvenanceISO-PaysProvenanceCOG/FHIR/ASS-A25-PaysProvenanceISO-PaysProvenanceCOG"
* identifier.value = "urn:oid:1.2.250.1.213.2.66"
* version = "20240126120000"
* name = "ASS_A25-PaysProvenanceISO-PaysProvenanceCOG"
* status = #active
* date = "2024-01-26T12:00:00+01:00"
* description = "Correspondance codes TRE_R268-PaysProvenanceISO / codes TRE_R20-Pays"
* group.source = "https://mos.esante.gouv.fr/NOS/TRE_R268-PaysProvenanceISO/FHIR/TRE-R268-PaysProvenanceISO"
* group.target = "https://mos.esante.gouv.fr/NOS/TRE_R20-Pays/FHIR/TRE-R20-Pays"
* group.element[0].code = #AD
* group.element[=].target.code = #99130
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AE
* group.element[=].target.code = #99247
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AF
* group.element[=].target.code = #99212
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AG
* group.element[=].target.code = #99441
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AI
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AL
* group.element[=].target.code = #99125
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AM
* group.element[=].target.code = #99252
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AN
* group.element[=].target.code = #99431
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AO
* group.element[=].target.code = #99395
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AR
* group.element[=].target.code = #99415
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AS
* group.element[=].target.code = #99505
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AT
* group.element[=].target.code = #99110
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AU
* group.element[=].target.code = #99501
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AW
* group.element[=].target.code = #99135
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #AZ
* group.element[=].target.code = #99253
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BA
* group.element[=].target.code = #99118
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BB
* group.element[=].target.code = #99434
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BD
* group.element[=].target.code = #99246
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BE
* group.element[=].target.code = #99131
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BF
* group.element[=].target.code = #99331
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BG
* group.element[=].target.code = #99111
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BH
* group.element[=].target.code = #99249
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BI
* group.element[=].target.code = #99321
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BJ
* group.element[=].target.code = #99327
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BM
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BN
* group.element[=].target.code = #99225
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BO
* group.element[=].target.code = #99418
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BQ
* group.element[=].target.code = #99443
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BR
* group.element[=].target.code = #99416
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BS
* group.element[=].target.code = #99436
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BT
* group.element[=].target.code = #99214
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BV
* group.element[=].target.code = #99103
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BW
* group.element[=].target.code = #99347
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BY
* group.element[=].target.code = #99148
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #BZ
* group.element[=].target.code = #99429
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CA
* group.element[=].target.code = #99401
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CC
* group.element[=].target.code = #99501
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CD
* group.element[=].target.code = #99312
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CF
* group.element[=].target.code = #99323
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CG
* group.element[=].target.code = #99324
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CH
* group.element[=].target.code = #99140
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CI
* group.element[=].target.code = #99326
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CK
* group.element[=].target.code = #99502
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CL
* group.element[=].target.code = #99417
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CM
* group.element[=].target.code = #99322
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CN
* group.element[=].target.code = #99216
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CO
* group.element[=].target.code = #99419
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CR
* group.element[=].target.code = #99406
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CU
* group.element[=].target.code = #99407
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CV
* group.element[=].target.code = #99396
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CW
* group.element[=].target.code = #99444
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CX
* group.element[=].target.code = #99501
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CY
* group.element[=].target.code = #99254
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #CZ
* group.element[=].target.code = #99116
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DE
* group.element[=].target.code = #99109
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DJ
* group.element[=].target.code = #99399
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DK
* group.element[=].target.code = #99101
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DM
* group.element[=].target.code = #99438
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DO
* group.element[=].target.code = #99408
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #DZ
* group.element[=].target.code = #99352
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #EC
* group.element[=].target.code = #99420
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #EE
* group.element[=].target.code = #99106
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #EG
* group.element[=].target.code = #99301
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #EH
* group.element[=].target.code = #99389
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ER
* group.element[=].target.code = #99317
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ES
* group.element[=].target.code = #99134
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ET
* group.element[=].target.code = #99315
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FI
* group.element[=].target.code = #99105
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FJ
* group.element[=].target.code = #99508
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FK
* group.element[=].target.code = #99427
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FM
* group.element[=].target.code = #99516
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FO
* group.element[=].target.code = #99101
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #FR
* group.element[=].target.code = #99100
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GA
* group.element[=].target.code = #99328
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GB
* group.element[=].target.code = #99132
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GD
* group.element[=].target.code = #99435
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GE
* group.element[=].target.code = #99255
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GG
* group.element[=].target.code = #99132
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GH
* group.element[=].target.code = #99329
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GI
* group.element[=].target.code = #99133
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GL
* group.element[=].target.code = #99430
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GM
* group.element[=].target.code = #99304
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GN
* group.element[=].target.code = #99330
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GQ
* group.element[=].target.code = #99314
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GR
* group.element[=].target.code = #99126
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GS
* group.element[=].target.code = #99427
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GT
* group.element[=].target.code = #99409
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GU
* group.element[=].target.code = #99505
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GW
* group.element[=].target.code = #99392
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #GY
* group.element[=].target.code = #99428
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HK
* group.element[=].target.code = #99230
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HM
* group.element[=].target.code = #99501
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HN
* group.element[=].target.code = #99411
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HR
* group.element[=].target.code = #99119
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HT
* group.element[=].target.code = #99410
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #HU
* group.element[=].target.code = #99112
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ID
* group.element[=].target.code = #99231
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IE
* group.element[=].target.code = #99136
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IL
* group.element[=].target.code = #99207
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IM
* group.element[=].target.code = #99132
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IN
* group.element[=].target.code = #99223
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IO
* group.element[=].target.code = #99308
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IQ
* group.element[=].target.code = #99203
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IR
* group.element[=].target.code = #99204
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IS
* group.element[=].target.code = #99102
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #IT
* group.element[=].target.code = #99127
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #JE
* group.element[=].target.code = #99132
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #JM
* group.element[=].target.code = #99426
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #JO
* group.element[=].target.code = #99222
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #JP
* group.element[=].target.code = #99217
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KE
* group.element[=].target.code = #99332
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KG
* group.element[=].target.code = #99257
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KH
* group.element[=].target.code = #99234
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KI
* group.element[=].target.code = #99513
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KM
* group.element[=].target.code = #99397
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KN
* group.element[=].target.code = #99442
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KP
* group.element[=].target.code = #99238
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KR
* group.element[=].target.code = #99239
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KW
* group.element[=].target.code = #99240
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KY
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #KZ
* group.element[=].target.code = #99256
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LA
* group.element[=].target.code = #99241
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LB
* group.element[=].target.code = #99205
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LC
* group.element[=].target.code = #99439
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LI
* group.element[=].target.code = #99113
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LK
* group.element[=].target.code = #99235
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LR
* group.element[=].target.code = #99302
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LS
* group.element[=].target.code = #99348
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LT
* group.element[=].target.code = #99108
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LU
* group.element[=].target.code = #99137
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LV
* group.element[=].target.code = #99107
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #LY
* group.element[=].target.code = #99316
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MA
* group.element[=].target.code = #99350
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MC
* group.element[=].target.code = #99138
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MD
* group.element[=].target.code = #99151
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ME
* group.element[=].target.code = #99120
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MG
* group.element[=].target.code = #99333
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MH
* group.element[=].target.code = #99515
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MK
* group.element[=].target.code = #99156
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ML
* group.element[=].target.code = #99335
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MM
* group.element[=].target.code = #99224
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MN
* group.element[=].target.code = #99242
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MO
* group.element[=].target.code = #99232
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MP
* group.element[=].target.code = #99505
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MR
* group.element[=].target.code = #99336
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MS
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MT
* group.element[=].target.code = #99144
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MU
* group.element[=].target.code = #99390
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MV
* group.element[=].target.code = #99229
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MW
* group.element[=].target.code = #99334
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MX
* group.element[=].target.code = #99405
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MY
* group.element[=].target.code = #99227
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #MZ
* group.element[=].target.code = #99393
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NA
* group.element[=].target.code = #99311
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NE
* group.element[=].target.code = #99337
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NF
* group.element[=].target.code = #99501
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NG
* group.element[=].target.code = #99338
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NI
* group.element[=].target.code = #99412
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NL
* group.element[=].target.code = #99135
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NO
* group.element[=].target.code = #99103
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NP
* group.element[=].target.code = #99215
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NR
* group.element[=].target.code = #99507
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NU
* group.element[=].target.code = #99502
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #NZ
* group.element[=].target.code = #99502
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #OM
* group.element[=].target.code = #99250
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PA
* group.element[=].target.code = #99413
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PE
* group.element[=].target.code = #99422
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PG
* group.element[=].target.code = #99510
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PH
* group.element[=].target.code = #99220
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PK
* group.element[=].target.code = #99213
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PL
* group.element[=].target.code = #99122
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PN
* group.element[=].target.code = #99503
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PR
* group.element[=].target.code = #99432
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PS
* group.element[=].target.code = #99261
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PT
* group.element[=].target.code = #99139
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PW
* group.element[=].target.code = #99517
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #PY
* group.element[=].target.code = #99421
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #QA
* group.element[=].target.code = #99248
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #RO
* group.element[=].target.code = #99114
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #RS
* group.element[=].target.code = #99121
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #RU
* group.element[=].target.code = #99123
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #RW
* group.element[=].target.code = #99340
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SA
* group.element[=].target.code = #99201
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SB
* group.element[=].target.code = #99512
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SC
* group.element[=].target.code = #99398
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SD
* group.element[=].target.code = #99343
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SE
* group.element[=].target.code = #99104
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SG
* group.element[=].target.code = #99226
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SH
* group.element[=].target.code = #99306
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SI
* group.element[=].target.code = #99145
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SJ
* group.element[=].target.code = #99103
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SK
* group.element[=].target.code = #99117
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SL
* group.element[=].target.code = #99342
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SM
* group.element[=].target.code = #99128
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SN
* group.element[=].target.code = #99341
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SO
* group.element[=].target.code = #99318
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SR
* group.element[=].target.code = #99437
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SS
* group.element[=].target.code = #99349
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ST
* group.element[=].target.code = #99394
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SV
* group.element[=].target.code = #99414
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SX
* group.element[=].target.code = #99445
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SY
* group.element[=].target.code = #99206
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #SZ
* group.element[=].target.code = #99391
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TC
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TD
* group.element[=].target.code = #99344
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TG
* group.element[=].target.code = #99345
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TH
* group.element[=].target.code = #99219
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TJ
* group.element[=].target.code = #99259
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TK
* group.element[=].target.code = #99502
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TL
* group.element[=].target.code = #99262
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TM
* group.element[=].target.code = #99260
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TN
* group.element[=].target.code = #99351
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TO
* group.element[=].target.code = #99509
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TR
* group.element[=].target.code = #99208
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TT
* group.element[=].target.code = #99433
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TV
* group.element[=].target.code = #99511
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TW
* group.element[=].target.code = #99236
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #TZ
* group.element[=].target.code = #99309
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #UA
* group.element[=].target.code = #99155
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #UG
* group.element[=].target.code = #99339
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #US
* group.element[=].target.code = #99404
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #UY
* group.element[=].target.code = #99423
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #UZ
* group.element[=].target.code = #99258
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VA
* group.element[=].target.code = #99129
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VC
* group.element[=].target.code = #99440
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VE
* group.element[=].target.code = #99424
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VG
* group.element[=].target.code = #99425
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VI
* group.element[=].target.code = #99432
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VN
* group.element[=].target.code = #99243
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #VU
* group.element[=].target.code = #99514
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #WS
* group.element[=].target.code = #99506
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #XK
* group.element[=].target.code = #99157
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #YE
* group.element[=].target.code = #99251
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ZA
* group.element[=].target.code = #99303
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ZM
* group.element[=].target.code = #99346
* group.element[=].target.equivalence = #equivalent
* group.element[+].code = #ZW
* group.element[=].target.code = #99310
* group.element[=].target.equivalence = #equivalent