Alias: $usage-context-type = http://terminology.hl7.org/CodeSystem/usage-context-type

Instance: ASS-A11-CorresModeleCDA-XdsFormatCode-CISIS
InstanceOf: ConceptMap
Usage: #definition
* url = "https://mos.esante.gouv.fr/NOS/ASS_A11-CorresModeleCDA-XdsFormatCode-CISIS"
* version = "5.0.0"
* name = "ASS_A11_CorresModeleCDA_XdsFormatCode_CISIS"
* title = "ASS_A11-CorresModeleCDA-XdsFormatCode-CISIS"
* status = #active
* experimental = false
* description = "Lorsque le corps du CDA est structuré, la métadonnée 'formatCode' provient de l'élément 'templateId' (modèle du document CDA). La correspondance entre templateId et formatCode est assurée par cette table d'association"
* useContext.code = $usage-context-type#task
* useContext.valueCodeableConcept.text = "Pour la constitution des metadata XDS"
* publisher = "ANS"
* contact.name = "ANS"
* contact.telecom.system = #url
* contact.telecom.value = "https://esante.gouv.fr"
* jurisdiction = urn:iso:std:iso:3166#FR "France"
* sourceUri = "https://mos.esante.gouv.fr/NOS/JDV-ModeleDocumentCDA"
* targetUri = "https://mos.esante.gouv.fr/NOS/JDV_J10-XdsFormatCode-CISIS/FHIR/JDV-J10-XdsFormatCode-CISIS"
* group[0].source = "https://mos.esante.gouv.fr/NOS/TRE_R220-ModeleDocumentCDAStructure/FHIR/TRE-R220-ModeleDocumentCDAStructure"
* group[=].target = "https://mos.esante.gouv.fr/NOS/TRE_A06-FormatCodeComplementaire/FHIR/TRE-A06-FormatCodeComplementaire"
* group[=].element[0].code = #1.2.250.1.213.1.1.1.5.1
* group[=].element[=].target.code = #urn:asip:ci-sis:cse-cs8:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.5.2
* group[=].element[=].target.code = #urn:asip:ci-sis:cse-cs9:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.5.3
* group[=].element[=].target.code = #urn:asip:ci-sis:cse-cs24:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.5.4
* group[=].element[=].target.code = #urn:ans:ci-sis:cse-mde:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.8
* group[=].element[=].target.code = #urn:asip:ci-sis:frcp:2011
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.9
* group[=].element[=].target.code = #urn:asip:ci-sis:idap:2011
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.10
* group[=].element[=].target.code = #urn:asip:ci-sis:cva:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.12.1
* group[=].element[=].target.code = #urn:asip:ci-sis:obp-sap:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.12.2
* group[=].element[=].target.code = #urn:asip:ci-sis:obp-snm:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.12.3
* group[=].element[=].target.code = #urn:asip:ci-sis:obp-sne:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.12.4
* group[=].element[=].target.code = #urn:asip:ci-sis:obp-scm:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.12.5
* group[=].element[=].target.code = #urn:asip:ci-sis:obp-sem:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.13
* group[=].element[=].target.code = #urn:asip:ci-sis:vsm:2012
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.15
* group[=].element[=].target.code = #urn:asip:ci-sis:aunv:2013
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.16
* group[=].element[=].target.code = #urn:asip:ci-sis:eunv:2013
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.17
* group[=].element[=].target.code = #urn:asip:ci-sis:sunv:2013
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.18
* group[=].element[=].target.code = #urn:asip:ci-sis:crrtn:2013
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.2.1.1
* group[=].element[=].target.code = #urn:asip:ci-sis:avk:2009
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.2.1.2
* group[=].element[=].target.code = #urn:asip:ci-sis:tap:2009
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.2.1.3
* group[=].element[=].target.code = #urn:asip:ci-sis:dci:2009
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.2.1.4
* group[=].element[=].target.code = #urn:asip:ci-sis:psc:2009
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.2.1.5
* group[=].element[=].target.code = #urn:asip:ci-sis:ppv:2009
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.20
* group[=].element[=].target.code = #urn:asip:ci-sis:pps-paerpa:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.21
* group[=].element[=].target.code = #urn:asip:ci-sis:ldl-ees:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.22
* group[=].element[=].target.code = #urn:asip:ci-sis:dlu:2015
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.23
* group[=].element[=].target.code = #urn:asip:ci-sis:fludt:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.24
* group[=].element[=].target.code = #urn:asip:ci-sis:fludr:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.25
* group[=].element[=].target.code = #urn:asip:ci-sis:pavc:2016
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.26
* group[=].element[=].target.code = #urn:asip:ci-sis:pps-cancer:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.27
* group[=].element[=].target.code = #urn:asip:ci-sis:d2lm-fin:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.28
* group[=].element[=].target.code = #urn:asip:ci-sis:d2lm-fidd:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.29
* group[=].element[=].target.code = #urn:asip:ci-sis:ldl-ses:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.30
* group[=].element[=].target.code = #urn:asip:ci-sis:sdm-mr:2017
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.32
* group[=].element[=].target.code = #urn:asip:ci-sis:crgm:2018
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.36
* group[=].element[=].target.code = #urn:asip:ci-sis:hr:2019
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.37
* group[=].element[=].target.code = #urn:asip:ci-sis:vac:2019
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.38
* group[=].element[=].target.code = #urn:asip:ci-sis:tlm-da:2020
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.40
* group[=].element[=].target.code = #urn:asip:ci-sis:cr-anest:2020
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.41
* group[=].element[=].target.code = #urn:asip:ci-sis:cr-cpa:2020
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.46
* group[=].element[=].target.code = #urn:asip:ci-sis:vac-note:2021
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.47
* group[=].element[=].target.code = #urn:ans:ci-sis:img-da:2022
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.48
* group[=].element[=].target.code = #urn:asip:ci-sis:dlu-dlu-dom:2022
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.49
* group[=].element[=].target.code = #urn:asip:ci-sis:dlu-fludt-dom:2022
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.50
* group[=].element[=].target.code = #urn:asip:ci-sis:dlu-fludr-dom:2022
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.52
* group[=].element[=].target.code = #urn:ans:ci-sis:bio-ep-bio:2022
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.58
* group[=].element[=].target.code = #urn:asip:ci-sis:export-dui:2023
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.56
* group[=].element[=].target.code = #urn:asip:ci-sis:ppp:2023
* group[=].element[=].target.equivalence = #equivalent
* group[+].source = "https://mos.esante.gouv.fr/NOS/TRE_R220-ModeleDocumentCDAStructure/FHIR/TRE-R220-ModeleDocumentCDAStructure"
* group[=].target = "https://mos.esante.gouv.fr/NOS/TRE_A11-IheFormatCode/FHIR/TRE-A11-IheFormatCode"
* group[=].element[0].code = #1.2.250.1.213.1.1.1.39
* group[=].element[=].target.code = #urn:ihe:pharm:pre:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.54
* group[=].element[=].target.code = #urn:ihe:pharm:dis:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.42
* group[=].element[=].target.code = #urn:ihe:eyecare:geneyeevalcn:2014
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.43
* group[=].element[=].target.code = #urn:ihe:eyecare:geneyeevalcn:2014
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.44
* group[=].element[=].target.code = #urn:ihe:eyecare:geneyeevalcn:2014
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.45
* group[=].element[=].target.code = #urn:ihe:rad:CDA:ImagingReportStructuredHeadings:2013
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.55
* group[=].element[=].target.code = #urn:ihe:lab:xd-lab:2008
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.57
* group[=].element[=].target.code = #urn:ihe:palm:apsr:2016
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.3.3
* group[=].element[=].target.code = #urn:ihe:lab:xd-lab:2008
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.2.250.1.213.1.1.1.51
* group[=].element[=].target.code = #urn:ihe:pcc:ips:2020
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.1
* group[=].element[=].target.code = #urn:ihe:pat:apsr:all:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.1
* group[=].element[=].target.code = #urn:ihe:pat:apsr:breast:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.2
* group[=].element[=].target.code = #urn:ihe:pat:apsr:colon:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.3
* group[=].element[=].target.code = #urn:ihe:pat:apsr:prostate:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.4
* group[=].element[=].target.code = #urn:ihe:pat:apsr:thyroid:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.5
* group[=].element[=].target.code = #urn:ihe:pat:apsr:lung:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.6
* group[=].element[=].target.code = #urn:ihe:pat:apsr:skin:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.7
* group[=].element[=].target.code = #urn:ihe:pat:apsr:kidney:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.8
* group[=].element[=].target.code = #urn:ihe:pat:apsr:cervix:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.9
* group[=].element[=].target.code = #urn:ihe:pat:apsr:endometrium:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.10
* group[=].element[=].target.code = #urn:ihe:pat:apsr:ovary:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.11
* group[=].element[=].target.code = #urn:ihe:pat:apsr:esophagus:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.12
* group[=].element[=].target.code = #urn:ihe:pat:apsr:stomach:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.13
* group[=].element[=].target.code = #urn:ihe:pat:apsr:liver:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.14
* group[=].element[=].target.code = #urn:ihe:pat:apsr:pancreas:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.15
* group[=].element[=].target.code = #urn:ihe:pat:apsr:testis:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.16
* group[=].element[=].target.code = #urn:ihe:pat:apsr:urinary_bladder:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.17
* group[=].element[=].target.code = #urn:ihe:pat:apsr:lip_oral_cavity:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.18
* group[=].element[=].target.code = #urn:ihe:pat:apsr:pharynx:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.19
* group[=].element[=].target.code = #urn:ihe:pat:apsr:salivary_gland:2010
* group[=].element[=].target.equivalence = #equivalent
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.8.1.1.2.20
* group[=].element[=].target.code = #urn:ihe:pat:apsr:larynx:2010
* group[=].element[=].target.equivalence = #equivalent
* group[+].source = "https://mos.esante.gouv.fr/NOS/TRE_R221-ModeleDocumentCDANonStructure/FHIR/TRE-R221-ModeleDocumentCDANonStructure"
* group[=].target = "https://mos.esante.gouv.fr/NOS/TRE_A11-IheFormatCode/FHIR/TRE-A11-IheFormatCode"
* group[=].element[0].code = #1.3.6.1.4.1.19376.1.2.20
* group[=].element[=].target.code = #urn:ihe:iti:xds-sd:pdf:2008
* group[=].element[=].target.equivalence = #narrower
* group[=].element[=].target.comment = "Pour les CDA N1 avec un PDF embarqué"
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.2.20
* group[=].element[=].target.code = #urn:ihe:iti:xds-sd:text:2008
* group[=].element[=].target.equivalence = #narrower
* group[=].element[=].target.comment = "Pour les CDA N1 avec un texte embarqué"
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.2.20
* group[=].element[=].target.code = #urn:ihe:iti-fr:xds-sd:jpeg:2010
* group[=].element[=].target.equivalence = #narrower
* group[=].element[=].target.comment = "Pour les CDA N1 avec un jpeg embarqué"
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.2.20
* group[=].element[=].target.code = #urn:ihe:iti-fr:xds-sd:rtf:2010
* group[=].element[=].target.equivalence = #narrower
* group[=].element[=].target.comment = "Pour les CDA N1 avec un RTF embarqué"
* group[=].element[+].code = #1.3.6.1.4.1.19376.1.2.20
* group[=].element[=].target.code = #urn:ihe:iti-fr:xds-sd:tiff:2010
* group[=].element[=].target.equivalence = #narrower
* group[=].element[=].target.comment = "Pour les CDA N1 avec un tiff embarqué"
