ValueSet: JDV_J17_ActiviteOperationnelle_ROR
Id: JDV-J17-ActiviteOperationnelle-ROR
Description: "Activité Operationnelle - ROR"
* ^meta.versionId = "32"
* ^meta.lastUpdated = "2026-07-29T08:04:51.145+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2016-09-01T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J17-ActiviteOperationnelle-ROR/FHIR/JDV-J17-ActiviteOperationnelle-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.5"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R211-ActiviteOperationnelle#001 "Addictologie comportementale (sans substance)"
* $TRE-R211-ActiviteOperationnelle#003 "Alcoologie"
* $TRE-R211-ActiviteOperationnelle#004 "Algologie et Médecine de la douleur"
* $TRE-R211-ActiviteOperationnelle#005 "Allergologie"
* $TRE-R211-ActiviteOperationnelle#006 "Andrologie (urologie médicale)"
* $TRE-R211-ActiviteOperationnelle#007 "Anesthésie et Médecine périopératoire"
* $TRE-R211-ActiviteOperationnelle#009 "Biochimie"
* $TRE-R211-ActiviteOperationnelle#010 "Biologie du développement et de la reproduction"
* $TRE-R211-ActiviteOperationnelle#013 "Cardiologie générale"
* $TRE-R211-ActiviteOperationnelle#014 "Cardiologie interventionnelle"
* $TRE-R211-ActiviteOperationnelle#015 "Conseil antipoison et toxicovigilance"
* $TRE-R211-ActiviteOperationnelle#016 "Chirurgie cervico-faciale et Oto-rhino-laryngologie (ORL)"
* $TRE-R211-ActiviteOperationnelle#017 "Chirurgie de l'obésité (bariatrique)"
* $TRE-R211-ActiviteOperationnelle#018 "Chirurgie cardiaque et gros vaisseaux (cardio-vasculaire)"
* $TRE-R211-ActiviteOperationnelle#022 "Chirurgie gynécologique"
* $TRE-R211-ActiviteOperationnelle#023 "Chirurgie maxillo-faciale"
* $TRE-R211-ActiviteOperationnelle#025 "Chirurgie orthopédique et traumatologique"
* $TRE-R211-ActiviteOperationnelle#030 "Chirurgie thoracique et pulmonaire"
* $TRE-R211-ActiviteOperationnelle#031 "Urologie (chirurgie urologique)"
* $TRE-R211-ActiviteOperationnelle#032 "Chirurgie vasculaire et endovasculaire"
* $TRE-R211-ActiviteOperationnelle#033 "Chirurgie digestive et viscérale fonctionnelle (hors carcinologie)"
* $TRE-R211-ActiviteOperationnelle#035 "Coordination hospitalière de prélèvement d'organe"
* $TRE-R211-ActiviteOperationnelle#037 "Dermatologie"
* $TRE-R211-ActiviteOperationnelle#038 "Dermatologie esthétique et cosmétique"
* $TRE-R211-ActiviteOperationnelle#039 "Diabétologie"
* $TRE-R211-ActiviteOperationnelle#040 "Médecine nutritionnelle"
* $TRE-R211-ActiviteOperationnelle#041 "Endocrinologie"
* $TRE-R211-ActiviteOperationnelle#042 "Epidémiologie"
* $TRE-R211-ActiviteOperationnelle#044 "Foetopathologie et Embryopathologie"
* $TRE-R211-ActiviteOperationnelle#046 "Gastro-entérologie"
* $TRE-R211-ActiviteOperationnelle#049 "Génétique médicale et clinique"
* $TRE-R211-ActiviteOperationnelle#050 "Gériatrie, Gérontologie"
* $TRE-R211-ActiviteOperationnelle#051 "Psychiatrie du sujet âgé (et géronto-psychiatrie)"
* $TRE-R211-ActiviteOperationnelle#052 "Gestion de crise, plan blanc"
* $TRE-R211-ActiviteOperationnelle#053 "Gynécologie médicale"
* $TRE-R211-ActiviteOperationnelle#055 "Hématologie"
* $TRE-R211-ActiviteOperationnelle#056 "Hématologie biologique"
* $TRE-R211-ActiviteOperationnelle#058 "Hémodialyse en urgence"
* $TRE-R211-ActiviteOperationnelle#059 "Hémodialyse chronique"
* $TRE-R211-ActiviteOperationnelle#062 "Hépatologie"
* $TRE-R211-ActiviteOperationnelle#063 "Hygiène, prévention, contrôle des infections associées aux soins"
* $TRE-R211-ActiviteOperationnelle#064 "Hygiène hospitalière"
* $TRE-R211-ActiviteOperationnelle#067 "Imagerie par échographie"
* $TRE-R211-ActiviteOperationnelle#068 "Imagerie par IRM"
* $TRE-R211-ActiviteOperationnelle#069 "Imagerie par radiologie conventionnelle"
* $TRE-R211-ActiviteOperationnelle#070 "Imagerie par scanner (TDM)"
* $TRE-R211-ActiviteOperationnelle#071 "Immuno-hématologie"
* $TRE-R211-ActiviteOperationnelle#072 "Immunologie biologique"
* $TRE-R211-ActiviteOperationnelle#073 "Immunologie clinique"
* $TRE-R211-ActiviteOperationnelle#075 "Information médicale (DIM)"
* $TRE-R211-ActiviteOperationnelle#076 "Soins palliatifs avec lits identifiés de soins palliatifs (LISP)"
* $TRE-R211-ActiviteOperationnelle#077 "Maladies infectieuses et tropicales"
* $TRE-R211-ActiviteOperationnelle#080 "Médecine de la reproduction"
* $TRE-R211-ActiviteOperationnelle#081 "Médecine du sport"
* $TRE-R211-ActiviteOperationnelle#082 "Médecine du travail (pathologie professionnelle)"
* $TRE-R211-ActiviteOperationnelle#083 "Médecine polyvalente"
* $TRE-R211-ActiviteOperationnelle#084 "Médecine hyperbare"
* $TRE-R211-ActiviteOperationnelle#085 "Médecine interne"
* $TRE-R211-ActiviteOperationnelle#086 "Médecine légale"
* $TRE-R211-ActiviteOperationnelle#087 "Médecine nucléaire"
* $TRE-R211-ActiviteOperationnelle#088 "Médecine pédiatrique"
* $TRE-R211-ActiviteOperationnelle#089 "Médecine pénitentiaire"
* $TRE-R211-ActiviteOperationnelle#090 "Médecine physique et de réadaptation"
* $TRE-R211-ActiviteOperationnelle#091 "Médecine vasculaire (Angiologie, Phlébologie)"
* $TRE-R211-ActiviteOperationnelle#093 "Microbiologie"
* $TRE-R211-ActiviteOperationnelle#094 "Néonatalogie"
* $TRE-R211-ActiviteOperationnelle#095 "Néphrologie"
* $TRE-R211-ActiviteOperationnelle#096 "Neurochirurgie"
* $TRE-R211-ActiviteOperationnelle#097 "Neurologie"
* $TRE-R211-ActiviteOperationnelle#098 "Neurologie vasculaire"
* $TRE-R211-ActiviteOperationnelle#099 "Médecine de l'obésité"
* $TRE-R211-ActiviteOperationnelle#100 "Obstétrique"
* $TRE-R211-ActiviteOperationnelle#101 "Odontologie (dentaire)"
* $TRE-R211-ActiviteOperationnelle#102 "Oncologie médicale (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#103 "Ophtalmologie"
* $TRE-R211-ActiviteOperationnelle#104 "Orthodontie ou orthopédie dento-faciale"
* $TRE-R211-ActiviteOperationnelle#105 "Orthogénie"
* $TRE-R211-ActiviteOperationnelle#106 "Orthoptie"
* $TRE-R211-ActiviteOperationnelle#110 "Pharmacologie"
* $TRE-R211-ActiviteOperationnelle#111 "Pharmacovigilance"
* $TRE-R211-ActiviteOperationnelle#114 "Pneumologie"
* $TRE-R211-ActiviteOperationnelle#115 "Suivi post urgences"
* $TRE-R211-ActiviteOperationnelle#117 "Proctologie médico-chirurgicale"
* $TRE-R211-ActiviteOperationnelle#118 "Protection maternelle et infantile (PMI)"
* $TRE-R211-ActiviteOperationnelle#120 "Radiologie interventionnelle"
* $TRE-R211-ActiviteOperationnelle#121 "Réanimation spécialisée brûlés"
* $TRE-R211-ActiviteOperationnelle#122 "Réanimation chirurgicale"
* $TRE-R211-ActiviteOperationnelle#123 "Réanimation spécialisée chirurgie cardiaque et gros vaisseaux"
* $TRE-R211-ActiviteOperationnelle#124 "Réanimation spécialisée chirurgie thoracique et pulmonaire"
* $TRE-R211-ActiviteOperationnelle#125 "Réanimation spécialisée chirurgie viscérale et digestive"
* $TRE-R211-ActiviteOperationnelle#126 "Réanimation médicale"
* $TRE-R211-ActiviteOperationnelle#127 "Réanimation polyvalente"
* $TRE-R211-ActiviteOperationnelle#128 "Réanimation spécialisée néonatale"
* $TRE-R211-ActiviteOperationnelle#129 "Réanimation spécialisée neurochirurgicale"
* $TRE-R211-ActiviteOperationnelle#130 "Réanimation spécialisée pédiatrique"
* $TRE-R211-ActiviteOperationnelle#131 "Rhumatologie"
* $TRE-R211-ActiviteOperationnelle#132 "Rythmologie"
* $TRE-R211-ActiviteOperationnelle#133 "Rythmologie interventionnelle"
* $TRE-R211-ActiviteOperationnelle#135 "Sexologie médicale"
* $TRE-R211-ActiviteOperationnelle#136 "SMUR primaire"
* $TRE-R211-ActiviteOperationnelle#137 "Stomatologie"
* $TRE-R211-ActiviteOperationnelle#138 "Surveillance post-interventionnelle SSPI (réveil)"
* $TRE-R211-ActiviteOperationnelle#139 "Tabacologie"
* $TRE-R211-ActiviteOperationnelle#142 "Toxicologie"
* $TRE-R211-ActiviteOperationnelle#145 "Traumatologie"
* $TRE-R211-ActiviteOperationnelle#147 "Urgences Médico-Psychologiques (CUMP)"
* $TRE-R211-ActiviteOperationnelle#152 "Evaluation Médico-Judiciaire (UMJ)"
* $TRE-R211-ActiviteOperationnelle#154 "Urgences spécialisées ophtalmologiques"
* $TRE-R211-ActiviteOperationnelle#156 "Urgences spécialisées Oto-Rhino-Laryngologiques (ORL)"
* $TRE-R211-ActiviteOperationnelle#157 "Urgences polyvalentes hospitalières"
* $TRE-R211-ActiviteOperationnelle#158 "Urgences psychiatriques hospitalières"
* $TRE-R211-ActiviteOperationnelle#159 "Urgences spécialisées traumatologiques"
* $TRE-R211-ActiviteOperationnelle#160 "Urgences vitales (SAUV - déchocage)"
* $TRE-R211-ActiviteOperationnelle#161 "Vaccinations"
* $TRE-R211-ActiviteOperationnelle#162 "Evaluation et suivi des Infections Sexuellement Transmissibles (IST)"
* $TRE-R211-ActiviteOperationnelle#163 "Anatomie et Cytologie pathologique"
* $TRE-R211-ActiviteOperationnelle#164 "Traitements médicamenteux systémiques du cancer (chimiothérapie)"
* $TRE-R211-ActiviteOperationnelle#167 "Curiethérapie"
* $TRE-R211-ActiviteOperationnelle#168 "Radiothérapie externe"
* $TRE-R211-ActiviteOperationnelle#169 "Scintigraphie"
* $TRE-R211-ActiviteOperationnelle#170 "Soins palliatifs"
* $TRE-R211-ActiviteOperationnelle#172 "Réadaptation polyvalente"
* $TRE-R211-ActiviteOperationnelle#175 "Brûlologie"
* $TRE-R211-ActiviteOperationnelle#177 "Chirurgie reconstructrice"
* $TRE-R211-ActiviteOperationnelle#178 "Chirurgie plastique et esthétique"
* $TRE-R211-ActiviteOperationnelle#179 "Médecine aéronautique et aérospatiale"
* $TRE-R211-ActiviteOperationnelle#180 "Médecine d'altitude (médecine de montagne)"
* $TRE-R211-ActiviteOperationnelle#182 "Evaluation et traitement de la mucoviscidose"
* $TRE-R211-ActiviteOperationnelle#183 "Traitement neurochirurgical de la douleur"
* $TRE-R211-ActiviteOperationnelle#184 "Neurochirurgie vasculaire"
* $TRE-R211-ActiviteOperationnelle#186 "Oncologie médicale neurologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#187 "Oncogériatrie médicale (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#188 "Oncologie médicale dermatologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#189 "Oncologie médicale digestive et viscérale (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#190 "Oncologie médicale gynécologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#191 "Oncologie médicale hématologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#192 "Oncologie médicale oto-rhino-laryngologique (ORL) et cervico-faciale (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#193 "Oncologie médicale pneumologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#195 "Oncologie médicale sénologique (cancer du sein) (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#196 "Oncologie médicale urologique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#197 "Ostéopathie (hors actes réservés aux médecins)"
* $TRE-R211-ActiviteOperationnelle#198 "Parodontologie"
* $TRE-R211-ActiviteOperationnelle#199 "Chirurgie orale"
* $TRE-R211-ActiviteOperationnelle#200 "Orthophonie"
* $TRE-R211-ActiviteOperationnelle#201 "Pédicurie-Podologie (bilan diagnostic et mise en œuvre des activités thérapeutiques si nécessaire)"
* $TRE-R211-ActiviteOperationnelle#202 "Réunion de Concertation Pluridisciplinaire (RCP) Appareil Digestif"
* $TRE-R211-ActiviteOperationnelle#203 "Réunion de Concertation Pluridisciplinaire (RCP) Appareil Respiratoire et Autres Thorax"
* $TRE-R211-ActiviteOperationnelle#204 "Réunion de Concertation Pluridisciplinaire (RCP) Glandes Endocrines"
* $TRE-R211-ActiviteOperationnelle#205 "Réunion de Concertation Pluridisciplinaire (RCP) Hématologie"
* $TRE-R211-ActiviteOperationnelle#206 "Réunion de Concertation Pluridisciplinaire (RCP) Oeil"
* $TRE-R211-ActiviteOperationnelle#207 "Réunion de Concertation Pluridisciplinaire (RCP) Organes génitaux féminins"
* $TRE-R211-ActiviteOperationnelle#208 "Réunion de Concertation Pluridisciplinaire (RCP) Organes génitaux masculins"
* $TRE-R211-ActiviteOperationnelle#209 "Réunion de Concertation Pluridisciplinaire (RCP) Os et tissus mous et myélome"
* $TRE-R211-ActiviteOperationnelle#210 "Réunion de Concertation Pluridisciplinaire (RCP) Peau"
* $TRE-R211-ActiviteOperationnelle#211 "Réunion de Concertation Pluridisciplinaire (RCP) Sein"
* $TRE-R211-ActiviteOperationnelle#212 "Réunion de Concertation Pluridisciplinaire (RCP) Système Nerveux"
* $TRE-R211-ActiviteOperationnelle#214 "Réunion de Concertation Pluridisciplinaire (RCP) Voies Aéro-Digestives Supérieures (VADS)"
* $TRE-R211-ActiviteOperationnelle#215 "Réunion de Concertation Pluridisciplinaire (RCP) Voies urinaires"
* $TRE-R211-ActiviteOperationnelle#216 "Réunion de Concertation Pluridisciplinaire (RCP) Cancers rares"
* $TRE-R211-ActiviteOperationnelle#217 "Réunion de Concertation Pluridisciplinaire (RCP) Douleur"
* $TRE-R211-ActiviteOperationnelle#218 "Réunion de Concertation Pluridisciplinaire (RCP) Métastase osseuse"
* $TRE-R211-ActiviteOperationnelle#219 "Réunion de Concertation Pluridisciplinaire (RCP) Oncogénétique"
* $TRE-R211-ActiviteOperationnelle#220 "Réunion de Concertation Pluridisciplinaire (RCP) Oncogériatrie"
* $TRE-R211-ActiviteOperationnelle#221 "Réunion de Concertation Pluridisciplinaire (RCP) Oncologie médicale"
* $TRE-R211-ActiviteOperationnelle#222 "Réunion de Concertation Pluridisciplinaire (RCP) Préservation de la fertilité"
* $TRE-R211-ActiviteOperationnelle#223 "Réunion de Concertation Pluridisciplinaire (RCP) Radiologie interventionnelle"
* $TRE-R211-ActiviteOperationnelle#224 "Réunion de Concertation Pluridisciplinaire (RCP) Soins de support général"
* $TRE-R211-ActiviteOperationnelle#225 "Réunion de Concertation Pluridisciplinaire (RCP) Soins palliatifs"
* $TRE-R211-ActiviteOperationnelle#226 "Expertise des infections osteo-articulaires complexes (CRIOA, CRIOAC)"
* $TRE-R211-ActiviteOperationnelle#227 "Psychiatrie de l’enfant (pédopsychiatrie)"
* $TRE-R211-ActiviteOperationnelle#228 "Psychiatrie de l’adolescent (pédopsychiatrie)"
* $TRE-R211-ActiviteOperationnelle#229 "Psychiatrie adulte"
* $TRE-R211-ActiviteOperationnelle#230 "Psychiatrie périnatale"
* $TRE-R211-ActiviteOperationnelle#231 "Evaluation et soins de réhabilitation psychosociale"
* $TRE-R211-ActiviteOperationnelle#232 "Bilan expert"
* $TRE-R211-ActiviteOperationnelle#233 "Réadaptation des affections de l'appareil locomoteur"
* $TRE-R211-ActiviteOperationnelle#234 "Réadaptation des affections du système nerveux"
* $TRE-R211-ActiviteOperationnelle#235 "Réadaptation des affections cardio-vasculaires"
* $TRE-R211-ActiviteOperationnelle#236 "Réadaptation des affections respiratoires"
* $TRE-R211-ActiviteOperationnelle#237 "Réadaptation des affections du système digestif, endocrino-métaboliques et nutrition"
* $TRE-R211-ActiviteOperationnelle#238 "Réadaptation des affections onco-hématologiques"
* $TRE-R211-ActiviteOperationnelle#239 "Réadaptation des brulés (dont maladies nécrosantes et bulleuses de la peau)"
* $TRE-R211-ActiviteOperationnelle#240 "Réadaptation des affections liées aux conduites addictives"
* $TRE-R211-ActiviteOperationnelle#241 "Réadaptation gériatrique"
* $TRE-R211-ActiviteOperationnelle#242 "Soins de Suite et de Réadaptation (SSR) polyvalent, reconnaissance affections onco-hématologiques"
* $TRE-R211-ActiviteOperationnelle#243 "Réadaptation néphrologie"
* $TRE-R211-ActiviteOperationnelle#244 "Réadaptation Post-Réanimation (SRPR)"
* $TRE-R211-ActiviteOperationnelle#245 "Réadaptation des personnes en état de conscience altérée (ex EVC/EPR)"
* $TRE-R211-ActiviteOperationnelle#246 "Réadaptation cognitivo-comportementale (UCC)"
* $TRE-R211-ActiviteOperationnelle#247 "Réadaptation des déficiences visuelles"
* $TRE-R211-ActiviteOperationnelle#248 "Réadaptation des déficiences auditives"
* $TRE-R211-ActiviteOperationnelle#249 "Urgences pédiatriques hospitalières"
* $TRE-R211-ActiviteOperationnelle#250 "Urgences spécialisées céphalées"
* $TRE-R211-ActiviteOperationnelle#251 "Urgences spécialisées dermatologiques"
* $TRE-R211-ActiviteOperationnelle#252 "Urgences spécialisées endocrinologiques"
* $TRE-R211-ActiviteOperationnelle#253 "Urgences spécialisées hématologiques"
* $TRE-R211-ActiviteOperationnelle#254 "Urgences spécialisées néphrologiques"
* $TRE-R211-ActiviteOperationnelle#255 "Urgences spécialisées hépato-gastro-entérologiques"
* $TRE-R211-ActiviteOperationnelle#256 "Urgences spécialisées neuro-vasculaires"
* $TRE-R211-ActiviteOperationnelle#257 "Urgences spécialisées odontologiques (dentaires)"
* $TRE-R211-ActiviteOperationnelle#258 "Urgences spécialisées main"
* $TRE-R211-ActiviteOperationnelle#259 "Urgences spécialisées gynécologiques"
* $TRE-R211-ActiviteOperationnelle#260 "Urgences spécialisées obstétricales"
* $TRE-R211-ActiviteOperationnelle#261 "Urgences spécialisées maxillo-faciales"
* $TRE-R211-ActiviteOperationnelle#262 "Urgences spécialisées stomatologiques"
* $TRE-R211-ActiviteOperationnelle#263 "Urgences spécialisées oncologiques"
* $TRE-R211-ActiviteOperationnelle#264 "Urgences spécialisées chirurgicales viscérales et digestives"
* $TRE-R211-ActiviteOperationnelle#265 "Urgences spécialisées infectieuses"
* $TRE-R211-ActiviteOperationnelle#266 "Urgences spécialisées urologiques"
* $TRE-R211-ActiviteOperationnelle#267 "Urgences spécialisées neuro-chirurgicales"
* $TRE-R211-ActiviteOperationnelle#268 "Transfert inter-hospitalier (TIH SMUR)"
* $TRE-R211-ActiviteOperationnelle#269 "Transfert infirmier inter-hospitalier (TIIH SMUR)"
* $TRE-R211-ActiviteOperationnelle#270 "SMUR pédiatrique"
* $TRE-R211-ActiviteOperationnelle#271 "Evacuation sanitaire (EVASAN)"
* $TRE-R211-ActiviteOperationnelle#272 "Régulation médicale libérale (CRRA)"
* $TRE-R211-ActiviteOperationnelle#273 "Régulation médicale hospitalière (CRRA)"
* $TRE-R211-ActiviteOperationnelle#274 "Régulation médicale maritime (CRRA)"
* $TRE-R211-ActiviteOperationnelle#275 "Régulation médicale en montagne (CRRA)"
* $TRE-R211-ActiviteOperationnelle#276 "Régulation médicale pédiatrique (CRRA)"
* $TRE-R211-ActiviteOperationnelle#277 "Régulation psychiatrique"
* $TRE-R211-ActiviteOperationnelle#278 "Régulation des transferts in utero"
* $TRE-R211-ActiviteOperationnelle#279 "Oncologie médicale pédiatrique (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#280 "Chirurgie dermatologique"
* $TRE-R211-ActiviteOperationnelle#281 "Chirurgie oncologique"
* $TRE-R211-ActiviteOperationnelle#282 "Périnatalité (suivi de grossesse)"
* $TRE-R211-ActiviteOperationnelle#283 "Rééducation - réadaptation"
* $TRE-R211-ActiviteOperationnelle#284 "Evaluation et traitement de la drépanocytose"
* $TRE-R211-ActiviteOperationnelle#285 "Soins médicaux somatiques"
* $TRE-R211-ActiviteOperationnelle#287 "Soins infirmiers"
* $TRE-R211-ActiviteOperationnelle#288 "Soins de nursing lourds"
* $TRE-R211-ActiviteOperationnelle#289 "Suivi psychologique"
* $TRE-R211-ActiviteOperationnelle#290 "Réadaptation des fonctions du langage et de la communication"
* $TRE-R211-ActiviteOperationnelle#291 "Réadaptation pour la mobilité"
* $TRE-R211-ActiviteOperationnelle#292 "Réadaptation des fonctions cognitives"
* $TRE-R211-ActiviteOperationnelle#293 "Accompagnements pour les actes de la vie quotidienne (AVQ)"
* $TRE-R211-ActiviteOperationnelle#294 "Accompagnements pour la communication"
* $TRE-R211-ActiviteOperationnelle#295 "Accompagnements pour les relations avec autrui"
* $TRE-R211-ActiviteOperationnelle#296 "Accompagnements pour prendre des décisions adaptées"
* $TRE-R211-ActiviteOperationnelle#297 "Accompagnements pour la sécurité"
* $TRE-R211-ActiviteOperationnelle#298 "Accompagnements pour vivre dans un logement"
* $TRE-R211-ActiviteOperationnelle#299 "Accompagnements pour accomplir les activités domestiques"
* $TRE-R211-ActiviteOperationnelle#300 "Accompagnements à la scolarisation"
* $TRE-R211-ActiviteOperationnelle#301 "Enseignement et/ou formation"
* $TRE-R211-ActiviteOperationnelle#302 "Accompagnements pour préparer sa vie professionnelle"
* $TRE-R211-ActiviteOperationnelle#303 "Accompagnements à la recherche d'un emploi"
* $TRE-R211-ActiviteOperationnelle#304 "Activité professionnelle adaptée"
* $TRE-R211-ActiviteOperationnelle#305 "Accompagnements pour mener sa vie professionnelle"
* $TRE-R211-ActiviteOperationnelle#306 "Activités visant la stimulation cognitivo-comportementale"
* $TRE-R211-ActiviteOperationnelle#307 "Organisation d'activités péri-scolaires-péri-professionnelles"
* $TRE-R211-ActiviteOperationnelle#308 "Soutien à la parentalité et accompagnement familial"
* $TRE-R211-ActiviteOperationnelle#309 "Accompagnements à la vie intime, affective et sexuelle"
* $TRE-R211-ActiviteOperationnelle#310 "Accompagnements pour l'exercice des mandats électoraux, la représentation des pairs"
* $TRE-R211-ActiviteOperationnelle#311 "Accompagnements pour la pair aidance"
* $TRE-R211-ActiviteOperationnelle#312 "Accompagnements pour créer ou maintenir le lien social et éviter l'isolement"
* $TRE-R211-ActiviteOperationnelle#313 "Accompagnements à des activités sociales, culturelles, sportives et de loisirs"
* $TRE-R211-ActiviteOperationnelle#314 "Activités de bien-être"
* $TRE-R211-ActiviteOperationnelle#315 "Soins socio-esthétiques"
* $TRE-R211-ActiviteOperationnelle#316 "Apprentissage et accompagnements à la conduite de véhicule (voiture,...)"
* $TRE-R211-ActiviteOperationnelle#317 "Informer, évaluer, accompagner et orienter pour l'ouverture des droits et l'accès aux prestations pour l'aidé et l'aidant"
* $TRE-R211-ActiviteOperationnelle#318 "Apprentissage et-ou aide à la gestion du budget"
* $TRE-R211-ActiviteOperationnelle#319 "Conseils et accompagnements dans les démarches afin de mobiliser les mesures de protection adaptées"
* $TRE-R211-ActiviteOperationnelle#320 "Mettre en oeuvre les mesures de protection juridiques"
* $TRE-R211-ActiviteOperationnelle#322 "Prestation de restauration (dont portage de repas à domicile)"
* $TRE-R211-ActiviteOperationnelle#323 "Entretien du linge par l'établissement"
* $TRE-R211-ActiviteOperationnelle#324 "Organisation du transport de la personne"
* $TRE-R211-ActiviteOperationnelle#325 "Soutien et aide aux aidants et/ou à la famille/entourage"
* $TRE-R211-ActiviteOperationnelle#326 "Formation des aidants"
* $TRE-R211-ActiviteOperationnelle#330 "Promouvoir et sensibiliser aux activités physiques adaptées"
* $TRE-R211-ActiviteOperationnelle#332 "Préparation et reconstitution centralisée des médicaments cytotoxiques (UPC, URC)"
* $TRE-R211-ActiviteOperationnelle#333 "Soins de longue durée (SLD)"
* $TRE-R211-ActiviteOperationnelle#334 "Activité de dépistage et de prévention"
* $TRE-R211-ActiviteOperationnelle#335 "Coordination de parcours complexes"
* $TRE-R211-ActiviteOperationnelle#336 "Education thérapeutique"
* $TRE-R211-ActiviteOperationnelle#337 "Régulation médicale néonatale (CRRA)"
* $TRE-R211-ActiviteOperationnelle#338 "Neuroradiologie"
* $TRE-R211-ActiviteOperationnelle#339 "Kinésithérapie"
* $TRE-R211-ActiviteOperationnelle#340 "Coordination plan de soins"
* $TRE-R211-ActiviteOperationnelle#341 "Coordination plan d'aide"
* $TRE-R211-ActiviteOperationnelle#342 "Accompagnement vie familiale"
* $TRE-R211-ActiviteOperationnelle#343 "Exploration fonctionnelle respiratoire (EFR) pléthysmographie, gaz du sang"
* $TRE-R211-ActiviteOperationnelle#344 "Exploration fonctionnelle cardiaque"
* $TRE-R211-ActiviteOperationnelle#345 "Exploration fonctionnelle vasculaire"
* $TRE-R211-ActiviteOperationnelle#346 "Exploration fonctionnelle neurologique"
* $TRE-R211-ActiviteOperationnelle#347 "Exploration fonctionnelle ORL"
* $TRE-R211-ActiviteOperationnelle#348 "Exploration fonctionnelle digestive"
* $TRE-R211-ActiviteOperationnelle#349 "Exploration fonctionnelle urologique"
* $TRE-R211-ActiviteOperationnelle#350 "Exploration fonctionnelle ophtalmologique"
* $TRE-R211-ActiviteOperationnelle#351 "Soins intensifs polyvalents"
* $TRE-R211-ActiviteOperationnelle#352 "Soins intensifs chirurgicaux"
* $TRE-R211-ActiviteOperationnelle#353 "Soins intensifs médicaux"
* $TRE-R211-ActiviteOperationnelle#354 "Soins intensifs spécialisés cardiologie (USIC)"
* $TRE-R211-ActiviteOperationnelle#355 "Soins intensifs spécialisés en psychiatrie"
* $TRE-R211-ActiviteOperationnelle#356 "Soins intensifs spécialisés neurologie vasculaire (USINV)"
* $TRE-R211-ActiviteOperationnelle#357 "Soins intensifs spécialisés pneumologie"
* $TRE-R211-ActiviteOperationnelle#359 "Soins intensifs spécialisés brûlés"
* $TRE-R211-ActiviteOperationnelle#360 "Soins intensifs spécialisés cancérologie oncologie"
* $TRE-R211-ActiviteOperationnelle#361 "Soins intensifs spécialisés hématologie (USIH)"
* $TRE-R211-ActiviteOperationnelle#362 "Soins intensifs spécialisés chirurgie cardiaque et gros vaisseaux"
* $TRE-R211-ActiviteOperationnelle#363 "Soins intensifs spécialisés chirurgie thoracique et pulmonaire"
* $TRE-R211-ActiviteOperationnelle#364 "Soins intensifs spécialisés chirurgie urologique"
* $TRE-R211-ActiviteOperationnelle#365 "Soins intensifs spécialisés chirurgie viscérale et digestive"
* $TRE-R211-ActiviteOperationnelle#366 "Soins intensifs spécialisés gynécologie obstétrique"
* $TRE-R211-ActiviteOperationnelle#367 "Soins intensifs spécialisés hépato-gastro-entérologie"
* $TRE-R211-ActiviteOperationnelle#368 "Soins intensifs spécialisés maladies infectieuses et tropicales"
* $TRE-R211-ActiviteOperationnelle#369 "Soins intensifs spécialisés néonatalogie"
* $TRE-R211-ActiviteOperationnelle#370 "Soins intensifs spécialisés pédiatrie"
* $TRE-R211-ActiviteOperationnelle#371 "Soins intensifs spécialisés néphrologique"
* $TRE-R211-ActiviteOperationnelle#372 "Soins intensifs spécialisés neurochirurgicaux"
* $TRE-R211-ActiviteOperationnelle#373 "Surveillance continue polyvalente"
* $TRE-R211-ActiviteOperationnelle#374 "Surveillance continue chirurgicale"
* $TRE-R211-ActiviteOperationnelle#375 "Surveillance continue médicale"
* $TRE-R211-ActiviteOperationnelle#376 "Surveillance continue spécialisée cardiologie"
* $TRE-R211-ActiviteOperationnelle#377 "Surveillance continue spécialisée neurochirurgie"
* $TRE-R211-ActiviteOperationnelle#378 "Surveillance continue spécialisée pneumologie"
* $TRE-R211-ActiviteOperationnelle#379 "Surveillance continue spécialisée brûlés"
* $TRE-R211-ActiviteOperationnelle#380 "Surveillance continue spécialisée cancérologie oncologie"
* $TRE-R211-ActiviteOperationnelle#381 "Surveillance continue spécialisée chirurgie cardiaque et gros vaisseaux"
* $TRE-R211-ActiviteOperationnelle#382 "Surveillance continue spécialisée chirurgie thoracique et pulmonaire"
* $TRE-R211-ActiviteOperationnelle#383 "Surveillance continue spécialisée chirurgie urologique"
* $TRE-R211-ActiviteOperationnelle#384 "Surveillance continue spécialisée chirurgie viscérale et digestive"
* $TRE-R211-ActiviteOperationnelle#385 "Surveillance continue spécialisée gynécologie obstétrique"
* $TRE-R211-ActiviteOperationnelle#386 "Surveillance continue spécialisée hépato-gastro-entérologie"
* $TRE-R211-ActiviteOperationnelle#387 "Surveillance continue spécialisée néphrologique"
* $TRE-R211-ActiviteOperationnelle#388 "Surveillance continue spécialisée neurologique"
* $TRE-R211-ActiviteOperationnelle#389 "Surveillance continue spécialisée chirurgie maxillo-faciale et stomatologie"
* $TRE-R211-ActiviteOperationnelle#390 "Surveillance continue spécialisée chirurgie orthopédique et traumatologie"
* $TRE-R211-ActiviteOperationnelle#391 "Surveillance continue spécialisée pédiatrique"
* $TRE-R211-ActiviteOperationnelle#392 "Hébergement temporaire d'urgence"
* $TRE-R211-ActiviteOperationnelle#393 "Hébergement temporaire d'urgence en sortie d'hospitalisation"
* $TRE-R211-ActiviteOperationnelle#394 "Aide au répit (relayage)"
* $TRE-R211-ActiviteOperationnelle#395 "Préparation hospitalière"
* $TRE-R211-ActiviteOperationnelle#396 "Préparation pour essais cliniques"
* $TRE-R211-ActiviteOperationnelle#397 "Pharmacie à Usage Intérieur (PUI)"
* $TRE-R211-ActiviteOperationnelle#398 "Stérilisation des dispositifs médicaux"
* $TRE-R211-ActiviteOperationnelle#399 "Préparation des médicaments radiopharmaceutiques"
* $TRE-R211-ActiviteOperationnelle#400 "Vente de médicaments au public (rétrocession hospitalière)"
* $TRE-R211-ActiviteOperationnelle#401 "Evaluation du logement et préconisation d'adaptation pour le maintien à domicile"
* $TRE-R211-ActiviteOperationnelle#402 "Accompagnement à l'autonomie pour la mobilité et les déplacements"
* $TRE-R211-ActiviteOperationnelle#403 "Apprentissage de l'autonomie pour la vie courante"
* $TRE-R211-ActiviteOperationnelle#404 "Addictologie avec substance(s)"
* $TRE-R211-ActiviteOperationnelle#408 "Chambre mortuaire"
* $TRE-R211-ActiviteOperationnelle#409 "Oncologie médicale endocrinienne et thyroïdienne"
* $TRE-R211-ActiviteOperationnelle#410 "Oncologie médicale os et tissus mous"
* $TRE-R211-ActiviteOperationnelle#411 "Oncologie métastases osseuses"
* $TRE-R211-ActiviteOperationnelle#412 "Onco-génétique"
* $TRE-R211-ActiviteOperationnelle#413 "Exploration et suivi complexe en oncologie et hématologie"
* $TRE-R211-ActiviteOperationnelle#414 "Soins de support"
* $TRE-R211-ActiviteOperationnelle#416 "Soins Prolongés Complexes (USPC)"
* $TRE-R211-ActiviteOperationnelle#417 "Kinésithérapie orientation Neurologie"
* $TRE-R211-ActiviteOperationnelle#419 "Kinésithérapie orientation Respiratoire"
* $TRE-R211-ActiviteOperationnelle#420 "Kinésithérapie orientation Cardiologie"
* $TRE-R211-ActiviteOperationnelle#421 "Kinésithérapie orientation Pelvi-périnéologie"
* $TRE-R211-ActiviteOperationnelle#422 "Kinésithérapie orientation Vasculaire / Lymphatique"
* $TRE-R211-ActiviteOperationnelle#423 "Kinésithérapie orientation Troubles de l'équilibre"
* $TRE-R211-ActiviteOperationnelle#424 "Kinésithérapie orientation Rhumatologie"
* $TRE-R211-ActiviteOperationnelle#425 "Kinésithérapie orientation Système musculo-squelettique (traumatologie, orthopédie)"
* $TRE-R211-ActiviteOperationnelle#426 "Kinésithérapie orientation Lésions cutanées et cicatrices (dermatologie, brûlés)"
* $TRE-R211-ActiviteOperationnelle#427 "Kinésithérapie orientation Sport"
* $TRE-R211-ActiviteOperationnelle#428 "Kinésithérapie orientation Gériatrie (troubles liés à l'âge)"
* $TRE-R211-ActiviteOperationnelle#429 "Réunion de Concertation Pluridisciplinaire (RCP) Oncologie pédiatrique"
* $TRE-R211-ActiviteOperationnelle#431 "Endoscopie broncho-pulmonaire diagnostic"
* $TRE-R211-ActiviteOperationnelle#432 "Endoscopie broncho-pulmonaire interventionnelle"
* $TRE-R211-ActiviteOperationnelle#433 "Médecine Transfusionnelle et hémovigilance"
* $TRE-R211-ActiviteOperationnelle#434 "Elaboration du plan d'aide individualisé"
* $TRE-R211-ActiviteOperationnelle#435 "Expertise médicale (évaluation de préjudice)"
* $TRE-R211-ActiviteOperationnelle#436 "Chirurgie du rachis"
* $TRE-R211-ActiviteOperationnelle#437 "Médecine générale"
* $TRE-R211-ActiviteOperationnelle#438 "Accompagnement dans le cadre d'un dispositif d'emploi accompagné (DEA)"
* $TRE-R211-ActiviteOperationnelle#439 "Gynécologie endocrinienne"
* $TRE-R211-ActiviteOperationnelle#440 "Chirurgie intracrânienne"
* $TRE-R211-ActiviteOperationnelle#441 "Médecine bucco-dentaire"
* $TRE-R211-ActiviteOperationnelle#442 "Chirurgie dentaire"
* $TRE-R211-ActiviteOperationnelle#443 "Pédodontie ou odontologie pédiatrique"
* $TRE-R211-ActiviteOperationnelle#444 "Endodontie"
* $TRE-R211-ActiviteOperationnelle#445 "Biologie moléculaire sur prélèvement Anapath"
* $TRE-R211-ActiviteOperationnelle#446 "Cytopathologie"
* $TRE-R211-ActiviteOperationnelle#447 "Histopathologie"
* $TRE-R211-ActiviteOperationnelle#448 "Diagnostic lié à un retard ou Trouble du Neuro-Développement (TND)"
* $TRE-R211-ActiviteOperationnelle#449 "Appui et coopération auprès des acteurs de l'enseignement"
* $TRE-R211-ActiviteOperationnelle#450 "Accompagnement à la réduction des risques en addictologie"
* $TRE-R211-ActiviteOperationnelle#451 "Exploration des troubles du sommeil"
* $TRE-R211-ActiviteOperationnelle#452 "Exploration des troubles psycho-comportementaux et cognitifs"
* $TRE-R211-ActiviteOperationnelle#453 "Médecine et santé de l'adolescent"
* $TRE-R211-ActiviteOperationnelle#454 "Radiologie polyvalente générale"
* $TRE-R211-ActiviteOperationnelle#455 "Médecine thermale"
* $TRE-R211-ActiviteOperationnelle#457 "Réunion de Concertation Pluridisciplinaire (RCP) Rhumatismes Inflammatoires Chroniques (RIC), maladies auto-immunes et biothérapies en rhumatologie"
* $TRE-R211-ActiviteOperationnelle#465 "Réadaptation des fonctions sexuelles et de la reproduction"
* $TRE-R211-ActiviteOperationnelle#467 "Chirurgie orthopédique et traumatologique spécialisée main"
* $TRE-R211-ActiviteOperationnelle#468 "Chirurgie orthopédique et traumatologique spécialisée membres inférieurs"
* $TRE-R211-ActiviteOperationnelle#469 "Chirurgie orthopédique et traumatologique spécialisée membres supérieurs (sauf la main)"
* $TRE-R211-ActiviteOperationnelle#471 "Orientation vers un médecin traitant acceptant de nouveaux patients"
* $TRE-R211-ActiviteOperationnelle#472 "Veille et prévention de la récidive suicidaire"
* $TRE-R211-ActiviteOperationnelle#473 "Chirurgie oncologique de la sphère oto-rhino-laryngée, cervico-faciale et maxillo-faciale"
* $TRE-R211-ActiviteOperationnelle#474 "Chirurgie oncologique viscérale et digestive"
* $TRE-R211-ActiviteOperationnelle#475 "Coordination de soins non-programmés"
* $TRE-R211-ActiviteOperationnelle#476 "Exploration fonctionnelle de l'audition"
* $TRE-R211-ActiviteOperationnelle#477 "Exploration fonctionnelle de la voix et de la déglutition"
* $TRE-R211-ActiviteOperationnelle#478 "Exploration fonctionnelle des vertiges (audio vestibulaire)"
* $TRE-R211-ActiviteOperationnelle#479 "Explorations fonctionnelles endocrinologie, diabétologie, métabolisme et nutrition"
* $TRE-R211-ActiviteOperationnelle#480 "Médecine du sommeil (prise en charge des troubles du sommeil)"
* $TRE-R211-ActiviteOperationnelle#481 "Médecine générale à orientation Allergologie"
* $TRE-R211-ActiviteOperationnelle#482 "Médecine générale à orientation Andrologie"
* $TRE-R211-ActiviteOperationnelle#483 "Médecine générale à orientation Diabétologie"
* $TRE-R211-ActiviteOperationnelle#484 "Médecine générale à orientation Gériatrie, Gérontologie"
* $TRE-R211-ActiviteOperationnelle#485 "Médecine générale à orientation Gynécologie médicale"
* $TRE-R211-ActiviteOperationnelle#486 "Médecine générale à orientation Maladies infectieuses, parasitaires et tropicales"
* $TRE-R211-ActiviteOperationnelle#487 "Médecine générale à orientation Médecine pédiatrique"
* $TRE-R211-ActiviteOperationnelle#488 "Médecine générale à orientation Médecine vasculaire (Angiologie, Phlébologie)"
* $TRE-R211-ActiviteOperationnelle#489 "Médecine générale à orientation Oncogériatrie (cancérologie)"
* $TRE-R211-ActiviteOperationnelle#490 "Médecine générale à orientation Pathologies osseuses médicales"
* $TRE-R211-ActiviteOperationnelle#491 "Médecine gériatrique aiguë"
* $TRE-R211-ActiviteOperationnelle#492 "Neuroradiologie interventionnelle"
* $TRE-R211-ActiviteOperationnelle#493 "Psychomotricité"
* $TRE-R211-ActiviteOperationnelle#494 "Radiologie abdominale et digestive"
* $TRE-R211-ActiviteOperationnelle#495 "Radiologie cardio-vasculaire"
* $TRE-R211-ActiviteOperationnelle#496 "Radiologie gynécologique"
* $TRE-R211-ActiviteOperationnelle#497 "Radiologie interventionnelle musculosquelettique"
* $TRE-R211-ActiviteOperationnelle#498 "Radiologie interventionnelle oncologique"
* $TRE-R211-ActiviteOperationnelle#499 "Radiologie interventionnelle pédiatrique"
* $TRE-R211-ActiviteOperationnelle#500 "Radiologie interventionnelle vasculaire"
* $TRE-R211-ActiviteOperationnelle#501 "Radiologie musculo-squelettique"
* $TRE-R211-ActiviteOperationnelle#502 "Radiologie ORL et maxillo-faciale"
* $TRE-R211-ActiviteOperationnelle#503 "Radiologie prénatale et pédiatrique"
* $TRE-R211-ActiviteOperationnelle#504 "Radiologie sénologique (dont mammographie)"
* $TRE-R211-ActiviteOperationnelle#505 "Radiologie thoracique"
* $TRE-R211-ActiviteOperationnelle#506 "Transplantation d'organe"
* $TRE-R211-ActiviteOperationnelle#507 "Uro-Radiologie"
* $TRE-R211-ActiviteOperationnelle#508 "Exploration fonctionnelle de l'exercice et du sport"
* $TRE-R211-ActiviteOperationnelle#509 "Traumatologie de l'activité physique et du sport"
* $TRE-R211-ActiviteOperationnelle#510 "Échographie obstétricale de dépistage (1er, 2ème, 3ème trimestre)"
* $TRE-R211-ActiviteOperationnelle#511 "Accueil et hébergement spécialisé"
* $TRE-R211-ActiviteOperationnelle#512 "Accueil et orientation des victimes de violences sexuelles"
* $TRE-R211-ActiviteOperationnelle#513 "Réadaptation locomotrice des patients amputés"
* $TRE-R211-ActiviteOperationnelle#514 "Réadaptation PREcoce Post-Aiguë Cardiologique (PREPAC)"
* $TRE-R211-ActiviteOperationnelle#515 "Réadaptation PREcoce Post-Aiguë Respiratoire (PREPAR)"
* $TRE-R211-ActiviteOperationnelle#516 "Réadaptation neuro-orthopédique"
* $TRE-R211-ActiviteOperationnelle#517 "Réadaptation PREcoce Post-Aiguë Neurologique (PREPAN)"
* $TRE-R211-ActiviteOperationnelle#518 "Réadaptation des troubles cognitifs et comportementaux des patients cérébro-lésés"
* $TRE-R211-ActiviteOperationnelle#519 "Réadaptation des affections médullaires"
* $TRE-R211-ActiviteOperationnelle#520 "Réadaptation de l'obésité complexe"
* $TRE-R211-ActiviteOperationnelle#521 "Réadaptation des troubles cognitifs sévères liés à une conduite addictive"
* $TRE-R211-ActiviteOperationnelle#522 "Réadaptation polyhandicap"
* $TRE-R211-ActiviteOperationnelle#523 "Réadaptation des affections oncologiques"
* $TRE-R211-ActiviteOperationnelle#524 "Réadaptation troubles du langage et des apprentissages"
* $TRE-R211-ActiviteOperationnelle#525 "Evaluation et orientation des auteurs de violences sexuelles"
* $TRE-R211-ActiviteOperationnelle#526 "Informer, évaluer, accompagner et orienter dans le cadre d'une orientation professionnelle"
* $TRE-R211-ActiviteOperationnelle#527 "Suivi gynécologique de prévention et contraception"
* $TRE-R211-ActiviteOperationnelle#528 "Suivi neuropsychologique"
* $TRE-R211-ActiviteOperationnelle#529 "Suivi post-natal (dont séances post-natales)"
* $TRE-R211-ActiviteOperationnelle#530 "Suivi prénatal (suivi de grossesse)"
* $TRE-R211-ActiviteOperationnelle#531 "Réadaptation viroses chroniques"
* $TRE-R211-ActiviteOperationnelle#532 "Réadaptation lymphologie"
* $TRE-R211-ActiviteOperationnelle#533 "Accession à un logement individuel"
* $TRE-R211-ActiviteOperationnelle#535 "Sexologie clinique"
* $TRE-R211-ActiviteOperationnelle#536 "Chirurgie oncologique thoracique"
* $TRE-R211-ActiviteOperationnelle#537 "Chirurgie oncologique urologique"
* $TRE-R211-ActiviteOperationnelle#538 "Chirurgie oncologique gynécologique"
* $TRE-R211-ActiviteOperationnelle#539 "Chirurgie oncologique mammaire"
* $TRE-R211-ActiviteOperationnelle#540 "Chirurgie oncologique neurologique"
* $TRE-R211-ActiviteOperationnelle#541 "Chirurgie oncologique ophtalmologique"
* $TRE-R211-ActiviteOperationnelle#542 "Chirurgie oncologique dermatologique"
* $TRE-R211-ActiviteOperationnelle#543 "Chirurgie oncologique des os et des tissus mous"
* $TRE-R211-ActiviteOperationnelle#544 "Chirurgie oncologique de la thyroïde"
* $TRE-R211-ActiviteOperationnelle#545 "Chimiothérapie intensive"
* $TRE-R211-ActiviteOperationnelle#546 "Exploration et prise en charge de la dénutrition"
* $TRE-R211-ActiviteOperationnelle#547 "Evaluation de situation sociale préoccupante"
* $TRE-R211-ActiviteOperationnelle#548 "Coordination de parcours (Care management)"
* $TRE-R211-ActiviteOperationnelle#549 "Diététique et nutrition"
* $TRE-R211-ActiviteOperationnelle#550 "Accompagnement puériculteur à la périnatalité"
* $TRE-R211-ActiviteOperationnelle#551 "Génétique chromosomique"
* $TRE-R211-ActiviteOperationnelle#552 "Génétique moléculaire"
* $TRE-R211-ActiviteOperationnelle#553 "Suivi socio-éducatif"
* $TRE-R211-ActiviteOperationnelle#554 "Promotion de la santé de l'enfant"
* $TRE-R211-ActiviteOperationnelle#555 "Soins infirmiers orientation Onco-hématologie"
* $TRE-R211-ActiviteOperationnelle#556 "Soins infirmiers en puériculture"
* $TRE-R211-ActiviteOperationnelle#557 "Suivi du développement de l'enfant"
* $TRE-R211-ActiviteOperationnelle#558 "Ergothérapie"
* $TRE-R211-ActiviteOperationnelle#559 "Kinésithérapie orientation Fonctions sexuelles et de la reproduction"
* $TRE-R211-ActiviteOperationnelle#560 "Kinésithérapie orientation Obésité complexe"
* $TRE-R211-ActiviteOperationnelle#561 "Kinésithérapie orientation Cancérologie"
* $TRE-R211-ActiviteOperationnelle#562 "Kinésithérapie orientation Pédiatrie"
* $TRE-R211-ActiviteOperationnelle#563 "Kinésithérapie orientation Soins palliatifs"
* $TRE-R211-ActiviteOperationnelle#564 "Kinésithérapie orientation Santé mentale"
* $TRE-R211-ActiviteOperationnelle#565 "Kinésithérapie orientation Maxillo-faciale"
* $TRE-R211-ActiviteOperationnelle#566 "Kinésithérapie orientation Gestion de la douleur"
* $TRE-R211-ActiviteOperationnelle#567 "Soins infirmiers orientation Gestion de la douleur"
* $TRE-R211-ActiviteOperationnelle#568 "Soins infirmiers orientation Santé mentale"
* $TRE-R211-ActiviteOperationnelle#569 "Soins infirmiers orientation Cardiologie"
* $TRE-R211-ActiviteOperationnelle#570 "Soins infirmiers orientation Respiratoire"
* $TRE-R211-ActiviteOperationnelle#571 "Soins infirmiers orientation Soins palliatifs"
* $TRE-R211-ActiviteOperationnelle#572 "Soins infirmiers orientation Neurologie"
* $TRE-R211-ActiviteOperationnelle#573 "Soins infirmiers orientation Diabète"
* $TRE-R211-ActiviteOperationnelle#574 "Ergothérapie orientation accompagnement dans le cadre des maladies chroniques"
* $TRE-R211-ActiviteOperationnelle#575 "Ergothérapie orientation compensation matérielle dans l'environnement de la personne"
* $TRE-R211-ActiviteOperationnelle#576 "Ergothérapie orientation Gériatrie"
* $TRE-R211-ActiviteOperationnelle#577 "Ergothérapie orientation Neurologie"
* $TRE-R211-ActiviteOperationnelle#578 "Ergothérapie orientation Pédiatrie"
* $TRE-R211-ActiviteOperationnelle#579 "Ergothérapie orientation Psychiatrie et Santé mentale"
* $TRE-R211-ActiviteOperationnelle#580 "Evaluation en ergothérapie par l'analyse d'activité et accompagnement dans l'environnement de la personne"
* $TRE-R211-ActiviteOperationnelle#581 "Interventions éducatives pour renforcer l'autorégulation"
* $TRE-R211-ActiviteOperationnelle#582 "Orientation vers professionnel pour diagnostic"
* $TRE-R211-ActiviteOperationnelle#583 "Dialyse péritonéale"
* $TRE-R211-ActiviteOperationnelle#584 "Diététique des Troubles des Conduites Alimentaires (TCA)"
* $TRE-R211-ActiviteOperationnelle#585 "Diététique orientation Dénutrition"
* $TRE-R211-ActiviteOperationnelle#586 "Diététique orientation Gynécologie / Obstétrique"
* $TRE-R211-ActiviteOperationnelle#587 "Diététique orientation maladies inflammatoires et malabsorptives (MICI, SII, NASH)"
* $TRE-R211-ActiviteOperationnelle#588 "Diététique orientation Nutrition du sportif"
* $TRE-R211-ActiviteOperationnelle#589 "Diététique orientation Périnatalité"
* $TRE-R211-ActiviteOperationnelle#590 "Échographie gynécologique"
* $TRE-R211-ActiviteOperationnelle#591 "Ostéopathie médicale"
* $TRE-R211-ActiviteOperationnelle#592 "Prévention et lutte contre la tuberculose"
* $TRE-R211-ActiviteOperationnelle#593 "Prise en charge coordonnée des patients atteints de maladies rares"
* $TRE-R211-ActiviteOperationnelle#594 "Coordination hospitalière de prélèvement de tissu"
* $TRE-R211-ActiviteOperationnelle#595 "Coordination hospitalière de prélèvement de tissu pédiatrique"
* $TRE-R211-ActiviteOperationnelle#596 "Coordination hospitalière de prélèvement d’organe pédiatrique"
* $TRE-R211-ActiviteOperationnelle#597 "Evaluation de la mémoire (bilan mémoire)"
* $TRE-R211-ActiviteOperationnelle#598 "Toxicologie clinique"
* $TRE-R211-ActiviteOperationnelle#599 "Analyse toxicologique"
* $TRE-R211-ActiviteOperationnelle#600 "Prise en charge des malaises et surdoses liés à la prise de drogues"
* $TRE-R211-ActiviteOperationnelle#601 "Médiation pour le maintien en hospitalisation"
* $TRE-R211-ActiviteOperationnelle#602 "Pair aidance pour l'autodétermination"
* $TRE-R211-ActiviteOperationnelle#603 "Prise en charge coordonnée des patients atteints de maladies neurodégénératives"
* $TRE-R211-ActiviteOperationnelle#604 "Chirurgie pédiatrique spécialisée orthopédique"
* $TRE-R211-ActiviteOperationnelle#605 "Chirurgie pédiatrique spécialisée digestif et viscérale"
* $TRE-R211-ActiviteOperationnelle#606 "Accompagnement pour l’autodétermination de la personne"
* $TRE-R211-ActiviteOperationnelle#607 "Fonction-ressource : expertise-conseils auprès des acteurs du secteur sanitaire"
* $TRE-R211-ActiviteOperationnelle#608 "Fonction-ressource : expertise-conseils auprès des acteurs du milieu ordinaire"
* $TRE-R211-ActiviteOperationnelle#609 "Fonction-ressource : expertise-conseils auprès de acteurs du secteur judiciaire"
* $TRE-R211-ActiviteOperationnelle#610 "Pédiatrie spécialisée neurologie"
* $TRE-R211-ActiviteOperationnelle#611 "Pédiatrie spécialisée pneumologie"
* $TRE-R211-ActiviteOperationnelle#612 "Psychiatrie de crise"
* $TRE-R211-ActiviteOperationnelle#613 "Echographie obstétricale de diagnostic"
* $TRE-R211-ActiviteOperationnelle#614 "Soins infirmiers en pratique avancée en pathologies chroniques stabilisées"
* $TRE-R211-ActiviteOperationnelle#615 "Soins infirmiers en pratique avancée en oncologie et hémato-oncologie"
* $TRE-R211-ActiviteOperationnelle#616 "Soins infirmiers en pratique avancée en maladie rénale chronique"
* $TRE-R211-ActiviteOperationnelle#617 "Soins infirmiers en pratique avancée en santé mentale"
* $TRE-R211-ActiviteOperationnelle#618 "Collecte de don de lait maternel cru"
* $TRE-R211-ActiviteOperationnelle#619 "Distribution de lait maternel pasteurisé"
* $TRE-R211-ActiviteOperationnelle#620 "Bilan psychomoteur"
* $TRE-R211-ActiviteOperationnelle#621 "Soin psychomoteur"
* $TRE-R211-ActiviteOperationnelle#622 "Education psychomotrice (pédagogie du développement psychomoteur)"
* $TRE-R211-ActiviteOperationnelle#623 "Stimulation psychomotrice (stimulation du fonctionnement psychomoteur à visée préventive)"
* $TRE-R211-ActiviteOperationnelle#624 "Rééducation de la graphomotricité et de l’écriture (dysgraphie)"
* $TRE-R211-ActiviteOperationnelle#625 "Orthoptie : orientation troubles neuro-visuels (pathologies neurologiques, maladies neurodégénératives)"
* $TRE-R211-ActiviteOperationnelle#626 "Orthoptie orientation basse vision"
* $TRE-R211-ActiviteOperationnelle#627 "Orthoptie orientation pédiatrique"
* $TRE-R211-ActiviteOperationnelle#628 "Dispensation de médicaments et autres produits de santé appartenant au monopole pharmaceutique"
* $TRE-R211-ActiviteOperationnelle#629 "Conseil et accompagnement dans la gestion des traitements"
* $TRE-R211-ActiviteOperationnelle#630 "Evaluation et accompagnement des auteurs de violences conjugales"
* $TRE-R211-ActiviteOperationnelle#631 "Prise en charge et coordination de plaies et cicatrisations complexes"