ValueSet: JDV_J59_ContentTypeCode_DMP
Id: JDV-J59-ContentTypeCode-DMP
Description: "Jeu de valeurs pour contentTypeCode"
* ^meta.versionId = "7"
* ^meta.lastUpdated = "2025-07-02T17:06:39.953+00:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-01-18T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J59-ContentTypeCode-DMP/FHIR/JDV-J59-ContentTypeCode-DMP"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.2"
* ^version = "20240927120000"
* ^status = #active
* ^experimental = false
* ^date = "2024-09-27T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FR
* $TRE-A00-ProducteurDocNonPS#EXP_PATIENT "Expression personnelle du patient"
* $TRE-R276-FormeActivite#05 "Hospitalisation à domicile (au domicile du patient)"
* $TRE-R276-FormeActivite#11 "Centre postcure"
* $TRE-R276-FormeActivite#12 "Centre de crise"
* $TRE-R209-TypeActivite#03 "Hospitalisation complète (non compris hospitalisation de semaine)"
* $TRE-R209-TypeActivite#04 "Hospitalisation de jour"
* $TRE-R209-TypeActivite#07 "Consultations soins externes"
* $TRE-R209-TypeActivite#08 "Bloc opératoire (y compris obstétrical et gynécologique)"
* $TRE-R209-TypeActivite#09 "Autres unités médico-techniques (anesthésiologie, explor fonct, rééduc et réadapt fonct, pharmacie)"
* $TRE-R209-TypeActivite#11 "Hébergement complet ou internat (non compris internat de semaine)"
* $TRE-R209-TypeActivite#13 "Semi-internat"
* $TRE-R209-TypeActivite#14 "Externat"
* $TRE-R209-TypeActivite#15 "Placement en famille d'accueil (strictement social)"
* $TRE-R209-TypeActivite#16 "Prestations sur le lieu de vie (non compris placement familial)"
* $TRE-R209-TypeActivite#17 "Internat de semaine"
* $TRE-R209-TypeActivite#18 "Hébergement de nuit en structure éclatée"
* $TRE-R209-TypeActivite#19 "Traitement et cure ambulatoire"
* $TRE-R209-TypeActivite#20 "Hospitalisation de semaine"
* $TRE-R209-TypeActivite#21 "Accueil de Jour (sans distinction entre semi-internat et externat)"
* $TRE-R209-TypeActivite#22 "Accueil de nuit"
* $TRE-R209-TypeActivite#25 "Accueil temporaire week-end ou vacances"
* $TRE-R209-TypeActivite#26 "Analyses médicales biologiques"
* $TRE-R209-TypeActivite#27 "Accueil modulable/séquentiel"
* $TRE-R209-TypeActivite#28 "Consultations dentaires et soins dentaires"
* $TRE-R209-TypeActivite#33 "Recherche"
* $TRE-R209-TypeActivite#37 "Accueil et prise en charge en appartement thérapeutique"
* $TRE-R209-TypeActivite#40 "Accueil temporaire avec hébergement"
* $TRE-R209-TypeActivite#42 "Equipe mobile de rue"
* $TRE-R209-TypeActivite#43 "Tous modes d'accueil avec hébergement"
* $TRE-R209-TypeActivite#44 "Accueil temporaire de jour"
* $TRE-R209-TypeActivite#45 "Accueil temporaire (avec et sans hébergement)"
* $TRE-R209-TypeActivite#46 "Tous modes d'accueil (avec et sans hébergement)"
* $TRE-R209-TypeActivite#47 "Accueil de jour et accompagnement en milieu ordinaire"
* $TRE-R209-TypeActivite#48 "Tous modes d'accueil et d'accompagnement"
* $TRE-R209-TypeActivite#50 "Protection juridique"
* $TRE-R209-TypeActivite#52 "Accompagnement social personnalisé"
* $TRE-R209-TypeActivite#60 "Consultations et actes"
* $TRE-R209-TypeActivite#97 "Type d'activité indifférencié"
* $TRE-R02-SecteurActivite#SA05 "Centre de santé"
* $TRE-R02-SecteurActivite#SA06 "Autre structure du Service de santé des armées"
* $TRE-R02-SecteurActivite#SA07 "Cabinet individuel"
* $TRE-R02-SecteurActivite#SA08 "Cabinet de groupe"
* $TRE-R02-SecteurActivite#SA09 "Exercice en société"
* $TRE-R02-SecteurActivite#SA10 "Transporteur sanitaire"
* $TRE-R02-SecteurActivite#SA11 "Entreprise d'intérim"
* $TRE-R02-SecteurActivite#SA12 "Etablissement de soins et prévention"
* $TRE-R02-SecteurActivite#SA13 "Prévention et soins en entreprise"
* $TRE-R02-SecteurActivite#SA14 "Etablissements scolaires, universitaires et de formation hors champ FINESS"
* $TRE-R02-SecteurActivite#SA15 "PMI et Planification familiale"
* $TRE-R02-SecteurActivite#SA16 "Etablissement pour personnes handicapées"
* $TRE-R02-SecteurActivite#SA17 "Etablissement pour personnes âgées"
* $TRE-R02-SecteurActivite#SA18 "Etablissement aide à la famille"
* $TRE-R02-SecteurActivite#SA19 "Etablissements FINESS de formation aux professions sanitaires et sociales"
* $TRE-R02-SecteurActivite#SA20 "Etablissement pour la protection de l'enfance"
* $TRE-R02-SecteurActivite#SA21 "Etablissement d'hébergement et de réadaptation"
* $TRE-R02-SecteurActivite#SA22 "Recherche"
* $TRE-R02-SecteurActivite#SA23 "Assurance privée"
* $TRE-R02-SecteurActivite#SA24 "Organisme de sécurité sociale"
* $TRE-R02-SecteurActivite#SA25 "Laboratoire de biologie médicale"
* $TRE-R02-SecteurActivite#SA26 "Ministère ou Service déconcentré"
* $TRE-R02-SecteurActivite#SA27 "Collectivité territoriale"
* $TRE-R02-SecteurActivite#SA28 "Association ou organisme humanitaire"
* $TRE-R02-SecteurActivite#SA29 "Laboratoire d'analyses et de biologie médicale"
* $TRE-R02-SecteurActivite#SA30 "Autre établissement sanitaire"
* $TRE-R02-SecteurActivite#SA31 "Répartition et Distribution de médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA32 "Fabrication, Exploitation et Importation de médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA33 "Pharmacie d'officine"
* $TRE-R02-SecteurActivite#SA34 "Centre de dialyse"
* $TRE-R02-SecteurActivite#SA35 "Para-pharmacie"
* $TRE-R02-SecteurActivite#SA36 "Centre anti-cancer"
* $TRE-R02-SecteurActivite#SA37 "Centre de transfusion sanguine"
* $TRE-R02-SecteurActivite#SA38 "Pharmacie minière"
* $TRE-R02-SecteurActivite#SA39 "Pharmacie mutualiste"
* $TRE-R02-SecteurActivite#SA40 "Secteur privé, praticien hospitalier temps plein"
* $TRE-R02-SecteurActivite#SA41 "Autre établissement du domaine social ou médico-social"
* $TRE-R02-SecteurActivite#SA42 "Appareillage médical"
* $TRE-R02-SecteurActivite#SA43 "Secteur non défini"
* $TRE-R02-SecteurActivite#SA44 "Recrutement ou Gestion RH"
* $TRE-R02-SecteurActivite#SA45 "Communication, Marketing, Consulting, Média"
* $TRE-R02-SecteurActivite#SA46 "Fabrication, Exploitation, Importation, Répartition, Distribution médicaments et dispositifs médicaux"
* $TRE-R02-SecteurActivite#SA47 "Incendie et secours"
* $TRE-R02-SecteurActivite#SA48 "Entreprise industrielle et tertiaire hors industrie pharmaceutique"
* $TRE-R02-SecteurActivite#SA49 "Entité Outre-Mer"
* $TRE-R02-SecteurActivite#SA50 "Permanence des soins ambulatoires hors cabinet"
* $TRE-R02-SecteurActivite#SA51 "Structure de coopération avec autorisation de soins"
* $TRE-R02-SecteurActivite#SA52 "Maison de santé ou Pôle de santé"
* $TRE-R02-SecteurActivite#SA53 "Siège administratif d'un établissement de santé"
* $TRE-R02-SecteurActivite#SA54 "Centre de dépistage et de prévention"
* $TRE-R02-SecteurActivite#SA55 "Laboratoire pharmaceutique préparant et délivrant des allergènes"
* $TRE-R02-SecteurActivite#SA56 "Propharmacie"
* $TRE-R02-SecteurActivite#SA57 "Structure de coopération avec mission de coordination de soins"
* $TRE-R02-SecteurActivite#SA58 "Entreprise de taxis"
* $TRE-R02-SecteurActivite#SA59 "Laboratoire de biologie médicale hors catégorie standard"
* $TRE-R02-SecteurActivite#SA60 "Centres médicaux SNCF"
* $TRE-R02-SecteurActivite#SA61 "Structure Dispensatrice à domicile d'Oxygène à usage médical"
* $TRE-R02-SecteurActivite#SA63 "Communauté Professionnelle Territoriale de Santé"
* $TRE-R02-SecteurActivite#SA64 "Société de téléconsultation"
* $TRE-R02-SecteurActivite#SA65 "Antenne de pharmacie"
* $TRE-R02-SecteurActivite#SA68 "Services départementaux d'incendie et de secours"
* $TRE-R02-SecteurActivite#SA69 "Maisons de naissance"