ValueSet: JDV_J05_SubjectRole_CISIS
Id: JDV-J05-SubjectRole-CISIS
Description: "subjectRole CI-SIS"
* ^meta.versionId = "31"
* ^meta.lastUpdated = "2026-07-29T08:04:44.548+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2012-10-06T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J05-SubjectRole-CISIS/FHIR/JDV-J05-SubjectRole-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.470"
* ^version = "20260928120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-09-28T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-A00-ProducteurDocNonPS#ALIM_AM "Alimentation automatique à partir du Système d'Information de l'Assurance Maladie"
* $TRE-A00-ProducteurDocNonPS#DISPOSITIF "Dispositif médical"
* $TRE-A00-ProducteurDocNonPS#EXP_PATIENT "Expression personnelle du patient"
* $TRE-A00-ProducteurDocNonPS#SECRETARIAT_MEDICAL "Secrétariat médical"
* $TRE-A00-ProducteurDocNonPS#AUTOMATE "Automate"
* $TRE-G15-ProfessionSante#10 "Médecin"
* $TRE-G15-ProfessionSante#21 "Pharmacien"
* $TRE-G15-ProfessionSante#26 "Audioprothésiste"
* $TRE-G15-ProfessionSante#28 "Opticien-Lunetier"
* $TRE-G15-ProfessionSante#31 "Assistant dentaire"
* $TRE-G15-ProfessionSante#32 "Physicien médical"
* $TRE-G15-ProfessionSante#40 "Chirurgien-Dentiste"
* $TRE-G15-ProfessionSante#50 "Sage-Femme"
* $TRE-G15-ProfessionSante#60 "Infirmier"
* $TRE-G15-ProfessionSante#69 "Infirmier psychiatrique"
* $TRE-G15-ProfessionSante#70 "Masseur-Kinésithérapeute"
* $TRE-G15-ProfessionSante#80 "Pédicure-Podologue"
* $TRE-G15-ProfessionSante#81 "Orthoprothésiste"
* $TRE-G15-ProfessionSante#82 "Podo-Orthésiste"
* $TRE-G15-ProfessionSante#83 "Orthopédiste-Orthésiste"
* $TRE-G15-ProfessionSante#84 "Oculariste"
* $TRE-G15-ProfessionSante#85 "Epithésiste"
* $TRE-G15-ProfessionSante#86 "Technicien de laboratoire médical"
* $TRE-G15-ProfessionSante#91 "Orthophoniste"
* $TRE-G15-ProfessionSante#92 "Orthoptiste"
* $TRE-G15-ProfessionSante#94 "Ergothérapeute"
* $TRE-G15-ProfessionSante#95 "Diététicien"
* $TRE-G15-ProfessionSante#96 "Psychomotricien"
* $TRE-G15-ProfessionSante#98 "Manipulateur ERM"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R291-AutreProfession#99 "Acteur participant au système de santé caractérisé par rôle"
* $TRE-G16-ProfessionFormation#10 "Médecin en formation"
* $TRE-G16-ProfessionFormation#21 "Pharmacien en formation"
* $TRE-G16-ProfessionFormation#40 "Chirurgien-Dentiste en formation"
* $TRE-G16-ProfessionFormation#50 "Sage-Femme en formation"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SCD01 "Orthopédie dento-faciale (SCD)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SCD02 "Chirurgie orale (SCD)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SCD03 "Médecine bucco-dentaire (SCD)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#PAC00 "Qualification Praticien adjoint contractuel (PAC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM01 "Anatomie et Cytologie pathologiques (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM02 "Anesthésie-réanimation (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM03 "Biologie médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM04 "Cardiologie et Maladies vasculaires (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM05 "Chirurgie générale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM06 "Chirurgie maxillo-faciale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM07 "Chirurgie maxillo-faciale et Stomatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM08 "Chirurgie orthopédique et Traumatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM09 "Chirurgie infantile (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM10 "Chirurgie plastique reconstructrice et esthétique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM11 "Chirurgie thoracique et cardio-vasculaire (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM12 "Chirurgie urologique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM13 "Chirurgie vasculaire (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM14 "Chirurgie viscérale et digestive (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM15 "Dermatologie et vénéréologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM16 "Endocrinologie et métabolisme (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM17 "Génétique médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM18 "Gériatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM19 "Gynécologie médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM20 "Gynécologie-obstétrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM21 "Hématologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM22 "Hématologie, option Maladie du sang (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM23 "Hématologie, option Onco-hématologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM24 "Gastro-entérologie et Hépatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM25 "Médecine du travail (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM26 "Qualifié en Médecine générale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM27 "Médecine interne (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM28 "Médecine nucléaire (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM29 "Médecine physique et réadaptation (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM30 "Néphrologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM31 "Neuro-chirurgie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM32 "Neurologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM33 "Neuro-psychiatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM34 "ORL et Chirurgie cervico-faciale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM35 "Oncologie, option Onco-hématologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM36 "Oncologie, option médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM37 "Oncologie, option radiothérapie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM38 "Ophtalmologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM39 "Oto-rhino-laryngologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM40 "Pédiatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM41 "Pneumologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM42 "Psychiatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM43 "Psychiatrie, option enfant et adolescent (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM44 "Radio-diagnostic (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM45 "Radio-thérapie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM46 "Médecine intensive-réanimation (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM47 "Recherche médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM48 "Rhumatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM49 "Santé publique et Médecine sociale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM50 "Stomatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM51 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-obstétrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM52 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM53 "Spécialiste en Médecine générale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM54 "Médecine générale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM55 "Radio-diagnostic et Radio-thérapie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM56 "Chirurgie orale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM57 "Allergologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM58 "Maladies infectieuses et tropicales (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM59 "Médecine d'urgence (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM60 "Médecine légale et expertises médicales (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM61 "Médecine vasculaire (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM62 "Endocrinologie, diabétologie, nutrition (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM63 "Biologie médicale option biologie générale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM64 "Biologie médicale option médecine moléculaire, génétique et pharmacologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM65 "Biologie médicale option hématologie et immunologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM66 "Biologie médicale option agents infectieux (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM67 "Biologie médicale option biologie de la reproduction (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM68 "Chirurgie maxillo-faciale (réforme 2017) (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM69 "Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM70 "Chirurgie pédiatrique option orthopédie pédiatrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM71 "Hématologie (réforme 2017) (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM72 "Médecine interne et immunologie clinique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM73 "Médecine cardiovasculaire (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM74 "Radiologie et imagerie médicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM75 "Santé publique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM76 "Anesthésie-réanimation option anesthésie-pédiatrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM77 "Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM78 "Chirurgie viscérale et digestive option endoscopie chirurgicale (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM79 "Médecine cardiovasculaire option cardiologie interventionnelle (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM80 "Médecine cardiovasculaire option imagerie cardio d'expert (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM81 "Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM82 "Médecine intensive-réanimation option réanimation pédiatrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM83 "Néphrologie option soins intensifs néphrologiques (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM84 "Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM85 "Ophtalmo option chirurgie ophtalmopédiatrique et strabologique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM86 "ORL et chirurgie cervico-faciale option audiophonologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM87 "Pédiatrie option néonatologie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM88 "Pédiatrie option neuropédiatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM89 "Pédiatrie option pneumopédiatrie (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM90 "Pédiatrie option réanimation pédiatrique (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM91 "Pneumologie option soins intensifs respiratoires (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM92 "Psychiatrie option enfant et adolescent (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM93 "Psychiatrie option psychiatrie personne âgée (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM94 "Radiologie imagerie médicale option radiologie interventionnelle avancée (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SM95 "Santé publique option administration de la santé (SM)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CEX22 "Gynécologie médicale et obstétrique (CEX)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CEX24 "Gynécologie médicale (CEX)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CEX26 "Obstétrique (CEX)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CEX64 "Urologie (CEX)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI01 "Infirmier(ère) en pratique avancée Pathologies chroniques stabilisées (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI02 "Infirmier(ère) en pratique avancée Oncologie et hémato-oncologie (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI03 "Infirmier(ère) en pratique avancée Maladie rénale chronique, dialyse, transplantation rénale (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI04 "Infirmier(ère) en pratique avancée Psychiatrie et santé mentale (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI05 "Infirmier(ère) en pratique avancée Urgences (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI06 "Infirmier(ère) de bloc opératoire (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI07 "Infirmier(ère) anesthésiste (SI)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SI08 "Infirmier(ère) puériculteur(trice)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C01 "Anatomie et Cytologie pathologiques humaines (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C03 "Anesthésie-réanimation (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C05 "Médecine appliquée aux sports (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C07 "Cardiologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C09 "Chirurgie plastique, reconstructrice et esthétique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C10 "Chirurgie maxillo-faciale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C11 "Chirurgie thoracique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C12 "Chirurgie orthopédique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C13 "Urologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C15 "Dermato-vénéréologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C20 "Hémobiologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C23 "Gynécologie médicale et Obstétrique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C25 "Gynécologie médicale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C27 "Obstétrique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C29 "Maladies de l'appareil digestif (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C30 "Néphrologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C31 "Médecine exotique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C33 "Allergologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C34 "Angéiologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C35 "Cancérologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C36 "Diabétologie-nutrition (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C37 "Endocrinologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C38 "Maladies du sang (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C39 "Réanimation (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C40 "Médecine légale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C41 "Médecine du travail (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C43 "Neurologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C45 "Neuro-chirurgie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C47 "Neuro-psychiatrie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C51 "Pédiatrie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C52 "Phoniatrie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C54 "Pneumologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C57 "Psychiatrie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C58 "Psychiatrie, option enfant et adolescent (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C60 "Médecine physique et réadaptation (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C62 "Rhumatologie (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C68 "Chirurgie pédiatrique (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C69 "Médecine nucléaire (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C71 "Médecine thermale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C72 "Génétique médicale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C75 "Endocrinologie Maladies métaboliques (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C76 "Orthopédie dento-maxillo-faciale (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#C83 "Chirurgie face et cou (C)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA01 "Addictologie clinique (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA02 "Aide médicale urgente (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA03 "Allergologie (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA04 "Angéiologie (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA05 "Evaluation et Traitement de la douleur (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA06 "Gérontologie (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA07 "Hydrologie et Climatologie médicales (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA08 "Médecine aérospatiale (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA09 "Médecine de catastrophe (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA10 "Médecine et Biologie du sport (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA11 "Médecine de santé au travail et Prévention des risques professionnels (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA12 "Médecine pénitentiaire (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA13 "Médecine tropicale (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA14 "Pratiques médico-judiciaires (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA15 "Technologie transfusionnelle (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#CAPA16 "Toxicomanies et Alcoologies (CAPA)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM200 "Addictologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM201 "Allergologie et Immunologie clinique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM202 "Andrologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM203 "Biochimie hormonale et métabolique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM204 "Biologie des agents infectieux (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM205 "Biologie moléculaire (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM206 "Cancérologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM207 "Chirurgie de la face et du cou (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM208 "Chirurgie plastique et reconstructrice (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM209 "Chirurgie vasculaire (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM210 "Cytogénétique humaine (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM211 "Dermatopathologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM212 "Foetopathologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM213 "Gériatrie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM214 "Hématologie biologique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM215 "Hématologie maladies du sang (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM216 "Hémobiologie-transfusion (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM217 "Immunologie et Immunopathologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM218 "Médecine de la reproduction (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM219 "Médecine du sport (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM220 "Médecine d'urgence (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM221 "Médecine légale et Expertises médicales (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM222 "Médecine nucléaire (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM223 "Médecine vasculaire (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM224 "Néonatalogie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM225 "Neuropathologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM226 "Nutrition (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM227 "Orthopédie dento-maxillo-faciale (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM228 "Pathologie infectieuse et tropicale, clinique et biologique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM229 "Pharmacocinétique et Métabolisme des médicaments (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM230 "Pharmacologie clinique et Evaluation des thérapeutiques (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM231 "Psychiatrie de l'enfant et de l'adolescent (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM232 "Radiopharmacie et radiobiologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM233 "Réanimation médicale (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM234 "Toxicologie biologique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM235 "Médecine de la douleur et Médecine palliative (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM236 "Cancérologie, option Traitements médicaux des cancers (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM237 "Cancérologie, option Chirurgie cancérologique (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM238 "Cancérologie, option Réseaux de cancérologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM239 "Cancérologie, option Biologie cancérologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DSM240 "Cancérologie, option Imagerie cancérologie (DNQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#80 "Homéopathie (OP)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#81 "Acupuncture (OP)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC01 "Addictologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC02 "Allergologie et immunologie clinique (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC03 "Andrologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC04 "Cancérologie option traitements médicaux des cancers (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC05 "Cancérologie option chiruggie cancérologique (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC06 "Cancérologie option réseaux de cancérologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC07 "Cancérologie option biologie en cancérologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC08 "Cancérologie option imagerie en cancérologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC09 "Dermatopathologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC10 "Foetopathologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC11 "Hémobiologie - tranfusion (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC12 "Médecine de la douleur et médecine palliative (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC13 "Médecine de la reproduction (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC14 "Médecine d'urgence (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC15 "Médecine du sport (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC16 "Médecine légale et expertises médicales (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC17 "Médecine vasculaire (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC18 "Néonatologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC19 "Neuropathologie (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC20 "Nutrition (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC21 "Orthopédie dento-maxillo-faciale (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC22 "Pathologie infectieuse et tropicale, clinique et biologique (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC23 "Pharmacologie clinique et évaluation des thérapeutiques (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#DEC24 "Psychiatrie de l'enfant et de l'adolescent (DEC)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#FQ01 "Expérience prat. art. R.5124-16 du CSP Fabricant (FQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#FQ02 "Expérience prat. art. R.5124-16 du CSP Exploitant (FQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#FQ03 "Exp. prat. art. R.5124-16 du CSP Thérapie Cellulaire (FQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#FQ04 "Expérience pratique article R.5124-18 du CSP (FQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#FQ05 "Expérience pratique article R.5141-129 du CSP (FQ)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST01 "Addictologie (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST02 "Bio-informatique médicale (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST03 "Cancérologie déc. hémato-cancérologie pédiatrique (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST04 "Cancérologie traitements médicaux des cancers (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST05 "Cardiologie pédiatrique et congénitale (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST06 "Chirurgie de la main (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST07 "Chirurgie en situation de guerre ou de catastrophe (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST08 "Chirurgie orbito-palpébro-lacrymale (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST09 "Douleur (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST10 "Expertise médicale-préjudice corporel (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST11 "Foetopathologie (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST12 "Génétique et médecine moléculaire bioclinique (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST13 "Hématologie bioclinique (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST14 "Hygiène-prévention de l'infection, résistances (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST15 "Maladies allergiques (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST16 "Médecine hospitalière polyvalente (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST17 "Médecine palliative (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST18 "Médecine scolaire (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST19 "Médecine en situation de guerre ou en SSE (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST20 "Médecine et biologie de la reproduction-andrologie (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST21 "Médecine du sport (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST22 "Nutrition appliquée (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST23 "Pharmacologie médicale/thérapeutique (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST24 "Sommeil (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST25 "Thérapie cellulaire/transfusion (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST26 "Urgences pédiatriques (SST)"
* $TRE-R01-EnsembleSavoirFaire-CISIS#SST27 "Innovation et recherche en sciences biologiques et pharmaceutiques (SST)"
* $TRE-G05-SousSectionTableauCNOP#A "Pharmacien titulaire d'officine"
* $TRE-G05-SousSectionTableauCNOP#B "Pharmacien d'entreprise - industrie"
* $TRE-G05-SousSectionTableauCNOP#C "Pharmacien d'entreprise - distribution"
* $TRE-G05-SousSectionTableauCNOP#D "Pharmacien adjoint, remplaçant ou gérant"
* $TRE-G05-SousSectionTableauCNOP#DA "Pharmacien adjoint"
* $TRE-G05-SousSectionTableauCNOP#DM "Pharmacien mutualiste ou minier"
* $TRE-G05-SousSectionTableauCNOP#E "Pharmacien d'Outre-Mer"
* $TRE-G05-SousSectionTableauCNOP#EA "Pharmacien titulaire d'officine - OM"
* $TRE-G05-SousSectionTableauCNOP#EB "Pharmacien d'entreprise - industrie - OM"
* $TRE-G05-SousSectionTableauCNOP#EC "Pharmacien d'entreprise - distribution - OM"
* $TRE-G05-SousSectionTableauCNOP#ED "Pharmacien adjoint - OM"
* $TRE-G05-SousSectionTableauCNOP#EG "Pharmacien biologiste - OM"
* $TRE-G05-SousSectionTableauCNOP#EH "Pharmacien d'établissement de santé - OM"
* $TRE-G05-SousSectionTableauCNOP#G "Pharmacien biologiste"
* $TRE-G05-SousSectionTableauCNOP#H "Pharmacien d'établissement de santé"
* $TRE-G05-SousSectionTableauCNOP#M "Pharmacien militaire"
* $TRE-R22-GenreActivite#GENR01 "Activité de soin et de pharmacie"
* $TRE-R22-GenreActivite#GENR02 "Activité de soins ou de pharmacien en tant que remplaçant"
* $TRE-R22-GenreActivite#GENR03 "Remplacement dans une activité de soins"
* $TRE-R22-GenreActivite#GENR04 "Activité non soignante"
* $TRE-R22-GenreActivite#GENR06 "Délégation de responsabilité pour continuité de service"
* $TRE-R22-GenreActivite#GENR08 "Activité de coordination et d'orientation"
* $TRE-R22-GenreActivite#GENR09 "Activité de professionnel du secteur social et médico-social exerçant des fonctions administratives ou d'appui à l'organisation de l'accompagnement"
* $TRE-R22-GenreActivite#GENR10 "Activité de professionnel du secteur social et médico-social exerçant des fonctions d'accompagnement à la vie sociale, professionnelle et éducative"
* $TRE-R22-GenreActivite#GENR11 "Activité de professionnel du secteur social et médico-social exerçant des fonctions d'accompagnement au soin"
* $TRE-R22-GenreActivite#GENR12 "Activité de professionnel du social et médico-social exerçant des fonctions d'encadrement et d'organisation de l'accompagnement"
* $TRE-R22-GenreActivite#GENR13 "Activité médico-administrative"
* $TRE-R22-GenreActivite#GENR99 "Autre activité"
* $TRE-R21-Fonction#FON-01 "Titulaire de cabinet"
* $TRE-R21-Fonction#FON-02 "Associé dans une société d'exercice (SEL ou SCP)"
* $TRE-R21-Fonction#FON-03 "Titulaire d'officine"
* $TRE-R21-Fonction#FON-04 "Remplaçant du titulaire d'officine"
* $TRE-R21-Fonction#FON-05 "Adjoint"
* $TRE-R21-Fonction#FON-07 "Gérant après incapacité ou décès"
* $TRE-R21-Fonction#FON-09 "Responsable d'établissement"
* $TRE-R21-Fonction#FON-17 "Collaborateur"
* $TRE-R21-Fonction#FON-18 "Assistant"
* $TRE-R21-Fonction#FON-19 "Praticien Conseil"
* $TRE-R21-Fonction#FON-21 "Médecin scolaire"
* $TRE-R21-Fonction#FON-22 "Remplaçant, intérimaire, intermittent"
* $TRE-R21-Fonction#FON-23 "Gérant"
* $TRE-R21-Fonction#FON-24 "Médecin de santé publique"
* $TRE-R21-Fonction#FON-29 "Médecin du travail"
* $TRE-R21-Fonction#FON-32 "Régulateur libéral"
* $TRE-R21-Fonction#FON-33 "Salarié en poste fixe"
* $TRE-R21-Fonction#FON-36 "Délégué"
* $TRE-R21-Fonction#FON-37 "Gérant de pharmacie à usage intérieur (PUI)"
* $TRE-R21-Fonction#FON-39 "Exercice en PMI"
* $TRE-R21-Fonction#FON-40 "Biologiste responsable"
* $TRE-R21-Fonction#FON-41 "Biologiste médical"
* $TRE-R21-Fonction#FON-42 "Assistant collaborateur"
* $TRE-R21-Fonction#FON-43 "Cadre de santé"
* $TRE-R21-Fonction#FON-45 "Directeur des soins"
* $TRE-R21-Fonction#FON-46 "Enseignant salarié"
* $TRE-R21-Fonction#FON-47 "Etudiant remplaçant, adjoint"
* $TRE-R21-Fonction#FON-48 "Interne"
* $TRE-R21-Fonction#FON-49 "Pharmacien responsable Bonnes Pratiques de Dispensation d'Oxygène"
* $TRE-R21-Fonction#FON-50 "Pharmacien adjoint Bonnes Pratiques de Dispensation d'Oxygène"
* $TRE-R21-Fonction#FON-51 "Remplacement partiel"
* $TRE-R21-Fonction#FON-52 "Etudiant militaire"
* $TRE-R21-Fonction#FON-54 "Permanence des soins ambulatoires hors cabinet"
* $TRE-R21-Fonction#FON-55 "Participation libérale aux missions de service public d'un établissement de santé"
* $TRE-R21-Fonction#FON-56 "Intervention libérale dans le cadre d'un GCS"
* $TRE-R21-Fonction#FON-57 "Docteur junior"
* $TRE-R21-Fonction#FON-58 "Activité en piscine ou bassin"
* $TRE-R21-Fonction#FON-59 "Gérant d'antenne"
* $TRE-R21-Fonction#FON-60 "Pharmacien remplaçant Bonnes Pratiques de Dispensation d'Oxygène"
* $TRE-R21-Fonction#FON-61 "Prestataire de Services"
* $TRE-R21-Fonction#FON-62 "Consultations de solidarité territoriale"
* $TRE-R21-Fonction#FON-63 "Coordonnateur en EHPAD"
* $TRE-R21-Fonction#FON-AU "Fonction non définie"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#331 "Secrétaire assistante médico-administrative"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#336 "Autre professionnel intervenant dans l'accueil et l'orientation des personnes"
* $TRE-R85-RolePriseCharge#337 "Autre professionnel intervenant dans la logistique"
* $TRE-R85-RolePriseCharge#338 "Autre professionnel intervenant dans l'hôtellerie et la restauration"
* $TRE-R85-RolePriseCharge#339 "Autre professionnel intervenant dans la direction de la qualité, hygiène, sécurité et environnement"
* $TRE-R85-RolePriseCharge#340 "Autre professionnel intervenant dans la direction des systèmes d'information"
* $TRE-R85-RolePriseCharge#341 "Autre professionnel intervenant dans la direction des finances et comptabilité"
* $TRE-R85-RolePriseCharge#342 "Autre professionnel intervenant dans la direction de la communication"
* $TRE-R85-RolePriseCharge#343 "Autre professionnel intervenant dans la direction des ressources humaines"
* $TRE-R85-RolePriseCharge#344 "Autre professionnel intervenant dans la direction des affaires médicales"
* $TRE-R85-RolePriseCharge#345 "Autre professionnel intervenant dans le social, éducatif, psychologie et culturel"
* $TRE-R85-RolePriseCharge#346 "Etudiant - infirmier"
* $TRE-R85-RolePriseCharge#347 "Etudiant - aide-soignant"
* $TRE-R85-RolePriseCharge#348 "Etudiant - auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#349 "Etudiant - masseur-kinésithérapeute"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE-R85-RolePriseCharge#353 "Membre de l'équipe de soins"
* $TRE-R85-RolePriseCharge#354 "Externe en médecine"
* $TRE-R85-RolePriseCharge#355 "Externe en odontologie"
* $TRE-R85-RolePriseCharge#356 "Externe en maïeutique"
* $TRE-R85-RolePriseCharge#357 "Externe en pharmacie"
* $TRE-R85-RolePriseCharge#358 "Autre étudiant"
* $TRE-R85-RolePriseCharge#359 "Directeur d'établissement"
* $TRE-R85-RolePriseCharge#360 "Brancardier"
* $TRE-R85-RolePriseCharge#361 "Educateur en activité physique adaptée"
* $TRE-R85-RolePriseCharge#362 "Technicien d'informations médicales"
* $TRE-R85-RolePriseCharge#363 "Attaché de recherche clinique"
* $TRE-R85-RolePriseCharge#364 "Praticien A Diplôme Hors Union Européenne (PADHUE)"
* $TRE-R85-RolePriseCharge#365 "Gestionnaire admissions / frais de séjour / traitement externe"
* $TRE-R85-RolePriseCharge#366 "Archiviste"
* $TRE-R85-RolePriseCharge#367 "Surveillant de nuit"
* $TRE-R85-RolePriseCharge#368 "Animateur"
* $TRE-R85-RolePriseCharge#370 "Opérateur de Soins Non Programmés"
* $TRE-R85-RolePriseCharge#371 "Aide à domicile qualifié(e)"
* $TRE-R85-RolePriseCharge#372 "Aide à domicile"
* $TRE-R85-RolePriseCharge#373 "Technicien d’études cliniques"
* $TRE-R85-RolePriseCharge#374 "Agent d'autorité d'enregistrement"
* $TRE-R85-RolePriseCharge#375 "Conseiller conjugal et familial"
* $TRE-R85-RolePriseCharge#376 "PADHUE - Médecin"
* $TRE-R85-RolePriseCharge#377 "PADHUE - Pharmacien"
* $TRE-R85-RolePriseCharge#378 "PADHUE - Sage Femme"
* $TRE-R85-RolePriseCharge#379 "PADHUE - Chirurgien Dentiste"