ValueSet: JDV_J121_RolePriseCharge_ENREG
Id: JDV-J121-RolePriseCharge-ENREG
Description: "Code des rôles et fonctions pour l'application ENREG"
* ^meta.versionId = "17"
* ^meta.lastUpdated = "2026-07-06T19:04:57.039+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset|4.0.1"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2020-06-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J121-RolePriseCharge-ENREG/FHIR/JDV-J121-RolePriseCharge-ENREG"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.200"
* ^version = "20260505120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-05-05T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#331 "Secrétaire assistante médico-administrative"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#336 "Autre professionnel intervenant dans l'accueil et l'orientation des personnes"
* $TRE-R85-RolePriseCharge#337 "Autre professionnel intervenant dans la logistique"
* $TRE-R85-RolePriseCharge#338 "Autre professionnel intervenant dans l'hôtellerie et la restauration"
* $TRE-R85-RolePriseCharge#339 "Autre professionnel intervenant dans la direction de la qualité, hygiène, sécurité et environnement"
* $TRE-R85-RolePriseCharge#340 "Autre professionnel intervenant dans la direction des systèmes d'information"
* $TRE-R85-RolePriseCharge#341 "Autre professionnel intervenant dans la direction des finances et comptabilité"
* $TRE-R85-RolePriseCharge#342 "Autre professionnel intervenant dans la direction de la communication"
* $TRE-R85-RolePriseCharge#343 "Autre professionnel intervenant dans la direction des ressources humaines"
* $TRE-R85-RolePriseCharge#344 "Autre professionnel intervenant dans la direction des affaires médicales"
* $TRE-R85-RolePriseCharge#345 "Autre professionnel intervenant dans le social, éducatif, psychologie et culturel"
* $TRE-R85-RolePriseCharge#347 "Etudiant - aide-soignant"
* $TRE-R85-RolePriseCharge#348 "Etudiant - auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#349 "Etudiant - masseur-kinésithérapeute"
* $TRE-R85-RolePriseCharge#354 "Externe en médecine"
* $TRE-R85-RolePriseCharge#355 "Externe en odontologie"
* $TRE-R85-RolePriseCharge#356 "Externe en maïeutique"
* $TRE-R85-RolePriseCharge#357 "Externe en pharmacie"
* $TRE-R85-RolePriseCharge#358 "Autre étudiant"
* $TRE-R85-RolePriseCharge#359 "Directeur d'établissement"
* $TRE-R85-RolePriseCharge#360 "Brancardier"
* $TRE-R85-RolePriseCharge#361 "Educateur en activité physique adaptée"
* $TRE-R85-RolePriseCharge#362 "Technicien d'informations médicales"
* $TRE-R85-RolePriseCharge#363 "Attaché de recherche clinique"
* $TRE-R85-RolePriseCharge#364 "Praticien A Diplôme Hors Union Européenne (PADHUE)"
* $TRE-R85-RolePriseCharge#365 "Gestionnaire admissions / frais de séjour / traitement externe"
* $TRE-R85-RolePriseCharge#366 "Archiviste"
* $TRE-R85-RolePriseCharge#367 "Surveillant de nuit"
* $TRE-R85-RolePriseCharge#368 "Animateur"
* $TRE-R85-RolePriseCharge#370 "Opérateur de Soins Non Programmés"
* $TRE-R85-RolePriseCharge#371 "Aide à domicile qualifié(e)"
* $TRE-R85-RolePriseCharge#372 "Aide à domicile"
* $TRE-R85-RolePriseCharge#374 "Agent d'autorité d'enregistrement"
* $TRE-R85-RolePriseCharge#375 "Conseiller conjugal et familial"
* $TRE-R85-RolePriseCharge#376 "PADHUE - Médecin"
* $TRE-R85-RolePriseCharge#377 "PADHUE - Pharmacien"
* $TRE-R85-RolePriseCharge#378 "PADHUE - Sage Femme"
* $TRE-R85-RolePriseCharge#379 "PADHUE - Chirurgien Dentiste"