ValueSet: JDV_J01_XdsAuthorSpecialty_CISIS
Id: JDV-J01-XdsAuthorSpecialty-CISIS
Description: "XDS authorSpecialty CI-SIS"
* ^meta.versionId = "21"
* ^meta.lastUpdated = "2026-07-29T08:04:43.603+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2012-11-12T00:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J01-XdsAuthorSpecialty-CISIS/FHIR/JDV-J01-XdsAuthorSpecialty-CISIS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.1.5.461"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-A00-ProducteurDocNonPS#ALIM_AM "Alimentation automatique à partir du Système d'Information de l'Assurance Maladie"
* $TRE-A00-ProducteurDocNonPS#DISPOSITIF "Dispositif médical"
* $TRE-A00-ProducteurDocNonPS#EXP_PATIENT "Expression personnelle du patient"
* $TRE-A00-ProducteurDocNonPS#SECRETARIAT_MEDICAL "Secrétariat médical"
* $TRE-A00-ProducteurDocNonPS#AUTOMATE "Automate"
* $TRE-A00-ProducteurDocNonPS#SNR "Service numérique référencé"
* $TRE-A00-ProducteurDocNonPS#LOGICIEL_DUI "Logiciel de Dossier Usager Informatisé"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10 "Médecin"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/PAC00 "Médecin - Qualification Praticien adjoint contractuel (PAC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM01 "Médecin - Anatomie et Cytologie pathologiques (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM02 "Médecin - Anesthésie-réanimation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM03 "Médecin - Biologie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM04 "Médecin - Cardiologie et maladies vasculaires (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM05 "Médecin - Chirurgie générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM06 "Médecin - Chirurgie maxillo-faciale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM07 "Médecin - Chirurgie maxillo-faciale et Stomatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM08 "Médecin - Chirurgie orthopédique et Traumatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM09 "Médecin - Chirurgie infantile (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM10 "Médecin - Chirurgie plastique reconstruct et esthétique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM11 "Médecin - Chirurgie thoracique et cardio-vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM12 "Médecin - Chirurgie urologique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM13 "Médecin - Chirurgie vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM14 "Médecin - Chirurgie viscérale et digestive (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM15 "Médecin - Dermatologie et Vénéréologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM16 "Médecin - Endocrinologie et métabolisme (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM17 "Médecin - Génétique médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM18 "Médecin - Gériatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM19 "Médecin - Gynécologie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM20 "Médecin - Gynécologie-obstétrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM21 "Médecin - Hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM22 "Médecin - Hématologie, opt Maladie du sang (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM23 "Médecin - Hématologie, opt Onco-hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM24 "Médecin - Gastro-entérologie et hépatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM25 "Médecin - Médecine du travail (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM26 "Médecin - Qualifié en Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM27 "Médecin - Médecine interne (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM28 "Médecin - Médecine nucléaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM29 "Médecin - Médecine physique et réadaptation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM30 "Médecin - Néphrologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM31 "Médecin - Neuro-chirurgie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM32 "Médecin - Neurologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM33 "Médecin - Neuro-psychiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM34 "Médecin - ORL et Chirurgie cervico-faciale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM35 "Médecin - Oncologie, opt Onco-hématologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM36 "Médecin - Oncologie, opt médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM37 "Médecin - Oncologie, opt radiothérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM38 "Médecin - Ophtalmologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM39 "Médecin - Oto-rhino-laryngologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM40 "Médecin - Pédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM41 "Médecin - Pneumologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM42 "Médecin - Psychiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM43 "Médecin - Psychiatrie, opt enfant et adolescent (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM44 "Médecin - Radio-diagnostic (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM45 "Médecin - Radio-thérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM46 "Médecin - Médecine intensive-réanimation (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM47 "Médecin - Recherche médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM48 "Médecin - Rhumatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM49 "Médecin - Santé publique et Médecine sociale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM50 "Médecin - Stomatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM51 "Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-obs (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM52 "Médecin - Gynéco-obstétrique et Gynéco méd, opt Gyn-méd (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM53 "Médecin - Spécialiste en Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM54 "Médecin - Médecine Générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM55 "Médecin - Radio-diagnostic et Radio-Thérapie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM56 "Médecin - Chirurgie orale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM57 "Médecin - Allergologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM58 "Médecin - Maladies infectieuses et tropicales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM59 "Médecin - Médecine d'urgence (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM60 "Médecin - Médecine légale et expertises médicales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM61 "Médecin - Médecine vasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM62 "Médecin - Endocrinologie, diabétologie, nutrition (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM63 "Médecin - Biologie médicale option biologie générale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM64 "Médecin - Biologie médicale option médecine moléculaire, génétique et pharmacologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM65 "Médecin - Biologie médicale option hématologie et immunologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM66 "Médecin - Biologie médicale option agents infectieux (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM67 "Médecin - Biologie médicale option biologie de la reproduction (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM68 "Médecin - Chirurgie maxillo-faciale (réforme 2017) (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM69 "Médecin - Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM70 "Médecin - Chirurgie pédiatrique option orthopédie pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM71 "Médecin - Hématologie (réforme 2017) (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM72 "Médecin - Médecine interne et immunologie clinique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM73 "Médecin - Médecine cardiovasculaire (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM74 "Médecin - Radiologie et imagerie médicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM75 "Médecin - Santé publique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM76 "Médecin - Anesthésie-réanimation option anesthésie-pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM77 "Médecin - Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM78 "Médecin - Chirurgie viscérale et digestive option endoscopie chirurgicale (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM79 "Médecin - Médecine cardiovasculaire option cardiologie interventionnelle (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM80 "Médecin - Médecine cardiovasculaire option imagerie cardio d'expert (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM81 "Médecin - Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM82 "Médecin - Médecine intensive-réanimation option réanimation pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM83 "Médecin - Néphrologie option soins intensifs néphrologiques (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM84 "Médecin - Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM85 "Médecin - Ophtalmo option chirurgie ophtalmopédiatrique et strabologique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM86 "Médecin - ORL et chirurgie cervico-faciale option audiophonologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM87 "Médecin - Pédiatrie option néonatologie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM88 "Médecin - Pédiatrie option neuropédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM89 "Médecin - Pédiatrie option pneumopédiatrie (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM90 "Médecin - Pédiatrie option réanimation pédiatrique (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM91 "Médecin - Pneumologie option soins intensifs respiratoires (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM92 "Médecin - Psychiatrie option enfant et adolescent (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM93 "Médecin - Psychiatrie option psychiatrie personne âgée (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM94 "Médecin - Radiologie imagerie médicale option radiologie interventionnelle avancée (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SM95 "Médecin - Santé publique option administration de la santé (SM)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX22 "Médecin - Gynécologie médicale et obstétrique (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX24 "Médecin - Gynécologie médicale (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX26 "Médecin - Obstétrique (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CEX64 "Médecin - Urologie (CEX)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C01 "Médecin - Anatomie et Cytologie pathologiques humaines (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C03 "Médecin - Anesthésie-réanimation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C05 "Médecin - Médecine appliquée aux sports (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C07 "Médecin - Cardiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C09 "Médecin - Chirurgie plast reconstruct, esthétique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C10 "Médecin - Chirurgie maxillo-faciale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C11 "Médecin - Chirurgie thoracique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C12 "Médecin - Chirurgie orthopédique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C13 "Médecin - Urologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C15 "Médecin - Dermato-vénéréologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C20 "Médecin - Hémobiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C23 "Médecin - Gynécologie médicale et Obstétrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C25 "Médecin - Gynécologie médicale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C27 "Médecin - Obstétrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C29 "Médecin - Maladies de l'appareil digestif (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C30 "Médecin - Néphrologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C31 "Médecin - Médecine exotique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C33 "Médecin - Allergologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C34 "Médecin - Angéiologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C35 "Médecin - Cancérologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C36 "Médecin - Diabétologie-nutrition (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C37 "Médecin - Endocrinologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C38 "Médecin - Maladies du sang (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C39 "Médecin - Réanimation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C40 "Médecin - Médecine légale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C41 "Médecin - Médecine du travail (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C43 "Médecin - Neurologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C45 "Médecin - Neuro-chirurgie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C47 "Médecin - Neuro-psychiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C51 "Médecin - Pédiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C52 "Médecin - Phoniatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C54 "Médecin - Pneumologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C57 "Médecin - Psychiatrie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C58 "Médecin - Psychiatrie, opt enfant et adolescent (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C60 "Médecin - Médecine physique et réadaptation (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C62 "Médecin - Rhumatologie (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C68 "Médecin - Chirurgie pédiatrique (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C69 "Médecin - Médecine nucléaire (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C71 "Médecin - Médecine thermale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C72 "Médecin - Génétique médicale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C75 "Médecin - Endocrinologie et Maladies métaboliques (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C76 "Médecin - Orthopédie dento-maxillo-faciale (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/C83 "Médecin - Chirurgie face et cou (C)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA01 "Médecin - Addictologie clinique (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA02 "Médecin - Aide médicale urgente (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA03 "Médecin - Allergologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA04 "Médecin - Angéiologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA05 "Médecin - Evaluation et traitement de la douleur (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA06 "Médecin - Gérontologie (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA07 "Médecin - Hydrologie et climatologie médicales (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA08 "Médecin - Médecine aérospatiale (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA09 "Médecin - Médecine de catastrophe (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA10 "Médecin - Médecine et biologie du sport (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA11 "Médecin - Médecine de travail, prév risques prof (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA12 "Médecin - Médecine pénitentiaire (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA13 "Médecin - Médecine tropicale (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA14 "Médecin - Pratiques médico-judiciaires (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA15 "Médecin - Technologie transfusionnelle (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/CAPA16 "Médecin - Toxicomanies et Alcoologies (CAPA)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM200 "Médecin - Addictologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM201 "Médecin - Allergologie et Immunologie clinique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM202 "Médecin - Andrologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM203 "Médecin - Biochimie hormonale et métabolique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM204 "Médecin - Biologie des agents infectieux (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM205 "Médecin - Biologie moléculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM206 "Médecin - Cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM207 "Médecin - Chirurgie de la face et du cou (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM208 "Médecin - Chirurgie plastique et reconstructrice (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM209 "Médecin - Chirurgie vasculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM210 "Médecin - Cytogénétique humaine (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM211 "Médecin - Dermatopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM212 "Médecin - Foetopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM213 "Médecin - Gériatrie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM214 "Médecin - Hématologie biologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM215 "Médecin - Hématologie maladies du sang (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM216 "Médecin - Hémobiologie-transfusion (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM217 "Médecin - Immunologie et Immunopathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM218 "Médecin - Médecine de la reproduction (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM219 "Médecin - Médecine du sport (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM220 "Médecin - Médecine d'urgence (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM221 "Médecin - Médecine légale et Expertises médicales (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM222 "Médecin - Médecine nucléaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM223 "Médecin - Médecine vasculaire (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM224 "Médecin - Néonatalogie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM225 "Médecin - Neuropathologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM226 "Médecin - Nutrition (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM227 "Médecin - Orthopédie dento-maxillo-faciale (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM228 "Médecin - Pathologie infect et trop, clin et bio (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM229 "Médecin - Pharmacocinétique et Métabolisme des méd (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM230 "Médecin - Pharmacologie clin et Eval thérapeutiq (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM231 "Médecin - Psychiatrie de l'enfant et de l'ado (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM232 "Médecin - Radiopharmacie et radiobiologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM233 "Médecin - Réanimation médicale (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM234 "Médecin - Toxicologie biologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM235 "Médecin - Médecine de la douleur et Méd palliative (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM236 "Médecin - Cancérologie, opt Trait méd des cancers (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM237 "Médecin - Cancérologie, opt Chir cancérologique (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM238 "Médecin - Cancérologie, opt Réseaux cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM239 "Médecin - Cancérologie, opt Biologie cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DSM240 "Médecin - Cancérologie, opt Imagerie cancérologie (DNQ)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21 "Pharmacien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/A "Pharmacien titulaire d'officine"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/B "Pharmacien d'entreprise - industrie"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/C "Pharmacien d'entreprise - distribution"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/D "Pharmacien adjoint, remplaçant ou gérant"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/DA "Pharmacien adjoint"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/DM "Pharmacien mutualiste ou minier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/E "Pharmacien d'Outre-Mer"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EA "Pharmacien titulaire d'officine - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EB "Pharmacien d'entreprise - industrie - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EC "Pharmacien d'entreprise - distribution - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/ED "Pharmacien adjoint - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EG "Pharmacien biologiste - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/EH "Pharmacien d'un établissement de santé - OM"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/G "Pharmacien biologiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/H "Pharmacien d'établissement de santé"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/M "Pharmacien militaire"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_26 "Audioprothésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_28 "Opticien-Lunetier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_31 "Assistant dentaire"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_32 "Physicien médical"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40 "Chirurgien-Dentiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD01 "Chirurgien-Dentiste - Orthopédie dento-faciale (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD02 "Chirurgien-Dentiste - Chirurgie orale (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_40/SCD03 "Chirurgien-Dentiste - Médecine bucco-dentaire (SCD)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_50 "Sage-Femme"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60 "Infirmier"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI01 "Infirmier - Exercice infirmier en pratique avancée pathologies chroniques stabilisées (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI02 "Infirmier - Exercice infirmier en pratique avancée oncologie et hémato-oncologie (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI03 "Infirmier - Exerc. infirmier pratique avancée maladie rénale chroniq.,dialyse,transp. rénale (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI04 "Infirmier - Exercice infirmier en pratique avancée santé mentale (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI05 "Infirmier - Exercice infirmier en pratique avancée urgences (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI06 "Infirmier(ère) de bloc opératoire (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI07 "Infirmier(ère) anesthésiste (SI)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_60/SI08 "Infirmier(ère) puériculteur(trice)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_69 "Infirmier psychiatrique"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_70 "Masseur-Kinésithérapeute"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_80 "Pédicure-Podologue"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_81 "Orthoprothésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_82 "Podo-Orthésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_83 "Orthopédiste-Orthésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_84 "Oculariste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_85 "Epithésiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_86 "Technicien de laboratoire médical"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_91 "Orthophoniste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_92 "Orthoptiste"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_94 "Ergothérapeute"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_95 "Diététicien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_96 "Psychomotricien"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_98 "Manipulateur ERM"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_10 "Médecin en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_21 "Pharmacien en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_40 "Chirurgien-Dentiste en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G16_50 "Sage-Femme en formation"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/80 "Médecin - Homéopathie (OP)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/81 "Médecin - Acupuncture (OP)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC01 "Médecin - Addictologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC02 "Médecin - Allergologie et immunologie clinique (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC03 "Médecin - Andrologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC04 "Médecin - Cancérologie option traitements médicaux des cancers (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC05 "Médecin - Cancérologie option chirurgie cancérologique (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC06 "Médecin - Cancérologie option réseaux de cancérologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC07 "Médecin - Cancérologie option biologie en cancérologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC08 "Médecin - Cancérologie option imagerie en cancérologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC09 "Médecin - Dermatopathologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC10 "Médecin - Foetopathologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC11 "Médecin - Hémobiologie - tranfusion (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC12 "Médecin - Médecine de la douleur et médecine palliative (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC13 "Médecin - Médecine de la reproduction (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC14 "Médecin - Médecine d'urgence (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC15 "Médecin - Médecine du sport (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC16 "Médecin - Médecine légale et expertises médicales (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC17 "Médecin - Médecine vasculaire (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC18 "Médecin - Néonatologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC19 "Médecin - Neuropathologie (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC20 "Médecin - Nutrition (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC21 "Médecin - Orthopédie dento-maxillo-faciale (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC22 "Médecin - Pathologie infectieuse et tropicale, clinique et biologique (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC23 "Médecin - Pharmacologie clinique et évaluation des thérapeutiques (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/DEC24 "Médecin - Psychiatrie de l'enfant et de l'adolescent (DEC)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST01 "Médecin - Addictologie (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST02 "Médecin - Bio-informatique médicale (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST03 "Médecin - Cancérologie déc. hémato-cancérologie pédiatrique (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST04 "Médecin - Cancérologie traitements médicaux des cancers (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST05 "Médecin - Cardiologie pédiatrique et congénitale (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST06 "Médecin - Chirurgie de la main (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST07 "Médecin - Chirurgie en situation de guerre ou de catastrophe (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST08 "Médecin - Chirurgie orbito-palpébro-lacrymale (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST09 "Médecin - Douleur (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST10 "Médecin - Expertise médicale-préjudice corporel (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST11 "Médecin - Foetopathologie (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST12 "Médecin - Génétique et médecine moléculaire bioclinique (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST13 "Médecin - Hématologie bioclinique (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST14 "Médecin - Hygiène-prévention de l'infection, résistances (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST15 "Médecin - Maladies allergiques (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST16 "Médecin - Médecine hospitalière polyvalente (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST17 "Médecin - Médecine palliative (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST18 "Médecin - Médecine scolaire (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST19 "Médecin - Médecine en situation de guerre ou en SSE (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST20 "Médecin - Médecine et biologie de la reproduction-andrologie (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST21 "Médecin - Médecine du sport (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST22 "Médecin - Nutrition appliquée (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST23 "Médecin - Pharmacologie médicale/thérapeutique (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST24 "Médecin - Sommeil (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST25 "Médecin - Thérapie cellulaire/transfusion (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST26 "Médecin - Urgences pédiatriques (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_10/SST27 "Médecin - Innovation et recherche en sciences biologiques et pharmaceutiques (SST)"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/FQ01 "Pharmacien - Expérience prat. art. R.5124-16 du CSP Fabricant"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/FQ02 "Pharmacien - Expérience prat. art. R.5124-16 du CSP Exploitant"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/FQ03 "Pharmacien - Exp. prat. art. R.5124-16 du CSP Thérapie Cellulaire"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/FQ04 "Pharmacien - Expérience pratique article R.5124-18 du CSP"
* $TRE-A02-ProfessionSavFaire-CISIS#G15_21/FQ05 "Pharmacien - Expérience pratique article R.5141-129 du CSP"
* $TRE-R95-UsagerTitre#71 "Ostéopathe"
* $TRE-R95-UsagerTitre#72 "Psychothérapeute"
* $TRE-R95-UsagerTitre#73 "Chiropracteur"
* $TRE-R95-UsagerTitre#93 "Psychologue"
* $TRE-R94-ProfessionSocial#41 "Assistant de service social"
* $TRE-R85-RolePriseCharge#300 "Assistant de service social (PAERPA)"
* $TRE-R85-RolePriseCharge#301 "Coordination territoriale d'appui (PAERPA)"
* $TRE-R85-RolePriseCharge#302 "Aide et accompagnement à domicile (PAERPA)"
* $TRE-R85-RolePriseCharge#303 "Avocat participant aux processus de soins sans consentement (eSSS)"
* $TRE-R85-RolePriseCharge#304 "Assistant de service social (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#305 "Psychologue (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#306 "Psychothérapeute (Expérimentation MAIA)"
* $TRE-R85-RolePriseCharge#307 "Mandataire judiciaire à la protection des majeurs (MJPM)"
* $TRE-R85-RolePriseCharge#308 "Pilote MAIA"
* $TRE-R85-RolePriseCharge#309 "Gestionnaire de cas MAIA"
* $TRE-R85-RolePriseCharge#310 "Equipe médico-sociale APA"
* $TRE-R85-RolePriseCharge#311 "Autre acteur mettant en oeuvre la méthode MAIA"
* $TRE-R85-RolePriseCharge#312 "Autre professionnel"
* $TRE-R85-RolePriseCharge#313 "Aide-soignant"
* $TRE-R85-RolePriseCharge#314 "Ambulancier"
* $TRE-R85-RolePriseCharge#315 "Auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#316 "Préparateur en pharmacie hospitalière"
* $TRE-R85-RolePriseCharge#317 "Préparateur en pharmacie"
* $TRE-R85-RolePriseCharge#319 "Technicien de l'intervention sociale et familiale"
* $TRE-R85-RolePriseCharge#320 "Conseiller en économie sociale et familiale"
* $TRE-R85-RolePriseCharge#321 "Médiateur familial"
* $TRE-R85-RolePriseCharge#322 "Assistant familial"
* $TRE-R85-RolePriseCharge#324 "Moniteur éducateur"
* $TRE-R85-RolePriseCharge#325 "Educateur de jeunes enfants"
* $TRE-R85-RolePriseCharge#326 "Educateur spécialisé"
* $TRE-R85-RolePriseCharge#327 "Educateur technique spécialisé"
* $TRE-R85-RolePriseCharge#328 "Accompagnant éducatif et social"
* $TRE-R85-RolePriseCharge#329 "Conseiller en génétique"
* $TRE-R85-RolePriseCharge#330 "Coordonnateur de parcours"
* $TRE-R85-RolePriseCharge#331 "Secrétaire assistante médico-administrative"
* $TRE-R85-RolePriseCharge#333 "Responsable de secteur"
* $TRE-R85-RolePriseCharge#334 "Biologiste médical ni médecin ni pharmacien"
* $TRE-R85-RolePriseCharge#332 "Assistant médical"
* $TRE-R85-RolePriseCharge#335 "Gestionnaire alertes et urgences sanitaires"
* $TRE-R85-RolePriseCharge#336 "Autre professionnel intervenant dans l'accueil et l'orientation des personnes"
* $TRE-R85-RolePriseCharge#337 "Autre professionnel intervenant dans la logistique"
* $TRE-R85-RolePriseCharge#338 "Autre professionnel intervenant dans l'hôtellerie et la restauration"
* $TRE-R85-RolePriseCharge#339 "Autre professionnel intervenant dans la direction de la qualité, hygiène, sécurité et environnement"
* $TRE-R85-RolePriseCharge#340 "Autre professionnel intervenant dans la direction des systèmes d'information"
* $TRE-R85-RolePriseCharge#341 "Autre professionnel intervenant dans la direction des finances et comptabilité"
* $TRE-R85-RolePriseCharge#342 "Autre professionnel intervenant dans la direction de la communication"
* $TRE-R85-RolePriseCharge#343 "Autre professionnel intervenant dans la direction des ressources humaines"
* $TRE-R85-RolePriseCharge#344 "Autre professionnel intervenant dans la direction des affaires médicales"
* $TRE-R85-RolePriseCharge#345 "Autre professionnel intervenant dans le social, éducatif, psychologie et culturel"
* $TRE-R85-RolePriseCharge#346 "Etudiant - infirmier"
* $TRE-R85-RolePriseCharge#347 "Etudiant - aide-soignant"
* $TRE-R85-RolePriseCharge#348 "Etudiant - auxiliaire de puériculture"
* $TRE-R85-RolePriseCharge#349 "Etudiant - masseur-kinésithérapeute"
* $TRE-R85-RolePriseCharge#351 "Assistant(e) maternel(le)"
* $TRE-R85-RolePriseCharge#353 "Membre de l'équipe de soins"
* $TRE-R85-RolePriseCharge#354 "Externe en médecine"
* $TRE-R85-RolePriseCharge#355 "Externe en odontologie"
* $TRE-R85-RolePriseCharge#356 "Externe en maïeutique"
* $TRE-R85-RolePriseCharge#357 "Externe en pharmacie"
* $TRE-R85-RolePriseCharge#358 "Autre étudiant"
* $TRE-R85-RolePriseCharge#359 "Directeur d'établissement"
* $TRE-R85-RolePriseCharge#360 "Brancardier"
* $TRE-R85-RolePriseCharge#361 "Educateur en activité physique adaptée"
* $TRE-R85-RolePriseCharge#362 "Technicien d'informations médicales"
* $TRE-R85-RolePriseCharge#363 "Attaché de recherche clinique"
* $TRE-R85-RolePriseCharge#364 "Praticien A Diplôme Hors Union Européenne (PADHUE)"
* $TRE-R85-RolePriseCharge#365 "Gestionnaire admissions / frais de séjour / traitement externe"
* $TRE-R85-RolePriseCharge#366 "Archiviste"
* $TRE-R85-RolePriseCharge#367 "Surveillant de nuit"
* $TRE-R85-RolePriseCharge#368 "Animateur"
* $TRE-R85-RolePriseCharge#370 "Opérateur de Soins Non Programmés"
* $TRE-R85-RolePriseCharge#371 "Aide à domicile qualifié(e)"
* $TRE-R85-RolePriseCharge#372 "Aide à domicile"
* $TRE-R85-RolePriseCharge#373 "Technicien d’études cliniques"
* $TRE-R85-RolePriseCharge#374 "Agent d'autorité d'enregistrement"
* $TRE-R85-RolePriseCharge#375 "Conseiller conjugal et familial"
* $TRE-R85-RolePriseCharge#376 "PADHUE - Médecin"
* $TRE-R85-RolePriseCharge#377 "PADHUE - Pharmacien"
* $TRE-R85-RolePriseCharge#378 "PADHUE - Sage Femme"
* $TRE-R85-RolePriseCharge#379 "PADHUE - Chirurgien Dentiste"