ValueSet: JDV_J107_EnsembleSavoirFaire_RASS
Id: JDV-J107-EnsembleSavoirFaire-RASS
Description: "Ensemble des savoir-faire et compétences du RASS"
* ^meta.versionId = "12"
* ^meta.lastUpdated = "2026-07-06T19:04:48.245+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2019-08-30T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J107-EnsembleSavoirFaire-RASS/FHIR/JDV-J107-EnsembleSavoirFaire-RASS"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.1.6.1.175"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R38-SpecialiteOrdinale#SI01 "Exercice infirmier en pratique avancée pathologies chroniques stabilisées (SI)"
* $TRE-R38-SpecialiteOrdinale#SI02 "Exercice infirmier en pratique avancée oncologie et hémato-oncologie (SI)"
* $TRE-R38-SpecialiteOrdinale#SI03 "Exercice infirmier en pratique avancée maladie rénale chronique (SI)"
* $TRE-R38-SpecialiteOrdinale#SI04 "Exercice infirmier en pratique avancée santé mentale (SI)"
* $TRE-R38-SpecialiteOrdinale#SI05 "Exercice infirmier en pratique avancée urgences (SI)"
* $TRE-R38-SpecialiteOrdinale#SI06 "Infirmier(ère) de bloc opératoire (SI)"
* $TRE-R38-SpecialiteOrdinale#SI07 "Infirmier(ère) anesthésiste (SI)"
* $TRE-R38-SpecialiteOrdinale#SI08 "Infirmier(ère) puériculteur(trice)"
* $TRE-R38-SpecialiteOrdinale#SCD01 "Orthopédie dento-faciale (SCD)"
* $TRE-R38-SpecialiteOrdinale#SCD02 "Chirurgie orale (SCD)"
* $TRE-R38-SpecialiteOrdinale#SCD03 "Médecine bucco-dentaire (SCD)"
* $TRE-R38-SpecialiteOrdinale#SM01 "Anatomie et Cytologie pathologiques (SM)"
* $TRE-R38-SpecialiteOrdinale#SM02 "Anesthésie-réanimation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM03 "Biologie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM04 "Cardiologie et Maladies vasculaires (SM)"
* $TRE-R38-SpecialiteOrdinale#SM05 "Chirurgie générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM06 "Chirurgie maxillo-faciale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM07 "Chirurgie maxillo-faciale et Stomatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM08 "Chirurgie orthopédique et Traumatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM09 "Chirurgie infantile (SM)"
* $TRE-R38-SpecialiteOrdinale#SM10 "Chirurgie plastique reconstructrice et esthétique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM11 "Chirurgie thoracique et cardio-vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM12 "Chirurgie urologique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM13 "Chirurgie vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM14 "Chirurgie viscérale et digestive (SM)"
* $TRE-R38-SpecialiteOrdinale#SM15 "Dermatologie et Vénéréologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM16 "Endocrinologie et Métabolisme (SM)"
* $TRE-R38-SpecialiteOrdinale#SM17 "Génétique médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM18 "Gériatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM19 "Gynécologie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM20 "Gynécologie-obstétrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM21 "Hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM22 "Hématologie, option Maladie du sang (SM)"
* $TRE-R38-SpecialiteOrdinale#SM23 "Hématologie, option Onco-hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM24 "Gastro-entérologie et Hépatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM25 "Médecine du travail (SM)"
* $TRE-R38-SpecialiteOrdinale#SM26 "Qualifié en Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM27 "Médecine interne (SM)"
* $TRE-R38-SpecialiteOrdinale#SM28 "Médecine nucléaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM29 "Médecine physique et de réadaptation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM30 "Néphrologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM31 "Neuro-chirurgie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM32 "Neurologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM33 "Neuro-psychiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM34 "ORL et Chirurgie cervico-faciale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM35 "Oncologie, option Onco-hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM36 "Oncologie, option médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM37 "Oncologie, option radiothérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM38 "Ophtalmologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM39 "Oto-rhino-laryngologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM40 "Pédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM41 "Pneumologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM42 "Psychiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM43 "Psychiatrie, option enfant et adolescent (SM)"
* $TRE-R38-SpecialiteOrdinale#SM44 "Radio-diagnostic (SM)"
* $TRE-R38-SpecialiteOrdinale#SM45 "Radio-thérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM46 "Médecine intensive-réanimation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM47 "Recherche médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM48 "Rhumatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM49 "Santé publique et Médecine sociale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM50 "Stomatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM51 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-obstétrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM52 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM53 "Spécialiste en Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM54 "Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM55 "Radio-diagnostic et Radio-thérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM56 "Chirurgie orale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM57 "Allergologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM58 "Maladies infectieuses et tropicales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM59 "Médecine d'urgence (SM)"
* $TRE-R38-SpecialiteOrdinale#SM60 "Médecine légale et expertises médicales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM61 "Médecine vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM62 "Endocrinologie, diabétologie, nutrition (SM)"
* $TRE-R38-SpecialiteOrdinale#SM63 "Biologie médicale option biologie générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM64 "Biologie médicale option médecine moléculaire, génétique et pharmacologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM65 "Biologie médicale option hématologie et immunologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM66 "Biologie médicale option agents infectieux (SM)"
* $TRE-R38-SpecialiteOrdinale#SM67 "Biologie médicale option biologie de la reproduction (SM)"
* $TRE-R38-SpecialiteOrdinale#SM68 "Chirurgie maxillo-faciale (réforme 2017) (SM)"
* $TRE-R38-SpecialiteOrdinale#SM69 "Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM70 "Chirurgie pédiatrique option orthopédie pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM71 "Hématologie (réforme 2017) (SM)"
* $TRE-R38-SpecialiteOrdinale#SM72 "Médecine interne et immunologie clinique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM73 "Médecine cardiovasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM74 "Radiologie et imagerie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM75 "Santé publique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM76 "Anesthésie-réanimation option anesthésie-pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM77 "Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM78 "Chirurgie viscérale et digestive option endoscopie chirurgicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM79 "Médecine cardiovasculaire option cardiologie interventionnelle (SM)"
* $TRE-R38-SpecialiteOrdinale#SM80 "Médecine cardiovasculaire option imagerie cardio d'expert (SM)"
* $TRE-R38-SpecialiteOrdinale#SM81 "Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque (SM)"
* $TRE-R38-SpecialiteOrdinale#SM82 "Médecine intensive-réanimation option réanimation pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM83 "Néphrologie option soins intensifs néphrologiques (SM)"
* $TRE-R38-SpecialiteOrdinale#SM84 "Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe (SM)"
* $TRE-R38-SpecialiteOrdinale#SM85 "Ophtalmo option chirurgie ophtalmopédiatrique et strabologique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM86 "ORL et chirurgie cervico-faciale option audiophonologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM87 "Pédiatrie option néonatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM88 "Pédiatrie option neuropédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM89 "Pédiatrie option pneumopédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM90 "Pédiatrie option réanimation pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM91 "Pneumologie option soins intensifs respiratoires (SM)"
* $TRE-R38-SpecialiteOrdinale#SM92 "Psychiatrie option enfant et adolescent (SM)"
* $TRE-R38-SpecialiteOrdinale#SM93 "Psychiatrie option psychiatrie personne âgée (SM)"
* $TRE-R38-SpecialiteOrdinale#SM94 "Radiologie imagerie médicale option radiologie interventionnelle avancée (SM)"
* $TRE-R38-SpecialiteOrdinale#SM95 "Santé publique option administration de la santé (SM)"
* $TRE-R39-Competence#C01 "Anatomie et Cytologie pathologiques humaines (C)"
* $TRE-R39-Competence#C03 "Anesthésie-réanimation (C)"
* $TRE-R39-Competence#C05 "Médecine appliquée aux sports (C)"
* $TRE-R39-Competence#C07 "Cardiologie (C)"
* $TRE-R39-Competence#C09 "Chirurgie plastique, reconstructrice et esthétique (C)"
* $TRE-R39-Competence#C10 "Chirurgie maxillo-faciale (C)"
* $TRE-R39-Competence#C11 "Chirurgie thoracique (C)"
* $TRE-R39-Competence#C12 "Chirurgie orthopédique (C)"
* $TRE-R39-Competence#C13 "Urologie (C)"
* $TRE-R39-Competence#C15 "Dermato-vénéréologie (C)"
* $TRE-R39-Competence#C20 "Hémobiologie (C)"
* $TRE-R39-Competence#C23 "Gynécologie médicale et Obstétrique (C)"
* $TRE-R39-Competence#C25 "Gynécologie médicale (C)"
* $TRE-R39-Competence#C27 "Obstétrique (C)"
* $TRE-R39-Competence#C29 "Maladies de l'appareil digestif (C)"
* $TRE-R39-Competence#C30 "Néphrologie (C)"
* $TRE-R39-Competence#C31 "Médecine exotique (C)"
* $TRE-R39-Competence#C33 "Allergologie (C)"
* $TRE-R39-Competence#C34 "Angéiologie (C)"
* $TRE-R39-Competence#C35 "Cancérologie (C)"
* $TRE-R39-Competence#C36 "Diabétologie-nutrition (C)"
* $TRE-R39-Competence#C37 "Endocrinologie (C)"
* $TRE-R39-Competence#C38 "Maladies du sang (C)"
* $TRE-R39-Competence#C39 "Réanimation (C)"
* $TRE-R39-Competence#C40 "Médecine légale (C)"
* $TRE-R39-Competence#C41 "Médecine du travail (C)"
* $TRE-R39-Competence#C43 "Neurologie (C)"
* $TRE-R39-Competence#C45 "Neuro-chirurgie (C)"
* $TRE-R39-Competence#C47 "Neuro-psychiatrie (C)"
* $TRE-R39-Competence#C51 "Pédiatrie (C)"
* $TRE-R39-Competence#C52 "Phoniatrie (C)"
* $TRE-R39-Competence#C54 "Pneumologie (C)"
* $TRE-R39-Competence#C57 "Psychiatrie (C)"
* $TRE-R39-Competence#C58 "Psychiatrie, option enfant et adolescent (C)"
* $TRE-R39-Competence#C60 "Médecine physique et de réadaptation (C)"
* $TRE-R39-Competence#C62 "Rhumatologie (C)"
* $TRE-R39-Competence#C68 "Chirurgie pédiatrique (C)"
* $TRE-R39-Competence#C69 "Médecine nucléaire (C)"
* $TRE-R39-Competence#C71 "Médecine thermale (C)"
* $TRE-R39-Competence#C72 "Génétique médicale (C)"
* $TRE-R39-Competence#C75 "Endocrinologie et Maladies métaboliques (C)"
* $TRE-R39-Competence#C76 "Orthopédie dento-maxillo-faciale (C)"
* $TRE-R39-Competence#C83 "Chirurgie de la face et du cou (C)"
* $TRE-R40-CompetenceExclusive#CEX22 "Gynécologie médicale et Obstétrique (CEX)"
* $TRE-R40-CompetenceExclusive#CEX24 "Gynécologie médicale (CEX)"
* $TRE-R40-CompetenceExclusive#CEX26 "Obstétrique (CEX)"
* $TRE-R40-CompetenceExclusive#CEX64 "Urologie (CEX)"
* $TRE-R42-DESCnonQualifiant#DSM200 "Addictologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM201 "Allergologie et Immunologie clinique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM202 "Andrologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM203 "Biochimie hormonale et métabolique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM204 "Biologie des agents infectieux (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM205 "Biologie moléculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM206 "Cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM207 "Chirurgie de la face et du cou (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM208 "Chirurgie plastique et reconstructrice (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM209 "Chirurgie vasculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM210 "Cytogénétique humaine (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM211 "Dermatopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM212 "Foetopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM213 "Gériatrie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM214 "Hématologie biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM215 "Hématologie maladies du sang (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM216 "Hémobiologie-transfusion (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM217 "Immunologie et Immunopathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM218 "Médecine de la reproduction (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM219 "Médecine du sport (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM220 "Médecine d'urgence (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM221 "Médecine légale et Expertises médicales (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM222 "Médecine nucléaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM223 "Médecine vasculaire (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM224 "Néonatalogie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM225 "Neuropathologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM226 "Nutrition (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM227 "Orthopédie dento-maxillo-faciale (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM228 "Pathologie infectieuse et tropicale, clinique et biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM229 "Pharmacocinétique et Métabolisme des médicaments (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM230 "Pharmacologie clinique et Evaluation des thérapeutiques (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM231 "Psychiatrie de l'enfant et de l'adolescent (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM232 "Radiopharmacie et Radiobiologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM233 "Réanimation médicale (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM234 "Toxicologie biologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM235 "Médecine de la douleur et Médecine palliative (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM236 "Cancérologie, option Traitements médicaux des cancers (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM237 "Cancérologie, option Chirurgie cancérologique (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM238 "Cancérologie, option Réseaux de cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM239 "Cancérologie, option Biologie cancérologie (DNQ)"
* $TRE-R42-DESCnonQualifiant#DSM240 "Cancérologie, option Imagerie cancérologie (DNQ)"
* $TRE-R43-CapaciteSavoirFaire#CAPA01 "Addictologie clinique (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA02 "Aide médicale urgente (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA03 "Allergologie (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA04 "Angéiologie (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA05 "Evaluation et Traitement de la douleur (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA06 "Gérontologie (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA07 "Hydrologie et Climatologie médicales (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA08 "Médecine aérospatiale (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA09 "Médecine de catastrophe (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA10 "Médecine et Biologie du sport (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA11 "Médecine de santé au travail et Prévention des risques professionnels (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA12 "Médecine pénitentiaire (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA13 "Médecine tropicale (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA14 "Pratiques médico-judiciaires (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA15 "Technologie transfusionnelle (CAPA)"
* $TRE-R43-CapaciteSavoirFaire#CAPA16 "Toxicomanies et Alcoologies (CAPA)"
* $TRE-R44-QualificationPAC#PAC00 "Qualification Praticien adjoint contractuel (PAC)"
* $TRE-R45-FonctionQualifiee#FQ01 "Expérience pratique art R.5124-16 du CSP Fabricant (FQ)"
* $TRE-R45-FonctionQualifiee#FQ02 "Expérience pratique art R.5124-16 du CSP Exploitant (FQ)"
* $TRE-R45-FonctionQualifiee#FQ03 "Expérience pratique art R.5124-16 du CSP Thérapie cellulaire (FQ)"
* $TRE-R45-FonctionQualifiee#FQ04 "Expérience pratique art R.5124-18 du CSP Pharmacie (FQ)"
* $TRE-R45-FonctionQualifiee#FQ05 "Expérience pratique art R.5141-129 du CSP Autovaccins (FQ)"
* $TRE-R97-DroitExerciceCompl#DEC01 "Addictologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC02 "Allergologie et Immunologie clinique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC03 "Andrologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC04 "Cancérologie, option traitements médicaux des cancers (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC05 "Cancérologie, option chirurgie cancérologique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC06 "Cancérologie, option réseaux de cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC07 "Cancérologie, option biologie en cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC08 "Cancérologie, option imagerie en cancérologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC09 "Dermatopathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC10 "Foetopathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC11 "Hémobiologie et Transfusion (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC12 "Médecine de la douleur et Médecine palliative (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC13 "Médecine de la reproduction (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC14 "Médecine d'urgence (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC15 "Médecine du sport (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC16 "Médecine légale et Expertises médicales (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC17 "Médecine vasculaire (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC18 "Néonatologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC19 "Neuropathologie (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC20 "Nutrition (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC21 "Orthopédie dento-maxillo-faciale (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC22 "Pathologie infectieuse et tropicale, clinique et biologique (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC23 "Pharmacologie clinique et Evaluation des thérapeutiques (DEC)"
* $TRE-R97-DroitExerciceCompl#DEC24 "Psychiatrie de l'enfant et de l'adolescent (DEC)"
* $TRE-G13-OrientationParticuliere#80 "Homéopathie"
* $TRE-G13-OrientationParticuliere#81 "Acupuncture"
* $TRE-R359-SurspecialiteTransversale#SST01 "Addictologie"
* $TRE-R359-SurspecialiteTransversale#SST02 "Bio-informatique médicale"
* $TRE-R359-SurspecialiteTransversale#SST03 "Cancérologie déclinaison hémato-cancérologie pédiatrique"
* $TRE-R359-SurspecialiteTransversale#SST04 "Cancérologie traitements médicaux des cancers"
* $TRE-R359-SurspecialiteTransversale#SST05 "Cardiologie pédiatrique et congénitale"
* $TRE-R359-SurspecialiteTransversale#SST06 "Chirurgie de la main"
* $TRE-R359-SurspecialiteTransversale#SST07 "Chirurgie en situation de guerre ou de catastrophe"
* $TRE-R359-SurspecialiteTransversale#SST08 "Chirurgie orbito-palpébro-lacrymale"
* $TRE-R359-SurspecialiteTransversale#SST09 "Douleur"
* $TRE-R359-SurspecialiteTransversale#SST10 "Expertise médicale-préjudice corporel"
* $TRE-R359-SurspecialiteTransversale#SST11 "Foetopathologie"
* $TRE-R359-SurspecialiteTransversale#SST12 "Génétique et médecine moléculaire bioclinique"
* $TRE-R359-SurspecialiteTransversale#SST13 "Hématologie bioclinique"
* $TRE-R359-SurspecialiteTransversale#SST14 "Hygiène-prévention de l'infection, résistances"
* $TRE-R359-SurspecialiteTransversale#SST15 "Maladies allergiques"
* $TRE-R359-SurspecialiteTransversale#SST16 "Médecine hospitalière polyvalente"
* $TRE-R359-SurspecialiteTransversale#SST17 "Médecine palliative"
* $TRE-R359-SurspecialiteTransversale#SST18 "Médecine scolaire"
* $TRE-R359-SurspecialiteTransversale#SST19 "Médecine en situation de guerre ou en SSE"
* $TRE-R359-SurspecialiteTransversale#SST20 "Médecine et biologie de la reproduction-andrologie"
* $TRE-R359-SurspecialiteTransversale#SST21 "Médecine du sport"
* $TRE-R359-SurspecialiteTransversale#SST22 "Nutrition appliquée"
* $TRE-R359-SurspecialiteTransversale#SST23 "Pharmacologie médicale/ thérapeutique"
* $TRE-R359-SurspecialiteTransversale#SST24 "Sommeil"
* $TRE-R359-SurspecialiteTransversale#SST25 "Thérapie cellulaire/ transfusion"
* $TRE-R359-SurspecialiteTransversale#SST26 "Urgences pédiatriques"
* $TRE-R359-SurspecialiteTransversale#SST27 "Innovation et recherche en sciences biologiques et pharmaceutiques"
* $tre-r394-competence-metier#CM0001 "Certificat de décès"