ValueSet: JDV_J210_SpecialiteOrdinale_ROR
Id: JDV-J210-SpecialiteOrdinale-ROR
Description: "Spécialité ordinale"
* ^meta.versionId = "7"
* ^meta.lastUpdated = "2026-07-06T19:05:55.314+02:00"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^language = #fr-FR
* ^extension.url = "http://hl7.org/fhir/StructureDefinition/resource-effectivePeriod"
* ^extension.valuePeriod.start = "2022-08-26T12:00:00+01:00"
* ^url = "https://mos.esante.gouv.fr/NOS/JDV_J210-SpecialiteOrdinale-ROR/FHIR/JDV-J210-SpecialiteOrdinale-ROR"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.250.1.213.3.4.42"
* ^version = "20260730120000"
* ^status = #active
* ^experimental = false
* ^date = "2026-07-30T12:00:00+01:00"
* ^publisher = "Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris"
* ^jurisdiction = urn:iso:std:iso:3166#FRA
* $TRE-R38-SpecialiteOrdinale#SCD01 "Orthopédie dento-faciale (SCD)"
* $TRE-R38-SpecialiteOrdinale#SCD02 "Chirurgie orale (SCD)"
* $TRE-R38-SpecialiteOrdinale#SCD03 "Médecine bucco-dentaire (SCD)"
* $TRE-R38-SpecialiteOrdinale#SI01 "Exercice infirmier en pratique avancée pathologies chroniques stabilisées (SI)"
* $TRE-R38-SpecialiteOrdinale#SI02 "Exercice infirmier en pratique avancée oncologie et hémato-oncologie (SI)"
* $TRE-R38-SpecialiteOrdinale#SI03 "Exercice infirmier en pratique avancée maladie rénale chronique, dialyse et transplantation rénale (SI)"
* $TRE-R38-SpecialiteOrdinale#SI04 "Exercice infirmier en pratique avancée santé mentale (SI)"
* $TRE-R38-SpecialiteOrdinale#SI06 "Exercice infirmier en pratique avancée bloc opératoire (SI)"
* $TRE-R38-SpecialiteOrdinale#SI07 "Exercice infirmier en pratique avancée anesthésie (SI)"
* $TRE-R38-SpecialiteOrdinale#SI08 "Exercice infirmier en pratique avancée puériculture (SI)"
* $TRE-R38-SpecialiteOrdinale#SM01 "Anatomie et Cytologie pathologiques (SM)"
* $TRE-R38-SpecialiteOrdinale#SM02 "Anesthésie-réanimation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM03 "Biologie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM04 "Cardiologie et Maladies vasculaires (SM)"
* $TRE-R38-SpecialiteOrdinale#SM05 "Chirurgie générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM06 "Chirurgie maxillo-faciale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM07 "Chirurgie maxillo-faciale et Stomatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM08 "Chirurgie orthopédique et Traumatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM09 "Chirurgie infantile (SM)"
* $TRE-R38-SpecialiteOrdinale#SM10 "Chirurgie plastique reconstructrice et esthétique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM11 "Chirurgie thoracique et cardio-vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM12 "Chirurgie urologique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM13 "Chirurgie vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM14 "Chirurgie viscérale et digestive (SM)"
* $TRE-R38-SpecialiteOrdinale#SM15 "Dermatologie et Vénéréologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM16 "Endocrinologie et Métabolisme (SM)"
* $TRE-R38-SpecialiteOrdinale#SM17 "Génétique médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM18 "Gériatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM19 "Gynécologie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM20 "Gynécologie-obstétrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM21 "Hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM22 "Hématologie, option Maladie du sang (SM)"
* $TRE-R38-SpecialiteOrdinale#SM23 "Hématologie, option Onco-hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM24 "Gastro-entérologie et Hépatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM25 "Médecine du travail (SM)"
* $TRE-R38-SpecialiteOrdinale#SM26 "Qualifié en Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM27 "Médecine interne (SM)"
* $TRE-R38-SpecialiteOrdinale#SM28 "Médecine nucléaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM29 "Médecine physique et de réadaptation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM30 "Néphrologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM31 "Neuro-chirurgie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM32 "Neurologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM33 "Neuro-psychiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM34 "ORL et Chirurgie cervico-faciale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM35 "Oncologie, option Onco-hématologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM36 "Oncologie, option médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM37 "Oncologie, option radiothérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM38 "Ophtalmologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM39 "Oto-rhino-laryngologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM40 "Pédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM41 "Pneumologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM42 "Psychiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM43 "Psychiatrie, option enfant et adolescent (SM)"
* $TRE-R38-SpecialiteOrdinale#SM44 "Radio-diagnostic (SM)"
* $TRE-R38-SpecialiteOrdinale#SM45 "Radio-thérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM46 "Médecine intensive-réanimation (SM)"
* $TRE-R38-SpecialiteOrdinale#SM47 "Recherche médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM48 "Rhumatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM49 "Santé publique et Médecine sociale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM50 "Stomatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM51 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-obstétrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM52 "Gynéco-obstétrique et Gynéco-médicale, option Gynéco-médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM53 "Spécialiste en Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM54 "Médecine générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM55 "Radio-diagnostic et Radio-thérapie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM56 "Chirurgie orale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM57 "Allergologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM58 "Maladies infectieuses et tropicales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM59 "Médecine d'urgence (SM)"
* $TRE-R38-SpecialiteOrdinale#SM60 "Médecine légale et expertises médicales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM61 "Médecine vasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM62 "Endocrinologie, diabétologie, nutrition (SM)"
* $TRE-R38-SpecialiteOrdinale#SM63 "Biologie médicale option biologie générale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM64 "Biologie médicale option médecine moléculaire, génétique et pharmacologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM65 "Biologie médicale option hématologie et immunologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM66 "Biologie médicale option agents infectieux (SM)"
* $TRE-R38-SpecialiteOrdinale#SM67 "Biologie médicale option biologie de la reproduction (SM)"
* $TRE-R38-SpecialiteOrdinale#SM68 "Chirurgie maxillo-faciale (réforme 2017) (SM)"
* $TRE-R38-SpecialiteOrdinale#SM69 "Chirurgie pédiatrique option chirurgie viscérale pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM70 "Chirurgie pédiatrique option orthopédie pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM71 "Hématologie (réforme 2017) (SM)"
* $TRE-R38-SpecialiteOrdinale#SM72 "Médecine interne et immunologie clinique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM73 "Médecine cardiovasculaire (SM)"
* $TRE-R38-SpecialiteOrdinale#SM74 "Radiologie et imagerie médicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM75 "Santé publique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM76 "Anesthésie-réanimation option anesthésie-pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM77 "Chirurgie maxillo-faciale option orthodontie des dysmorphies maxillo-faciales (SM)"
* $TRE-R38-SpecialiteOrdinale#SM78 "Chirurgie viscérale et digestive option endoscopie chirurgicale (SM)"
* $TRE-R38-SpecialiteOrdinale#SM79 "Médecine cardiovasculaire option cardiologie interventionnelle (SM)"
* $TRE-R38-SpecialiteOrdinale#SM80 "Médecine cardiovasculaire option imagerie cardio d'expert (SM)"
* $TRE-R38-SpecialiteOrdinale#SM81 "Médecine cardiovasculaire option rythmologie interventionnelle et stimulation cardiaque (SM)"
* $TRE-R38-SpecialiteOrdinale#SM82 "Médecine intensive-réanimation option réanimation pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM83 "Néphrologie option soins intensifs néphrologiques (SM)"
* $TRE-R38-SpecialiteOrdinale#SM84 "Neurologie option traitement interventionnel de l'ischémie cérébrale aigüe (SM)"
* $TRE-R38-SpecialiteOrdinale#SM85 "Ophtalmo option chirurgie ophtalmopédiatrique et strabologique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM86 "ORL et chirurgie cervico-faciale option audiophonologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM87 "Pédiatrie option néonatologie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM88 "Pédiatrie option neuropédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM89 "Pédiatrie option pneumopédiatrie (SM)"
* $TRE-R38-SpecialiteOrdinale#SM90 "Pédiatrie option réanimation pédiatrique (SM)"
* $TRE-R38-SpecialiteOrdinale#SM91 "Pneumologie option soins intensifs respiratoires (SM)"
* $TRE-R38-SpecialiteOrdinale#SM92 "Psychiatrie option enfant et adolescent (SM)"
* $TRE-R38-SpecialiteOrdinale#SM93 "Psychiatrie option psychiatrie personne âgée (SM)"
* $TRE-R38-SpecialiteOrdinale#SM94 "Radiologie imagerie médicale option radiologie interventionnelle avancée (SM)"
* $TRE-R38-SpecialiteOrdinale#SM95 "Santé publique option administration de la santé (SM)"