
name: Create ZIP NOS Expand

on:
  workflow_call:
  workflow_dispatch:




# The following jobs are equal for all IGs and can be moved to a common composite-action if 'uses'-support is added, see:
# https://github.com/actions/runner/blob/main/docs/adrs/1144-composite-actions.md
jobs:
  publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: igSource

      - run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./igSource/publication-request.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: |
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'
          echo '${{ fromJson(env.PACKAGE_JSON).desc }}'

      - name: Install fhirpy
        run :  pip install fhirpy

      - name: Install typing-extensions
        run :  pip install typing-extensions

      - name: Install modules
        run: npm install -g fsh-sushi

      - name: Suppression des fichiers templates
        run : |
          rm  -rf ./igSource/DM/input/fsh/Template/*.fsh
          rm  -rf ./igSource/DM/input/fsh/Template/ontoserver/TRE/*.fsh
          rm  -rf ./igSource/DM/input/fsh/Template/ontoserver/JDV/*.fsh

      - name: Run sushi pour les DM
        run: sushi ./igSource/DM

      - name: Suppression des fichiers FSH
        run: |
          rm -rf ./igSource/DM/input/fsh/Done/GitHub/*.fsh
          rm -rf ./igSource/DM/input/fsh/InProgress/*.fsh

      - name: Get From ontoserver
        run: |
          mkdir ./igSource/input/ontoserver
          mkdir ./igSource/input/ontoserver/JDV
          mkdir ./igSource/input/ontoserver/TRE
          mkdir ./igSource/input/ontoserver/ASS
          mkdir ./igSource/input/ontoserver/NamingSystem
          cd ./igSource/tools
          python ./upload_nos_expand.py

      - name: List des repertoires
        run: ls -R ./igSource/input

      - name: Cache TX responses
        uses: actions/cache@v4
        with:
          path: ~/.fhir/txcache
          key: tx-cache-${{ runner.os }}-${{ hashFiles('**/sushi-config.yaml') }}
          restore-keys: tx-cache-${{ runner.os }}-

      # Downloads the newest version of the IG Publisher, this could probable be cached.
      - name: 📥 Download IG Publisher
        run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/download/1.8.22/publisher.jar



      - name: Build and test with Rake
        run: |
          sudo apt-get install ruby-full
          sudo gem install jekyll

      - name: Run sushi
        run: sushi ./igSource

      # Builds the HTML page for the IG.
      - name: 🏃‍♂️ Run IG Publisher
        run: |
          cd ./igSource
          java -Xmx6g -jar ../publisher.jar -ig . \
            -tx https://r4.ontoserver.csiro.au/fhir \
            -authorise-non-conformant-tx-servers


      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install saxon
        run : pip install saxonche

      - name: Install requests
        run : pip install requests

      - name: Install glob
        shell: bash
        run : pip install glob2

      - name: Run script python
        run: |
              cd  ./igSource
              python ./tools/transform.py './output' './tools/xsl'

      - name: Run Create ZIP NOS Expand
        run: |
              cd  ./igSource/
              python ./tools/create_zip_nos.py './output' '../zip_nos_expand'
              zip -r ./output/zip_nos_expand.zip ../zip_nos_expand/*

      - name: Upload ZIP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          cd  ./igSource
          regex='^https?:\/\/[A-Za-z0-9:.]*([\/]{1}.*\/?)$'
          [[ ${{ fromJson(env.PACKAGE_JSON).path }} =~ $regex ]]
          file_path=${BASH_REMATCH[1]}

          gh release upload "${{ fromJson(env.PACKAGE_JSON).version }}" ./output/zip_nos_expand.zip --repo="$GITHUB_REPOSITORY"



